### ISSUE TITLE
how to change mime-type?

### ISSUE THREAD

**Issue by pangyulei** [koajs/koa#1007]
i am working on Over-The-Air iOS distribute, according to apple's document I have to set mime-type for .ipa and .plist file, how can I do it in Koa framework? I found the nodejs way, but it have to modify res and rep, which koa not support.

**Comment by fl0w** [comment]
Isn't `ctx.type=` sufficient?

**Comment by pangyulei** [comment]
@fl0w but how to specify "application/octet-stream" for ".ipa" ?  ctx.type = "application/octet-stream" doesn't relate any code to "ipa"

**Comment by pangyulei** [comment]
put this middleware upon every others
`app.use(async function(ctx, next){
       await next();
       if (ctx.url.toLowerCase().includes('.plist')) {
             ctx.type = 'text/xml';
      }
})`
