### ISSUE TITLE
How to custom handling stream error?

### ISSUE THREAD

**Issue by JounQin** [koajs/koa#1009]
As above, how can I handle stream error like custom error content or redirect to another page with different error?

For now, I can only use code like this:
``` js
app.use(async (ctx, next) => {
  try {
    let stream

    await new Promise((resolve, reject) => {
      stream = renderer.renderToStream(context)
        .once('data', data => {
          stream.pause()
          stream.unshift(data)
          resolve()
        })
        .on('error', reject)
    })

    ctx.body = stream.resume()
  } catch (e) {
    if (e.url) {
      ctx.redirect(e.url)
    } else if (e.status === 404) {
      ctx.body = '404 | Page Not Found'
    } else {
      ctx.status = 500
      ctx.body = '500 | Internal Server Error'
      console.error(`error during render : ${url}`)
      console.error(e.stack)
    }
  }
})
```

**Comment by jonathanong** [comment]
unfortunately, you can't decide to throw an error page in the middle of the response stream. you'll have to buffer the stream and send it all at once if u want that functionality. unless u want to write some really complicated code. 

your code is fine, except don't do `stream.resume()`

**Comment by jonathanong** [comment]
I also don't know what you're trying to do. your code should just look like:

```js
ctx.body = renderer.renderToStream(context)
```

**Comment by JounQin** [comment]
I'm trying to wait for the first successful chuck of stream, so that if it throws an error on first chuck, I can handle it by myself.

**Comment by dead-horse** [comment]
@JounQin maybe you can try to rewrite ctx.onerror like [koa-onerror](https://github.com/koajs/onerror)

**Comment by jonathanong** [comment]
@JounQin got it. IMO that should be handled in `respond()` or an upstream middleware. the way you are doing it is a little incorrect as you should just be piping it to a passthrough stream

**Comment by JounQin** [comment]
@jonathanong Finally I change my code like this and it works:
``` js
ctx.respond = false
ctx.status = 200

const {res} = ctx

renderer.renderToStream(context)
  .on('error', e => {
    switch (ctx.status = e.status || 500) {
      case 302:
        ctx.redirect(e.url)
        return res.end()
      case 404:
        return res.end('404 | Page Not Found')
      default:
        res.end('500 | Internal Server Error')
        console.error(`error during render : ${url}`)
        console.error(e.stack)
    }
  })
  .pipe(res)
```

**Comment by jonathanong** [comment]
that will fail if the stream has a mid-stream error
