### ISSUE TITLE
Security Issue. Status?

### ISSUE THREAD

**Issue by juancancela** [koajs/koa#1014]
Hi,
I have just read this article: https://www.bleepingcomputer.com/news/security/52-percent-of-all-javascript-npm-packages-could-have-been-hacked-via-weak-credentials/
and since koa is directly referenced, I just wanted to know if theres an status / update on this.

Thanks!

**Comment by nathan-k** [comment]
> One of the passwords with access to publish koa was literally 'password'
How can you trust a status update after this?

**Comment by jonathanong** [comment]
luckily, i know that one wasn't me 😹 

we can just do a user audit and kick out people without 2 factor in the github org and remote npm publishing rights from people who haven't been publishing

**Comment by jonathanong** [comment]
@koajs/owners

**Comment by fl0w** [comment]
@nathan-k to be fair, now is probably when you should be "least" worried - right after an exposé like this. A lifejacket should be worn even in calm waters - when it's stormy, everyones knows to wear it. *Weird analogy*

So Koa was directly targeted in that article - they say there's no bad press, but .. well :rofl:

**Comment by fengmk2** [comment]
Everyone should enable 2 factor.

**Comment by dead-horse** [comment]
> we can just do a user audit and kick out people without 2 factor in the github org and remote npm publishing rights from people who haven't been publishing

😓  Let's do this.

**Comment by jonathanong** [comment]
emailed/tweeted people who don't have 2 factor auth in this org.

**Comment by jonathanong** [comment]
still a few people left.

for npm permission... not sure, that's a lot more work. lol. ideally, npm has 2 factor auth

**Comment by jonathanong** [comment]
i will need to spend time later to boot people off npm packages

**Comment by niftylettuce** [comment]
@jonathanong we should prob just do this immediately, we can always add people back after they take this seriously

**Comment by jonathanong** [comment]
removed people. let me know if you see anyone a collaborator of a koa project that shouldn't be or hasn't been active in a while
