### ISSUE TITLE
How to build docs?

### ISSUE THREAD

**Issue by tolmasky** [koajs/koa#1016]
Apologies for the novice question, but I can't seem to figure out how to make the koajs.com website. It appears that it is constructed from the markdown files in docs/api, but I don't see where the build tool is or how to actually generate the HTML.

**Comment by fl0w** [comment]
The docs within this repo isn't the website I'm afraid.
I think you're you looking for https://github.com/koajs/koajs.com

**Comment by jonathanong** [comment]
yeah. go to that repo and build the docs!
