### ISSUE TITLE
consider providing a way to override `respond` function

### ISSUE THREAD

**Issue by bttmly** [koajs/koa#1019]
I'd be interested in a way to override the [`respond` function](https://github.com/koajs/koa/blob/aaac09af1a6aa02161fead1422fac460fbdcce3e/lib/application.js#L193-L238) – perhaps exposing it as a method?

My particular use case at the moment has to do with how the current `respond` function interacts with `ctx.respond = false`, in the context of embedding Koa within a larger application. Generally this works fine -- you can set `ctx.respond` to false, and after Koa's middleware stack runs to completion you can check `res.headersSent` to see if Koa handled the request; if not, continue handling it elsewhere. However this fails when `ctx.body` is a stream. Because of the semantics of `.pipe()`, the first write will happen asynchronously, and when `ctx.headersSent` is checked, it is `false`. This particular case could possibly be solved by doing a `res.write("")` before `body.pipe(res)` but that fails a couple test cases, for reasons that weren't immediately obvious.

While this is definitely a niche case, exposing a way to override or customize `respond` would certainly have other benefits. During a large project we are currently undertaking to migrate an application from Express to Koa, not being able to customize and instrument the response step has required several awkward workarounds.

**Comment by jonathanong** [comment]
yeah, streams kind of suck. ideally, we could fix it here. perhaps you could give us a test case and we can fix it here.

**Comment by bttmly** [comment]
Turns out that the behavior I want (flush the headers when you do `body.pipe(res)`) is incompatible with handling errors in streaming response bodies. For my specific case I would rather have the headers flushed immediately at the expense of error handling; it sort of depends on the use case. I'm also curious, since I don't see a test case for it, what is the intended behavior if a stream encounters an error after its first `data` event has arrived (and thus the status code has been set and the headers flushed)?

Anyway, providing a way to override `respond` would be a nice escape hatch for advanced or uncommon use cases, since there are a lot of assumptions baked into the `respond` function.

**Comment by jonathanong** [comment]
> what is the intended behavior if a stream encounters an error after its first data event has arrived (and thus the status code has been set and the headers flushed)?

you either make your stream super smart and change its data to an error page or something or you do nothing and let it finish.

**Comment by bttmly** [comment]
Any thoughts about this? It seems simple enough to make `respond` an instance method of `Application` which would allow monkeypatching/subclassing. The alternative is to set `respond: false`, which works but a.) the docs say this is basically unsupported and may do weird things and b.) there's not a clear way to tie into the end of the middleware stack e.g. some kind of event emitted right before calling `respond` where I could do the respondign myself.

**Comment by dead-horse** [comment]
closes via https://github.com/koajs/koa/pull/1303#issuecomment-455033090
