### ISSUE TITLE
Add a multipart example

### ISSUE THREAD

**Issue by Raynos** [koajs/koa#102]
@jonathanong is removing the multipart body parser from connect and the koajs/body-parser modules doesn't support it either.

It would be cool to have a new example of doing multipart, especially since there was some recent negative feedback on how connect did it with the temp files.

**Comment by Globik** [comment]
Блять, а как вы будете проверять у многих файлов mimetype? Бля, цикл виснет и все нахуй.

**Comment by Globik** [comment]
Когда по одному файл загружаешь заебись, а когда сразу то виснет сука и в обратку ошибку не шлет.

**Comment by juliangruber** [comment]
@Globik english please
