### ISSUE TITLE
How to send binary data

### ISSUE THREAD

**Issue by nikitaulshin** [koajs/koa#1020]
Hello!

I'm building an app using awesome Koa2.
Could you please tell me how can I send binary data (i. e. ArrayBuffer)?

Thanks!

**Comment by fengmk2** [comment]
## Buffer Data

```js
const buf = Buffer.alloc(1024);
this.body = buf;
```

## Stream object

```js
const stream = fs.createReadStream(__filename);
this.body = stream;
```

**Comment by nikitaulshin** [comment]
Thanks
