### ISSUE TITLE
How to set default response from route handler to 200 w/ body as promise fulfilled value

### ISSUE THREAD

**Issue by cdaringe** [koajs/koa#1022]
hi all, im new to koa and trying to implement some default behaviors.

# problem statement

i cannot see from the API docs how i would do:

```js
app.use(_.get('/:id', (ctx, id) => getSomeValue())
```

where the `getSomeValue()` returns a promise resolving to `{ data: 'ANYTHING' }`.  i want, if no error occurs, for:
 
- `{ data: 'ANYTHING' }` to be the `ctx.body`
- `200` to be the status
- and application/json to be the ContentType

# discussion

im assuming i can access the result in middleware somewhere, but i'm not seein' it!  any tips would great!  thx!

**Comment by logicoder** [comment]
Hello,

you can access it in a middleware with `await` return value, like:

```js
app.use(async (ctx, next) => {
  ctx.body = await next();
});

app.use(ctx => {
  return "whatever";
});
```

but at that point I think the middleware should manage errors and various situations.

**Comment by cdaringe** [comment]
woo hoo!  thx
