### ISSUE TITLE
Multiple async actions in response to a request

### ISSUE THREAD

**Issue by jarredr** [koajs/koa#1024]
I'm new to Koa (and backend-dev in general) and I'm trying to set up a simple signup api. When a user posts to /api/user, bcrypt hashes the password and the user information is stored in a database. In my code it successfully does this but Node returns "headers have already been sent" error and returns a 404 response to the client.
I have no trouble doing either of these async actions on their own but when I try to figure out a way to do them one after the other the headers always get sent early.

Here is my code:
```javascript
async function createUser (ctx, req, next) {
  try {
    let d = new Date()
    await db.none('INSERT INTO users(email, username, hash, created, permissions) VALUES($1, $2, $3, $4, $5)', [req.email, req.username, req.pass, d, 'user'])
    ctx.status = 200
    next()
  } catch (e) {
    if (e.constraint === 'users_email_uindex') {
      ctx.response.body = 'This email address is already in use'
    } else if (e.constraint === 'users_username_uindex') {
      ctx.response.body = 'This username is already in use'
    }
    ctx.status = 400
    console.log(e)
    next()
  }
}

userService.post('/', async (ctx, next) => {
  console.log('POST /api/user/')
  let req = ctx.request.body
  try {
    await bcrypt.hash(req.pass, 10, (e, hash) => {
      if (e) {
        console.log(e)
      }
      req.pass = hash
      createUser(ctx, req, next)
    })
  } catch (e) {
    console.log(e)
  }
})
```

**Comment by fl0w** [comment]
you need to either `return createUser(...)` or `await createUser(...)` because otherwise, the middleware (function) resolves without consideration of if createUser resolves. In other words, you're executing an unhandled promise.

**Comment by jarredr** [comment]
> you need to either return createUser(...) or await createUser(...) because otherwise, the middleware (function) resolves without consideration of if createUser resolves. In other words, you're executing an unhandled promise.

Leaving all other code unchanged, adding await to the createUser call causes node to crash with the following error: "SyntaxError: Unexpected identifier 'createUser'".
The code:
```javascript
userService.post('/', async (ctx, next) => {
  console.log('POST /api/user/')
  let req = ctx.request.body
  try {
    await bcrypt.hash(req.pass, 10, (e, hash) => {
      if (e) {
        console.log(e)
      }
      req.pass = hash
      await createUser(ctx, req, next)
    })
  } catch (e) {
    console.log(e)
  }
})
```

If I add a return statement in front of the function call node gives an UnhandledPromiseRejectionWarning: "headers have already been sent" and the request returns a 404. The new user is created and inserted into the database though.
The code:
```javascript
userService.post('/', async (ctx, next) => {
  console.log('POST /api/user/')
  let req = ctx.request.body
  try {
    await bcrypt.hash(req.pass, 10, (e, hash) => {
      if (e) {
        console.log(e)
      }
      req.pass = hash
      return createUser(ctx, req, next)
    })
  } catch (e) {
    console.log(e)
  }
})

```
Any ideas?

**Comment by fl0w** [comment]
Im in my phone so can't give a detailed answer - but await needs always to be within an async function. The callback fn you're creating isn't async and thus why you get the syntax error.

The bigger issue I'm now seeing is that bcrypt isn't returning a promise - yet you're awaiting it (as if it did).

I recommend two things, checkout package brypt-then (which converts the library from traditional callback signature to a promise), and for you to read up on how promises (and thus async await) work a little more.

It's an important (and sometimes confusing at first) concept which you really should spend some time on learning.

Again, what's happening is that your breaking the "promise-chain", and code es evalutated and executed outside expected context (due to javascripts asynchronious nature).

**Comment by uniibu** [comment]
Using your code i would do it like this: 

Changes:(Node v8.x+)
- Use of ctx.body instead of ctx.response.body
- Added ctx.body on createUser successful db insert, instead of just ctx.status 200
- Removed next on createUser
- Uses Node v8+ for util.promisify
- Added constant bchash which is a promisified version of bcrypt.hash
```javascript
const bcrypt = require("bcrypt")
const {promisify} = require('util')
const bchash = promisify(bcrypt.hash);

async function createUser (ctx, req) {
  try {
    let d = new Date()
    await db.none('INSERT INTO users(email, username, hash, created, permissions) VALUES($1, $2, $3, $4, $5)', [req.email, req.username, req.pass, d, 'user'])
    // simply setting ctx.status = 200 wont work, it will return as 204 No Content, so ctx.body must be set if you want a blank 200 response
   ctx.body = ''
  } catch (e) {
    console.log(e)
    ctx.status = 400
    if (e.constraint === 'users_email_uindex') {
      ctx.body = 'This email address is already in use'
    } else if (e.constraint === 'users_username_uindex') {
      ctx.body = 'This username is already in use'
    }    
  }
}

userService.post('/', async (ctx, next) => {
  console.log('POST /api/user/')
  let req = ctx.request.body
  try {
    req.pass = await bchash(req.pass, 10)
    await createUser(ctx, req)
  } catch (e) {
    console.log(e)
  }
})
```
Changes:(Node < v8.x)
- Pretty much the same as the first example except this does not use Node v8's `util promisify`
```javascript
 async function createUser (ctx, req) {
  try {
    let d = new Date()
    await db.none('INSERT INTO users(email, username, hash, created, permissions) VALUES($1, $2, $3, $4, $5)', [req.email, req.username, req.pass, d, 'user'])
    ctx.body = ''    
  } catch (e) {
    console.log(e)
    ctx.status = 400
    if (e.constraint === 'users_email_uindex') {
      ctx.response.body = 'This email address is already in use'
    } else if (e.constraint === 'users_username_uindex') {
      ctx.response.body = 'This username is already in use'
    }    
  }
}

async function bchash(pw,rounds){
  return new Promise(function(resolve,reject){
        bcrypt.hash(pw,rounds,function(err,hash){
            if (err) reject(err);
            else resolve(hash);               
        })
    })
}

userService.post('/', async (ctx, next) => {
  console.log('POST /api/user/')
  let req = ctx.request.body
  try {
    req.pass = await bchash(req.pass, 10)
    await createUser(ctx, req)
  } catch (e) {
    console.log(e)
  }
})
```
Changes:(My ow version, Node v8+)
- Simplified the routes controller to a single async function
- Uses ctx.throw for error handling
```javascript
const bcrypt = require("bcrypt")
const {promisify} = require('util')
const bchash = promisify(bcrypt.hash);

 async function createUser (ctx) {
  let req = ctx.request.body
  let d = new Date()
  try {    
    req.pass = await bchash(req.pass,10);
    await db.none('INSERT INTO users(email, username, hash, created, permissions) VALUES($1, $2, $3, $4, $5)', [req.email, req.username, req.pass, d, 'user'])
   ctx.body = "Success"   
  } catch (e) {
    console.log(e)
    if (e.constraint === 'users_email_uindex') {
      ctx.throw('This email address is already in use', 400);
    } else if (e.constraint === 'users_username_uindex') {
      ctx.throw('This username is already in use', 400);
    }   
  }
}

userService.post('/', createUser)
```

**Comment by jarredr** [comment]
@uniibu Thanks to your help I now have it working as intended. I appreciate the time you took to improve my code.
ctx.throw is not working for me like in your examples though. First, I get a warning to swap the status and the message. But even after doing that Insomnia (REST client) shows a 404 when the request should be displaying the error. Because of this I resorted to my old method.
Simply setting the status to 200 on successful database insert was working for me using Insomnia (was not returning 204), but I agree that a message would be better.

Here is my working code if anyone else stumbles across this issue
```javascript
const KoaRouter = require('koa-router')
const bcrypt = require('bcrypt')
const db = require('../db') // database connection using pg-promise
const {promisify} = require('util')
const bchash = promisify(bcrypt.hash)

const userService = new KoaRouter()
userService.prefix('/api/user')

async function createUser (ctx) {
  console.log('POST /api/user/')
  let req = ctx.request.body
  let d = new Date()
  try {
    req.pass = await bchash(req.pass, 10)
    await db.none('INSERT INTO users(email, username, hash, created, permissions) VALUES($1, $2, $3, $4, $5)', [req.email, req.username, req.pass, d, 'user'])
    ctx.body = 'Successfully created user'
  } catch (e) {
    if (e.constraint === 'users_email_uindex') {
      ctx.body = 'This email address is already in use'
    } else if (e.constraint === 'users_username_uindex') {
      ctx.body = 'This username is already in use'
    } else {
      ctx.body = 'Unknown error creating user'
    }
    ctx.status = 400
  }
}

userService.post('/', createUser)
```

**Comment by uniibu** [comment]
Glad to be of help.
My best guess is that you are using a lower version of bcrypt(<1.x) which doesn't support. The latest version of bcrypt (1.0.2) supports promises. So in case you updates your bcrypt module, you could use await directly like `req.pass = await bcrypt.hash(req.pass, 10)`

In regards with ctx.throw i just followed the one on docs https://github.com/koajs/koa/wiki/Error-Handling, which is probably outdated due to changes from http-errors

Cheers!
