### ISSUE TITLE
Easily send a 201 response with no body

### ISSUE THREAD

**Issue by dupski** [koajs/koa#1030]
I would like to be able to:

* Set `ctx.status` to `201`
* Set `ctx.body` to `''`, and
* Exit the middleware function

In a single statement.

In Hapi I could do this: `return reply('').code(201);`

Currently in Koa I am doing it like this:

```
ctx.status = 200;
ctx.body = '';
return;
```

I'd love to be able to do something like:

`return ctx.setResponse(201, '')`

Is this something that has been considered? Have I just missed something obvious? :)

**Comment by BruceHem** [comment]
U can create a function like that yourself

**Comment by dupski** [comment]
@BruceHam I could, but then I'd have to require it everywhere. Setting the status + body together is a pretty common thing to want to do.

Also the `ctx.throw([status], [msg], [properties])` method already has a similar signature.

Was just wondering if there is a reason this doesn't exist? Happy to work on a PR

**Comment by BruceHem** [comment]
actually all u need is a middleware, which it appends that function to the koa context, that ways u don't have to require it. Something similar to koa-respond module.

**Comment by dupski** [comment]
Ah good point! So I was missing something obvious! Cool :)
