### ISSUE TITLE
Why was generators deprecated in favor of async/await?

### ISSUE THREAD

**Issue by jsheely** [koajs/koa#1034]
I got the deprecation warning and was wondering why it was deprecated? 

>koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md

Was there a specific performance reason? 
A memory allocation issue?
The idea that it would only ever return a single value?

I like async/await just fine. Just curious as to why fully deprecate it and not just let the user choose which style they liked best.

**Comment by EduardoRFS** [comment]
Because the actual implementations of generators is a pure hack to exactly the same thing of async await, async / await is slower, but the "right thing"

**Comment by fl0w** [comment]
Todays compliance will legacy mw signature is done through koa-convert, which wraps the generator. It's a "best effort" support and is not full-proof. I don't think it was ever ment to be a choice, but rather to ease upgradeability.

**Comment by jsheely** [comment]
@EduardoRFS But was that not at a time when generators were a shim? Now that generators are baked into node.js can't it work with both?

**Comment by jsheely** [comment]
Thanks for the info
