### ISSUE TITLE
ctx.accepts('webp') false positive

### ISSUE THREAD

**Issue by tinovyatkin** [koajs/koa#1035]
For some reason `ctx.accepts('webp')` always returning `webp` even when `Accept` header doesn't contain `image/webp`. Replacing it with `request.get('Accept').includes('image/webp')` works well for me, but I'm just curios whether it's a bug or desired behaviour?

**Comment by tinovyatkin** [comment]
I think it's because Safari includes `*/*` in `Accept` (`Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`). Is there any better way to do non-wildcard check?

**Comment by jonathanong** [comment]
seems like an issue with safari's default accept header – it matches anything.

this is better discussed here: https://github.com/jshttp/negotiator

thanks!
