### ISSUE TITLE
repeated properties in object ctx

### ISSUE THREAD

**Issue by rabbitmeow** [koajs/koa#1047]
I think removing repeated properties in ctx is better.

    console.log(ctx.header === ctx.headers)
    console.log(ctx.header === ctx.request.header)
    console.log(ctx.response.req === ctx.req)
    console.log(ctx.response.res === ctx.res)
    console.log(ctx.request.req === ctx.req)
    console.log(ctx.request.res === ctx.res)
    console.log(ctx.request.URL === ctx.URL)
    etc

I think this is a better solution.
const { header, URL } = ctx.request;

**Comment by vkhv** [comment]
Aliases  is convenient.

**Comment by rabbitmeow** [comment]
aliases confuse new users.

    ctx.body -> ctx.request.body ? ctx.response.body ?
    ctx.header -> ctx.accept.header ? ctx.request.header ? ctx.response.header ?
    ctx.request -> ctx.app ? ctx.reponse.app ? ctx.request.app ?
    etc

so many repeated properties.
some are identical but some are not.
repeated names confuse usages of methods and properties.
why not provide a pure Koa?

**Comment by alqu** [comment]
I think @rabbitmeow is right. Having repeated properties here and there seem to be OK... but I often asked myself why the naming went down that road.
Fiddling around with ctx.body and ctx.request.body is not straight forward. Having a simple rule like `ctx.request.<something from request>` and `ctx.response.<something from response>` is easy to remember and looks good.

My 2 cents

**Comment by fl0w** [comment]
So in practice, `async ({ request, response }) => { ... }` ...

**Comment by rabbitmeow** [comment]
And it's really ugly when you print out Koa's instance. I print it out just for looking for the usages of methods and properties. But it has too many repeated properties such that I cannot distinguish which one is what I want.
If I wanna use the aliases, I have got to print out "ctx.properties === ctx.higherProperties.properties" . So I would type the second one rather than the first one.
I think this type of secondary packaging should not be used in a basic framework.

**Comment by iyuq** [comment]
－1
