### ISSUE TITLE
Http2ServerResponse.statusMessage is not writeable

### ISSUE THREAD

**Issue by BernzSed** [koajs/koa#1048]
Node 8.4.0 has introduced the "http2" module as part of node core, which you can use if you launch node with `--expose-http2`.

When using it with koa, however, I get an error:

```
TypeError: Cannot set property statusMessage of #<Http2ServerResponse> which has only a getter
```

The error comes from /lib/response.js, line 88. HTTP/2 does not have status messages, so Node throws an error when you try to set one.

This is the code I'm using:

```javascript
const http2 = require('http2');
const fs = require('fs');
const Koa = require('koa');
const Router = require('koa-router');

const app = new Koa();

const options = {
  key: fs.readFileSync('server.key'),
  cert: fs.readFileSync('server.crt')
};

http2.createSecureServer(options, app.callback()).listen(3000);

const router = new Router();
router.get('/', (ctx) => ctx.body = "response");

app.use(router.routes());
```

**Comment by dougwilson** [comment]
imo this is a Node.js core issue. The API is supposed to be compatible, and really there should be a setter in the compat layer even if it just printed a deprecated message, because the existing API allows set. Another user expressed the same thought here: https://github.com/nodejs/node/pull/14690#issuecomment-321756459

**Comment by BernzSed** [comment]
Closing because Node now emits a warning instead of throwing an exception.

**Comment by ShimShamSam** [comment]
@BernzSed  Any chance of detecting HTTP/2 and disabling the setting of the statusMessage? It seems silly to have these warnings thrown after each request.

![image](https://user-images.githubusercontent.com/2212177/32018662-9af868aa-b998-11e7-8c3c-eb4897646e8b.png)

**Comment by BernzSed** [comment]
@ShimShamSam The PR I opened is still open (https://github.com/koajs/koa/pull/1049), which should address some of that.
