### ISSUE TITLE
Node versions should be consistent

### ISSUE THREAD

**Issue by nickmccurdy** [koajs/koa#1051]
The engine versions, Travis versions, and recommended version from the readme should be consistent. See #935 and #1050.

## Potential solutions
(mutually exclusive)
1. Support 6 by testing it for users that may need to use it with Babel, otherwise it should not be in Node engines because it may be broken. Documentation (`Readme.md` and `docs/api/index.md`) should make it clear that 6 is required but 7.6 is recommended. 6 should be added to Travis versions.
2. Revert #935 and the Node 6 support added in 2.0.1. Engines should be `>= 7.6.0`. Other versions can be left alone since using 6 would be discouraged.

### Node engines
`>= 6.0.0`

### Recommended versions in documentation
`>= 7.6.0`

### Travis builds
(similar to doc versions, Travis only installs the latest versions of major releases)

`7` and `8`

**Comment by debel88** [comment]
I would be in favor of solution 2, and go bit further :

**Node engines**
`>= 7.6.0`

**Recommended versions in documentation**
`>= 8.9.0` (start of LTS). Still mention that it works for `>= 7.6.0`, but discourage its use due to its discontinued support and its non-adequacy for production environments.

**Comment by jonathanong** [comment]
current version ranges are `^4.8.4 || ^6.10.1 || ^7.10.1 || >= 8.1.4`

if the range is consistent anywhere, a PR is welcomed!

when node@4 is out of LTS in April 2018, we should drop support for it

**Comment by nickmccurdy** [comment]
Was Node 4 support added? I thought that Koa still doesn't support Node `<7.10.1` because it uses `async`/`await` without transpiling them. We should stop using this syntax, compile the npm build, or change the current version ranges to `^7.10.1 || >= 8.1.4`. What would you prefer?

**Comment by nickmccurdy** [comment]
@jonathanong I've been thinking about this more and realized I missed a couple details from other issues and PRs. I think we should use same version range you mentioned as long as Koa itself supports them without Babel, but either dropping 7 or adding 5 to keep our non-LTS support consistent. Then in order to ensure that Koa works on older versions of Node without Babel, we should adjust the tests so they don't use `async`/`await` at all. I would be happy to work on this last bit, do you think this is a good idea?

**Comment by jonathanong** [comment]
at this point i'd just like `>= 10`
