### ISSUE TITLE
Create eslint-config-koa package

### ISSUE THREAD

**Issue by nickmccurdy** [koajs/koa#1054]
Koala is transitioning to Koa's eslint config. We're copying the `.eslintrc` for now, but for convenience and ease of maintenance it would be great if there was an official eslint config package for Koa's coding style (which is based on Koa but different enough that I think it makes sense to promote it on its own).

If a maintainer/collaborator expresses interest I'd be happy to work on extracting a new package repository and submitting a PR to use it at least in Koa.

**Comment by jonathanong** [comment]
https://github.com/koajs/eslint-config-koa created a bare repo and added you :) let me know your npm username so i can add you

**Comment by nickmccurdy** [comment]
Sweet thanks! I'm [`nicolasmccurdy`](https://www.npmjs.com/~nicolasmccurdy) on npm.

**Comment by nickmccurdy** [comment]
Sorry for the delay, `eslint-config-koa@2.0.0` is now usable!
