### ISSUE TITLE
redirect is routing POST requests to GET

### ISSUE THREAD

**Issue by edwmurph** [koajs/koa#1057]
```
const Koa = require('koa')
const Router = require('koa-router')

const app = new Koa()
const router = new Router()

router.post('/newRoute/subPath', (ctx) => {
    ctx.body = 'Hello, from POST';
});

router.get('/newRoute/subPath', (ctx) => {
    ctx.body = 'Hello, from GET';
});

router.put('/newRoute/subPath', (ctx) => {
    ctx.body = 'Hello, from PUT';
});

router.delete('/newRoute/subPath', (ctx) => {
    ctx.body = 'Hello, from DELETE';
});

router.all(/^\/oldRoute\//, (ctx) => {
    const newUrl = ctx.url.replace(/^\/oldRoute\/(.*)/, '/newRoute/$1');
    console.log(`-- redirecting request -- ${ctx.url} -> ${newUrl}`);

    ctx.redirect(newUrl);
});

app
    .use(router.routes())
    .use(router.allowedMethods());

app.listen(3002, () => console.log('Koa app listening on 3002'));
```

Calling `localhost:3002/oldRoute/subPath` with GET, PUT, and DELETE methods correctly redirect to the new url with the same method. However, calling that url with a POST method redirects to the new url but ends up in the GET method handler when it should end up in the POST handler for the new url.

**Comment by jasonxia23** [comment]
It seems not to be Koa's problem. https://stackoverflow.com/questions/8138137/http-post-request-receives-a-302-should-the-redirect-request-be-a-get

**Comment by edwmurph** [comment]
That's right. The problem was resolved by setting `ctx.status = 308` before redirecting.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308

**Comment by shinelp100** [comment]
I encountered the same problem, set 308 to display Method Not Allowed, how did you solve it?

**Comment by edwmurph** [comment]
@shinelp100 see my previous comment. That's all I did.

**Comment by shinelp100** [comment]
but i setting ctx.status = 308; chrome give me :405 Method Not Allowed

**Comment by maghidini** [comment]
`ctx.status = 307` works for me on POST redirection (https://softwareengineering.stackexchange.com/questions/99894/why-doesnt-http-have-post-redirect)
