### ISSUE TITLE
Tests: koa server not closed

### ISSUE THREAD

**Issue by entropitor** [koajs/koa#1061]
This is not really a bug report but I'm wondering why you don't close the server in your tests (e.g. you open one here: https://github.com/koajs/koa/blob/master/test/application/index.js#L22) but you never close it, as far as I can find. How can the test process terminate?

**Comment by fl0w** [comment]
supertest closes the server once it's done. https://github.com/visionmedia/supertest/blob/master/lib/test.js#L126

**Comment by entropitor** [comment]
Thank you. I'll check with supertest then https://github.com/visionmedia/supertest/issues/436

**Comment by likegun** [comment]
Supertest only close server when server(this._server) is set
```javascript
Test.prototype.end = function(fn) {
  var self = this;
  var server = this._server;
  var end = Request.prototype.end;

  end.call(this, function(err, res) {
    if (server && server._handle) return server.close(assert);
    ...
  });

  return this;
};
```
But this._server is set only when app.address() do not exist, which means the app is created by supertest itself.
```javascript
Test.prototype.serverAddress = function(app, path) {
  var addr = app.address();
  var port;
  var protocol;

  if (!addr) this._server = app.listen(0);
  ...
};
```
So if we pass `app.listen()` to supertest, supertest will not close it.

**Comment by khotey** [comment]
@likegun so If I want to close server on done I need pass app without listen() ?

**Comment by fl0w** [comment]
try `supertest.agent(app.callback())`

**Comment by khotey** [comment]
@fl0w works, but server don't close

**Comment by fl0w** [comment]
Im not close to a computer now, but is it possible your app opens other persistent connections? Such as perhaps a database connection pool?

**Comment by khotey** [comment]
@fl0w koa sever connected to mongoose server, if I add ` --forceExit` flag server close and mongo connection close to. I thought supreteset closes server connection and after server closes mongoose connection automatically without ` --forceExit` , dont it ?

**Comment by fl0w** [comment]
No, you'll have to manage a graceful shutdown of mongoose yourself in app. Supertest only closes the http server (if correctly used), it has no knowledge of other lingering connections.

**Comment by khotey** [comment]
@fl0w thanks!) Can you tell how it do with koa, because when supertest up server he up with mongoose and I can get mongo instance. I monitor connections in mongo by `db.serverStatus().conecctions` `--forceExit` kill node process and it automatically kill connection to mongo.

**Comment by fl0w** [comment]
I do it by hooking on a teardown function on https://nodejs.org/api/http.html#http_event_close
