### ISSUE TITLE
can't npm install koa

### ISSUE THREAD

**Issue by SunnySnail** [koajs/koa#1080]
when I execute ‘npm install koa’, an error show. And the error info is "Cannot find module 'internal/fs'". My node version is v7.6.0

**Comment by maticrivo** [comment]
@SunnySnail whats the error you're getting?

**Comment by SunnySnail** [comment]
![image](https://user-images.githubusercontent.com/8349779/31383192-bff57474-ad7f-11e7-9cd0-0777bcec2a31.png)

this is the error info.

**Comment by fl0w** [comment]
I recommend you reinstall your node installation. There's nothing wrong with Koa specifically here.

**Comment by dead-horse** [comment]
yep, please reinstall npm
