### ISSUE TITLE
is `ctx.is` bug?

### ISSUE THREAD

**Issue by Matrixbirds** [koajs/koa#1081]
```version
node: 8.4.0
koa: 2.3.0
```

koa/lib/request.js
![image](https://user-images.githubusercontent.com/9990676/31487810-495f7ad0-af6e-11e7-8361-852566c10bfb.png)

my app code  

![image](https://user-images.githubusercontent.com/9990676/31488220-9d51dd62-af6f-11e7-9de4-4011a10e2085.png)
 

my test code  
```js
// mocha + co-mocha
context('POST /api/balabala', function () {
        let resp;
        function fetch(params) {
            return request.get('/api/balabala')
               .query(params);
        }
        it.only("should response 200 ", function *() {
            resp = yield fetch({
                balbalbalabl: 234234234234
            });
            console.log(resp.body);
            console.log(resp.status);
            expect(resp.status).to.equal(200);
        });
});
```
![image](https://user-images.githubusercontent.com/9990676/31488062-23fdc4d0-af6f-11e7-9d12-0f81a858b652.png)

ctx.is("application/json") return null;
but actual its header contains{ 'content-type': 'application/json'}

**Comment by Runrioter** [comment]
Because you have no request content, so it's no point in geting content type.
https://github.com/koajs/koa/blob/43a1df8200dad6860f688713a112785535a3ed3d/lib/request.js#L565

**Comment by Matrixbirds** [comment]
oh i got it, thx
