### ISSUE TITLE
Update to fresh 0.5.2

### ISSUE THREAD

**Issue by dlebedynskyi** [koajs/koa#1085]
[fresh](https://github.com/jshttp/fresh) has [Vulnerable Regular Expression issue](https://github.com/jshttp/fresh/issues/24).
https://snyk.io/vuln/npm:fresh:20170908
Current version listed in package.json is 0.5
it is advised to up update to 0.5.2 for fix.

**Comment by jonathanong** [comment]
18e4fafb024366112b22084e2d0311dd5f4f8922
