### ISSUE TITLE
Missing req.body introduction in main page of koa.

### ISSUE THREAD

**Issue by realzzz** [koajs/koa#1087]
Hey ~

I'm newbie to koa, after I walked through koa main page introduction (http://koajs.com/# ), I found after all the detail explanation of ctx.request, there is no introduction about req.body, is this because koa discourage the usage of POST request ?  Or is there any other concern not to expose this in the document ? 

Thanks,
Jerry

**Comment by popomore** [comment]
You should use thie middleware https://github.com/koajs/bodyparser

**Comment by jonathanong** [comment]
@realzzz check out the wiki! https://github.com/koajs/koa/wiki#body-parsing
