### ISSUE TITLE
koa attachment 

### ISSUE THREAD

**Issue by Matrixbirds** [koajs/koa#1091]
```javascript
        const filename = "sutff_2017_xx_xx.xlsx"
        ctx.response.attachment(filename+";");
```

```response header
Content-Disposition:attachment; filename="sutff_2017_xx_xx.xlsx;"
```
and chrome will automatically add hyphen as preffix like below
`-sutff_2017_xx_xx.xlsx`

**Comment by jonathanong** [comment]
sorry, what's the bug for koa? seems like a chrome issue, not a koa issue.

**Comment by azl397985856** [comment]
seem like you'r using the post method. try "get" instead
