### ISSUE TITLE
[question] is there an event when the response end?

### ISSUE THREAD

**Issue by tuananh** [koajs/koa#1097]
i would like to capture when the response end, is there something like this in koa?

```js
ctx.res.on('end', cb)
```

**Comment by carlisliu** [comment]
ctx.res.on('finish', cb)

**Comment by tuananh** [comment]
@carlisliu thank you. i can't find it on context api documentation. is it mentioned somewhere else?

**Comment by fl0w** [comment]
@tuananh `ctx.res` references core http, https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_event_finish
