### ISSUE TITLE
Performance issue while returning a large Object

### ISSUE THREAD

**Issue by greguz** [koajs/koa#1099]
I have a 1.7MB object to send.

Doing this will cause a *TTFB* time of 330ms (that's ok) and a *Content download* time of 4s in Chrome.
```javascript
router.get('/heavy', async function heavyRoute(ctx, next) {
  const result = await collectHeavyData()
  ctx.body = result // my 1.7MB object
  console.log('less than 100ms and we are here')
})
```

The same logic written with .NET cause a *TTFB* time of 2s (that's ok, my bad) and a *Content download* time of **92ms**.

The response are the same, the Koa route code execute in less than 100ms, but the client get the complete response really slowly.

Am I missing something?

**Comment by greguz** [comment]
The issue appear even on production mode.

**Comment by greguz** [comment]
## SW stack
- Node.js 8.9.1
- Typescript 2.6.1
- koa 2.4.1
- koa-router 7.3.0

**Comment by jonathanong** [comment]
try using streams or a more optimized `JSON.stringify()` module

**Comment by ChBernat** [comment]
Just as @jonathanong wrote, @greguz - use Streams since it is where Node.js shines and has the biggest advantage over other back-end technologies. Stream will basically divide your object/file into small chunks of data and send them one by one. It may sounds crazy but results are astonishing.

**Comment by fl0w** [comment]
I am going to close this issue. Feel free to re-open if you still believe this to be an issue with Koa.
