### ISSUE TITLE
Use https://koajs.com vs. http://koajs.com?  Or use JS.org as https://koa.js.org

### ISSUE THREAD

**Issue by niftylettuce** [koajs/koa#1101]
Thoughts on using an SSL for the docs?  Would be nice.

**Comment by dotnil** [comment]
I believe koajs.com is hosted by Github Pages which supports custom domain but once you've got custom domain enabled the ssl part is a no-no.

**Comment by fl0w** [comment]
Yes, koajs.com leverages Github Pages, which does not support custom domain SSL.
This can be closed IMO.

**Comment by niftylettuce** [comment]
This should be kept open until https://koajs.com is up.

**Comment by niftylettuce** [comment]
See see https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b or https://medium.freecodecamp.org/an-illustrated-guide-for-setting-up-your-website-using-github-cloudflare-5a7a11ca9465.

Another alternative is to wildcard redirect koajs.com to koa.js.org and then use <https://dns.js.org/>

**Comment by fl0w** [comment]
How about creating an issue when it's actually practical? Github Pages does not support SSL and there's allot requests and petitions submitted regarding it - it's not like it'll get forgotten.

Proxying via Cloudflare or similar services is just overdoing it IMO, what's the benefit/burden ratio :). It's just docs and it'll be fixed as soon as Github supports SSL for custom domains.

**Comment by marswong** [comment]
I think we can try [Cloudflare](https://www.cloudflare.com/).

**Comment by fl0w** [comment]
This is now possible to fix, https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by niftylettuce** [comment]
thanks for letting us know, pinging @jonathanong

**Comment by niftylettuce** [comment]
resolved https://koajs.com/
