### ISSUE TITLE
Assertion Error: Headers already sent

### ISSUE THREAD

**Issue by haxxorsid** [koajs/koa#1107]
Code:
https://gist.github.com/haxxorsid/348169a3a6c93ee241dfdb8170709651
Run:
```
git clone https://gist.github.com/haxxorsid/348169a3a6c93ee241dfdb8170709651.git
cd 348169a3a6c93ee241dfdb8170709651
npm install
npm start
```
In browser: `http://localhost:3000/my-scale/resize/100/123?url=image.jpg`
It resizes image.jpg(without overwriting the file) to 100width & 123height and displays that in browser.

Error:
`AssertionError [ERR_ASSERTION]: headers have already been sent`

Can someone solve this issue for me. Maybe this issue is not at all related to koajs.

**Comment by fl0w** [comment]
Yea, that entire request isn't wrapped in a promise. The promise resolves and Koa returns, then you set status.

Make sure your middleware returns a promise which resolves after you set `ctx.status`.

**Comment by haxxorsid** [comment]
@fl0w I didn't understood. I am new to this, can you give me a example code?

**Comment by jeffijoe** [comment]
@haxxorsid I wrote an article describing how Koa middleware works, including an example that covers why your code does not work (and @fl0w gave the correct answer) so I hope it will explain it in more detail for you: https://medium.com/netscape/mastering-koa-middleware-f0af6d327a69

**Comment by haxxorsid** [comment]
@jeffijoe 
Did as you and fl0w said:
```

router.get('/my-scale/resize/:width/:height?', async(ctx, next) => {
  const protocol = (options.baseHost.startsWith('https')) ? https : http
		let format = 'webp'

		const imageUrl = getImageUrl(options.baseHost, ctx.query.url)

		const width = parseInt(ctx.params.width, 10)
		const height = parseInt(ctx.params.height, 10) || null
		const transformer = transform(width, height).on('error', function sharpError(err) {
        ctx.status = 500;
        next(new Error(err))
      })

		const etagBuffer = Buffer.from([imageUrl, width, height, format])
		ctx.set('ETag', etag(etagBuffer, {weak: true}))
		if (ctx.fresh) {
			ctx.status = 304;
			next();
		}
		        const request = new Promise(resolve => protocol.get(imageUrl, resolve));
        const result = await request;
		

        if (result.statusCode >= 400) {
          ctx.status = result.statusCode;
		  next();
        }
        ctx.status = result.statusCode;
        const inputFormat = result.headers['content-type'] || ''
        format = format || inputFormat.replace('image/', '')

        format = sharp.format.hasOwnProperty(format) ? format : 'jpeg'

        ctx.type = 'image/' + format
        result.pipe(transformer).pipe(ctx)

});
```

What is wrong in this?

**Comment by jeffijoe** [comment]
All the places you use `next()` you need to `return next()` instead. Please read the article to understand why. 😄

**Comment by haxxorsid** [comment]
Ok I rectified and updated the gist. I am receiving a 404 not found. I think the route is unreachable, do you have any idea?

**Comment by jeffijoe** [comment]
@haxxorsid another thing I noticed, https://gist.github.com/haxxorsid/348169a3a6c93ee241dfdb8170709651#file-server-js-L36

You should not pass anything to `next()`; if you want to throw an error, you should just `throw` it.

Additionally, I don't think `ctx` is a Stream, so you might want to pipe to `ctx.res` instead.

**Comment by haxxorsid** [comment]
@jeffijoe Ok fixed and updated the gist. I am receiving "OK" on screen. Almost close the complete this...

I expect output to be like this:
![image](https://user-images.githubusercontent.com/13928803/34161752-945b393e-e4f7-11e7-8e5c-043304e5f4ea.png)

But I am getting output like this:
![1](https://user-images.githubusercontent.com/13928803/34161812-c3658496-e4f7-11e7-977e-a00e444c4b92.JPG)

**Comment by jeffijoe** [comment]
Actually, instead of `result.pipe(transformer).pipe(ctx.res)`, try `ctx.body = result.pipe(transformer)`

**Comment by haxxorsid** [comment]
WORKED!!!

**Comment by haxxorsid** [comment]
![a9ade90862c01733bbd7f56e883eb60b18c899d6119a040bd58609f6ef0a0aad](https://user-images.githubusercontent.com/13928803/34161983-41fd97e4-e4f8-11e7-8af0-3b19673a3d69.jpg)
