### ISSUE TITLE
Intermittent build failures on Node 8

### ISSUE THREAD

**Issue by nickmccurdy** [koajs/koa#1109]
There's a daily cron job that's been failing for a while with a syntax error on Node 8 that appears to be intermittent. Here's an example of two cron builds using the same commit, only one fails. I'm guessing it's a bug in Jest's transpilation and/or cache.

https://travis-ci.org/koajs/koa/builds/317786352
https://travis-ci.org/koajs/koa/builds/318262778

```
> jest "--coverage"

 FAIL  test/context/cookies.js
  ● Test suite failed to run

    /home/travis/build/koajs/koa/lib/response.js:7
    }});
      ^
   
    SyntaxError: Unexpected token )
     
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (lib/application.js:11:68)
      at Object.<anonymous> (test/context/cookies.js:6:13)
```

**Comment by jonathanong** [comment]
@nickmccurdy ^ did this fix it?

**Comment by KentonYu** [comment]
#1139    the same question
