### ISSUE TITLE
flow-typed: property not found on mixed

### ISSUE THREAD

**Issue by budarin** [koajs/koa#1110]
```js
import type { Request } from 'koa';

function SetProps(request: Request) {
   request.state.someProp = {....};
                  ^^^^ Error: property `someProp`. Property not found in mixed
}
```

**Comment by fl0w** [comment]
While I've never used flow I'm assuming you're looking for `ctx.state` which is a reserved property for user-land.

**Comment by budarin** [comment]
it inherited Request from Context in JS but not declared in Flow-typed file

**Comment by fl0w** [comment]
I'm sorry, that doesn't make sense to me but that's irrelevant.

This (koajs/koa) repo doesn't define flow typings, so I suggest you take this question to whichever repo that provides those.

**Comment by budarin** [comment]
thanks, I'll try in flow-typed
