### ISSUE TITLE
Conflicting routes when declared with prefix keyword

### ISSUE THREAD

**Issue by sujaykakkad** [koajs/koa#1117]
I have written this piece of code
```js
const Koa = require("koa");
const Router = require('koa-router');
const app = new Koa();

const parentRouter = new Router()
const router = new Router({ prefix: '/countries'})

router.get('/', async(ctx) =>{
    console.log('countries called');
    ctx.body = {}
})

parentRouter.use(router.routes())

app.use(parentRouter.routes())

app.listen(3000);

console.log('Listening on port 3000')
```

When I call
`localhost:3000/countries`  then it prints `countries called`
But it is conflicting with other routes also
`localhost:3000/some_route_1/countries` prints `countries called`
`localhost:3000/some_route_1/some_route_2/countries` prints `countries called`
`localhost:3000/some_route_1/some_route_2/some_route_3/countries`  prints `countries called`
and so on

I guess it is adding it as suffix instead of prefix

**Comment by fl0w** [comment]
Please turn to https://github.com/alexmingoia/koa-router/issues instead

**Comment by sujaykakkad** [comment]
ok I realised that...
