### ISSUE TITLE
how to modify request before proxying?

### ISSUE THREAD

**Issue by JoeyAspire** [koajs/koa#1118]
Dear friends, i meet a problem, can anybody help :

I starts two different koa **https** servers, namely Svr1 and  Svr2.

When Svr1 receives a post  request, i need to add some params into the form and then proxy it to Svr2.

how can i accomplish that ?

by the way , cookies also need to be proxied to Svr2

**Comment by JoeyAspire** [comment]
by the way, cookies also need to be proxied to Svr2 ~ thanks a lot

**Comment by fl0w** [comment]
Take a look at either of these (in no particular order):
 * https://github.com/popomore/koa-proxy
 * https://github.com/vagusX/koa-proxies
 * https://github.com/nsimmons/koa-better-http-proxy

**Comment by JoeyAspire** [comment]
@fl0w thanks bro~ 
but it seems that none of them support modifing form content before proxying?

**Comment by fl0w** [comment]
https://github.com/nsimmons/koa-better-http-proxy has decorators. I'm unfamiliar with all of them.

**Comment by JoeyAspire** [comment]
@fl0w thanks a lot my friend~
