### ISSUE TITLE
Get port koa is running on

### ISSUE THREAD

**Issue by rightaway** [koajs/koa#1122]
Is there a koa equivalent of `server.address().port` in express that can be used to print out the port that koa is running on? If not would be nice to have available.

**Comment by fl0w** [comment]
```js
const Koa = require('koa')
const app = new Koa()
const server = app.listen(3000)
constole.log(server.address().port)
// -> 3000
```

**Comment by raitono** [comment]
I ran across this in a search and figured I would share my knowledge.

If you are using Typescript, you must take an extra step to cast the `address` function to the correct type before you can access the `port`. Otherwise you get errors about `port` not existing.

```javascript
import { AddressInfo } from 'net';  
const port = (<AddressInfo>server.address()).port;
```
