### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by s3y** [koajs/koa#1125]

**Comment by fl0w** [comment]
That getter isn't an attemp at mitigating CSRF attacks.

There's however two packages under koajs org which do, https://github.com/koajs/csrf and https://github.com/koajs/stateless-csrf

**Comment by s3y** [comment]
Like this:
https://github.com/VictorKid/backend-demo/blob/3319d12dbbb564c0f82528836950676947525714/middlewares/ensureReferer.js
