### ISSUE TITLE
Response headers will be ignored/removed while using ctx.throw.

### ISSUE THREAD

**Issue by LvChengbin** [koajs/koa#1127]
```js
ctx.set( 'Access-Control-Allow-Origin', '*' );
ctx.throw( 404 );
```
By using the code above, the header of `Access-Control-Allow-Origin` will not be sent with responding. Even though I can use `res.statusCode` instead, but I think the `ctx.throw` method should not remove response headers.

Koa@2.4.1
Node@8.9.3

**Comment by jonathanong** [comment]
yes, that is by design. this should be handled by an error handler:

```js
app.use(async (ctx, next) => {
  try {
    await next()
  } catch (err) {
    ctx.set('Access-Control-Allow-Origin', '*')
    ctx.status = err.status
})

app.use(async (ctx) => {
  ctx.throw(404)
})
```

**Comment by mutoe** [comment]
According to my usage, you also put it in the try block like this
``` js
app.use(async (ctx, next) => {
  try {
    ctx.set('Access-Control-Allow-Origin', '*')
    await next()
  } catch (err) {
    ctx.set('Access-Control-Allow-Origin', '*')
    ctx.status = err.status
})
```
Otherwise, there will be no header you set in the normal code.

**Comment by snuggs** [comment]
@mutoe @jonathanong @LvChengbin  FWIW we use the second parameter in `context.throw`. YMMV

![capture d ecran 2018-04-10 a 16 52 26](https://user-images.githubusercontent.com/38223/38583026-ab932c70-3cdf-11e8-8240-8ecd4be6e0c0.png)

**Comment by lichangwei** [comment]
any updates? I am also confused about this problem.

**Comment by niftylettuce** [comment]
Feel free to use https://github.com/ladjs/koa-better-error-handler.
