### ISSUE TITLE
Response 'Not Found' while using setTimeout

### ISSUE THREAD

**Issue by LvChengbin** [koajs/koa#1135]
```js
app.use( async ( ctx, next ) => {
    await new Promise( resolve => {
        setTimeout( resolve, 100 );
    } )
    ctx.body = 'xxxxxxxxxxxx';
} );
```

I got a `404` after visiting.

**Comment by carlisliu** [comment]
const Koa = require('koa');
    const app = new Koa();
    app.use( async ( ctx, next ) => {
        await new Promise( resolve => {
            setTimeout( resolve, 100 );
        } )
        ctx.body = 'xxxxxxxxxxxx';
    } );

    app.listen(3000);

I got 'xxxxxxxxxxxx', nothing wrong.

**Comment by dead-horse** [comment]
please check other middleware if you have.

**Comment by pyuyu** [comment]
> ```
> const Koa = require('koa');
> const app = new Koa();
> app.use( async ( ctx, next ) => {
>     await new Promise( resolve => {
>         setTimeout( resolve, 100 );
>     } )
>     ctx.body = 'xxxxxxxxxxxx';
> } );
> 
> app.listen(3000);
> ```
> 
> I got 'xxxxxxxxxxxx', nothing wrong.

owing to what?  event-loop?
