### ISSUE TITLE
How to detect when function is executed in 'upstream' ?

### ISSUE THREAD

**Issue by myuseringithub** [koajs/koa#1140]
I would like to ignore a second 'next()' call if a previous one was called. Something the following on the second 'next()' in the middleware: 
`if(context.requestFlow != 'upstream') await next()`
(currently I'm getting 'Error: next() called multiple times')
The first 'next()' call is conditionally called. basically implemented dynamic middleware array execution. 
What's my options ?
Thanks

**Comment by fl0w** [comment]
```js
app.use(async (ctx, next) => {
})
```

**Comment by fl0w** [comment]
This reads like code smell, but to answer your question you could just set `ctx.state.nextCalled = true` before your `await next()`, and then just check for it before your if-condition.

**Comment by myuseringithub** [comment]
I see, I think it would be helpful if request/stream flow detection feature is implemented, where a field like Boolean "nextCalled" or even better String "upstream"/"downstream" is added. 

Side note - I've developed a graph-like middleware composition, where middlewares are combined on runtime depending on the request. Which in part also allows visual composition of middlewares through an interface.
