### ISSUE TITLE
Send a file after event 'close'

### ISSUE THREAD

**Issue by megabatz** [koajs/koa#1149]
`async create(ctx) {
    const archive = 'some/path/to/someArchive.zip';
    const stream = fs.createWriteStream(archive); //1 - create stream
    // 2 - write data into the archve, it's going to take some time

    stream.on('close', () => { // 3 - when all processes with this stream will closed
        ctx.attachment(filename); //4 - prepare headers
        ctx.set('Content-Type', mimetype);
        ctx.body = fs.createReadStream(archive); // 5 - and send client this file
    });
  },`
How can I do this?))

**Comment by fl0w** [comment]
Stick that into a promise and resolve after assigning a stream to ctx.body, e.g.

```js
app.use(async ctx => {
  await new Promise((resolve, reject) => {
    const stream = fs.createWriteStream(...)
    stream.on('close', () => {
      ctx.body = fs.createReadStream(...)
      resolve()
    })
  })
})
```

**Comment by megabatz** [comment]
Thanks for answer. It's work and I already did something similar))
