### ISSUE TITLE
task for global sidebar/footer

### ISSUE THREAD

**Issue by andreaslacza** [koajs/koa#1154]
i have this routes:
router.use('/about/', about.routes()
router.use('/blog/', blog.routes()
router.use('/imprint/', imprint.routes())
router.use('/', index.routes())
router.use('/user/:id/', user.routes())
app.use(router.routes())

and every page of this route has the same global sidebar with information about the latest blogs. Now i have a query for this (blogs on sidebar) on every route.
query database for blogs -> save result to variable -> render page with sidebar

Is it possible to to query this once on every request and set the result to a global variable and share this to the routes?

Example:
1: User visit the website
2: Koa query the results for the the sidebar (route: /)
3: User see the sidebar on the webpage
4: User click on a blog (new page route: /blog/)
5: Koa share the result of the sidebar (Point 2)
6: User see the sidebar on the webpage
...

**Comment by fl0w** [comment]
Yes, create a middleware and put the results in ctx.state

```js
router.use(async (ctx, next) => {
  ctx.state.sidebar = await queryDbForSiderbar()
  await next()
})

router.use('/about', about.routes())
// ... etc
```

**Comment by fl0w** [comment]
Closing this issue as it's not an issue with the library.

If my example was to constrained and/or you're still struggling with the problem, feel free to continue the discussion here (even though it's closed).

For future reference, there are more appropriate venues for general usage question like these - and will probably yield better explanations and examples, for your own sake!
