### ISSUE TITLE
Support "Forwarded" header

### ISSUE THREAD

**Issue by victorandree** [koajs/koa#1155]
The "Forwarded" header is the standardized replacement for `X-Forwarded-For`, `X-Forwarded-Proto` et cetera. If koa supports the latter, it should support the former when `app.proxy = true`.

* X-Forwarded-For is currently used for `ctx.ip`. It should support (and prefer) `Forwarded: for=192.168.0.1`
* X-Forwarded-Proto is currently used to determine protocol (for secure cookies). It should support (and prefer)`Forwarded: proto=https`

The [forwarded-parse](https://github.com/lpinca/forwarded-parse) package can be used to parse the header, or it could be done in-house.

I could potentially write a PR for this if there's interest. 

* [MDN article on Forwarded header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded)
* [RFC 7239](https://tools.ietf.org/html/rfc7239)

**Comment by seminelee** [comment]
我设置了`app.proxy = true`仍然无效，

**Comment by jonathanong** [comment]
https://github.com/koajs/koa/issues/281
