### ISSUE TITLE
What does ctx.app.emit does?

### ISSUE THREAD

**Issue by bertolo1988** [koajs/koa#1162]
I saw it here: https://github.com/koajs/koa/wiki/Error-Handling

**Comment by fl0w** [comment]
A Koa application extends the internal EventEmitter.
`ctx.app.emit` simply emits an event with a type, defined by the first argument. For each event you can hook on "listeners", which is a function that is called when the event is emitted.

Take a quick look at http://koajs.com/#error-handling and the official node.js documentation on [EventEmitters](https://nodejs.org/docs/latest-v8.x/api/events.html)

**Comment by bertolo1988** [comment]
Thanks for the answer @fl0w .
