### ISSUE TITLE
Whitelisting parameters in post/put request

### ISSUE THREAD

**Issue by BlueAccords** [koajs/koa#1165]
Sorry if this isn't the best place to ask but is there a standard way, or recommended library to support the equivalent of strong parameters from ruby on rails aka a way to whitelist parameters sent to post/put requests to ensure users are only allowed to change specific columns when trying to insert/update data?  

I found this library https://github.com/ssowonny/strong-params but it seems like it might not support koa v2 since there's an unresolved pull request that says `Update to koa v2.x middleware`

**Comment by fl0w** [comment]
That package looks quite unobtrusive - have you tried it? Due to koa-convert in Koa that package should "just work".

**Comment by BlueAccords** [comment]
Sorry for the late reply, I'll take a look at it. I also found https://github.com/oscaroox/objection-visibility which also might work since i'm using the objectionjs library

**Comment by fl0w** [comment]
I am going to close this as you seem to have found a solution.

**Comment by BlueAccords** [comment]
No problem, thanks!
