### ISSUE TITLE
Question on Memory growing

### ISSUE THREAD

**Issue by KingWu** [koajs/koa#1167]
My Koa application found memory leakage issue. I tried Koa Hello world sample. 

Using process.memoryUsage().
To check rss, heap total and heap used.

i call gc() everytime when i call to print Hello world.
I found that the heap used is slowly growing. 

Any idea on this?

**Comment by fl0w** [comment]
What version of Koa and node.js are you on?

This sounds odd and weird because I'm running multiple Koa applications without any issue as we speak.

Could you provide full minimal reproducible code you're using?

**Comment by fl0w** [comment]
For how long are you running the application? Growing heap isn't necessarily a leak when observed at low load at upstart, but it should stabilise.

**Comment by KingWu** [comment]
Koa: 2.5.0
Nodejs: 8.9.4

My Koa application run on VPS with 1g memory. Running about two days, it reach memory usage 90%. And then, out of memory to crash app. Normally, what code in Nodejs cause memory leakage?

For sample Code, i just use Hello Koa Sample code.
`app.use(ctx => {
  ctx.body = 'Hello Koa';
  global.gc();
});`

Any idea to trace memory growing issue?

**Comment by JacksonTian** [comment]
Hi @KingWu , You can use  https://www.aliyun.com/product/nodejs  to monitoring your application. And use heap dump can help you find the memory leak reason.

**Comment by KingWu** [comment]
@JacksonTian Thx for your suggestion. i set up typescript and webpack for development. I found that the webpack has memory leak issue.

**Comment by brian221** [comment]
My team identified a similar issue today.   Each time we called `ctx.render` in a route, it was holding onto the memory to generate that page (about 12kb per request).

**Comment by antgonzales** [comment]
Bump. I'm experiencing an issue where I create a render string of js to output to the main template. I save the string to `ctx.state.analytics` and it seems to retain it multiple times over. I'm using nunjucks templating to construct the template.

![image](https://user-images.githubusercontent.com/3740655/45042874-bf113300-b039-11e8-8ba5-74989cefd20b.png)

**Comment by fl0w** [comment]
@antgonzales please provide a fully reproducible example (with anything unrelated to Koa excluded) or I can't deduce your issue to be a Koa issue. An image gives nothing tangible.

**Comment by tehnuty** [comment]
Bump. The same issue here. Whenever we call ctx.render() it was holding that in a memory (as @brian221 was telling, about 12kb per request <- which is about 18gb/hour during low traffic on our site)

**Comment by edevil** [comment]
@tehnuty can you provide a repository with the minimal code to reproduce this issue, please?

**Comment by tehnuty** [comment]
@edevil the issue was not in Koa itself. I've changed nodejs from 7.x to 9.x and the memory leak was gone.
