### ISSUE TITLE
Response.redirect How to remove # words

### ISSUE THREAD

**Issue by zhailei31665431** [koajs/koa#1171]
Before Url : http://localhost:4000/#/home

Use response.redirect('/login')

After Url : http://localhost:4000/login#/home

How to remove # and they after words

**Comment by fl0w** [comment]
I am going to close this issue as there's insufficient information to do anything with it. If you still feel this is a Koa library issue please provide a minimal reproducible example and reopen the issue.

**Comment by hyingreborn** [comment]
I had the same problem...
