### ISSUE TITLE
ctx.accept seems to be a unused property

### ISSUE THREAD

**Issue by initial-wu** [koajs/koa#1176]
https://github.com/koajs/koa/blob/13086d2fcd5559296f473b4c7bbd56021f9cb373/lib/application.js#L175
`request.accept` could only be accessed indirectly through `request.accepts()`. But there is no method or getter/setter using the `ctx.accept` and it is not declared as a public API.

**Comment by fl0w** [comment]
`context.accept` is actually not ment to be meddled with by user, but the result from [accepts](https://github.com/jshttp/accepts). There's a description written down [here](https://koajs.com/#content-negotiation) so I'm going to close this.
