### ISSUE TITLE
query Parsing error

### ISSUE THREAD

**Issue by shengxq** [koajs/koa#1178]
http://192.168.10.153:88/?id=8448508&signature=tLPfwo/8N+QSQxhWo4zrxQ=="

query:Object
{
    id:"8448508",
    signature:"tLPfwo/8N QSQxhWo4zrxQ=="
}

Less one + symbol

**Comment by fl0w** [comment]
That's not an error, and how parsing usually works. Koa uses native [querystring](https://nodejs.org/api/querystring.html) implementation.

If you want to parse it with a different strategy you can access the raw querystring via `ctx.querystring`.
