### ISSUE TITLE
I get status 404 with async functions no matter what

### ISSUE THREAD

**Issue by gh67uyyghj** [koajs/koa#1179]
Hi all, this is most probably a question not a bug since it's very common but I don't know what's wrong with my code. This is a simple example that results in 404 with `Not Found` default body instead of applying my body and status codes

```
async function AsyncHandler(ctx) {
  ctx.body = await new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve({
        a: 'lol',
        b: 'wut'
      })
    }, 100);
  })  
  ctx.status = 200
}
```

, I have tried many other examples that require async operations like dealing with database and in most cases I get the same thing: 404 with `Not Found`, what's wrong here?

UPDATE: I use this function with koa router

**Comment by fl0w** [comment]
There's insufficient information to help here. There's nothing wrong in Koa with handling async functions. You probably have some other middleware that aren't behaving correctly. A common mistake is to `return next` (i.e. not calling next as a function), or simply doing `next()` (i.e. not returning or awaiting the next call).

**Comment by fl0w** [comment]
I am closing as this seems unrelated to Koa library. If you still feel this is an issue with the library please reopen and provide a minimal reproducible example.

If you still have issues getting it to work feel free to continue discussion here even though it's closed.
