### ISSUE TITLE
Release 2.5.1

### ISSUE THREAD

**Issue by BridgeAR** [koajs/koa#1185]
Currently koa fails in https://github.com/nodejs/citgm and it got fixed here already but a new version has to be released to stop showing up in `citgm` as failed.

Therefore it would be great to release v.2.5.1 :-).

**Comment by fl0w** [comment]
related PR https://github.com/koajs/koa/pull/1170 merged at https://github.com/koajs/koa/commit/13086d2fcd5559296f473b4c7bbd56021f9cb373

**Comment by dead-horse** [comment]
2.5.1 released. 😀
