### ISSUE TITLE
ctx.url has the same content as ctx.href

### ISSUE THREAD

**Issue by kmathmann** [koajs/koa#1187]
I have the problem that ctx.url has the same content as ctx.href. 
But this is only the case if our HAProxy makes health checks to the API.

**From HAProxy health check:**
* ctx.href = http://app.example.com/health
* ctx.url   = http://app.example.com/health
* header = `{"connection":"close"}`

**From a Client over HAProxy**
* ctx.href = https://app.example.com/health
* ctx.url   = /health
* header
   ``` json
   {
     "cache-control": "no-cache",
     "user-agent": "PostmanRuntime/7.1.1",
     "accept": "*/*",
     "host": "app.example.com",
     "accept-encoding": "gzip, deflate",
     "x-forwarded-for": "172.16.2.123, 172.16.2.123",
     "x-forwarded-port": "443",
     "x-forwarded-proto": "https",
     "connection": "close"
   } 
   ```

Could it be a problem with missing headers at the HAProxy request?

**Comment by kmathmann** [comment]
I tested the API (Running local on my windows maschine) without any proxy and got the same behavior as the HAProxy health check.

I called the API from an Linux maschine over my the dns name of my computer.

**Script with that i called the API from the Linux maschine**
```
sed $'s/$/\r/' <<EOF | nc mypc.example.com 3000
GET http://mypc.example.com:3000/health HTTP/1.1
cache-control: no-cache,
user-agent: PostmanRuntime/7.1.1,
accept: */*,
host: mypc.example.com:3000,
cookie: AspxAutoDetectCookieSupport=1,
accept-encoding: gzip, deflate,
connection: keep-alive

EOF
```

**Result with netcat from the Linux maschine**
```
{ url: 'http://mypc.example.com:3000/health',
  href: 'http://mypc.example.com:3000/health',
  header:
   { host: 'mypc.example.com:3000',
     'cache-control': 'no-cache,',
     'user-agent': 'PostmanRuntime/7.1.1,',
     accept: '*/*,',
     cookie: 'AspxAutoDetectCookieSupport=1,',
     'accept-encoding': 'gzip, deflate,',
     connection: 'keep-alive' } }
```
**Result with Postman from my Windows maschine**
```
{ url: '/health',
  href: 'http://mypc.example.com:3000/health',
  header:
   { 'cache-control': 'no-cache',
     'user-agent': 'PostmanRuntime/7.1.1',
     accept: '*/*',
     host: 'mypc.example.com:3000',
     cookie: 'AspxAutoDetectCookieSupport=1',
     'accept-encoding': 'gzip, deflate',
     connection: 'keep-alive' } }
```

**Comment by fl0w** [comment]
Koa isn't really doing anything other than delegating ctx.url to Request.url which in turn returns http.Request.url. Can you replicate this using a native server alone (without Koa)?.

**Comment by kmathmann** [comment]
Yes i can replicate this using a native server.

Thanks for your answer.
