### ISSUE TITLE
Find original RegexUrl

### ISSUE THREAD

**Issue by dmpvost** [koajs/koa#1191]
Hi,

There is a way to print the original RegexUrl which was use for match the routing inside a function?

If I do this : 
"/favoris/3"

I would like to be able to print 
"/fav/:id"

I need to find the regex for make some extra analyse with swagger.
Thank!

**Comment by likegun** [comment]
If you are using `koa-router`, you can access it by `ctx.matched`.

**Comment by dmpvost** [comment]
Thank! exactly what I needed!

**Comment by likegun** [comment]
@dmpvost Please close this if it's done.
