### ISSUE TITLE
Removing index signature from Typescript type definition for Context

### ISSUE THREAD

**Issue by davewasmer** [koajs/koa#1196]
I realize Koa is not a Typescript project, but I wanted to call out a potentially big change I'm proposing to the type definition over on DefinitelyTyped. DefinitelyTyped has a policy of automatically merging PRs that have no comments/objections, and I'd like to make sure this doesn't sneak in under the radar of anyone.

The full explanation can be found on [my DefinitelyTyped PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26008), but the tl;dr is:

Remove the index signature from the Context interface to enforce stricter type checking. You can add it back yourself if you prefer a looser approach, but going the other direction (i.e. removing the index signature in your own project to enforce stricter types) is not currently possible in Typescript.

This means that by default you won't be able to randomly assign properties to `ctx` anymore - you'd need to augment the Koa module with the property's type definition:

```ts
declare module 'koa' {
  export interface Context {
    myCustomProp: boolean;
  }
}
```

Or add the index signature to get back today's behavior:

```ts
declare module 'koa' {
  export interface Context {
    [key: string]: any;
  }
}
```

**Comment by deefour** [comment]
@davewasmer both `BaseContext` and `Context` type interfaces are within an [`Application` namespace](https://github.com/davewasmer/DefinitelyTyped/blob/e711b702bfbc0f080992ca3d452883fe56c65388/types/koa/index.d.ts#L526) not mentioned in your examples for restoring the previous behavior. 

The examples provided as is aren't working for me. Typscript complains about parameters on my context that aren't assignable. It's entirely possible I'm doing something wrong. 

My `tsconfig.json` has

```js
{ 
  // ...
  "files": [
    "./types.d.ts"
  ]
}
```
and my `types.d.ts` file has had what you've provided in your 2nd example as well as the following:

```typescript
declare module 'koa' {
  namespace Application {
    interface Context {
      [key: string]: any;
    }
  }
}
```

Is this a configuration issue on my end not picking up the type declaration for merging, or is there something wrong with these attempts at restoring the previous behavior?

**Comment by abenhamdine** [comment]
Good idea, it would be very usefull

**Comment by fl0w** [comment]
Thank you for posting this. I'm closing this informational issue as it's still searchable.
