### ISSUE TITLE
cannot use ctx in promise'then

### ISSUE THREAD

**Issue by Chen-WeiZhen** [koajs/koa#1200]
```
  static  like(ctx){
    const {unionId,topicId} = ctx.request.body
    console.log(unionId);
    LikeModel.findOrCreate({
      where:{topicId},
      defaults:{
        unionId,topicId
      }
      // attributes: { exclude: ['id'] } 
    }).spread(async (data,created)=>{
      if(created){
        ctx.body={mes:'success'}
      }else{
        console.log(23232)
        await LikeModel.destroy({
          where:{topicId}
        }).then((res)=>{
          console.log(res)  //above here is ok
          ctx.status = 200
          ctx.body = {mes:'fail'}
        })
      }
    })
  }
```

just the last code  do not works
``
 ctx.status = 200
ctx.body = {mes:'fail'}
```

why??

**Comment by fl0w** [comment]
I am going to close this as I believe you've either solved it yourself or got help elsewhere. Feel free to reopen if your problem still persist.

However, there's generally better venues to getting help on common usage issues. This tracker is generally intended for library development and discussion surrounding it. Try Stach Overflow, IRC och Gitter for (probably) better and faster response times.
