### ISSUE TITLE
cannot set object to ctx.body

### ISSUE THREAD

**Issue by djrolleyes** [koajs/koa#1208]
As I know from api, ctx.body could be Object || Array json-stringified. There is no problems with array, but I can't response with object, only blank one {}. If I have somthing inside such as key/value, for example {foo: 'bar'} browser has no response data available. But if I put it in array it's ok. What is it?

**Comment by jasonmacgowan** [comment]
@djrolleyes can you show an example of what's failing for you?  This works as expected for me:

server.js
```
const Koa = require('koa');
const app = new Koa();

app.use(ctx => {
  ctx.body = { foo: 'bar' };
});

app.listen(8080);
```

testing the server
```
$ curl http://localhost:8080/ --verbose
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.59.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Content-Length: 13
< Date: Mon, 18 Jun 2018 18:50:55 GMT
< Connection: keep-alive
<
{"foo":"bar"}
```

**Comment by djrolleyes** [comment]
@jasonmacgowan shure. that's what I do

`const Koa = require('koa');
const app = new Koa();
const router = require('koa-router')();
const koaBody = require('koa-body');
const ObjectId = require('mongodb').ObjectID;
const logger = require('koa-logger');
let MongoClient = require('mongodb').MongoClient;
let db;

app.use(logger());
app.use(router.routes());


router.get('/search/banner/:query/:page?', async(ctx, next) => {

  var query = ctx.params.query
  var page = ctx.params.page

  var pageSize = 10;

  var numberOfpages;

  if(!page){

    page = 1
  }

  var sea = [ query ];
  var regex = [];
  for (var i = 0; i < sea.length; i++) {
      regex[i] = new RegExp(sea[i]);
  }

  ctx.set('Access-Control-Allow-Origin', '*');
  ctx.body = await db.collection('banners').count({"tags": {$in: regex}}).then(async (numberOfDocuments) =>{

    var numberOfpages = (numberOfDocuments % pageSize > 0) ? Math.floor(numberOfDocuments / pageSize) : numberOfDocuments / pageSize;

    return await db.collection('banners').find({"tags": {$in: regex}}).skip((page === 1) ? 0 : pageSize*(page-1)).limit(pageSize).toArray().then(array => {

      var obj = {
                documents: array,
                pagesNum: numberOfpages,
                totalDocs: numberOfDocuments,
                currentPage: parseInt(page)
              };


      return [obj] // ok
      return obj // not ok

    });
  });
});`

**Comment by juzhiyuan** [comment]
@djrolleyes  if you separate the code below , just assign the data to an variable , maybe it will work.

**Comment by djrolleyes** [comment]
@juzhiyuan below what? sorry, not sure I've got a hint.

**Comment by juzhiyuan** [comment]
```js
    ctx.body = await db.collection('banners').count({
        "tags": {
            $in: regex
        }
    }).then(async(numberOfDocuments) =>{

        var numberOfpages = (numberOfDocuments % pageSize > 0) ? Math.floor(numberOfDocuments / pageSize) : numberOfDocuments / pageSize;

        return await db.collection('banners').find({
            "tags": {
                $in: regex
            }
        }).skip((page === 1) ? 0 : pageSize * (page - 1)).limit(pageSize).toArray().then(array = >{

            var obj = {
                documents: array,
                pagesNum: numberOfpages,
                totalDocs: numberOfDocuments,
                currentPage: parseInt(page)
            };

            return [obj] // ok
            return obj // not ok
        });
    });
```

![image](https://user-images.githubusercontent.com/2106987/41717096-e2bb0a22-7558-11e8-96dd-821e205738b5.png)


Maybe you complex the usage of await and then

**Comment by djrolleyes** [comment]
@jasonmacgowan not sure what so complex. all of this returns the correct data. But I'm pretty sure, koa parse body the weird way. Have to look at the source code.

**Comment by fl0w** [comment]
There's something wrong with the flow of your code, and has nothing to do with Koa.
I've done some cleanup to easier understand what's going on and cannot replicate your problem.

```js
'use strict'
const Koa = require('koa');
const app = new Koa();
const router = new require('koa-router')()
const koaBody = require('koa-body')
const logger = require('koa-logger')

// Lazy mock
const db = {
  collection () {
    return this
  },
  count () {
    return 12
  },
  find () {
    return this
  },
  skip () {
    return this
  },
  limit () {
    return this
  },
  toArray () {
    return [1, 2, 3, 4]
  },
}

router.get('/search/banner/:query/:page?', async ctx => {
  const query = ctx.params.query
  let page = ctx.params.page || 1
  const pageSize = 10
  let numberOfpages
  const sea = [ query ];
  const regex = [];

  for (var i = 0; i < sea.length; i++) {
    regex[i] = new RegExp(sea[i]);
  }

  ctx.set('Access-Control-Allow-Origin', '*');

  const documentsCount = await db.collection('banners')
    .count({"tags": {$in: regex}})

  const pagesCount = (documentsCount % pageSize > 0)
    ? Math.floor(documentsCount / pageSize)
    : documentsCount / pageSize

  const banners = await db.collection('banners')
    .find({"tags": {$in: regex}})
    .skip((page === 1) ? 0 : pageSize * (page-1))
    .limit(pageSize)
    .toArray()

  const obj = {
    documents: banners,
    pagesNum: pagesCount,
    totalDocs: documentsCount,
    currentPage: parseInt(page)
  }

  ctx.body = [obj] // works
  // ctx.body = obj // works
})

app.use(logger())
app.use(router.routes())
app.listen(3000, () => console.log(':3000'))
```

```sh
$ curl http://localhost:3000/search/banner/test+1
[{"documents":[1,2,3,4],"pagesNum":1,"totalDocs":12,"currentPage":1}]
```

A few notes for future reference.
Try to provide a fully reproducible example. The human brains are horrible debuggers (mine is at least), and by providing a clean example engages people to help.
When providing an example, whitespace is important.

I am going to close this for now, if you still have issues feel free to continue discussion here even though it's closed. If you feel this is a Koa issue, please provide a complete reproducible example with anything unrelated to Koa is mocked or excluded, and feel free to reopen.

Good luck!
