### ISSUE TITLE
why I cannot add key in ctx.body? like ctx.body[key]=value; thanks!

### ISSUE THREAD

**Issue by mytEcust** [koajs/koa#1219]

**Comment by dead-horse** [comment]
```js
ctx.body = {}
ctx.body[key] = value;
```

**Comment by mytEcust** [comment]
I want to add key in middleware
async (ctx, next) => {
    ....................
    await next();
    console.info(ctx.body); //{a:"a"}
    ctx.body.b='b';
    console.info(ctx.body); //this is also {a:"a"},I can not add another key to ctx.body
}

I only do that like
let body = JSON.stringify(ctx.body);
body = JSON.parse(body);
body.b = 'b';
ctx.body = body;

**Comment by fl0w** [comment]
```js
const Koa = require('koa')
const app = new Koa()
app.use(async (ctx, next) => {
  ctx.body = {}
  await next()
})
app.use(async (ctx, next) => {
  ctx.body['a'] = 1
  await next()
})
app.use(async ctx => {
  ctx.body.b = 2
})
app.listen(3000)
```

```sh
 $ curl localhost:3000
{"a":1,"b":2}
```

Works fine, please provide a full example if you feel this is a problem with Koa lib. There's better forums for general questions like these. Try StackOverflow, IRC och Gitter.

**Comment by mytEcust** [comment]
sorry it's my fault
