### ISSUE TITLE
gateway timeout while setting ctx.status=100

### ISSUE THREAD

**Issue by wuyanxin** [koajs/koa#1226]
I met a problem today

client send a request with header Expect='100-continue'
the server program can't handle it.
then i wrote a middleware to fix it but i doesn't work

```
// my test code
const koa = require('koa');
const app = new koa();

app.use(ctx => {
  ctx.status = 100;
  ctx.body = 'Hello Koa';
});

app.listen(3000);
```

is that a bug?

**Comment by fl0w** [comment]
Koa uses [statuses](https://github.com/jshttp/statuses) for this, I recommend you refer to its issue tracker.

node.js http emits an `continue` event in these cases which might be of use to you to solve your problem locally for now.
