### ISSUE TITLE
Dependency to `any-promise` still exists, which has a global leak issue

### ISSUE THREAD

**Issue by srmcconomy** [koajs/koa#1228]
this was supposed to be fixed with https://github.com/koajs/koa/issues/945, and it was fixed in `koa-compose`.  But `koa-convert` still has a dependency to an old version of `koa-compose` so `koa` still depends on `any-promise`

**Comment by fl0w** [comment]
You are correct. The thing about removing any-promise is that it could be a major release. This'll be fixed when there's a Koa 3 release as 1) koa-compose will be bumped and 2) koa-convert will be removed.

I'm going to close this as this is known and doesn't really raise a new issue.
