### ISSUE TITLE
Best practice on accessing context outside of routes and middlewares

### ISSUE THREAD

**Issue by SamiSammour** [koajs/koa#1234]
I'm developing an API and I'm new to Koa and I was reading the documentations and saw the ctx.state object that holds values to pass to other middlewares, and I am using this object to pass the registered user to all middlewares.  
Now my problem is that my application is multi-lingual and some data need to be translated in the requested language before sending the data back to the client, and obviously my models doesn't know about the Koa context state which contains the language value in the authenticated user object.  
So my question is how can I access the ctx.state object inside my model (or access it globally)?

**Comment by rictorres** [comment]
i don't think there's a way to accomplish that. also it would be really bad to have your models accessing koa _internals_.

how the _request_ reaches your models? `route -> middlewares -> controller -> model`? if so, then you `controller` has access to it and can pass it along to your `model`.

**Comment by fl0w** [comment]
Expanding on @rictorres answer, to access ctx.state you shouldn't think to make it global, that's a golden recipe for state-bleed disaster.

Just pass ctx.state to wherever you need it and you now have "access to it".
