### ISSUE TITLE
Allow for passing options to the `content-disposition` module

### ISSUE THREAD

**Issue by pepkin88** [koajs/koa#1257]
Currently the response method `attachment` takes only `filename` as a parameter. My suggestion is for it to take also `options` to pass to the `content-disposition` module, like this:
```js
  attachment(filename, options) {
    if (filename) this.type = extname(filename);
    this.set('Content-Disposition', contentDisposition(filename, options));
  },
```

My use case it to set in options `type: 'inline'`, so that a PDF document would display itself in the browser, but would also have a suggested filename, when a user decides to save the document on disk.

**Comment by fl0w** [comment]
There's a PR for this already @ https://github.com/koajs/koa/pull/1240

**Comment by pepkin88** [comment]
Thank you.
