### ISSUE TITLE
Remove app dependency in request & context

### ISSUE THREAD

**Issue by Vincz** [koajs/koa#1258]
Hi guys!
I'd like to use Koa Request, Response & Context but without the Application part. 
Unfortunately the app is injected in the 3 objects.
For the Context, it's for the context to be able to emit error event (`this.app.emit`), and for the Request it's just to get some config `this.app.proxy` and `this.app.subdomainOffset`.
Wouldn't it be better if these dependencies were set in a different way ? with Setter or in a constructor or whatever ... If think those objects should not be aware of the application. 
What do you think ?

**Comment by dead-horse** [comment]
You can just ignore it, what's the reason for remove it?
