### ISSUE TITLE
Provide way to set custom query parser

### ISSUE THREAD

**Issue by onufriievkyrylo** [koajs/koa#1260]
The recommended way with koa-qs module is not acceptable for me in few reasons:
1) I want to customize the default qs behavior, but this module doesn't provide this possibility.
2) The module is not updated for a long time.
3) It is just looks as awful side effect kode.

I'm asking you to provide some simple syntax to set custom query parser. Maybe with a constructor of koa instance or something like that.

**Comment by dead-horse** [comment]
it is easy to parse querystring by your self like `customizeQueryString.parse(ctx.querystring)`

**Comment by onufriievkyrylo** [comment]
This will doubling work. Because query will be parsing second time

**Comment by LuckyWindsck** [comment]
`ctx.query` is a getter and setter, and the query will only be parsed when one tries to access it.

https://github.com/koajs/koa/blob/eb51cf5fb35b39592a050b25fd261a574f547cfa/lib/request.js#L172-L187
