### ISSUE TITLE
Koa overwrites response status code if message is empty

### ISSUE THREAD

**Issue by gilbertKaradja** [koajs/koa#1270]
Not a big issue but thought it may be relevant somewhat

**How to reproduce**
ctx.status = 500;
ctx.body = undefined;

Obviously nobody will pass in undefined but I noticed this while creating my own custom errors/exceptions. For some reason setting the boxy to empty(or maybe not setting at all) switches ctx.status to 204. You can always set it back to 500 though. Not sure if this was intentional.

**Comment by fl0w** [comment]
Not necessarily intentional, but a side effect of how Koa understands body as the promise resolves.
