### ISSUE TITLE
Migration doc doesn't respect best practices on function name

### ISSUE THREAD

**Issue by mrtbld** [koajs/koa#1272]
The [Koa guide](https://github.com/koajs/koa/blob/master/docs/guide.md#named-middleware) says naming middleware is a best practice: 

> Naming middleware is optional, however it's useful for debugging purposes to assign a name.

But the [migration guide](https://github.com/koajs/koa/blob/master/docs/migration.md) only present middleware functions without names (arrow functions).

Why is that?

Thanks for this great lib :-)

**Comment by fl0w** [comment]
Docs are generally designed to avoid clutter.
