### ISSUE TITLE
Security notifications / mailing list?

### ISSUE THREAD

**Issue by davewasmer** [koajs/koa#1278]
Is there any place I can subscribe to security updates for Koa? I've looked around and didn't see a mailing list of any kind, so apologies if I simply missed the link. If no such thing exists, it might be helpful. I don't routinely go into the issue lists of dependencies that work as smoothly as Koa does, which makes it unlikely I'd see security conversations there :wink:.

**Comment by fl0w** [comment]
Unfortunately there's no mailing list and I'm not aware of any plans to have one either. Keeping Koa up to date and running `npm audit` is what's available unless you want to keep an eye on the issues tab.

**Comment by davewasmer** [comment]
Okay, thanks for the clarification 👍
