### ISSUE TITLE
Developer's responsibility to encode redirect URL?

### ISSUE THREAD

**Issue by bchociej** [koajs/koa#1289]
Hi, from reading the code and previous issues I believe I have the right answer, but since it is not 100% clear I just wanted to make sure:

Is it the developer's (my) responsibility to call `encodeURI`/`encodeURIComponent` when passing a URL into `ctx.redirect(url)`? I assume so, but I'm unclear on whether this is done automatically at some stage.

Thanks in advance and thank you for a great open source project.

**Comment by Runrioter** [comment]
It is your responsibility and is not done automatically.

**Comment by fl0w** [comment]
I'm going to close this one as question has been answered.
For future reference, https://github.com/koajs/koa/issues/1250
