### ISSUE TITLE
can i use two different body parsers based on a route?

### ISSUE THREAD

**Issue by chovy** [koajs/koa#1296]
For example for route1 I want to use bodyParser() and for route2 I want to use betterBodyparser().

Is that possible?

The reason why is I am working with an API I don't control and I need the rawBody as a buffer on one of my endpoints, and bodyParser isn't working properly, but there are some others that do.

**Comment by fl0w** [comment]
Yes, you can.

If you're using a router such as koa-router you could do something like (off the top of my head):

```js
router1.use(bodyParser())
router1.use(mw)
router2.use(betterBodyParser())
router2.use(mw)

app.use(router1.routes())
app.use(router2.routes())
```

If not then compose yourself, e.g.:

```js
const router = () => {
  const routes1 = compose([bodyParser(), ...mw])
  const routes2 = compose([betterBodyParser(), ...mw])
  return async (ctx, next) => {
    if (/* some path check */) await routes1(ctx, next)
    else await routes2(ctx, next)
    await next()
  }
}
```
