### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by zpc10** [koajs/koa#1297]
**Hi.I'm get the following error:**
   SyntaxError: Unexpected token ...

 **this is my code:**
_static async sandbox(config, debug) {
        let {
            sandbox_signkey
        } = await Payment.init(config).getSignkey();
        return new Payment({
            ...config,
            partnerKey: sandbox_signkey,
            sandbox: true
        }, debug);
    }_

Koa2 supports es2017, so I didn't configure Babel in my project.
my node is v8.2.1~
Does the koa2 need Babel?

**Comment by JounQin** [comment]
Object spread is only supported from Node.js v8.3.0

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility

**Comment by fl0w** [comment]
No, Koa does not require bable if you're running supported node version which current goes down to 4.8.4.

Update node or use `Object.assign(config, { partnerKey: sandbox_signkey, sandbox: true })` (which is what spread desugarizes to).

Closing as this isn't a Koa issue, but feel free to continue questioning if you're still having trouble even though it's closed.
