### ISSUE TITLE
running code after ctx.body

### ISSUE THREAD

**Issue by SimonSun1988** [koajs/koa#1304]
```js
app.use(async ctx => {
  ctx.body = 'Hello World';

  // running code here after response
});
```

how should i do ?

**Comment by dead-horse** [comment]
```js
app.use(async ctx => {
  ctx.body = 'Hello World';

  // running code here after response
  // don't use `await` here
  someBizLogic(ctx).catch(err => {
    // handle error
  });
});
async function someBizLogic(ctx) {
  // your async biz logic
}
```

**Comment by ndrantotiana** [comment]
Hello,
Trust you're fine.
Thank you @dead-horse for your reply but I'm wondering if we should add the `.catch(err => {...})` when calling `someBizLogic` ? In fact, I've been trying something like this but without `await`, nor `.then` nor `.catch` and, in unit test that, async function, the `someBizLogic` here, is always called but in production I'm running sometimes, randomly, an issue where `someBizLogic` isn't called and I want to have assurance that after any `ctx.body = ...` or `ctx.status = ...` or both of them, I can always call any async functions without `await` that will always be in the event loop and will be called in the background.
Thank you in advance.
Regards,
