### ISSUE TITLE
after call ctx.throw(), custom headers is disabaled in response.

### ISSUE THREAD

**Issue by PLA31001** [koajs/koa#1310]

**Comment by fl0w** [comment]
Could you please provide a minimal reproducible example (without any external packages)?

**Comment by PLA31001** [comment]
![00448b28-6dcb-4c73-a587-87df3896a46d](https://user-images.githubusercontent.com/27992386/52210794-ff176300-28c2-11e9-938a-3ecdf2787014.png)
![ddc45c40-d769-4301-83a2-d53e92ec23a1](https://user-images.githubusercontent.com/27992386/52210827-10606f80-28c3-11e9-98cc-6538fa40c3dc.png)

**Comment by PLA31001** [comment]
const Koa = require("koa");
const app = new Koa();

app.use((ctx, next) => {
    ctx.set("test", "test");
    ctx.status = 400;
    return;
});

app.on("error", async (err, ctx) => {
    console.log("error");
});

app.listen(3000);

**Comment by taokd** [comment]
`context.onerror` 对于错误的默认处理中，会清空header属性；
![image](https://user-images.githubusercontent.com/10239696/52986198-e4e89380-3431-11e9-88d4-ef0e0f066561.png)
[onerror](https://github.com/koajs/koa/blob/master/lib/context.js#L134)

如果想要设置header属性，可以通过
```
const err = new Error('name required');
err.status = 400;
err.expose = true;
err.headers = {  // header 属性
  test: 'teset'
}
throw err;
```

**Comment by fl0w** [comment]
I assume the answer provided was sufficient!
