### ISSUE TITLE
koajs.com does not build

### ISSUE THREAD

**Issue by adipascu** [koajs/koa#1311]
I want to submit a PR into [koajs.com](https://github.com/koajs/koajs.com/).

I wanted to update the docs to use the new async function api instead of the deprecated generator api.

I followed the instructions from [Readme.md](https://github.com/koajs/koajs.com/blob/55c7537d8dbbc00d9ffaaaf89fcb7522a469b962/Readme.md) and ended up with:
```
/private/tmp/koajs.com/node_modules/marked/lib/marked.js:1330
    throw e;
    ^

Error: Unknown language: "undefined"
```

I am running node 11.6.0 on macOS 10.14.2 .

I am a bit busy and can't submit a PR right now.

**Comment by fl0w** [comment]
This was fixed by tj with https://github.com/koajs/koajs.com/commit/761e9ab58a5eb33bb74b428d77695b6faf0ccc4e
