### ISSUE TITLE
What is query?

### ISSUE THREAD

**Issue by RWOverdijk** [koajs/koa#1315]
The question/issue is probably as weird as the title is.

I'm trying to figure out what ctx.query is. This is what I'm talking about:

```ts
console.log({
  obj: ctx.query,
  type: typeof ctx.query,
  prototype: ctx.query.prototype,
  constructor: ctx.query.constructor,
  isObj: ctx.query.constructor === Object,
});
```

Result:

```ts
{ obj: { name: 'test' },
  type: 'object',
  prototype: undefined,
  constructor: undefined,
  isObj: false }
```

Why is it not a pojo? What is its constructor? I can easily work around this by using Object.assign({}, ctx.query) but I'm really curious.

**Comment by fl0w** [comment]
Its created with null prototype `Object.create(null)`.

**Comment by fl0w** [comment]
So before I close this I'd like to add to the answer based on your questions. I'm not sure why but my best guess is optimisation. It is also a technique to denote its purpose, a simple map.

**Comment by RWOverdijk** [comment]
@fl0w Thanks for the answer.

Good to know... I wasn't aware of this approach. I'll read up on it.

Just as an fyi, I use it in some older libs that merge objects fr me, expecting either an array or a pojo. I needed to make sure it was a pojo and the constructor used to be the way to do it.

Do you by any chance know of a better way to check if something is a regular, mergeable object?

**Comment by fl0w** [comment]
@RWOverdijk honestly I've never thought about this. I wouldn't want to mutate that object anyway so my immediate approach would be to just clone/spread `const query = { ...ctx.query }` (care deep objects).

**Comment by RWOverdijk** [comment]
I'm using Object.assign, which works as well. I wish I could detect it instead of forcing it though, so I'll find a way.

Thanks again!

**Comment by fl0w** [comment]
Yea, `{ ...obj }` is syntactic sugar for `Object.assign`.
