### ISSUE TITLE
Is it better to use `Array.prototype.includes` instead of `Array.prototype.indexOf`?

### ISSUE THREAD

**Issue by hanzichi** [koajs/koa#1319]
Is it better to use `Array.prototype.includes` instead of `Array.prototype.indexOf`? It's easier to understand directly.

https://github.com/koajs/koa/blob/master/lib/request.js#L348

thanks

**Comment by fl0w** [comment]
Array#indexOf is a bit faster (negligible in real world application). There's no point in changing what's working.
