### ISSUE TITLE
Can koa-convert be updated 

### ISSUE THREAD

**Issue by zavr-1** [koajs/koa#1323]
Currently, koa depends on 2 koa-compose, one v3 and one v4. The v3 is coming from the old koa-convert, and it is pulling the blue-bird. Can this be fix now?
![Screenshot 2019-04-18 at 08 15 04](https://user-images.githubusercontent.com/21156791/56338485-e1b02080-61b2-11e9-9b95-ba6c6ee9f924.png)
 
https://github.com/koajs/convert/pull/11/files

Best

**Comment by fl0w** [comment]
This can't be fixed until Koa 3 is released because the removal of bluebird is a breaking change (thus requires semver major release).

**Comment by fl0w** [comment]
Actually, lets keep this open.
Ref: https://github.com/koajs/koa/issues/1114

**Comment by zavr-1** [comment]
ok thanks! While ^4 is in engines it's a semver indeed. But so what's happened here https://github.com/koajs/koa/commit/7bd82ac4103aef28fb2d2f40be91f495dfa6db5d?

**Comment by fl0w** [comment]
Yea I don't know. The decision was made that it was worth it.

My personal take on this is to NOT do/remove anything because compose will be removed in next version of Koa anyway. It's not worth possibly breaking applications IMO.

Others might disagree though.

**Comment by niftylettuce** [comment]
Waiting on koa-convert ownership to be given to me by @gyson or npm staff.  Then I will release new major release per https://github.com/koajs/convert/pull/13.

**Comment by niftylettuce** [comment]
v2.0.0 released https://github.com/koajs/convert/releases/tag/v2.0.0
