### ISSUE TITLE
No need for domains? What does that mean?

### ISSUE THREAD

**Issue by lomse** [koajs/koa#1324]
First off, thanks for making this awesome framework available.
I was reading the documentation and read the part where it said `No need for domains.`. What does that mean?

Thanks

**Comment by fl0w** [comment]
Domains was previously used for error handling and catching - which isn’t necessary when using Koa as promises (and previously co-routines) caught out of context errors as one might expect.

**Comment by fl0w** [comment]
To be more precise, docs is referring to [node.js domain module](https://nodejs.org/api/domain.html), not internet domains.
