### ISSUE TITLE
default response status code should be set at the end

### ISSUE THREAD

**Issue by dolsup** [koajs/koa#1326]
My suggestion:
[Default response status code](https://github.com/koajs/koa/blob/master/docs/api/response.md#responsestatus) should be set at the end of response, [not before route handlers run](https://github.com/koajs/koa/blob/master/lib/application.js#L147).

In my case, I'm trying to catch custom error object([Boom](https://github.com/hapijs/boom)) thrown from handlers and set response status by error type at middlewares. But I always get default 404 unless res.body is set, and I don't know whether the 404 is set by default or my handlers or middlewares.

[a known workaround](https://github.com/koajs/koa/issues/888#issuecomment-275696168) does not work now.

**Comment by fl0w** [comment]
You can make a PR if you want, but I'm afraid this might heavily break applications relying on current behaviour.

**Comment by dolsup** [comment]
It can be implemented as a form of app-wide option for compatibility. but I'm not sure if it can be approved because there is no app-wide option in Koa for now.

And I found out a workaround can solve my case by just adding a middleware at the first which is set status to undefined.. so this issue is not urgent but IMHO it should be default behavior in the next major version.

**Comment by turbobuilt** [comment]
This doesn't work anymore because of this code in response.js

```javascript
    assert(Number.isInteger(code), 'status code must be a number');
    assert(code >= 100 && code <= 999, `invalid status code: ${code}`);
```

**Comment by dolsup** [comment]
@turbobuilt 
Oh sorry. I found that I did it with a different method from I described above. In short, I just make every 404 error using Boom so I could distinguish 404 which I throw from default 404. I deal with it in middleware.

I think we should be able to distinguish whether status is default at least. This is quite important issue.  I'll try to make PR soon.

**Comment by turbobuilt** [comment]
Ah, good idea.

**Comment by LeonnardoVerol** [comment]
I stumbled upon this "bug" yesterday.
While I hope it gets fixed, that was my workaround: 
(I changed the example a little for this issue)

some-file:
```Javascript
// ...
context.throw([code], [message], { statusCode: [code] });
// ...
```

on error:
```Javascript
app.on('error', (error, context) => {
        // ...
	if (error.statusCode >= 500) {
	// ...
        }
        // ...
});
```

**Comment by jonathanong** [comment]
What's the use-case for this? If you didn't handle the response, then it should 404

**Comment by jonathanong** [comment]
please re-open with a use-case, closing to clean up the repo. thanks
