### ISSUE TITLE
Get Method:  ctx.query value is problem to me,I need help ,Thanks!

### ISSUE THREAD

**Issue by tanzhiling** [koajs/koa#1329]
![image](https://user-images.githubusercontent.com/31690439/57017442-dc8eaf00-6c51-11e9-83b7-1c4c9f950cba.png)
why ? i want get apkey , how to resolve,help me

**Comment by fl0w** [comment]
You need provide more information of what's going on. Please provide more information of how you're doing the requested and what the expected result it.
