### ISSUE TITLE
Non-expiring cookie

### ISSUE THREAD

**Issue by ChrisLahaye** [koajs/koa#1331]
Hello,

Is it possible to set a cookie that doesn't expire, or at least expires very far in the future. The maxAge value denotes the expire time in milliseconds, is there a maximum allowed value? Taking 2^31 would only result in 28 days.

Thank you,

Chris Lahaye

**Comment by dead-horse** [comment]
https://en.wikipedia.org/wiki/HTTP_cookie 

you can read the wiki or http rfc to figure out it, I think you can use cookie expires instead of max-age
