### ISSUE TITLE
How to define own ctx.state types

### ISSUE THREAD

**Issue by keyiis** [koajs/koa#1333]
I used typescript to devloper koa app,I want to define my own type for ctx.state in global of app,but i don't know how to do.
![QQ截图20190512150010](https://user-images.githubusercontent.com/7766085/57578885-b0332800-74c6-11e9-9734-91b8c33618e2.jpg)

**Comment by kibertoad** [comment]
Look up generics in Typescript. StateT is a generic of ParametrizedContext.

**Comment by keyiis** [comment]
@kibertoad Thks reply!but where should I define it?

**Comment by kibertoad** [comment]
@keyiis Inside route handler definition, I would think.

**Comment by keyiis** [comment]
@kibertoad I has many route in  different file,i hope define it somewhere  that can be used globally

**Comment by ljphilp** [comment]
ctx.state only relative to this request, such as verifying login token, the middleware specified ctx.state.user_name='zhangsan';
In the request method can use 
let user_name= ctx.state.user_name;

**Comment by keyiis** [comment]
@ljphilp thks reply! in my app,every route has same object in ctx.state,so i want define a interface for ctx.state at app level.

**Comment by kroleg** [comment]
@keyiis typings are provided by https://github.com/DefinitelyTyped/DefinitelyTyped, so this repo is not a correct place to ask such questions. You should ask questions on stackoverflow.

Regarding your issue. You can pass "global" state types when you initalize Koa app:
```js
interface MyState {
   userId: number;
   deptId: number;
}
const app = new Koa<{MyState}, {}>();
```

**Comment by keyiis** [comment]
@kroleg thks reply!but how to define global MyState to overwrite StateT?

**Comment by ljphilp** [comment]
> @ljphilp thks reply! in my app,every route has same object in ctx.state,so i want define a interface for ctx.state at app level.
`// 验证token中间件
const jwt = require('jsonwebtoken');

module.exports = function (){
  return function * ( next ) {
    // 执行中间件的操作
    let ctx = this;
    if (ctx.url !== '/apis/sysmgr/user/login' && ctx.request.headers['authorization']) {
      let auth_attr = ctx.request.headers['authorization'].split(' ');
      if(auth_attr[0] !=='Bearer' || auth_attr.length !== 2) {
        ctx.response.body = {
          msg: '授权错误，请重新登陆'
        };
        ctx.response.status = 401;
      }else{
        let token = auth_attr[1];
        let decoded = jwt.decode(token, process.env.JWT_SECRET);
        // 如果过期了就重新登录
        if (token && decoded.exp <= Date.now() / 1000) {
          ctx.response.body = {
            msg: '授权已经过期，请重新登陆'
          };
          ctx.response.status = 401;
        }else{
          ctx.state.user_name = decoded.user_name;
        }
      }
    }
    yield next
  }
};`

This is my solution that registers a middleware that assigns a value to ctx.state on each request, which can be used in the current request,hope that may help you,you can also refer to my project.

[ https://github.com/ljphilp/koa-restful](url)

**Comment by keyiis** [comment]
@ljphilp 谢谢你的回复，我在ctx.state里保存的数据不仅用于授权，的不是授权问题，在不同的router里需要读取ctx.state里的用户信息进行数据过滤，为保证团队成员都能规范的使用ctx.state里的信息，所以我需要定义一个interface来对ctx.state里的参数类型进行约束，我首先想到的是去改koa的types，但是这对以后升级koa会造成影响，所以我想是不是能自己定义一个全局的MyStateT类型去覆盖koa的StateT，这样就不用团队成员每次要使用ctx.state时，都要去再引入一遍MyStateT，比如 
**apiRouter.ts**这是总的路由，负责把请求转发到不同的子路由，子路由定义在各自独立的文件中
```
apiRouter.use('/staff', JwtAuth2Rest, staffRouter.routes());
apiRouter.use('/role', JwtAuth2Rest, RoleRouter.routes());
apiRouter.use('/cat', JwtAuth2Rest, CatRouter.routes());
......
```
比如**staffRouter.ts**
```
ItemRouter.post('/list', async ctx => {
    let reqUser:MyStateT=ctx.state;
    ......
});
ItemRouter.post('/get', async ctx => {
    let reqUser:MyStateT=ctx.state;
    ......
});
```
上面代码中每次使用ctx.state时都要引入我自己定义的MyStateT，这样就比较麻烦

**Comment by ricardocasares** [comment]
Hello @keyiis, I was having problems with the same thing, I've tried the following:

```ts
import Koa from 'koa'

interface User {
  id: number;
  name: string;
}

interface State {
  user: User;
}

interface Context extends Koa.Context {
  state: State;
}

interface Middleware extends Koa.Middleware<State, Context> {}

const app = new Koa<State, Context>();

// here typings won't work as for some reason seems that state
// property is overwritten by Koa typings to be type "any"
app.use(ctx => ctx.state.user)

// but typings will work if you define your middleware like this:
const yourMiddleware: Middleware = ctx => ctx.state.user
```

Another options is, since `state` is just a recommended namespace (as I understand), you can chose a different namespace to place your state:

```ts
import Koa from 'koa'

interface Context extends Koa.Context {
  data: State
}

const app = new Koa<State, Context>();

// here typings work as expected
app.use(ctx => ctx.data.user)
```

I'm currently experimenting with Koa and different patterns, you can check [this repo](https://github.com/ricardocasares/koats)

**Comment by ricardocasares** [comment]
Sorry my last message was confusing, try this, should work:

```ts
interface State {
  userId: number;
}

interface Context {
  something: string;
} 

const app = new Koa<State, Context>().use(ctx => {
  ctx.state.userId // works
  ctx.something // works
});
```

I'm currently experimenting with TS and Koa [here](https://github.com/ricardocasares/koats)

**Comment by fl0w** [comment]
Closing this as it seems to be answered. Please feel free to re-open if you still have issues with this.
