### ISSUE TITLE
class constructors must be invoked with |new|

### ISSUE THREAD

**Issue by SixeLaama** [koajs/koa#1334]
i try do create a ligne as coding train do in his video but i have this error and i don't know why
there is the full code  `let ligne

function setup () {
createCanvas(400,400)
background(0)
ligne = new line(100,200)
}

function draw () {
	background(0)
	ligne.show()

	

}

class line{
	constructor(x,y){
		this.pos = createVector(x,y)
		this.direc = createVector(1,0)
	}

	show(){

		 stroke(255)
		push()
		translate(this.pos.x,this.pos.y)
		line(0,0,this.direc.x*50,this.direc.y*50)
		pop()
		}
}`

**Comment by fl0w** [comment]
I think you're in the wrong repository. This isn't at all related to Koa I'm afraid.
