### ISSUE TITLE
Has the koa-vs-express document been finished?

### ISSUE THREAD

**Issue by andpeterson** [koajs/koa#1335]
The document [koa/docs/koa-vs-express.md](https://github.com/koajs/koa/blob/master/docs/koa-vs-express.md) has a note at the top. 

> THIS DOCUMENT IS IN PROGRESS. THIS PARAGRAPH SHALL BE REMOVED WHEN THIS DOCUMENT IS DONE.

Is the document done so this header can be taken off? Is there anything else that should be added before removing this header?

EDIT: linked the document above

**Comment by fl0w** [comment]
Yea I think that header can be removed.
