### ISSUE TITLE
Quick question (not necessarily an issue)

### ISSUE THREAD

**Issue by exside** [koajs/koa#1338]
https://github.com/koajs/koa/blob/75233d974a30af6e3b8ab38a73e5ede67172fc1c/lib/application.js#L127

looking at the callback for https.createServer(), which (afaik) will be executed on every request: Wouldn't it make sense (from a performance standpoint) to initialize a middleware variable beforehand and then only compose it once (e.g. on the first request) and store it in the variable outside of the `callback()` function
and then check if the variable is already a function in the callback and skip re-composing the entire thing on each request?

but maybe I'm missing something! Thanks for your great work and your time to answer my noob question =)

~~or is it a common use case that a specified middleware will add in another middleware depending on the request it receives? Then it would make sense to re-compose (but could probably still be optimized)...~~ does not seem to matter actually, as the compose function re-evaluates `this.middleware` on each execution anyways...

**Comment by dead-horse** [comment]
```js
http.createServer(app.callback());
```

`callback` will only executed once when create http server.

**Comment by fl0w** [comment]
@exside it composes every time you call `callback`, however once created it returns a http.createServer compliant requestListener.
