### ISSUE TITLE
layout not work in (koa2 t1 -e -hbs)

### ISSUE THREAD

**Issue by kongtir** [koajs/koa#1339]
layout not work in (koa2 t1 -e -hbs);
     >  koa2 t1 -e --hbs
install dependencies:
     > cd t1 && npm install
run the app:
     > SET DEBUG=koa* & npm start t1
------------------------------
get  http://127.0.0.1:3000/
reback 
 <h1>Hello Koa 2!</h1>
<p>Welcome to Hello Koa 2!</p>
it not work in layout ,what it is happend?
![this is pic](https://user-images.githubusercontent.com/40745299/58768658-50b1cf00-85d1-11e9-9abc-8e0ff57ed363.png)

**Comment by fl0w** [comment]
koa2-cli isn't officially a Koa js org package, so I'm not sure what's going on. I suggest to turn to the maintainers of that package (guessing its https://github.com/ly2011/koa2-cli) and file an issue there.
