### ISSUE TITLE
koa-qs does work with koa v2

### ISSUE THREAD

**Issue by igorvolnyi** [koajs/koa#1342]
Please update in Wiki

**Comment by fl0w** [comment]
What wiki entry are you referring to?

According to a Github search, the only mention of koa-qs is in [Home](https://github.com/koajs/koa/wiki), and that row does **not** have a checkmark for Koa v2.

**Comment by fl0w** [comment]
Oh, I see. I misread the subject.

**Comment by fl0w** [comment]
Fixed (you could have done it yourself btw, the wiki is open to changes).
