### ISSUE TITLE
Compression does not happen after build

### ISSUE THREAD

**Issue by amrita-syn** [koajs/koa#1356]
Koa, by default, compresses its responses. Works great in dev env. But I use webpack to generate an uglified/minified single index.js for the backend and although the functionality of the app is fine, the compression fails. 
Some of my apis return json arrays of MBs and on dev mode(running app with npm start), the transfer size is in KBs but after build, the transfer size is the actual content size.

Can this be fixed?

**Comment by fl0w** [comment]
Koa doesn't compress responses. Koa-compose however does?

**Comment by amrita-syn** [comment]
We are using koa-compose as well. package.json has the following from koa - 
    "koa": "^2.7.0",
    "koa-bodyparser": "^4.2.1",
    "koa-compose": "^4.1.0",
    "koa-router": "^7.4.0",

and we compose all our routes.

**Comment by amrita-syn** [comment]
No, there was no change when I added koa-compress explicitly. 

But, I found that when i build the app as part of CI and copy only the built index.js to the server, it does not compress. but when I copy app to server and build it there and then use the built file, it works.

I hope someone doesn't close this issue because this is an inefficient workaround.

**Comment by fl0w** [comment]
There's a number of things that might be happening, and without code (minimal reproducible) it's impossible to be specific. this issue tracker is about bug reporting so general question like these are unlikely to be prioritised.

I won't close the issue unless it's stale.

I can be that you're sending to small payloads (i.e. not worth compressing unless a specific threshold is met size-wise). It could be that tests written in CI doesn't send appropriate Accept header field. Either way, this is clearly an environment issue and not a Koa issue - as, as you noted, it works in your production environment.

**Comment by amrita-syn** [comment]
I did mention the sizes in the issue description. And I have to take back the 'working from build if built on prod'. I'll try other things and see if I can pinpoint the cause.

**Comment by amrita-syn** [comment]
Explicitly adding koa-compress in packages and using the middleware in the app works. So closing this.
