### ISSUE TITLE
How to use the quickjs engine to compile koajs Javascript sources to executables with no external dependency?

### ISSUE THREAD

**Issue by pinghe** [koajs/koa#1358]
How to use the QuickJS engine to compile KoaJS Javascript sources to executables with no external dependency?

QuickJS is Javascript Engine.
https://bellard.org/quickjs/

Main Features:

1. Small and easily embeddable: just a few C files, no external dependency, 190 KiB of x86 code for a simple hello world program.
1. Fast interpreter with very low startup time: runs the 56000 tests of the ECMAScript Test Suite in about 100 seconds on a single core of a desktop PC. The complete life cycle of a runtime instance completes in less than 300 microseconds.
1. Almost complete ES2019 support including modules, asynchronous generators and full Annex B support (legacy web compatibility).
1. Passes 100% of the ECMAScript Test Suite.
1. **Can compile Javascript sources to executables with no external dependency.**
1. Garbage collection using reference counting (to reduce memory usage and have deterministic behavior) with cycle removal.
1. Mathematical extensions: BigInt, BigFloat, operator overloading, bigint mode, math mode.
1. Command line interpreter with contextual colorization implemented in Javascript.
1. Small built-in standard library with C library wrappers.

**Comment by dougwilson** [comment]
It wouldn't be possible yet because QuickJS doesn't support network I/O, only STDIO and file I/O.
