### ISSUE TITLE
request.URL should be frozen

### ISSUE THREAD

**Issue by matthieusieben** [koajs/koa#1369]
Since it's memoized, it could be tempered with by a middleware and cause errors in totally unrelated middlewares.

An example of how it could inadvertently be tempered with:
```js
ctx.body = {
  otherPageUrl: String(Object.assign(ctx.request.URL, { pathname: '/other/page' }))
}
```

Memoized data should be frozen using `Object.freeze`

**Comment by fl0w** [comment]
I'm not a fan of freezing, nor do I think it's necessary. I'm -1 on this. Unless someone objects this will stay closed as wontfix.
