### ISSUE TITLE
Options in the constructor

### ISSUE THREAD

**Issue by djake** [koajs/koa#1370]
Would you accept a pull request to allow `env` (and perhaps other settings) to be passed as a configuration argument to the `Application` constructor which would take precedence over process.env.NODE_ENV?

**Comment by dead-horse** [comment]
hmm,  sounds good to me. there are several configurations we can pass from the constructor, it's more clear that what options koa accepted.

- proxy
- subdomainOffset
- env
- keys

```js
// before
const app = new Koa();
app.proxy = true;
app.subdomainOffset = 3;
app.keys =  [ key1, key2 ];
app.env = 'production';

// after
const app = new Koa({
  env: 'production',
  keys: [ key1, key2 ],
  proxy: true,
  subdomainOffset: 3,
})
```
