### ISSUE TITLE
How can i get the file

### ISSUE THREAD

**Issue by Cdmoonb** [koajs/koa#1371]
{ request: 
   { method: 'POST',
     url: '/UpdateImage/FaceSnap?deviceid=b4b7c891bd06c7155096815757121391&id=576&score=76',
     header: 
      { host: '192.168.31.88',
        'content-transfer-encoding': 'base64',
        'content-type': 'image/jpeg',
        'content-length': '37124',
        'cache-control': 'no-cache' } },
  response: { status: 404, message: 'Not Found', header: {} },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/UpdateImage/FaceSnap?deviceid=b4b7c891bd06c7155096815757121391&id=576&score=76',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }

**Comment by fl0w** [comment]
https://github.com/koajs/multer
