### ISSUE TITLE
TypeError: Cannot set property keys of #<Application> which has only a getter

### ISSUE THREAD

**Issue by menggong** [koajs/koa#1376]
![image](https://user-images.githubusercontent.com/4995779/63238376-c5afaf00-c278-11e9-9193-059d39b99fc4.png)

**Comment by Furholeder** [comment]
npm install koa@2.7.0 可以临时解决

**Comment by Furholeder** [comment]
npm install koa@2.7.9  may be resolve your problem

**Comment by Furholeder** [comment]
npm install koa@2.7.0 may be resolve your problem

**Comment by hearAllParties** [comment]
https://github.com/koajs/koa/commit/287e589ac773d3738b2aa7d40e0b6d43dde5261b
fix了

**Comment by luqimin** [comment]
when will the patch be released?
