### ISSUE TITLE
[Discussion] Apply Worker Threads？

### ISSUE THREAD

**Issue by libook** [koajs/koa#1383]
The status of `Worker Threads` became `Stable` in [master branch](https://github.com/nodejs/node/blob/master/doc/api/worker_threads.md) of Node.js . It probably will be post in next release.

Is there any needs to apply `Workder Threads` with Koa.js?

**Comment by fl0w** [comment]
Honestly, I can't think of a use-case. Sure specific middleware could reap great benefits but I'm not sure Koa (which is just a sugarized requestListener + a serial promise runner) would. Koa isn't CPU intensive.

Do you have any use-cases in mind?
