### ISSUE TITLE
Is it literally a stack?

### ISSUE THREAD

**Issue by zzz6519003** [koajs/koa#1385]

**Comment by zzz6519003** [comment]
Expressive middleware is a [] XD

**Comment by fl0w** [comment]
Sorry, what do you mean by "expressive"? But yes, once composed all middleware used in Koa is expected to be a flat array.

**Comment by zzz6519003** [comment]
> Sorry, what do you mean by "expressive"? But yes, once composed all middleware used in Koa is expected to be a flat array.

not a fat array XD
