### ISSUE TITLE
Remove babel reference from koajs.com

### ISSUE THREAD

**Issue by tracker1** [koajs/koa#1386]
Probably time to remove the **Async Functions with Babel** section on the main website. And from the readme itself.

**Comment by fl0w** [comment]
I'm for removing clutter from both README and koajs.com, others might disagree. However, instead of removing it I'd vote for moving the information to wiki or something.

**Comment by jonathanong** [comment]
eh, don't think mentioning babel is necessary anymore

**Comment by tracker1** [comment]
Given that very few people should/would be using a node version from over 3 years ago, it's probably best to just remove it, and maybe have a footnote for Node versions before 8.x
