### ISSUE TITLE
HTTP Error code 425

### ISSUE THREAD

**Issue by VojtechKlos** [koajs/koa#1388]
When returning error code 425 according to the specification (https://tools.ietf.org/html/rfc8470#section-5.2) the message should be "Too Early" but in Koa it is now "Unordered Collection". Can you take a look at it and consider a fix? Thanks.

**Comment by hcz** [comment]
Koa.js uses built-in Node.js status codes nodejs/node#29879

**Comment by fl0w** [comment]
Just for reference, Koa also uses [statuses package](https://github.com/jshttp/statuses/blob/master/codes.json) via http-errors which does follow 8470 correctly.

**Comment by VojtechKlos** [comment]
Ok so it is not a koa issue. I shall close this one I guess
