### ISSUE TITLE
Node 12 deprecation of OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by konstardiy** [koajs/koa#1432]
I am not aware of which internals to update, so I feel I can't fix this myself.
In short, I get this deprecation warning after migrating to node 12 of our project:
```
OutgoingMessage.prototype._headers is deprecated
```
I guess usage if this must be updated before next node LTS version will go live anddeprecated `_headers` property will be removed at all.

**Comment by meetzoo** [comment]
Have you updated your koa version? From what I see this is fixed in the latest tags

**Comment by konstardiy** [comment]
Not yet. Thanks for letting me know. I will check the latest version for sure!

**Comment by konstardiy** [comment]
I used koa2 alpha version for a while. I guess this issue can be closed.
