### ISSUE TITLE
Is it possible to return Javascript via router?

### ISSUE THREAD

**Issue by hamzah-bao** [koajs/koa#1438]
Hi,
Sorry I am still a newbie to Koa, I need to return some Javscript code after a route is accessed, is this possible? So codewise, something along these lines...
```
router.get('/api/someJsFile.js', async (ctx) => {
    ctx.res.statusCode = 200;
    ctx.type = 'text/javascript; charset=utf-8';
    ctx.message= "alert('test')";
    return ctx.res;
  });
  server.use(router.allowedMethods());
  server.use(router.routes());
```

Thank you.

**Comment by AlexisJC** [comment]
Hi,
I never used Koa but I think you're looking to serve a static file (your javascript file). For this you can use this plugin https://github.com/koajs/static.

**Comment by hamzah-bao** [comment]
Ah thank you for that link :)
