### ISSUE TITLE
AsyncLocalStorage support

### ISSUE THREAD

**Issue by jonathanong** [koajs/koa#1453]
https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage

we should run every request in it so that errors can be traced to the original req/res even if they were called in a different event loop. this will also allow us to not pass req/res/ctx to track sources of errors.

the `store` would be `ctx`

```js
const ctx = app.asyncLocalStorage.getStore()
if (ctx) // ...
```

**Comment by fengmk2** [comment]
Just like ThreadLocal in Java.

**Comment by hauau** [comment]
What about performance? If you choose to use async hooks you take a significant hit, there's no way around it. That's a big decision to use it for every request.

**Comment by dmitriiivashko** [comment]
You can always create a middleware that wraps the next middleware in async storage run. There's no need to build this into koa core and force everyone to use this functionality

**Comment by jkomyno** [comment]
I agree, with @dmitriiivashko and @hauau.
@jonathanong, have you created a custom middleware as suggested? If so, can this issue be closed?
