### ISSUE TITLE
Trouble understanding middleware recommended in the docs

### ISSUE THREAD

**Issue by msxrx** [koajs/koa#1457]
Hi! While reading through the main website I've learned that it is recommended to [add middleware asserting correct body type](https://koajs.com/#response-body-). I have trouble understanding why it checks `typeof ctx` instead of `typeof ctx.body`. I'll be grateful for explanation and if this is a bug I'll happily submit a PR.
https://github.com/koajs/koa/blob/8d52105a34234be9e771ff3b76b43e4e30328943/docs/api/response.md#L137-L145

**Comment by dead-horse** [comment]
yep, it should be `ctx.body` here. welcome to create a PR to fix this. :)
