### ISSUE TITLE
Suggestion: consistent package names on NPM

### ISSUE THREAD

**Issue by njlr** [koajs/koa#1458]
One of the off-putting things about Koa vs other solutions is that it isn't clear which NPM packages are maintained by the Koa authors and which are community efforts. I would like to stick to official Koa packages to get some degree of assurance. 

**It would be great if these packages had a common naming scheme on NPM.** 

My suggestion would be to follow the [`@koa/router`](https://www.npmjs.com/package/@koa/router) package: 

 * Koa main package `koa`
 * Router `@koa/router`
 * Body Parser `@koa/bodyparser`
 * Static `@koa/static`
 * etc...

This convention is already used by [Babel](https://www.npmjs.com/search?q=%40babel).

**Comment by njlr** [comment]
Who has the access required to do this?

**Comment by yanickrochon** [comment]
Out of curisosity, why having the main package outside of the `@koa` namespace?

```js
import koa from 'koa';
import router from '@koa/router';
```

Why not having everything within the namespace?

```js
import koa from '@koa/core';   // or '@koa/app'
import router from '@koa/router';
```
This is what other projects, for example [Material UI](https://material-ui.com/) does.

**Comment by niftylettuce** [comment]
Yes I know.  It would be nice.  Time is a constraint, as are developers that actually know how to publish and semver release. 
 We're also not funded by Facebook or Google.

**Comment by yanickrochon** [comment]
@niftylettuce I totally agree. But this issue should be tied with the **3.0** roadmap. In that sense, some group should be formed and assignments made with ETAs. There are over 200 contributors to this project, so surely a dozen could spare a few hours and everything could happen by the end of this year.

That sounds reasonable to me.

**Comment by niftylettuce** [comment]
I don't think you can put an ETA on open-source software unless you financially sponsor and routinely follow up.  Like I said, I will try to dedicate time in the near future to this.  I highly doubt others would have the time.

**Comment by niftylettuce** [comment]
There also has to be an enforced mirroring concept, where `koa` gets mirrored to `@koa/app` (or whatever we name it) for at least 1 semver major version, then deprecated afterwards.  I've been doing this with `koa-router` and `@koa/router` since I finally got hold of it on npm after this debacle <https://news.ycombinator.com/item?id=19156707>.

**Comment by miwnwski** [comment]
> There also has to be an enforced mirroring concept, where `koa` gets mirrored to `@koa/app` (or whatever we name it)

I wrote about this in the [3.0 issue](https://github.com/koajs/koa/issues/1114#issuecomment-430165589), I would really love for Koa npm package to just stay as "koa".

**Comment by niftylettuce** [comment]
> > There also has to be an enforced mirroring concept, where `koa` gets mirrored to `@koa/app` (or whatever we name it)
> 
> I wrote about this in the [3.0 issue](https://github.com/koajs/koa/issues/1114#issuecomment-430165589), I would really love for Koa npm package to just stay as "koa".

Yeah, we'll definitely stick with just `koa` I'm sure for the main package.  The issue though is that npm still doesn't let you share a package ownership with an organization.  I've written to them about this countless times.  If anyone else wants to voice their thoughts with npm to add this feature, please email support@npmjs.com.  There seems to be a complete mess at npm right now.

**Comment by jonathanong** [comment]
we're slowly moving modules into the koa org with @koa/ (though koa itself will remain). LMK if you want to move a module into the org
