### ISSUE TITLE
Node's internal errors aren't properly handled by koa's onerror handler in some situations

### ISSUE THREAD

**Issue by julienw** [koajs/koa#1466]
In some cases, such as running tests in Jest, Node's internal errors such as PREMATURE_CLOSE (from the stream module) aren't properly handled by this code:
https://github.com/koajs/koa/blob/9ee65843d9be96329a3279c63657c2970e260acf/lib/context.js#L113

A bit of debugging showed me that despite that they're Errors, the `instanceof Error` call returns false. My guess is that they're not using the same `Error` object (different globals maybe?).

As a result, this is the error I get:
```
Error: non-error thrown: {}","stack":"Error: non-error thrown: {}
    at Object.onerror (/home/julien/travail/git/profiler-server/node_modules/koa/lib/context.js:115:40)
    at onerror (/home/julien/travail/git/profiler-server/node_modules/koa/lib/application.js:163:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
```
This is working properly out of the jest environment though. The same error when running the server directly:
```
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at LengthCheckerPassThrough.onclose (internal/streams/end-of-stream.js:61:15)
    at LengthCheckerPassThrough.emit (events.js:215:7)
    at LengthCheckerPassThrough.EventEmitter.emit (domain.js:476:20)
    at emitCloseNT (internal/streams/destroy.js:68:8)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
```
But this makes things confusing when finding such an error while working on tests for an app.

Would you be open changing this check using `Object.prototype.toString.call(err) !== '[object Error]'`? Or maybe use both checks to make sure we catch all cases? Any downsides?

**Comment by julienw** [comment]
I'm willing to do the patch if this is OK.

**Comment by julienw** [comment]
There's a problem in jest: https://github.com/facebook/jest/issues/2549
Other libs fixed it similarly: https://github.com/sindresorhus/execa/pull/423
node itself does it: https://github.com/nodejs/node/blob/81f6dd66fe9e08875e1c96d65b6bce427cfe8b2d/lib/util.js#L99

node proposes util.isError but it's marked as deprecated for a long time (but it's still there!). Newer node versions propose `utils.types.isNativeError` but this is node >= 7, and I believe koa supports older node for now. That's why I'll just do a patch with `Object.prototype.toString`.

**Comment by anlexN** [comment]
@julienw can we use this syntax?
`String(err) === 'Error'`

**Comment by julienw** [comment]
I... Don't think this would work ?
What is your problem ?

**Comment by anlexN** [comment]
i hate old syntax, can we write it in mordern syntax?

**Comment by julienw** [comment]
Koa supports older node versions so my understanding is that we want to keep using older syntax in this project. Moreover what you suggest doesn't work and I believe is not reliable.

**Comment by anlexN** [comment]
i just want to know its mordern syntax, can you tell me?
