### ISSUE TITLE
Context.assert and TypeScript with strict null check

### ISSUE THREAD

**Issue by lucafaggianelli** [koajs/koa#1467]
I'm using Koa with Typescript in strict mode, that is, TS compiler has `strict: true`, which includes strict null check.

Said so, I have routes defined like this:
```ts
async function signIn (ctx: Context) {
  // ... not interesting code

  // this line uses Typeorm, which returns a User instance or undefined (User | undefined)
  const user = await User.findOne({ email }, { select: [ 'password' ] })
  ctx.assert(user, 401)

  // here TS complains about user possibly being undefined
  const isValid = await argon2.verify(user.password, password)
}
```

Basically, TS doesn't understand that the `ctx.assert` call throws in case `user` is undefined, so it's perfectly safe to use it. To fix this compilation issue, I'm obliged to add `if (!user) return` after `ctx.assert` just to assure TS about the undefined check.

Do you have any idea how to solve this?

**Comment by ejose19** [comment]
It's because type annotations for http-assert can be improved (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/http-assert/index.d.ts)

Feel free to submit a patch to that repo, you can use something like this as a base:


```ts
type Truthy<T> = T extends null | undefined | false | '' | 0 ? never : T; // lodash implementation

declare function assert<T>(
  value: T,
  status?: number,
  msg?: string,
  opts?: Record<string, unknown>
): asserts value is Truthy<T>;

const x: User | undefined;

assert(x);

x.username; // typescript knows this is not undefined

```

**Comment by lucafaggianelli** [comment]
thank you @ejose19 this seems a solution, I'll try to create a PR on http-assert

**Comment by miwnwski** [comment]
I'll close this as it seems to be answered. Please re-open if I'm mistaken.
