### ISSUE TITLE
ctx.query is not a plain object while ctx.params and ctx.request.body is

### ISSUE THREAD

**Issue by raphaelsoul** [koajs/koa#1472]
![image](https://user-images.githubusercontent.com/8615787/84727329-5c481c00-afc1-11ea-8adf-918ddf11792c.png)

As screenshot shows that ctx.query has no method `hasOwnProperty` from prototype

Which causes some package depends on `ctx.query.hasOwnProperty` calling an undefined method.

I am using koa@2.11.0

**Comment by cmidkiff87** [comment]
(Not a koajs dev, but had the same issue)

This is [intended behavior](https://github.com/nodejs/node/pull/6055) as of node 6.  
To get around it, you can use this instead
```js
Object.hasOwnProperty.call(ctx.query, 'prop_name_here');
```

If you can't do that (such as using a library), you can shim it instead
```js
app.use(async (ctx, next) => {

  ctx.query.hasOwnProperty = function(key) {
    // `this` === `ctx.query`
    return Object.hasOwnProperty.call(this, key);
  }
});
```

If that causes issues with object enumeration (`let key of ctx.query` erroring on 'hasOwnProperty'), you can make it unenumerable
```js

app.use(async (ctx, next) => {

  function hasOwnPropertyShim(key) {
    // `this` === `ctx.query`
    return Object.hasOwnProperty.call(this, key);
  }

  Object.defineProperty(ctx.query, 'hasOwnProperty', {
    value: hasOwnPropertyShim,
    enumerable: false,
  });
});
```

**Comment by raphaelsoul** [comment]
> (Not a koajs dev, but had the same issue)
> 
> This is [intended behavior](https://github.com/nodejs/node/pull/6055) as of node 6.
> To get around it, you can use this instead
> 
> ```js
> Object.hasOwnProperty.call(ctx.query, 'prop_name_here');
> ```
> 
> If you can't do that (such as using a library), you can shim it instead
> 
> ```js
> app.use(async (ctx, next) => {
> 
>   ctx.query.hasOwnProperty = function(key) {
>     // `this` === `ctx.query`
>     return Object.hasOwnProperty.call(this, key);
>   }
> });
> ```
> 
> If that causes issues with object enumeration (`let key of ctx.query` erroring on 'hasOwnProperty'), you can make it unenumerable
> 
> ```js
> app.use(async (ctx, next) => {
> 
>   function hasOwnPropertyShim(key) {
>     // `this` === `ctx.query`
>     return Object.hasOwnProperty.call(this, key);
>   }
> 
>   Object.defineProperty(ctx.query, 'hasOwnProperty', {
>     value: hasOwnPropertyShim,
>     enumerable: false,
>   });
> });
> ```

hmmm indeed. But I am running in node v10.20.1

**Comment by cmidkiff87** [comment]
[Node 10 has the same behavior](https://nodejs.org/docs/latest-v10.x/api/querystring.html#querystring_querystring_parse_str_sep_eq_options).

Specifically 

> The object returned by the `querystring.parse()` method does not prototypically inherit from the JavaScript `Object`. This means that typical `Object` methods such as `obj.toString()`, `obj.hasOwnProperty()`, and others are not defined and will not work.

**Comment by dead-horse** [comment]
This behavior is by design to avoid some security problems. 

https://stackoverflow.com/questions/52366192/why-does-node-js-querystring-parse-returns-an-object-that-does-not-inherit-fro

**Comment by dead-horse** [comment]
Close for now. If you have any other doubts you can continue the discussion. :)
