### ISSUE TITLE
No Contributing.md

### ISSUE THREAD

**Issue by NotMoni** [koajs/koa#1473]
Are they any docs to read before I can contribute. I can't find any docs.

**Comment by miwnwski** [comment]
Hi,

Sorry, there are non that I'm aware of.

 - General common-sense rules apply however.
 - Stylistic changes are not accepted.
 - Koa strives to be simple and minimalistic. Big features are usually better as separate packages.

I'll close this unless you have other questions. And if you do, please feel free to reopen or open a new issue.
