### ISSUE TITLE
Shouldn't "ctx.request.get()" return "undefined" for non-existent headers?

### ISSUE THREAD

**Issue by LeonnardoVerol** [koajs/koa#1478]
I was expecting either `undefined` or the value itself when checking for a header.
But instead of `undefined` koa returns an empty string.

Defined headers or empty headers should be 2 different situations.

```Javascript
get(field) {
    const req = this.req;
    switch (field = field.toLowerCase()) {
      case 'referer':
      case 'referrer':
        return req.headers.referrer || req.headers.referer || '';
      default:
        return req.headers[field] || '';
    }
  }
```
Line: https://github.com/koajs/koa/blob/master/lib/request.js#L675

Shouldn't ctx.request.get() return "undefined" for non-existent headers?

**Comment by miwnwski** [comment]
This is sort of subjective. With current implementation you can always expect a string which is easier to work with, and it helps node.js/V8 to avoid juggling types. If you do want to check existence you could always access `ctx.req.headers[field]` manually.

**Comment by dead-horse** [comment]
The reason is just as @miwnwski said. thanks @miwnwski to explained this. :)
