### ISSUE TITLE
use process.nextTick as middleware, response 404

### ISSUE THREAD

**Issue by zhangwinning** [koajs/koa#1491]
```
const Koa = require('koa');
const app = new Koa();

const {promisify} = require('util');

const sleep = promisify(setTimeout);

app.use((ctx, next) => {
    process.nextTick(() => {
        next();
    });
});


app.use(async ctx => {
    await sleep(2000);
    ctx.body = 'Hello World';
});

app.listen(3000);
```

when run above this code.  invoke command `curl localhost:3000 -v `. show 404 statusCode.

**Comment by miwnwski** [comment]
Every middleware is a promise. When you invoke process.nextTick that middleware (the promise) will resolve and Koa will assign default status (404 in this case).

What you did is sort of equivalent to firing a promise without await. For your example to work you need to return a promise that resolves when you intend to, e.g.

```js

app.use((ctx, next) => {
  return new Promise(resolve => {
    process.nextTick(() => {
      resolve(next())
    })
  })
})
```
