### ISSUE TITLE
Question: Tracing request across multiple files. (Correlation Id) 

### ISSUE THREAD

**Issue by vejandla** [koajs/koa#1496]
I've been trying add request id to all my logs, I've a middleware which is adding a unique id to the context object when the request comes in. But how do i access this ctx across multiple files without passing from one file to another. like --> `controller --> service --> service --> utility --> etc...`

I tried looking into to find out for any package or built in functionality, but i could not find any.

**Comment by LabMemNo003** [comment]
Perhaps you can have a look at the implementation of egg.js which is based on koa.js

**Comment by LabMemNo003** [comment]
Or override the function **createContext()** in [koa/lib/application.js](https://github.com/koajs/koa/blob/6e1093be27b41135c8e67fce108743d54e9cab67/lib/application.js#L143) to expose the context object to somewhere you need it.

**Comment by miwnwski** [comment]
Either, as you've suggested yourself, pass the context and or request id or you create some sort of global store, or as suggested above overload and implement async hooks (there's a PR which you can draw inspiration if needed).

**Comment by miwnwski** [comment]
I'm going to close this as it seems you have no further questions after the provided answers. Please re-open or open a new issue if you feel this was a premature close.
