### ISSUE TITLE
can you explain null == val vs val === null?

### ISSUE THREAD

**Issue by anlexN** [koajs/koa#1498]
i am reviewing koa source code, some codes are really very confused for me.
![image](https://user-images.githubusercontent.com/8686739/91024712-e8fb0000-e62a-11ea-907f-785db3bcae99.png)

by the way, why not use this code style?
```js
    if (val == null) {
      if (!statuses.empty[this.status]) this.status = 204;
      if (val === null) this._explicitNullBody = true;
      this.remove('Content-Type');
      this.remove('Content-Length');
      this.remove('Transfer-Encoding');
      return;
    }
```

**Comment by dead-horse** [comment]
https://stackoverflow.com/questions/17570802/why-constant-first-in-an-if-condition

But I think we can change to `val == null` for better readability

**Comment by lagden** [comment]
Explanation:

```js
// val == null
undefined == null // true

// val === null
undefined === null // false
```

**Comment by anlexN** [comment]
@dead-horse , null == val is not useful, modern runtime syntax tree is so power that can do val == null
@lagden would you write `this.body = null, or this.body(null)` in your project? i think below is ok
```js
    if (!val) {
      if (!statuses.empty[this.status]) this.status = 204;
      this._explicitNullBody = true;
      this.remove('Content-Type');
      this.remove('Content-Length');
      this.remove('Transfer-Encoding');
      return;
    }
```

**Comment by miwnwski** [comment]
Type coercion is useful when used correctly. In this case, it's even a compatibility problem. People might be setting body to undefined, and by changing this to strict equality we could theoretically break a lot of code.

As for the `null == val` vs `val == null`, I'm going to great lengths and guess here. This is just TJ's style preference that originates from C/C++ to prevent typos like `if (val = null)`.

**Comment by anlexN** [comment]
if `null == val`, but why not `null === val`?

**Comment by miwnwski** [comment]
@anlexN because Koa treats `null` and `undefined` as the same value when responding:

```js
undefined == null // true
null == null // true
undefined === null // false
```

**Comment by anlexN** [comment]
I say that code style, do you understand?

**Comment by miwnwski** [comment]
> if null == val, but why not null === val?

@anlexN No I don't think I do, again, Koa doesn't care about the difference between null and undefined when responding. My answer wasn't about about style, but about leveraging the language to Koas advantage for simplicity - I would assume/guess.

If that doesn't answer your question you need to rephrase because I can't extrapolate a different question other than what I did from your comment.

**Comment by anlexN** [comment]
can we do below?
```js
    if (null == val) {
      if (!statuses.empty[this.status]) this.status = 204;
      if (null === val) this._explicitNullBody = true;
      this.remove('Content-Type');
      this.remove('Content-Length');
      this.remove('Transfer-Encoding');
      return;
    }
```

**Comment by lagden** [comment]
@anlexN 

> @lagden would you write this.body = null, or this.body(null) in your project?

I avoid using `null` and right syntax is `this.body = some_value`, because it is a `getter` and `setter`.

Take a look: https://medium.com/@hbarcelos/why-i-banned-null-from-my-js-code-and-why-you-should-too-13df90323cfa

**Comment by anlexN** [comment]
@lagden can you answer [can we give up getter and setter syntax?](https://github.com/koajs/koa/issues/1504)

**Comment by lagden** [comment]
answered
