### ISSUE TITLE
typeof this.res.hasHeader === 'function' is meaningless

### ISSUE THREAD

**Issue by anlexN** [koajs/koa#1499]
![image](https://user-images.githubusercontent.com/8686739/91116773-b51dea00-e6bf-11ea-8b7d-75b63fa013c4.png)
in the nodejs http and http2 module, hasHeader is **function**, In the Koa, it must be also a **function**.
by the way, why not support very old node version < 7.7, that is not LTS node version. i think it is not useful

**Comment by miwnwski** [comment]
Koa follows semver, we are not changing node supported versions until we do a major bump.

If you feel there's room for improvement please open a PR with suggested changes instead of these issues with underlined images. I'm going to close this.

**Comment by anlexN** [comment]
when koa V3 release?

**Comment by miwnwski** [comment]
@anlexN no timeline has been set.

**Comment by anlexN** [comment]
what to do in V3
