### ISSUE TITLE
docs: add an example about co-based control flow

### ISSUE THREAD

**Issue by jonathanong** [koajs/koa#150]
there's stuff on cascading, but i don't think most people know or understand its effectiveness. however, there are no examples about control flow, which more people would understand, as well as actually being able to `try/catch`. these points above cascading i think would make much more sense to most people.

maybe add something like `koa` is named after `co`... unless it's not. then i have to reevaluate things.

**Comment by inca** [comment]
I'd also add some examples on how to add custom async methods to context inside a middleware (as long as it's okay to do so).

Something simple like this would do:

```js
app.use(function *(next) {
  this.login = function(username) {
    return function *() {
      var user = yield User.findOne({ name: username });
      this.session.user = user;
    };
  };
  yield next;
});

// ... and to use it

rotuer.get('/login/:name', function *() {
  yield this.login(this.params.name);
  this.redirect('/');
});
```
