### ISSUE TITLE
can we give up keygrid?

### ISSUE THREAD

**Issue by anlexN** [koajs/koa#1503]
keygrid have many problems and i can not open issues in their repo
# no permission
![image](https://user-images.githubusercontent.com/8686739/91326163-9706d580-e7f6-11ea-888d-81a9befc0ae7.png)

# code problem
![image](https://user-images.githubusercontent.com/8686739/91325170-74c08800-e7f5-11ea-9a57-473104c1141c.png)
[Based on the recommendations of NIST SP 800-131A](https://nodejs.org/docs/latest-v14.x/api/crypto.html#crypto_support_for_weak_or_compromised_algorithms)

their dependency: tsscmp also have problems [there is no crypto.pseudoRandomBytes api](https://github.com/suryagh/tsscmp/issues/17)

**Comment by miwnwski** [comment]
We are going to keep keygrip for now. You can change default algorithms as you want by passing in your own (or custom) instance of keygrip. @suryagh gave a very constructive response why they haven't updated `pseudoRandomBytes`.
