### ISSUE TITLE
can we give up getter and setter syntax?

### ISSUE THREAD

**Issue by anlexN** [koajs/koa#1504]
![image](https://user-images.githubusercontent.com/8686739/91534040-7730f800-e943-11ea-8cd5-1c4b7de8aab4.png)
we can do it the same, and koa code size is decreased, for example；
```js
module.exports = {
... some code ...

  get message() {
  },
  set message(msg = null) {
    if (msg) {
      this.res.statusMessage = msg;
    } else {
      return this.res.statusMessage || statuses[this.status];
    }
  },

... some code ...
}
```

**Comment by lagden** [comment]
@anlexN 

> Can we give up getter and setter syntax?

Nope!

Take a look in your code!
You created poor readability and an unnecessary cyclomatic complexity.
By the way, in your example has a bug, it's not possible set `0` or `false`.

**Comment by anlexN** [comment]
how is this?
```js
module.exports = {
... some code ...

  get message() {
  },
  set message(msg) {
    if (msg != undefined) {
      this.res.statusMessage = msg;
    } else {
      return this.res.statusMessage || statuses[this.status];
    }
  },

... some code ...
}
```

**Comment by miwnwski** [comment]
There's no need to change this unless there's a bug involved.
