### ISSUE TITLE
TypeError: Cannot read property 'keys' of undefined at Object.get cookies [as cookies]

### ISSUE THREAD

**Issue by Israel001** [koajs/koa#1505]
I ran my koa app and I got this error in the console and I can't seem to figure out why.
```
TypeError: Cannot read property 'keys' of undefined

- at Object.get cookies [as cookies] (/home/israel/Documents/stylesteel-sound-wave/node_modules/koa/lib/context.js:171:24)
- at serializeInto (/home/israel/Documents/stylesteel-sound-wave/node_modules/bson/lib/bson/parser/serializer.js:895:21)
- at serializeObject (/home/israel/Documents/stylesteel-sound-wave/node_modules/bson/lib/bson/parser/serializer.js:347:18)
- at serializeInto (/home/israel/Documents/stylesteel-sound-wave/node_modules/bson/lib/bson/parser/serializer.js:941:17)
- at serializeObject (/home/israel/Documents/stylesteel-sound-wave/node_modules/bson/lib/bson/parser/serializer.js:347:18)
- at serializeInto (/home/israel/Documents/stylesteel-sound-wave/node_modules/bson/lib/bson/parser/serializer.js:941:17)
- at serializeObject (/home/israel/Documents/stylesteel-sound-wave/node_modules/bson/lib/bson/parser/serializer.js:347:18)
- at serializeInto (/home/israel/Documents/stylesteel-sound-wave/node_modules/bson/lib/bson/parser/serializer.js:941:17)
- at serializeObject (/home/israel/Documents/stylesteel-sound-wave/node_modules/bson/lib/bson/parser/serializer.js:347:18)
- at serializeInto (/home/israel/Documents/stylesteel-sound-wave/node_modules/bson/lib/bson/parser/serializer.js:941:17)
```

**Comment by ctrlaltdylan** [comment]
@Israel001 could you share what was the cause & fix of this issue? I'm running into it occasionally myself.

**Comment by Israel001** [comment]
@ctrlaltdylan unfortunately, i don't remember, perhaps you should share your code if you want a suggestion

**Comment by ctrlaltdylan** [comment]
@Israel001 the only thing I can think of is that the error happens on API routes, and I have this middleware for SameSite cookie handling:
```
        server.use(session({ sameSite: "none", secure: true }, server));
```

Does that ring a bell for you by chance? API routes vs browser consumed routes?

**Comment by Israel001** [comment]
@ctrlaltdylan nope, that doesn't ring a bell. Anyway, after checking the first file in the error stack, i think you should check if you have this line ```server.keys = ['some key']```. You should also reinspect every where you might have try to use ```ctx.session``` or ```ctx.cookies```.

**Comment by ctrlaltdylan** [comment]
Ah yup I definitely don't have that line before my routes are registered. I'll give that a shot! I see there's a section in the docs about the `server.keys`. I didn't think I was using signed cookies but this could be it!

Thanks!
