### ISSUE TITLE
ctx.state.user

### ISSUE THREAD

**Issue by mylastore** [koajs/koa#1506]
I save `ctx.state.user = await User.find(id)` when user logs in,  but when I try to access the `ctx.state.user` on another route request is "undefined"

**Comment by miwnwski** [comment]
`ctx.state` is ephemeral, it only exists for as long as the request exists. This is by design. You should take a look at cookies to keep state cross request.

**Comment by mylastore** [comment]
> `ctx.state` is ephemeral, it only exists for as long as the request exists. This is by design. You should take a look at cookies to keep state cross request.

Ok, I see, thank you for the response.
