### ISSUE TITLE
Consider removing `accepts` dependency to reduce package size

### ISSUE THREAD

**Issue by nfantone** [koajs/koa#1508]
Taking a look at the published `koa@2.13.0` bundle shows that [`mime-db`](https://www.npmjs.com/package/mime-db) [**takes up almost 62% of `koa` total size**](https://bundlephobia.com/result?p=koa@2.13.0).

![image](https://user-images.githubusercontent.com/476069/95188413-45be0e80-07c4-11eb-8c25-aaaff0180c7c.png)

`mime-db` comes as a transitive dependency from `accepts`.

```sh
❯ npm ls mime-db
@my-project@1.0.0 /dev/my-project
└─┬ koa@2.13.0
  └─┬ accepts@1.3.7
    └─┬ mime-types@2.1.27
      └── mime-db@1.44.0 
```

Your experience and mileage may, obviously, vary - but I've been using `koa` (and derivatives such as `apollo-server-koa`) extensively for a number of years now, in almost all of my web based projects, and I believe I have _only once_ used `ctx.accepts` or any of the other public API features related to `accepts`. IMHO, for something that offers very little in terms of aiding regular users in building robust web servers and covers a really small part of the API surface, letting it **take more than half the size of the entire framework** seems very disproportionate - not to mention, unnecessary.

It might be required internally, as a core component, so I'm not sure about the feasibility of stripping `accepts`. I doubt, however, that the effort to remove it altogether (or replace it with a slimmer version?) would not pay off in the end. If really needed, users could install it on their own. `accepts` could be turned into a middleware of sorts, even.

Thoughts?

**Comment by miwnwski** [comment]
We can only guess the actual usage of `ctx.accepts`, but the fact is that it's part of Koas public API so we have to assume it is used. Removing it would require a semver major. That being said, I know I use it - and I would argue that it is part of Koas domain to provide this functionality. The size of the dependency isn't really a practical metric in my opinion so I would advice not to remove it (now or in a future version). Others might disagree, let's keep this open and see what opinions comes.

**Comment by nfantone** [comment]
> Removing it would require a semver major.

Yes. There are already plans and a roadmap for v3. I don't see this as a big deal if we clearly document a path forward and alternatives.

>  That being said, I know I use it - and I would argue that it is part of Koas domain to provide this functionality. 

I don't use it as much, but I understand where you are coming from. Not quite convinced on being Koa's *core* responsibility to provide such functionality, though. It's obviously subjective and up for debate. But there are already dozens of first and third party middlewares out there providing features that we could argue fall right into "Koa's domain".

> The size of the dependency isn't really a practical metric in my opinion so I would advice not to remove it (now or in a future version).

This is a fair opinion. I don't necessarily see it the same way, however. With the current shift towards serverless infrastructure, there's an increasing need for lean packages. And while I agree size might not be a relevant metric outside these areas, it's _how much of it_ is allocated to a dubious purpose, to say the least.

For a framework that tries to explicitly market itself as "not bundling anything other than the bare minimum", it raises a flag (for me) that 62% of it is dedicated to something I very rarely feel the need for.

Being small is one of the few Koa's core values.

> Koa is a new web framework designed by the team behind Express, **which aims to be a smaller**, more expressive, and more robust foundation for web applications and APIs. [...] **Koa does not bundle any middleware within its core**, and it provides an elegant suite of methods that make writing servers fast and enjoyable.

-- https://koajs.com

**Comment by dead-horse** [comment]
As a backend framework, reduce package size is at a lower priority. :)

**Comment by nfantone** [comment]
@dead-horse I agree: it's lower. I also see this as low hanging fruit that would yield an _enormous_ return in terms of reducing Koa footprint, core size and overall bug surface. 62% percent is a bit unreasonable, in my opinion.

**Comment by nfantone** [comment]
I could try and open a PR for this if people would consider taking a stab at it or if there's any interest in it.

**Comment by 3imed-jaberi** [comment]
IMO, it's the time to think of the next release and write a ref focus on improving performance and reducing the bundle size or update the current one #1114

**Comment by jonathanong** [comment]
are you more concerned with the disk size or app startup time? if the latter, we can lazy load it. if you're just worried about disk size, this would be difficult because a lot of other middleware use it and there's a good a chance another dependency in your tree uses mime-db as well.

**Comment by nfantone** [comment]
@jonathanong Both, really. On serverless environments both aspects should be considered. Lazy loading it could be a first good step, but I'm concerned it'd break some bundlers out there.

> this would be difficult because a lot of other middleware use it

We can temper difficulties by introducing this as a major release. I think this was mentioned before here. This is exactly why we follow SemVer. I don't see it as a real setback.

> there's a good a chance another dependency in your tree uses mime-db as well.

Probably. Probably not. We can't really make assumptions on users' environments. Regardless, if a user installs `mime-db` (either explicitly or through a transitive dep), that's really on them.

Honestly, all I wanted to do is raise awareness on how much `koa` allocates to a functionality that feels completely secondary next to its core. This, IMHO, goes against `koa`'s own principles. Specially, since it can very easily be stripped out and made available as a different, optional package.

I would love to see `koa` v3 be published as a simple, barebones middleware engine and thin wrappers around the native `http` Node.js module. Everything else should be optional.

**Comment by siakc** [comment]
I think judging by size percentage does not give a whole insight. It is ~121 KBs only. It is nothing.

**Comment by HonzaMac** [comment]
Is it possible to read "mimedb" from operating system via nodejs API?
