### ISSUE TITLE
Shrink Koa's support to Node.js' currently supported versions

### ISSUE THREAD

**Issue by joelwallis** [koajs/koa#1509]
I'm starting a new project today with Koa and I noticed it _"requires"_ Node.js v7.6 in order to work. Well, since the Node.js' 7th version is far gone - with the 10th one being the oldest still "active" (maintenance patches only) and the 12th being the current LTS, maybe it's time to update Koa's supported Node.js versions.

**Is there any good reason to not deprecate Koa's support for Node.js versions prior to the LTS one?**

PS: I see there's #1502 that went over this topic before, but it seemed the approach took by its author was a bit aggressive, and the matter didn't have a chance to be taken seriously.

**Comment by joelwallis** [comment]
Sorry for those who got notified by email with a very short description - I hit the Create Issue button way sooner, accidentally. 😅

**Comment by miwnwski** [comment]
> Is there any good reason to not deprecate Koa's support for Node.js versions prior to the LTS one?

To upgrade, we need to bump semver. If you update the minimum requirements we'd be breaking peoples code. This has been talked over in numerous tickets so I'm going to close this one.

**Comment by joelwallis** [comment]
@miwnwski thank you very much for giving me proper context!
