### ISSUE TITLE
Koa await call error with stream.

### ISSUE THREAD

**Issue by jayli** [koajs/koa#1511]
When I want to print some messages one by one with a timmer. The following code does not work exactly as your wish.

```
  router.get('/demo',async (ctx)=>{
    var stream = ctx.body = new Readable();
    stream._read = function () {};

    ctx.set({
        'Content-Type': 'text/undefined-content',
        'Transfer-Encoding': 'chunked'
    });

    ctx.res.flushHeaders();
    stream.push('start\n');

    await repeat(stream); // output message one by one with a timmer

    stream.push('\nThere is only a one-time output!\n');
    stream.push(null);
  });
```

Take a look at the example here: <https://github.com/jayli/koa-stream-await-call-error>

Is it a bug?

**Comment by miwnwski** [comment]
I would say it's an unfortunate consequence of current inner workings of Koa

**Comment by miwnwski** [comment]
I'm closing this as conversation is stale and not necessarily a bug report either. If you feel there's an issue or improvement to be made reopen this or a new ticket/PR!
