### ISSUE TITLE
Koa update problem

### ISSUE THREAD

**Issue by jahnli** [koajs/koa#1514]
When I compared KOA with Express, I found that koA and its peripheral plug-ins were too slow to update and maintain. Could you tell me why

**Comment by miwnwski** [comment]
What package are you referring to?

**Comment by miwnwski** [comment]
Actually, I'll answer by rephrasing.

Koa core is generally a stable library with little requirement for updates.
As far as packages, you'll have to ask the maintainers of those packages.

I'm going to close this issue but if you feel my answer is inadequate, don't hesitate to reopen this ticket.
