### ISSUE TITLE
How is body stringified when returning `application/json` responses?

### ISSUE THREAD

**Issue by yuvke** [koajs/koa#1515]
Hi if I set an object or array as the body like so:
``` javascript
ctx.body = {
  some: 'prop'
}
```
How will Koa stringify this object? Will it always use JSON.stringify?
If we pass a custom object, can we count on `.toJSON()` methods being called in this transformation?

**Comment by miwnwski** [comment]
Yes, if body is and Object Koa will use JSON.stringify, unless type is e.g. a stream.
