### ISSUE TITLE
How can I type ctx.body

### ISSUE THREAD

**Issue by pkuczynski** [koajs/koa#1516]
This is my example controller:

```
export const getHealthCheck = (ctx) => {
    ctx.body = {
        status: 'HEALTHY'
    }
}
```

How can I provide a typescript interface to `ctx.body` to ensure it's returning the right shape of data?

**Comment by talentlessguy** [comment]
it might inconvinient to use but the easiest way to type it is extending Koa context and overriding `body` property. In `@types/koa` body is typed as `any` so I'm not sure how else it can be typed

```ts
import Koa, { Context } from 'koa'

interface MyContext extends Context {
  body: {
    status: 'HEALTHY'
  }
}

const app = new Koa()

app.use((ctx: MyContext) => {
  ctx.body = {
    status: 'HEALTHY'
  }
})
```

![image](https://user-images.githubusercontent.com/35937217/102873992-e9799b00-4452-11eb-9512-1740a634a5cb.png)

**Comment by pkuczynski** [comment]
I rather prefer to type the const, which better holds strict checking. So I wanted to achieve something like:

```js
interface GetHealthCheckResponse {
  status: string
}

export const getHealthCheck: Koa.Middleware<GetHealthCheckResponse> = (ctx) => {
    ctx.body = {
        status: 'HEALTHY'
    }
}
```

**Comment by miwnwski** [comment]
Linked PR is merged so I'm closing this.

**Comment by pkuczynski** [comment]
Yes! Thank you! :) Forgot to close this one :)
