### ISSUE TITLE
Unable to trap EADDRINUSE

### ISSUE THREAD

**Issue by Richie765** [koajs/koa#1517]
When doing `app.listen()` and the listening port is already in use, it will always terminate the program. I could not find a way to catch error. I tried `try/catch` isn't working. I also tried `app.on('error', ...)`, also with no effect. The callback to `app.listen` is also not called with an error object.

To reproduce the issue
```
app.on('error', err => {
  // Not reached with EADDRINUSE
  console.log('error event', err.message);
});
try {
  app.listen(8080, () => {
    // Not reached with EADDRINUSE
    console.log('listen callback', err.message);
  });
}
catch(err) {
  // Not reached with EADDRINUSE  
  console.log('listen catch', err.message);
}
```

Error message:
<pre>
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Application.listen (.../node_modules/koa/lib/application.js:82:19)
    at main (.../my_server.js:36:11)
    at .../my_server.js:71:5
</pre>

**Comment by miwnwski** [comment]
`EADDRINUSE` is an event fired by nodes http.Server. It's not a synchronous operation to start a server so you need to listen to its events. Here's a working example:

```js
const Koa = require('koa')
const app = new Koa()
const PORT = process.env.PORT || 8080

app.use(index)
const server = app.listen(PORT)
server.on('error', httpErrorHandler)

async function index (ctx) {
  ctx.body = 'should error out'
}

function httpErrorHandler (err) {
  console.error(err.message)
}
```

**Comment by miwnwski** [comment]
I'm going to close this as it seems my answer was sufficient. If you disagree or still have issue feel free to reopen or create a new issue!

**Comment by JosXa** [comment]
@miwnwski This does not actually work for me. Nothing is ever printed, despite the port definitely being used. I'm on ^2.14.1.
