### ISSUE TITLE
checking client certificate match

### ISSUE THREAD

**Issue by ilanl** [koajs/koa#1519]
Hi,
In nodejs/express we can do the following:

[julie-ng source code](https://raw.githubusercontent.com/julie-ng/nodejs-certificate-auth/master/server/server.js)

```
app.get('/authenticate', (req, res) => {
	const cert = req.socket.getPeerCertificate();

	if (req.client.authorized) {
		res.send(`Hello ${cert.subject.CN}, your certificate was issued by ${cert.issuer.CN}!`);

	} else if (cert.subject) {
		res.status(403)
			 .send(`Sorry ${cert.subject.CN}, certificates from ${cert.issuer.CN} are not welcome here.`);

	} else {
		res.status(401)
		   .send(`Sorry, but you need to provide a client certificate to continue.`);
	}
});
```
what would be the equivalent in koa to verify client certificate?

**Comment by miwnwski** [comment]
You can access node.js' native request and response via `ctx`, e.g: `ctx.req.socket.getPeerCertificate()`

**Comment by ilanl** [comment]
![Screenshot from 2021-01-22 13-44-54](https://user-images.githubusercontent.com/1138254/105487193-5da89800-5cb8-11eb-8081-53a25e157660.png)
Do I need an additional package? (using Koa with Typescript)

**Comment by miwnwski** [comment]
Unrelated to Koa, that is native node Socket. I don't know why  it doesn't work for you unfortunately - I am not a TS user. Maybe someone else have insight.

**Comment by ilanl** [comment]
May be someone else can reproduce it with TS?

**Comment by 3imed-jaberi** [comment]
Welcome @ilanl, I believe that the problem is from [@types/koa](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa/index.d.ts). 
So you need to do something like that:

```typescript
// the 1st solution: access from socket inside the koa context.
import * as Koa from 'koa'
import { TLSSocket } from 'tls'

const app = new Koa()

// the current Koa types use Socket from 'net' module 
// where 'getPeerCertificate' from 'tls' module.
interface IKoaContext extends Koa.Context {
  socket: TLSSocket
}

function middleware (ctx: IKoaContext, next: Koa.Next) {
  ctx.socket.getPeerCertificate()
}

// the 2nd solution: access from raw request inside the koa context or both.
import * as Koa from 'koa'
import { IncomingMessage } from 'http'
import { TLSSocket } from 'tls'

const app = new Koa()


interface RawRequest extends IncomingMessage {
  socket: TLSSocket
}

interface IKoaContext extends Koa.Context {
  socket: TLSSocket, // line 1
  req: RawRequest // line 2
}

function middleware (ctx: IKoaContext, next: Koa.Next) {
  ctx.socket.getPeerCertificate() // given from line 1
  ctx.req.socket.getPeerCertificate() // given from line 2
}
```

**Comment by miwnwski** [comment]
As a full working example was provided and this ticket has been stale for 20 days I'm going to close it. Please re-open if you feel you still need help or feedback.
