### ISSUE TITLE
ctx.state causes CORS issue

### ISSUE THREAD

**Issue by syntacticsolutions** [koajs/koa#1521]
When using Koa on a production server,  I'm getting the user from Firebase using the authorization header.

```javascript
let serviceAccount = require('./firebase-key.json');
const firebaseAdmin = require('firebase-admin')

firebaseAdmin.initializeApp({
    credential: firebaseAdmin.credential.cert(serviceAccount),
});

const processAuth = (ctx) => {
    return new Promise((resolve, reject) => {
        
        /**
            @desc - check if authorization header is present
        */
       resolve({})

        const authorizationHeader = ctx.headers.authorization;
        
        if (!authorizationHeader) return resolve({})
        
        const idToken = authorizationHeader.split(' ').pop();
        
        /**
            @desc - verify the token
        */
        return firebaseAdmin
            .auth()
            .verifyIdToken(idToken)
            .then(user => {
                resolve(user)
            })
            .catch(err => reject(err))
    })
}

exports.setAuthUser = async (ctx, next) => {
    let user = await processAuth(ctx)
        .catch(err => {throw new Error(err)})

    ctx.state = user || {}
    return await next()
}

exports.firebaseAdmin = firebaseAdmin
```

This code throws a CORS error in production, but not in local. It states that there is no Access-Control-Allow-Origin header but in my app.js I'm using `ctx.set('Access-Control-Allow-Origin', 'https://www.lavishweb.com')`

When I comment out `ctx.state = user || {}` everything works fine for using unprotected graphql queries/mutations, but now I'm not able to access the user data.

**Comment by syntacticsolutions** [comment]
Nevermind, I just added it to the graphql context instead.

**Comment by 3imed-jaberi** [comment]
I recommend to change this line `ctx.state = user || {}` by ` ctx.state.user  = user || {}`.

**Comment by miwnwski** [comment]
This seems to be resolved, and also as suggested don't override state but rather use it as a hash map. Please re-open if you feel I'm closing this ticket prematurely.

**Comment by syntacticsolutions** [comment]
haha, I guess that makes sense. Must have been sleep deprived lol
