### ISSUE TITLE
I am getting this error while running the node app, previously everything work fine, i thinks some changes occur in koa module due to which this error arrises.

### ISSUE THREAD

**Issue by niteshtripathi1234** [koajs/koa#1524]
src/server.ts(66,11): error TS2345: Argument of type 'Middleware<ParameterizedContext<DefaultState, DefaultContext>>' is not assignable to parameter of type 'Middleware<Context>'.
  Type 'ParameterizedContext<DefaultState, DefaultContext>' is not assignable to type 'Context'.
    Types of property 'app' are incompatible.
      Type 'import("/app/node_modules/@types/koa-compose/node_modules/@types/koa/index.d.ts")<DefaultState, DefaultContext>' is not assignable to type 'Application'.
        Types of property 'response' are incompatible.
          Type 'import("/app/node_modules/@types/koa-compose/node_modules/@types/koa/index.d.ts").BaseResponse' is not assignable to type 'import("/app/node_modules/@types/koa/index").BaseResponse'.
            Types of property 'is' are incompatible.
              Type '{ (...types: string[]): string | false; (types: string[]): string | false; }' is not assignable to type '{ (...types: string[]): string; (types: string[]): string; }'.
                Type 'string | false' is not assignable to type 'string'.
                  Type 'false' is not assignable to type 'string'.
src/server.ts(67,11): error TS2345: Argument of type 'Middleware<ParameterizedContext<DefaultState, DefaultContext>>' is not assignable to parameter of type 'Middleware<Context>'.
src/server.ts(69,11): error TS2345: Argument of type 'Middleware<ParameterizedContext<DefaultState, DefaultContext>>' is not assignable to parameter of type 'Middleware<Context>'.
src/server.ts(90,11): error TS2345: Argument of type 'Middleware<ParameterizedContext<any, IRouterParamContext<any, {}>>>' is not assignable to parameter of type 'Middleware<Context>'.
  Type 'ParameterizedContext<any, IRouterParamContext<any, {}>>' is not assignable to type 'Context'.
    Types of property 'app' are incompatible.
      Type 'import("/app/node_modules/@types/koa-compose/node_modules/@types/koa/index.d.ts")<DefaultState, DefaultContext>' is not assignable to type 'Application'.
npm ERR! code ELIFECYCLE

**Comment by 3imed-jaberi** [comment]
@niteshtripathi1234, can you provide more details like some code , modules versions .. !!

**Comment by miwnwski** [comment]
This question has been stale for 12 days now. I'm going to close this as I assume you've resolved your issue. If this is incorrect and you still need help/feedback please provide more details as @3imed-jaberi suggested and re-open this ticket.
