### ISSUE TITLE
Explicit-Null-Body should contains Content-Length

### ISSUE THREAD

**Issue by nfer** [koajs/koa#1525]
Koa version 2.13.1

Running below codes:
```js
const koa = require('koa');
const app = new koa();

app.use(ctx => {
  ctx.body = null;
  ctx.status = 404;
});

app.listen(3000, () => {} )
```

Both in chrome and curl test, it fails in 5s.

```shell
$> time curl http://localhost:3000/
curl http://localhost:3000/  0.01s user 0.01s system 0% cpu 5.013 total
```

I think the question is lost of Content-Length header:
> A user agent SHOULD send a Content-Length in a request message when
   no Transfer-Encoding is sent and the request method defines a meaning
   for an enclosed payload body. 

from [RFC7230](https://tools.ietf.org/html/rfc7230#section-3.3.2)

I add one line codes `ctx.length = 0;` in [application module](https://github.com/koajs/koa/blob/master/lib/application.js#L258), it pass all test cases and works for chrome and curl.

If it is really a bug, and the modification works, I will submit a PR.

**Comment by ognjenjevremovic** [comment]
Hey @nfer 👋 .

Are you working on this? Do you perhaps need some assistance?

If you're not actively working on this (and the bug is still present), I'd be willing to provide PR myself is that is ok with you?
Let me know if I can help somehow with this issue.

Cheers!

**Comment by nfer** [comment]
Thanks @ognjenjevremovic , I think PR is welcome.

**Comment by ognjenjevremovic** [comment]
Any updates on the PR?

**Comment by miwnwski** [comment]
This was merged by Jonathan into master so I'm closing this.

**Comment by 3N26** [comment]
this fix was not merged into master 
https://github.com/ognjenjevremovic/koa/blob/master/lib/application.js#L256
