### ISSUE TITLE
Unable to set custom headers to responses.

### ISSUE THREAD

**Issue by bosco-formative** [koajs/koa#1533]
Tried to set custom headers:
```
ctx.set( 'Cross-Origin-Opener-Policy', 'same-origin' );
ctx.set( 'Cross-Origin-Embedder-Policy', 'require-corp' );
```

The changes weren't propagating to my response headers, is there a way to set custom headers like this?
Has anyone else tried to set these to access SharedBufferArray() object?

**Comment by miwnwski** [comment]
There's some problem in your application because the following works fine.
Also there's [tests in repo](https://github.com/koajs/koa/blob/master/test/response/set.js) that confirm this so you'll have to give more context.

```js
const Koa = require('koa')

const app = new Koa()

app.use(async ctx => {
	ctx.set('Custom-Headerfield', 'Some Value')
	ctx.status = 200
})

app.listen(8080)
```

```sh
$ node index.js &
$ curl localhost:8080 -v
< HTTP/1.1 200 OK
< Custom-Headerfield: Some Value
< Content-Type: text/plain; charset=utf-8
< Content-Length: 2
< Date: Mon, 03 May 2021 21:12:48 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
OK* Closing connection 0
```

**Comment by bosco-formative** [comment]
Thanks @miwnwski, I was using webpack and it doesn't set custom headers in webpack, this is a non-issue.
