### ISSUE TITLE
Route called multiple times

### ISSUE THREAD

**Issue by hahatulk** [koajs/koa#1536]
I have routes: /orders, /orders/list. When i request /orders/list, /orders triggers too. How to prevent triggering higher routes?

**Comment by miwnwski** [comment]
You need to provide code or we can't t help - just guess. If you do provide code, make sure you provide a fully reproducible example to eliminate possible guesswork.

**Comment by miwnwski** [comment]
I'm going to close this question as no code was provided and I'm assuming you solved this already.
