### ISSUE TITLE
koa dependency keyGrip stale since 2019

### ISSUE THREAD

**Issue by noahehall** [koajs/koa#1539]
[koa introduction](https://koajs.com/#introduction) docs lists [keyGrip](https://github.com/crypto-utils/keygrip) dependency for use in setting `app.keys = ...`

however keyGrip hasnt received updates since 2019

is anyone using this functionality, and if so, how are you working around this stale dependency?

to be fair: the keygrip package code is relatively small (yet impactful). its own dependencies are nodes crypto (which would depend on your env and not packaged with keygrip) and more importantly the [tsscmp](https://github.com/suryagh/tsscmp) package.

the tsscmp hasnt been updated since apr 2020.

**Comment by miwnwski** [comment]
Lack of commits does not indicate usage. Keygrip is actively used/downloaded downloaded ~1m times from the npm registry every week. It's not stale, it's stable.

**Comment by noahehall** [comment]
You know what else was downloaded over 2illion times a week? eslint-scoped

**Comment by dougwilson** [comment]
I am the current maintainer of keygrip. If you are having trouble with something, please open an issue and I can help to fix your issue. If you think there are enhancements that can be made to it, please open an issue with your idea/request or even open a pull request. As @miwnwski stated, the module is stable and doesn't need constant releases to fix bugs any longer, but if there is a bug you want to report to fix, please do.

**Comment by noahehall** [comment]
@dougwilson thx - will take into account @miwnwski thoughts and do some research, and if necessary, reopen @keygrip repo

**Comment by dougwilson** [comment]
Hi @noahehall I was about to edit, but I'll just reply here: ultimately I am not here to tell Koa to use keygrip :) Koa is free to use whatever module they wish. But I just watch repos that depend on modules I maintain to help when I can -- I'm not sure you'll find a lot of other module maintainers that actually watch/interact with the repos that depend on their modules :)

As for the Keygrip repo, it is open and not archived or anything. Not having an update mainly means there is nothing to actually publish out. But if there is some specific bug, yes, please open an issue describing the bug and provide the specific steps to reproduce the issue. You're also welcome to open a pull request with a proposed fix if you already diagnosed it.

**Comment by noahehall** [comment]
valid points from you @dougwilson as well as by @miwnwski 

will gork a bit and see if i find anything

**Comment by miwnwski** [comment]
>>> is anyone using this functionality

>>  Keygrip is actively used/downloaded ~1 million times from the npm registry every week

> You know what else was downloaded over 2million times a week? eslint-scope

I'm not sure what you're implying? I was answering your question?
