### ISSUE TITLE
The official website details are wrong

### ISSUE THREAD

**Issue by qsbit** [koajs/koa#1546]
这意味着您可以同时支持 HTTPS 和 HTTPS，或者在多个端口监听同一个应用。
For “HTTPS”,The first one should be the "HTTP"

**Comment by adaex** [comment]
Hello, on which website did you see this error? I did not find it on the official website.

**Comment by miwnwski** [comment]
I'm closing this issue. If you still see this error don't hesitate to reopen and provide more information so we can find this.
