### ISSUE TITLE
"koa-range" has been unmaintained for many years. It is recommended to find someone else to maintain it.

### ISSUE THREAD

**Issue by masx200** [koajs/koa#1549]
https://www.npmjs.com/package/koa-range

"koa-range" has been unmaintained for many years. It is recommended to find someone else to maintain it.

https://github.com/koajs/koa-range

**Comment by jonathanong** [comment]
I see you've been making PRs. I will add you as a maintainer

**Comment by masx200** [comment]
> I see you've been making PRs. I will add you as a maintainer

It is recommended to find someone else to maintain it

**Comment by masx200** [comment]
https://www.npmjs.com/package/@masx200/koa-range

@jonathanong
