### ISSUE TITLE
Maintaining Order of array querystring element

### ISSUE THREAD

**Issue by mu-majid** [koajs/koa#1556]
I have a question/check, Does Koa (ctx.request.query) maintain the order of the array querystring element?

For example: a querystring like userIds=456&userIds=123 should be parsed to { userIds: ['456', '123'] } , but what I am experiencing right now is the order is not maintained, an it actually gets sorted.

I tried to trace this behavior, and found that Koa is using native NodeJS querystring module, which I tested this behavior with it, and it maintains the order.

So when/where this order changing happen, and how to maintain the querystring params order (for an array element) ?

**Comment by miwnwski** [comment]
Koa itself doesn't do any sorting. Koa returns (and caches) the result of node querystring.parse function. However, I'm aware of any guarantee of order made anywhere. Generally speaking order of keys are not to be trusted anywhere so I would recommend not to design for it.

**Comment by jonathanong** [comment]
correct, Koa just uses `querystring` right now
