### ISSUE TITLE
Support Map object in response body

### ISSUE THREAD

**Issue by valorad** [koajs/koa#1557]
Currently, koa.js does not support JavaScript Map Object in the response body.

Now, if a Map object is assigned to it, the front-end receives nothing but an empty object, as shown in [this repository](https://codesandbox.io/s/investigation-koa-router-map-gzz6n?file=/src/index.js).

The current work-around is calling `Object.fromEntries()` to convert a map to an object, then send the object to the front-end. It would be better to support this directly.

Related: koajs/router#120

**Comment by jonathanong** [comment]
you can create your own middleware for this. maps aren't used often enough to necessitate adding it to the framework

**Comment by valorad** [comment]
@jonathanong Can you please provide a code example instead of closing this issue brutely?!

**Comment by jonathanong** [comment]
```js
app.use(async (ctx, next) => {
  await next()
  if (ctx.body instanceof Map) {
    ctx.body = // whatever you want
  }
})
```
