### ISSUE TITLE
TypeScript rewrite

### ISSUE THREAD

**Issue by TheMisir** [koajs/koa#1560]
I would like to re-write koa.js completely in typescript. But I think before starting out I wanted to know a few things:

- Whether is it worth it? I mean what's your thoughts on that. I personally like using typescript but I usually use ASP.NET Core rather than js technologies for back end I don't know current market share of koa.js versus alternatives so don't know whether is it worth to work on this.
- Is this project maintained, (so will someone able to verify my PR afterwards).
- Is there any on-going progress that I can contribute to rather than starting from scratch?

Some of those questions might be stupid to ask, sorry for that. I just want to know current status of the project.

**Comment by dougwilson** [comment]
See https://github.com/koajs/koa/issues/1475

**Comment by TheMisir** [comment]
> See #1475

Thanks.
