### ISSUE TITLE
Fix ESM tests

### ISSUE THREAD

**Issue by jonathanong** [koajs/koa#1571]
when upgrade to jest and testing on node v16, they break. gonna need some help fixing them

**Comment by rubenmeza** [comment]
Hello @jonathanong is this still an issue? I ran the tests using node version 16.11.1 and all tests pass 

![Screen Shot 2021-10-18 at 20 13 04](https://user-images.githubusercontent.com/497410/137827737-a96b91d7-5a57-465b-a78e-61d948003d65.png)

**Comment by miwnwski** [comment]
I'm under the impression that this isn't an issue anymore, so I'm closing this until I hear otherwise.
