### ISSUE TITLE
如何在一个接口内调用内部另一个接口？

### ISSUE THREAD

**Issue by calmchang** [koajs/koa#1583]
比如Koa内我有2个接口，分别是： /login 和 /loginUser
我想在login这个接口内调用一下/loginUser 怎么做比较好？

**Comment by liamfend** [comment]
我的天。  你居然在这中文 提问 呢。。。  
这个 就是 你的项目结构有点 问题了。 
  把逻辑提取到 Service（or BLL  ）层处理下,不要把公用逻辑写到Conroller里面

**Comment by chenkai0520** [comment]
@calmchang 导出函数后随便调

**Comment by ManInTheWind** [comment]
ctx.redirect?

**Comment by lchrennew** [comment]
https://www.npmjs.com/package/es-fetch-api

**Comment by miwnwski** [comment]
I'm just going to assume this question is either invalid and/or answered. Please re-open if I'm mistaken.
