### ISSUE TITLE
What is the default Content-Type when response.body is set to a string?

### ISSUE THREAD

**Issue by jameshfisher** [koajs/koa#1591]
[In the docs](https://koajs.com/#response-body-) I read:

> **response.body=**
>
> Set response body to ...
> 
> String
> The Content-Type is defaulted to text/html or text/plain ...

But which is it? `text/html` or `text/plain`? Under which circumstances? How do I configure it?

**Comment by Spekpannenkoek** [comment]
https://github.com/koajs/koa/blob/65f9c939e173ff2fab82ee9229a2213690959426/lib/response.js#L158

This checks:

- Is there a Content-Type set?
- If not: is the body a string?
- If so: is there whitespace followed by `<`?
- If so: set to HTML, else plain text.

Followed by checks in case the body is a Buffer or Stream instance.

**Comment by miwnwski** [comment]
Asked and answered, but if you disagree please reopen this ticket (or create a new one).
