### ISSUE TITLE
TypeScript 4.5.0 has issues with our MJS

### ISSUE THREAD

**Issue by rayfoss** [koajs/koa#1597]
Related to #1513 

When using Node in ESM mode and TypeScript 4.5 with `compilerOptions.module set to "node12" OR "nodenext"` ESModuleInteropt is no longer needed and the MJS export can be used directly with TypeScript.

The problem comes when we use @types/koa... which doesn't define a default type export! Therefore Koa effectively has no types in this situation.

# Solution #1

Make a named export called Application in the MJS wrapper.

# Solution #2 

Add types to the MJS export with dist/koa.d.ts that references the DefinitelyTyped Koa definitions

```
// dist/koa.d.ts
import { Application } from "@types/koa"
declare module "koa" {
  export const mod: Application
}
```

# Solution #3

Rename mod to Application in dist/koa.mjs... then export Application as default

# Details
- **sandbox**: [run tsc in terminal](https://codesandbox.io/s/koa-types-on-ts-native-node-modules-v7dv9) 
    - Check the Terminal not the IDE... TypeScript 4.5 is installed in the project but the sandbox IDE has an out of date TS version
- https://unpkg.com/browse/@types/koa@2.13.4/index.d.ts
- https://unpkg.com/browse/koa@2.13.3/lib/application.js

**Comment by killagu** [comment]
@rayfoss With this solutions, Should we use like `import { Application} from 'koa'`?

**Comment by rayfoss** [comment]
Lots of changes happened to ts-node, and typescript ... I can no longer reproduce.
