### ISSUE TITLE
Please update History.md

### ISSUE THREAD

**Issue by glen-84** [koajs/koa#1606]
It hasn't been updated since v2.13.1.

**Comment by dead-horse** [comment]
@glen-84 koa is seperate to different branches to maintain v2 and v3, v2's history is updated at https://github.com/koajs/koa/tree/v2.x

**Comment by glen-84** [comment]
Oh I see. It's a bit confusing since the README on master is still referring to v2.

Perhaps v3 should have stayed on a branch until it was ready for release.

Thanks.
