### ISSUE TITLE
Some attribute in ctx.response can not printed by console.log

### ISSUE THREAD

**Issue by dadalxx** [koajs/koa#1611]
```
const Koa = require('koa');
const app = new Koa();

app.use(async ctx => {
  ctx.body = 'Hello World';
  console.log(ctx.response);
});

app.listen(3000);
```

I just want to see the attributions in ctx.response, but just status | message | header | body are shown.

It should have some other attributes like type | length | etag or app | res | req ...

Thx!

**Comment by VBetsun** [comment]
`console.log()` passes all arguments to the `util.format()`. That is why **koa** triggers [formatting for `ctx.response`](https://github.com/koajs/koa/blob/master/lib/response.js#L592).
If you want to access all available info about the response you can use the [inspector](https://nodejs.org/en/docs/guides/debugging-getting-started/)

**Comment by dadalxx** [comment]
Thx！
