### ISSUE TITLE
ctx.message assignment of Chinese or Other language(such as Japanese) will throw an error: TypeError [ERR_INVALID_CHAR]: Invalid character in statusMessage

### ISSUE THREAD

**Issue by ShiliangLuo** [koajs/koa#1627]
I want to assign ctx.message to specific message, but koa throw an error. See: https://codesandbox.io/s/quiet-thunder-q7po0?file=/src/index.js

**Comment by ShiliangLuo** [comment]
If I change the order of the sentence:

ctx.message = '中文';
ctx.body = 'hello world';

the program will run successfully, but the result of ctx.message is not changed. Puzzled!

**Comment by dober-mill** [comment]
maybe you can avoid this error by this way:
`ctx.message = new Buffer("中文").toString("base64");`

`ctx.body = {
    code: 0,
    data: ctx.body,
    msg: Buffer(ctx.message, "base64").toString()
  };`

Japanese is also no error
See: [link](https://codesandbox.io/s/optimistic-frog-lewyf?file=/src/index.js)

**Comment by ShiliangLuo** [comment]
> 

THX, I'll try. But, what's the reason?

**Comment by ckvv** [comment]
@ShiliangLuo 这似乎是node的问题，

执行`ctx.message = '中文';` 时会设置` res.statusMessage = '中文';`

对应代码在
https://github.com/koajs/koa/blob/8c1dd481207de0930956304a3e9f1e103f8492a5/lib/response.js#L111-L115

下面的代码也报相同错误
```
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusMessage = '中文';
  res.end('Hello World');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

**Comment by ShiliangLuo** [comment]
> @ShiliangLuo 这似乎是node的问题，
> 
> 执行`ctx.message = '中文';` 时会设置` res.statusMessage = '中文';`
> 
> 对应代码在
> 
> https://github.com/koajs/koa/blob/8c1dd481207de0930956304a3e9f1e103f8492a5/lib/response.js#L111-L115
> 
> node中对`statusMessage`做了限制，需要满足正则表达式`/[^\t\x20-\x7e\x80-\xff]/`，代码在
> 
> https://github.com/nodejs/node/blob/ccb8aae3932c13f33622203b2ffc5a33120e9d40/lib/_http_common.js#L224-L235
> 
> 下面这个issue有提到这个问题 [nodejs/node#28797](https://github.com/nodejs/node/issues/28797)

嗯，后来我找到原因了

**Comment by miwnwski** [comment]
Unfortunately this has little to do with Koa as Koa delegates status message assignment to `node:http.res.statusMessage`.
