### ISSUE TITLE
Does koajs org consider import outside collaborators?

### ISSUE THREAD

**Issue by xtx1130** [koajs/koa#1656]
I submit a pull request at last week and it's still waiting for review. I find many pull requests has been waiting for review. So does `koajs` organization consider import outside collaborators to help review and merge those pull requests?

**Comment by miwnwski** [comment]
I'll chime in here. The problem isn't necessarily finding people to merge PRs. 

On any normal day I guess I am the "grumpy" guy who denies features and changes by default. The sole purpose of me doing that (as I see it) is to keep bloat away from Koa core. I fend for Koas simplicity, which I think is its strongest ... erm, feature? The simplicity is what makes me value Koa and unless other maintainers decides to take the library in a different direction I'll probably stay "grumpy".

At the same time, I'm personally not active enough to even consider adding new members, I don't feel like that's my mandate to do. I'm sure if the "right" developer comes along, jongleberry wouldn't mind adding them as org members.
