### ISSUE TITLE
What's in a name?

### ISSUE THREAD

**Issue by KnorpelSenf** [koajs/koa#1663]
Non-technical issue. I've always wondered why it's called _koa_. Is it an abbreviation? An acrynom? Is there a story behind it?

Priority is low on this one :)

**Comment by KnorpelSenf** [comment]
Oh and no, I did not manage to find anything about this on Google or in the docs or in this repo. The closest I got was #230, but it does not reveal much.

**Comment by miwnwski** [comment]
Koa is a tree. I guess it's up for interpretation to why the creators chose it as it's logo: https://en.wikipedia.org/wiki/Acacia_koa
