### ISSUE TITLE
[fix] Docs not contain `writable` getter for `response`

### ISSUE THREAD

**Issue by Viiprogrammer** [koajs/koa#1680]
## Actual behavior
Docs not contain `writable` getter for `response`

## Expected behavior
Docs contain `writable` for response

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.

**Comment by siakc** [comment]
What do you mean by writable getter? A setter? Can you provide an example?

**Comment by Viiprogrammer** [comment]
> What do you mean by writable getter? A setter? Can you provide an example?

https://github.com/koajs/koa/blob/5ba533f83117316486a55f097a764dac9e7c140a/lib/response.js#L534
