### ISSUE TITLE
[feat] request.params is not missing at the docs?

### ISSUE THREAD

**Issue by ArthurPedroti** [koajs/koa#1683]
Hey everyone, I'm current use the params of a request at my backend, and it's a comom thing you do when you are creating the update route of your application.

And I don't thing anything about this property in the request object docs.

Shouldn`t that docs be there?

By the way I can even do this part of docs, I'm only asking myself why that is not over there.

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.

**Comment by kedarchandrayan** [comment]
PR https://github.com/koajs/koa/pull/1684 will solve this missing documentation issue. Please merge it.

**Comment by miwnwski** [comment]
There is no request.params in Koa. I assume you are using [@koa/router](https://github.com/koajs/router), in which case this should be moved to that repo.
