### ISSUE TITLE
[fix] Chinese documentation redirect to a third-party page

### ISSUE THREAD

**Issue by sjfkai** [koajs/koa#1691]
## Describe the bug

**Description:** koajs.cn redirect to a third-party page

## Actual behavior

redirect to a third-party page

## Expected behavior

show Chinese documentation

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.
- [x] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by fengmk2** [comment]
koajs.cn is not the koa project domain, I will remove it from koajs.com

**Comment by zhengbangbo** [comment]
I got a reply from the domain name owner and learned that the Chinese documentation is handled by "印记中文".

如果你确实需要中文文档，可以访问 https://koajs.docschina.org/
