### ISSUE TITLE
[feat] Prefer returning the next middleware's result in the documentation examples

### ISSUE THREAD

**Issue by zkulbeda** [koajs/koa#1710]
There are examples in the documentation that show that it is not necessary to return a result of the next middleware. If the developers follow this example for writing packages, then it will be impossible to do this things:

```js
app.use(async (ctx, next) => {
  const result = await next();
  if(result instanceof CustomError){
    ctx.body = "something wrong";
    ctx.status = 500;
    return;
  }
  if(!result && typeof result === "object"){
    ctx.body = result; // response with json
  }
})

app.use(async (ctx, next) => {
  // example code from external package
  await next();
  // the result is lost
});

app.use(async ctx => {
  if(ctx.request.charset !== 'utf-8') // some logic
    return new CustomError();

  return { ok: true }
});
```

Actually, I see this use case as extremely convenient. Why not allow something to be returned for processing? And, for example, consider it as the body of the response.  It doesn't matter whether it is a string, an object or a stream, just treat it as a response.

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.

**Comment by jonathanong** [comment]
for errors, you want to throw those. otherwise, just pass the data through `ctx` because passing the return value relies on the ordering of middleware
