### ISSUE TITLE
[fix] DESCRIPTIVE TITLE

### ISSUE THREAD

**Issue by iamgabrielsoft** [koajs/koa#1742]
## Describe the bug

Koa-body is failing to parse the context request from the client
I sense a bug
i changed to use the latest version of koa-bodyparser and its worked 

**Node.js version:** 
NODE 16.15.0

**OS version:** 
Linux - Ubuntu distro
**Description:** 

    const app = new Koa();
    const router = new KoaRouter();
    const server = http.createServer(app.callback()); 

    app.use(helmet());
    app.use(KoaBodyParser());
    app.use(mount("/api", api));
    app.use(mount("/auth", auth));
    app.use(router.routes());

    //catch errors in one place, automatically set status and response headers
    onerror(app);

**Comment by zacanger** [comment]
This should probably be opened on the middleware repo:
* [koa-body](https://github.com/koajs/koa-body)
* [koa-bodyparser](https://github.com/koajs/bodyparser)
And the maintainers will also probably want some more details, especially the content-type of the request and a simplified version of its content.

**Comment by 3imed-jaberi** [comment]
@iamgabrielsoft this issue should be reported to [@koa/body repo](https://github.com/koajs/koa-body).
