### ISSUE TITLE
[feat] send json type content when call ctx.throw

### ISSUE THREAD

**Issue by yunnysunny** [koajs/koa#1754]
## Describe the feature

Some time we want our server always reponse with json type, even if it throw custom error, for such code:
```javascript
ctx.throw(403, 'need right access', {
      message: JSON.stringify({code: 1234, msg: 'you dont have right permission', userId: 'xxx'}),
      expose: true
})
```
But koa reponse all errors with `text` type, we can not change it.
## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.

**Comment by siakc** [comment]
Guess you can put a middle there to catch the error and format the response before Koa. You can pass an object to ctx.throw() as any one of the arguments except first.
