### ISSUE TITLE
[fix] Some things cannot be found in the database where condition search, unless the where condition search ID

### ISSUE THREAD

**Issue by wintsa123** [koajs/koa#1763]
## Code to reproduce

`async findByQiniuKey(qiniu_key: string) {
    const result = await qiniuDataModel.findAndCountAll({
      where: { qiniu_key },
    });
    return result;
  }`
`const model = sequelize.define<QiniuDataModel>(
  'qiniu_data',
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
      autoIncrement: true,
    },
    user_id: {
      type: DataTypes.INTEGER,
    },
    prefix: {
      type: DataTypes.STRING(50),
    },
    bucket: {
      type: DataTypes.STRING(50),
    },
    qiniu_key: {
      type: DataTypes.STRING(150),
    },
    qiniu_hash: {
      type: DataTypes.STRING(50),
    },
    qiniu_fsize: {
      type: DataTypes.STRING(50),
    },
    qiniu_mimeType: {
      type: DataTypes.STRING(50),
    },
    qiniu_putTime: {
      // 会返回：16511776862952760，超出DataTypes.INTEGER大小，可以使用DataTypes.BIGINT
      type: DataTypes.STRING(50),
    },
    qiniu_type: {
      type: DataTypes.STRING(50),
    },
    qiniu_status: {
      type: DataTypes.STRING(50),
    },
    qiniu_md5: {
      type: DataTypes.STRING(50),
    },
  },
  {
    paranoid: true,
    freezeTableName: true,
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    deletedAt: 'deleted_at',
  }
);`
cant find.....but,use where id=something,it can find
`Executing (default): SELECT `id`, `user_id`, `prefix`, `bucket`, `qiniu_key`, `qiniu_hash`, `qiniu_fsize`, `qiniu_mimeType`, `qiniu_putTime`, `qiniu_type`, `qiniu_status`, `qiniu_md5`, `created_at`, `updated_at`, `deleted_at` FROM `qiniu_data` AS `qiniu_data` WHERE (`qiniu_data`.`deleted_at` IS NULL AND `qiniu_data`.`qiniu_key` = 'homeImage/111.png');
result:{ count: 0, rows: [] }`

but use sqltool,it can  work!
![image](https://github.com/koajs/koa/assets/47288630/e37df4ee-ffc3-40f6-aff8-30e0253d62ea)

**Comment by wintsa123** [comment]
![image](https://github.com/koajs/koa/assets/47288630/46c95da6-6ec5-4bbf-aa02-3fe913f5dee6)
![image](https://github.com/koajs/koa/assets/47288630/3feba353-0b54-4a1e-9562-c1b2736906c2)
![image](https://github.com/koajs/koa/assets/47288630/1cf18a1b-7718-4b94-8b79-b4e804f40157)

**Comment by wintsa123** [comment]
koa2 nodejs lastvision

**Comment by diego-oikos** [comment]
I don't think that has anything to do with Koa... You should check the SQL generated by Sequelize to perform that database query, as that can shed some light into why your code isn't working as expected. Add `logging: console.log`, like this:

`async findByQiniuKey(qiniu_key: string) {`
`    const result = await qiniuDataModel.findAndCountAll({`
`        logging: console.log,`
`        where: { qiniu_key },`
`    });`
`    return result;`
`}`

to see the generated SQL, and run that on you SQLTool to see what is going on.
