### ISSUE TITLE
Koa main website example code snippets disappear

### ISSUE THREAD

**Issue by sopwerdna** [koajs/koa#1775]
## Koa site has example code which renders for a split second, then disappears. 

I double checked and could not find other discussion of this problem, or a better place to report it (the koajs/koajs.com repo seems to be the actual home of the website code but issues are closed on that repo). I hope this is a helpful report. Thanks!

### Actual behavior

Open the [main koa site](https://koajs.com) and scroll down to "Application" then look under the line "The obligatory hello world application". Refresh the page and you will see the example code appear briefly then disappear again. The same occurs with the next example code snippet under "Cascading". This occurs for me on both firefox, safari, and chrome on macOS, although I don't have any other OSs handy to test.

### Expected behavior

Example code/hello world is displayed normally

**Comment by iwanofski** [comment]
I've tested this on Safari, Chrome and Firefox on a Macbook and I've had no issues seeing the examples. Could this have been a temporary bug? are you still missing the examples? Anyone else who can confirm the bug?

**Comment by iwanofski** [comment]
> Not sure why it needs a websocket connection to display code with syntax highlighting, or why the widget is hiding the plain text example code before successfully loading the enhanced code highlighting

I wouldn't want to speculate on the "why" of how Runkit operates but as far as the replacement I would imagine it's simply  in case Runkit is down the example still shows/exists on the page.
