### ISSUE TITLE
Consider alternatives to http-assert (including none at all)

### ISSUE THREAD

**Issue by wojtekmaj** [koajs/koa#1778]
http-assert targets very old Node.js version (0.8) and thus includes [bloated](https://packagephobia.com/result?p=deep-equal) deep-equal dependency that can be, for example, replaced with a [much smaller](https://packagephobia.com/result?p=dequal) alternative dequal. http-assert itself is [just a few lines really](https://github.com/jshttp/http-assert/blob/master/index.js) so I would argue copying these lines over and replacing deep-equal with dequal would be beneficial, improving install size and install time.

**Comment by siakc** [comment]
Why the sizes listed in npm differs this much with packagephobia?

**Comment by wojtekmaj** [comment]
Quoting their README: 

> The "install size" is the size your hard drive will report after running npm install. This includes the package, all of the dependencies, and its dependency's dependencies...and so on.

**Comment by siakc** [comment]
Size on disk:
deep-equal: 3.2M
dequal: 60K

**Comment by iwanofski** [comment]
Installation size isn't necessarily a metric Koa is tracking or cares too much about. A clean install of Koa is sub 2mb which in "node_modules theory" is considered negligible. For this reason alone http-assert will not be replaced.
