### ISSUE TITLE
[fix] Send response as buffer

### ISSUE THREAD

**Issue by AlcaYezzz** [koajs/koa#1782]
## Describe the bug

**Node.js version:** v18.12.1

**OS version:** Ubuntu 22

**Description:** Send response as buffer isn't working unless wrapped in object
## Actual behavior

provided the following code: 

```
const fooFunction = async (ctx: Context) => {
  ctx.response.set("Content-Type", "application/octet-stream");
  ctx.response.set(
    "Content-disposition",
    `attachment;filename=foo.bar`
  );
  ctx.body = {
    data: Buffer.from("test")
  }
  return ctx
}
```

The http request give me the following response: 

```
{
  "data":{
    "type":"Buffer",
    "data":[116,101,115,116]
  }
}
```

If I change the object affected to body:

```
const fooFunction = async (ctx: Context) => {
  ctx.response.set("Content-Type", "application/octet-stream");
  ctx.response.set(
    "Content-disposition",
    `attachment;filename=foo.bar`
  );
  ctx.body = Buffer.from("test")
  return ctx
}
```

the http response contains

```
test
```

## Expected behavior

The response to contain the buffer set to the body

```
{
  "type":"Buffer",
  "data":[116,101,115,116]
}
```

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.
- [x] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by iwanofski** [comment]
Just to be clear, you expect `ctx.body = Buffer.from(...)` to result in a response body as:

```json
{
  "type":"Buffer",
  "data":[116,101,115,116]
}
```

Because that's super opinionated?

**Comment by adebayohountondji** [comment]
Hello @AlcaYezzz,

Koa doesn't do anything special, you should try this to get the behavior you're hoping for:

```
const fooFunction = async (ctx: Context) => {
  // ...
  ctx.body = Buffer.from('test').toJSON()
  return ctx
}

```

**Comment by siakc** [comment]
Koa does something special in case body is set to a buffer. Changes the content type to bin.
