### ISSUE TITLE
async issue on app.listen(...)

### ISSUE THREAD

**Issue by Lucyfurnice** [koajs/koa#1783]
## Describe the bug
[app.listen](https://github.com/Lucyfurnice/koa-test/blob/35d18ee082eaba8b33d671f0c71f1571faa8fb1f/core.js/application.js#L18)
happens after
[process.exit](https://github.com/Lucyfurnice/koa-test/blob/35d18ee082eaba8b33d671f0c71f1571faa8fb1f/main.js#L17)
**Node.js version:** 
v18.18.2 LTS
**OS version:** 
Microsoft Windows [Version 10.0.22621.2428]
**Description:** 
Process.exit is happening before app.listen(...)
## Actual behavior
app.listen(...) happens after process.exit(...)
## Expected behavior
app.listen loops until ctrl+c then main function returns error code, and then process exits with main function error code.

## Code to reproduce
[lucyfurnice/koa-test](https://github.com/Lucyfurnice/koa-test)

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [ ] I have completely read through the README and documentation.
- [x] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.
- [x] I have examined the node.js source for net.Server and http.Server.

**Comment by prashant5025** [comment]
[https://github.com/Lucyfurnice/koa-test](https://github.com/koajs/koa/issues/lucyfurnice/koa-test) link is not working

**Comment by Lucyfurnice** [comment]
oops.

**Comment by Lucyfurnice** [comment]
i dont even think this is an issue with koa i think i need to ask on [https://github.com/nodejs/node](nodejs/node).

**Comment by Lucyfurnice** [comment]
after reviewing the library source for `net.Server` and `http.Server` I have determined that it may be due to `net.Server` extending `EventEmitter`, and then emitting an event on listen, however the code I looked at ( [setupListennHandler(...)](https://github.com/nodejs/node/blob/0cec82277c6fe3e9fbb3cf07324b9091d7f049db/lib/net.js#L1825C10-L1825C27) & [setupListenHandle(...)](https://github.com/nodejs/node/blob/0cec82277c6fe3e9fbb3cf07324b9091d7f049db/lib/net.js#L1825) ) does not appear to be asynchronous at first glance.

**Comment by Lucyfurnice** [comment]
https://github.com/nodejs/help/issues/4275

**Comment by iwanofski** [comment]
I realise you've done some investigation yourself and pretty much answered your own question. But just to confirm before I close the issue, yes, it'n not necessarily a bug but just a side effect of how events works! I'm closing this issue but feel free re-open if I misunderstood this ticket as "invalid".
