### ISSUE TITLE
[feat] Spanish translation for docs

### ISSUE THREAD

**Issue by SanGonzalezCarretero** [koajs/koa#1789]
## Spanish translation for Koa.js documentation

 I just wanted to ask the community if translations of the docs are welcome.
In that case, I could start contributing right away with an english to spanish translation of the koa.js docs 

## Checklist

- [x ] I have searched through GitHub issues for similar issues.
- [x ] I have completely read through the README and documentation.

**Comment by jonathanong** [comment]
I'm not sure it's worth the effort to create and maintain. is google translate not good enough?
