### ISSUE TITLE
Client disconnect

### ISSUE THREAD

**Issue by siakc** [koajs/koa#1821]
Suppose a route takes 60 seconds to respond. Client disconnects for some reason at second 25. Will Koa continue running middles or it will terminate context?
I ask this to know how to handle some slow routes.

**Comment by TommyDew42** [comment]
I guess koa will continue the request and stop when it responds and hits the `writable` check: in [respond](https://github.com/TommyDew42/koa/blob/8d5beb329d0851a9e2eb00ed08d3996ebde53994/lib/application.js#L261) and then reach [response.writable](https://github.com/TommyDew42/koa/blob/8d5beb329d0851a9e2eb00ed08d3996ebde53994/lib/response.js#L571).
