### ISSUE TITLE
better stream error handling

### ISSUE THREAD

**Issue by juliangruber** [koajs/koa#184]
Some ideas how to better handle streams, the biggest problem being error handling.

As in https://github.com/koajs/koa/issues/180#issuecomment-32126654

``` js
// what you have to do currently
// ugly as fuck
app.use(function*(){
  var a = streamA().on('error', this.onerror);
  var b = streamB().on('error', this.onerror);
  this.body = a.pipe(b).pipe(streamC());
});
```

With [multipipe](https://github.com/segmentio/multipipe).

``` js
// with `multipipe`
app.use(function*(){
  this.body = pipe(streamA(), streamB(), streamC());
});
```

``` js
// for fs leaks, also accept functions as this.body
// and call them when no other handler is set
// leaky as fuck
app.use(function*(){
  this.body = fs.createReadStream.bind(null, 'file.html');
});
```

**Comment by rtm** [comment]
I am using the `archiver` library to stream zips. In express world, I did

    var archive = new Archiver('zip');
    archiver.pipe(res);
    ...add files
    archiver.finalize();

What is the simplest way to do this in the koa world?

**Comment by yoshuawuyts** [comment]
@rtm probably wrap it in a promise and yield it.

**Comment by juliangruber** [comment]
@rtm

```js
var archiver = new Archiver('zip');
this.body = archiver;
// ...
archiver.finalize();
```

**Comment by rtm** [comment]
@juliangruber Thanks, how obvious.
