### ISSUE TITLE
continuous bench with travis

### ISSUE THREAD

**Issue by tj** [koajs/koa#191]

**Comment by tejasmanohar** [comment]
@hallas asks a good question here. anyone know the best way to handle this? i assume we wouldn't wanna bundle `wrk` since it's not a node tool O.o but i guess we could use some module and set it as a devDependency just like make-lint etc?

**Comment by jonathanong** [comment]
i'm just gonna run `make bench` in travis. 

if you want more thorough benchmarks like with `wrk`, then that's a different issue.
