### ISSUE TITLE
remove .keys getters and setters

### ISSUE THREAD

**Issue by jonathanong** [koajs/koa#203]
i changed cookies to be more user friendly and not require a keygrip instance all the time, though it might be less performant since you're initiating a new keygrip instance on every request (whatever, you can initialize yourself). if you care about the performance, i can revert https://github.com/koajs/koa/commit/c5655e093a974d01058736d9ee448d9fd551a7d2. otherwise, i think we should just remove the getters and setters for simplicity.

**Comment by da99** [comment]
I only have to set it on the main `app` w/ `app2` using the session middleware. Example:
```
  app.keys = [...];
  app2.use(session(....));
```
However, I am using: `koa 0.21`, `koa-generic-session 1.9.0` with `koa-pg-session`.

**Comment by vinerz** [comment]
This behavior is incorrect. I want to set a isolated session path on /connect because this the only place I will use sessions, my app is a stateless API but I have to use sessions for Grant (Facebook & Twitter Sign-in). I don't want to share my API v1 keys with all other endpoints of the server.

```js
var app = koa();

// first session handler
var connect = koa();
connect.keys = ['awesome-key'];
connect.use(session({
    store: redisStore()
}));

app.use(mount('/connect', connect));

// second session handler
var connect2 = koa();
connect2.keys = ['other-key'];
connect2.use(session({
    store: redisStore()
}));

app.use(mount('/connect2', connect2));
```
