### ISSUE TITLE
JSON message for ctx.throw

### ISSUE THREAD

**Issue by jksdua** [koajs/koa#237]
I've got a use case for returning a JSON body when throwing a validation error (400) with the error details. Are you interested in adding support for JSON responses when an error is thrown? One potential solution is setting a json property on the error object if msg passed is an object or array and use that in the onerror method to set the right content type etc.

Otherwise, is there a better way of returning from a middleware with a json response? I've tried setting the status code and body but that gets overriden.

Cheers,
Jaap

P.S Below seems to work, but this would still be nice to have

``` javascript
    this.type = 'json';
    this.throw(400, JSON.stringify({
        error: 'failed validation',
        validationErrors: validationResult.errors
    }));
```

**Comment by nicemaker** [comment]
+1 for `Error`
