### ISSUE TITLE
add some critical co-* modules to the wiki

### ISSUE THREAD

**Issue by tj** [koajs/koa#270]
multipart, co-body, co-views, etc are directly related, less hunting the better

**Comment by Mrluobo** [comment]
+1 
I have to search the koa-example to find which module to use,and then find them on npm to see how to use...

**Comment by magicdawn** [comment]
+1

May feel tired when someone start with koa who was familiar with express want a equality tool.

**Comment by jonathanong** [comment]
koa no longer uses co ;)
