### ISSUE TITLE
automatically set .status=200 when a content-ish header is set

### ISSUE THREAD

**Issue by jonathanong** [koajs/koa#294]
right now this won't work:

``` js
    ctx.response.etag = yield* calculate(path)
    ctx.response.lastModified = stats.mtime
    ctx.response.length = stats.size
    ctx.response.type = extname(path)
    if (ctx.request.fresh) ctx.response.status = 304
```

because `this.response.status === 404` until we set the body or a status. thus, i have to set `this.response.status = 200` before doing the fresh checking.

ideally, setting any `content-` header or `fresh`-ness header should automatically set `.status=200` since that means you're setting a response. i'm sure there are a lot of edge cases though...

**Comment by Louis-Tian** [comment]
What's the rationale behind this? Feels strange having to set the status to 200 beforehand. Logically, the freshness is completely determined by the if-modified-since request header and last-modified respond header, why do we need the status to be set?
