### ISSUE TITLE
After app.listen the Application ignores app.use

### ISSUE THREAD

**Issue by iliakan** [koajs/koa#321]
As of now, when the application is listening, `app.use` calls are ignored.

That is, they give no error, but the middleware is not added.

I've spent some time to figure that out. Maybe it's worth either to allow adding middlewares to the working app or if that's hard, throw in `app.use` that "the app is running and not accepting new middlewares".

**Comment by trisys3** [comment]
Express allows adding middleware after listening, contrary to what @hallas said. I don't know if this is new, or if it's recommended, but it does. If I add an `app.use` statement after doing `app.listen`, the new middleware is run as part of the stack in `express`, but not `koa` or `connect`.

**Comment by hallas** [comment]
Please show us this new change @trisys3  :-)

**Comment by trisys3** [comment]
I don't know, I tried it with Express and I was able to add middleware after listening, but when I tried it with koa I couldn't.

**Comment by trisys3** [comment]
It seems like with koa this should be easier than with express, because of the generator support, but then again express has more features so maybe it had to do something special to add it.

**Comment by hallas** [comment]
It's definitely not possible as it is right now in Koa, keep in mind this is an old issue.

**Comment by trisys3** [comment]
OK, just noticed it was an issue and it was something I was considering doing. Specifically, I need this for testing and for custom gulp plugins now that all server plugins seem are being blacklisted in short order. Do you know what is different in express that made it feasible?
