### ISSUE TITLE
feature: use() should accept an array of function

### ISSUE THREAD

**Issue by xpepermint** [koajs/koa#335]
It would be great to allow `app.use = function(fn)` to accept multiple functions or an array of functions. This feature would lower the amount of rows I have to write and would make my code more readable in some cases. 

Example: I created a module that returns a list of routes but I have to loop through each to attach them to `koa`. It would be great if I could just use 1 `use` statement (e.g. `app.use(routes())`).

I would appreciate if we can add this. Thanks.

**Comment by felixfbecker** [comment]
I would also like to have use() accept multiple middleware. Not array, but variadic. Would turn this:
```js
import router1 from './router1'
import router2 from './router2'
let app = koa()
app.use(router1.routes())
app.use(router1.allowedMethods())
app.use(router2.routes())
app.use(router2.allowedMethods())
```
into this:
```js
app.use(router1.routes(), router1.allowedMethods())
app.use(router2.routes(), router2.allowedMethods())
```

**Comment by yanickrochon** [comment]
@felixfbecker like it was mentioned, use [`koa-compose`](https://github.com/koajs/compose)

```
var compose = require('koa-compose');

...
app.use(compose([router1.routes(), router1.allowedMethods()]));
app.use(compose([router2.routes(), router2.allowedMethods()]));
```

There's no need to integrate this into the core.

**Comment by felixfbecker** [comment]
Is this really the recommended way?
```js
import koa from 'koa'
import Router from 'koa-router'
import logger from 'koa-logger'
import compose from 'koa-compose'
import anotherpath from './anotherpath/router'
import andanother from './andanother/router'
import thatsthelastone from './thatsthelastone/router'
import apath from './apath/router'

let router = new Router()

router.use('/apath', compose([apath.routes(), apath.allowedMethods()]))
router.use('/anotherpath', compose([anotherpath.routes(), anotherpath.allowedMethods()]))
router.use('/andanother', compose([andanother.routes(), andanother.allowedMethods()]))
router.use('/thatsthelastone', compose([thatsthelastone.routes(), thatsthelastone.allowedMethods()]))

let app = koa()
app.use(logger())
app.use(router.routes())
app.use(router.allowedMethods())
app.listen(8000)
```
That is sooo verbose. There should be something like `router.compose()` which composes `routes()` and `allowedMethods()`. If I don't use compose, I have to specify the mount path twice, which is ugly too.

**Comment by yanickrochon** [comment]
@felixfbecker well, this is the router you are using. I personally don't see any problem with the many use of `app.use`, and I actually find it not only more readable, but clean.

I, however, use [koa-trie-router](https://github.com/koajs/trie-router) in my project, as I find it a lot more flexible and, actually, it does support what you're asking :)

```
app.use(router(app));

app.get('/path', middleware1, [middleware2, middleware3], middleware4, ...);

// or
app.route('/path/to/route')
  .get(middleware1, middleware2);
```

Bottom line is, this will not be integrated directly into koa :)

**Comment by felixfbecker** [comment]
Did not know about that router. Looked into it, but I don't quite understand it. How would I structure my app into multiple modules? I'm used to having modules that export router objects, that are either mounted on a path in my main app or mounted independently in my tests.

**Comment by yanickrochon** [comment]
That question should be better addressed on SO than here. All I can recommend is looking through the code and take a look at the unit tests to understand it. There's really not much to understand, really... Or, at the very least, consider passing your `app` instance when initializing your modules so they can register their own routes. I'm not saying "use this" or "do that", I'm simply showing what's available :)
