### ISSUE TITLE
es7 async/await

### ISSUE THREAD

**Issue by jonathanong** [koajs/koa#339]
thinking about how koa would work when es7 comes out. ideally, this would work:

```js
app.use(async function (next) {
  // blah
  await next;
  // blah
})

app.use(function* (next) {
  // blah
  yield next;
  // blah
})
```

goal is to make it backwards compatible. async/await stuff won't be able to do stuff `co` does like `yield []`. main issue i'm thinking about is that `yield* next` would break if the next middleware isn't a generator function, but at least we don't tell people to use `yield* next` all the time.

i have a dispatcher designed in my mind. i made a pure promise version which is already faster than generators since generators aren't optimized.

**Comment by tj** [comment]
I wonder how that'll work for functions named "async" haha. Might as well drop the function keyword at that point

**Comment by dougwilson** [comment]
I think @yoshuawuyts may have swapped the syntax :) it's actually `async function () {}` (where `async` comes before the `function` keyword).

**Comment by tj** [comment]
oh right hahah I was going to say, that does nottttt look backwards compatible

**Comment by yoshuawuyts** [comment]
whoooops, updated to the correct syntax :smile_cat:
