### ISSUE TITLE
Middleware logging... how to?

### ISSUE THREAD

**Issue by soggie** [koajs/koa#367]
Hi guys, I'm looking at `koa-i18n` and it uses `debug` as a means to log information. I think this is sub-optimal and makes it hard for koa users to control what kind of information gets printed.

My suggestion is to provide an `info` and `debug` method alongside `throw` in `ctx` so that there is a standard way for middlewares to bubble up messages and as an end-user of koa.js you can choose your own logging library to handle the logs.

What do you guys think?

**Comment by hallas** [comment]
I'm leaning towards providing a suite of log methods like warn, info, log, debug and having them emit a log event on the application which comes with the log record and the context. That way people can listen on the event and log it the way they need to.

**Comment by cmwelsh** [comment]
+1 with a default log configuration to write logs to stderr. Koa should be the central dispach for middleware logs and even console output if we want to foster an ecosystem.

**Comment by fengmk2** [comment]
Summary above, there're two ways for logging:

- Event

```js
app.on('log', function (log) {
   // log.level = string, log level
   // log.message = string
   // log.ctx = ctx
});
```

- logger instance
 - methods: `debug()`, `info()`, `warn()`, `error()`
 - `app.logger`
 - `ctx.logger`, alias to `app.logger`

**Comment by wenshiqi0** [comment]
I prefer event,not the instance.Make a chance to write logger on my own,and feel much more fun.Actually I still think to make a middle ware for package the request ,response and ctx. = = Why not

**Comment by tj** [comment]
I'd vote for structured if this is something that people want to see in the core. printf-style is too hard to work with in practice, basically useless for querying so I wouldn't want to promote that out of the box

**Comment by yanickrochon** [comment]
I agree with @tj. The middleware would allow, just like `koa-view`, to use logging adapters more easily (such as winston, etc.), and would not tie this functionality to the core.

What I don't like about events is the unnecessary steps :

1. user calls `app.log` (or `app.emit('log', ...)`)
2. koa forwards to the even listener**s** (thus make koa responsible for such listeners)
3. listener receive events and user-custom call their logger
4. logger dispatch message

However, with a middleware, we get rid of steps 2 and 3 altogether :

1. user calls `app.logger.log` or `this.logger.log`, however the middleware is implemented.
2. logger dispatch message

Thus, completely separate logger from core and even allow users to implement their own middlewares.

**Comment by aheckmann** [comment]
The more I think about this, the less I believe we should build anything into core. It requires heavy-handed standardization of things many have differing opinions of - while also requiring keeping it flexible enough to be completely overridden to support things people are already doing (e.g. [this](https://github.com/pebble/koa-bunyan-logger/blob/master/index.js)). 

I'm +1 for documenting and promoting what a lot of the community seems to already be doing vs prescribing something for everyone. I see two common things in koa apps and modules regarding logs:

1. 3rd party module logging - Debug: Via documentation on the website, we can recommend its use in all 3rd party modules. It's flexible and easily toggled on/off. Lots of modules already use it _(non-scientific method, real numbers would be good)_.
2. Application logging - Custom: At the application level, have no default logger. Leave this undefined in koa itself and let each app make its own decision. If they want to use debug, they can. Bunyan? Go for it. We could add a logging patterns section to the website for the popular loggers out there and be done with it.

If ^ doesn't fly here, then I'm +0 for creating a standard `ctx.{debug,info,warn,error,fatal}()` method and documenting the method signatures. If the method arguments are documented, then anyone can easily override them with their own custom loggers. By default, the methods could do [something like this](https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L195-L204). However, we would probably need to go further and standardize on a way to differentiate between 3rd party middleware and application level logging to make it really useful.

**Comment by niieani** [comment]
How about, instead of worrying about standardizing issues when creating ```ctx.{debug,info,warn,error,fatal}()```, we instead opt to make ```ctx.log``` into a Proxy object. Here's how it could work:

```js
app.log = new Proxy({}, {
  get: (target, name) => function() { 
    app.emit('log', [name, ctx, ...arguments]) 
  }
});
```

Then you could to:
```js
ctx.log.error('your params...');
ctx.log.whatever('param1', 2, 3, 4);
ctx.log.crazy('works');
```
And it would pass the name of the function as the first parameter in the event. No problem with standardization of logging levels, since people can use what they want and it looks better than passing the level as a parameter.

Better yet, with this the community could create pluggable interfaces to any other loggers and they'd just listen for the right events and invoke their own methods.

The downside is that for now Proxy still requires ```--harmony_proxies``` flag passed to Node, but that will probably change relatively soon. We could wait until that happens before implementing this.

**Comment by niftylettuce** [comment]
@nicoder I like this approach, with helper methods on `ctx` object.  I don't think it should be in Koa core though, just a module that adds to `ctx` and exposes those methods.

**Comment by jonathanong** [comment]
it doesn't seem we've come to a conclusion, so i'm going to delegate this to "userland". if you're interested in profiling middleware, follow this discussion: https://github.com/koajs/koa/issues/219

- we have the https://github.com/orgs/koajs/teams/logging/repositories team. if you are interested in contributing, let me know.
- we have some options: https://github.com/koajs/trace https://github.com/koajs/timer https://github.com/koajs/statsd if you are interested in maintaining any of these, let me know
- if you have a tracing module that you think is suited for the @koajs/logging team, please let us know here: https://github.com/koajs/koa/issues/638
