### ISSUE TITLE
possible 0.15.0 release?

### ISSUE THREAD

**Issue by hallas** [koajs/koa#389]
looking for some updated co and .href feature :-)

**Comment by jonathanong** [comment]
i'm waiting for nvm to support iojs, then change up the docs for next release :)

**Comment by hallas** [comment]
you switching :) ?

**Comment by thelinuxlich** [comment]
You can use ivm https://github.com/demohi/ivm

**Comment by jonathanong** [comment]
nope, waiting on nvm because that's what travis uses :)

**Comment by tj** [comment]
we should still support node, at least until a compelling reason like async/await shows up

**Comment by hallas** [comment]
I think it would suffice if we just ran tests with iojs

**Comment by hallas** [comment]
Will be very interesting to measure the various differences

**Comment by tj** [comment]
still waiting on a "continuous benchmark" solution that doesn't suck haha

**Comment by hallas** [comment]
I'm a little uneasy about io.js or rather not uneasy just kind of bummed those changes couldn't stay in the joyent/node, but it was a long time coming...

**Comment by jonathanong** [comment]
@tj  it's a little hard to test both at the same time because node still requires `--harmony-generators` and `iojs` doesn't. don't feel like making a bunch of if statements...

**Comment by tj** [comment]
we'll have to figure something out unless everyone is just flat-out ditching node

**Comment by jonathanong** [comment]
just pushed 0.15.0 because i'm tired of waiting for nvm :D will figure out CI support for iojs when nvm supports it.

**Comment by hallas** [comment]
spank you mona
