### ISSUE TITLE
add support to use middleware even after `app.callback()` called.

### ISSUE THREAD

**Issue by TerenceZ** [koajs/koa#395]
I try to respond "server is starting." when preparing the middleware (defined in a config file) and data, I do it by:

```js
var app = koa();
app.use(function *(next) {
  if (/* is ready */) {
    return yield *next;
  }

  this.body = "server is starting.";
});

prepare(app); // ...async function, here we will load middleware to use

app.listen(3000);
```

However, it doesn't work. The `app.callback()`concats the `respond` and `app.middleware`, so middleware which is used after the `app.callback()` won't be called in future.

I think if not concat but compose `respond` and `compose(app.middleware)` in `app.callback`, the case above will work.

```
app.callback = function callback() {
  var gen = compose(this.middleware);
  var fn = co.wrap(compose([respond, gen]));
  var self = this;

  if (!this.listeners("error").length) {
  	this.on("error", this.onerror);
  }

  return function(req, res){
    res.statusCode = 404;
    var ctx = self.createContext(req, res);
    onFinished(res, ctx.onerror);
    fn.call(ctx).catch(ctx.onerror);
  }
};
```

**Comment by jonathanong** [comment]
solution is simple: don't `.listen()` until your app is ready.

**Comment by TerenceZ** [comment]
Thanks for jonathanong. I reconsider if it is important to respond starting message and now I think to keep things simple is more important.
