### ISSUE TITLE
why here this ~~

### ISSUE THREAD

**Issue by roelof1967** [koajs/koa#396]
im following the nodeschool tutorial about koa. 

When I looked at the official solution I saw this : 

var n = ~~this.cookies.get('view', { signed: true }) + 1;

why are there two ~~ needed. 
I saw that when im delete it I see wierd results. 

Roelof

**Comment by targos** [comment]
`~` is the bitwise NOT operator. Using two of them will apply this operation twice.  
It has the same effect as Math.floor with better performance.

**Comment by roelof1967** [comment]
oke, i did not take the bitwiser workshop. 
is it  the same as this :  var n = this.session.views || 0;

**Comment by jonathanong** [comment]
we use it to cast the value to an integer. easier than `parseInt()`

**Comment by hallas** [comment]
hacks!

**Comment by roelof1967** [comment]
What do you mean with hacks!  ?

**Comment by hallas** [comment]
@roelof1967 Oh I'm sorry. I just meant that ~~ is a neat little "hack" meaning that we take advantage of something in JavaScript that is faster and "smaller" than the obvious way to do it.
