### ISSUE TITLE
Error message when using wrong version of Node

### ISSUE THREAD

**Issue by marcusoftnet** [koajs/koa#397]
Just created a new application. `npm install koa --save` and ran it with `node --harmony app.js` but it threw on me. `ReferenceError: Promise is not defined`. 

Waaay down in the node_modules for koa (`./node_modules/koa/node_modules/co/index.js:47` to be exact)

After pulling my hair for awhile, not finding anything on StackOverflow that made sense I checked the `package.json` for koa. And sure enough, it now requires 0.11.13 or higher. 
```javascript
"engines": {
    "node": ">= 0.11.13"
  }
```
Wouldn't it be nice if Koa threw an error helping me to understand and fix this. For example:
```
Koa requires Node [field read from the package.json], but you are running on Node [process.version]. 
Get a new version of Node by using n (http://npmjs.org/package/n) or nvm (http://npmjs.org/package/nvm)
```

**Comment by dead-horse** [comment]
you can add `global.Promise = require('bluebird')` before `require('koa')` to use koa in node < 0.11.13 npm should warning you when you install koa with node < 0.11.13?

**Comment by juliangruber** [comment]
what @dead-horse said

**Comment by marcusoftnet** [comment]
By the powers - you're right! 

I've never read that before, but sure enough if I scroll up a bit i find 
```bash
npm WARN engine co@4.1.0: wanted: {"node":">= 0.11.13"} (current: {"node":"v0.11.12","npm":"1.4.3"})
```

Ok, so I revise my request for improvement to make this nugget of information a bit apparent?

How about maybe spitting it out to the console on start-up of an app? As a warning like the one above. 

But I will not cry rivers if you close this issue either. RT*M, huh? :)

**Comment by hallas** [comment]
NPM should do the warning bit here, right?

**Comment by marcusoftnet** [comment]
Yeah, thought a little bit further and I agree this is a npm thing.

**Comment by marcusoftnet** [comment]
http://www.marcusoft.net/2015/01/koa-and-the-referenceerror-promise-is-not-defined.html
