### ISSUE TITLE
Test failed in v0.11.15, url module has some break change

### ISSUE THREAD

**Issue by zensh** [koajs/koa#398]
http://blog.nodejs.org/

url: change hostname regex to negate invalid chars (Jonathan Johnson)

url: fixed encoding for slash switching emulation. (Evan Rutledge Borden)

url: improve parsing speed (CGavrila)

url: make query() consistent (Gabriel Wicke)

url: support path for url.format (Yazhong Liu)

util: add es6 Symbol support for util.inspect (gyson)

I try to fix, but have no idea in request.query setter~

**Comment by dead-horse** [comment]
#393 ?

**Comment by zensh** [comment]
yes
consistent query() can be change...
