### ISSUE TITLE
Replace media-typer with content-type

### ISSUE THREAD

**Issue by dougwilson** [koajs/koa#406]

**Comment by jonathanong** [comment]
*assigned to @dougwilson* ;)

**Comment by dougwilson** [comment]
I guess it can be... _my first koa contribution_

**Comment by jonathanong** [comment]
:scream_cat: :scream_cat: :scream_cat:

**Comment by dougwilson** [comment]
Actually, I should say first _direct_ contribution :) Working on dependencies is basically indirectly contributing.
