### ISSUE TITLE
what is wrong here ? 

### ISSUE THREAD

**Issue by roelof1967** [koajs/koa#407]
Hello, 

I try to solve this exercise from kick-off-koa : 

~~~

Create an app that checks the Content-Type of the request. If it's application/json, return {message: 'hi!'} with appropriate con
tent headers. Otherwise, return ok as a string.

~~~

so I have this : 

~~~

var koa = require('koa')

var app = koa(); 

app.use( function *() { 
     if (this.request.is('application/json ')) {  
        this.body = {message: 'hi' };
        } else { 
            this.body = 'ok';
        }
}); 

app.listen(process.argv[2]); 

~~~

but if I try to run in with kick-off-koa run file.js I see this error : 

~~~

 Error connecting to submission server(http://localhost:40158/), options: {"method":"POST","data":{"foo":"bar"},"headers":{"conte
nt-type":"application/json; charset=utf-8","Content-Length":7,"User-Agent":"node-urllib/0.5.18 node/v0.11.16 (linux 3.13.0-29-gen
eric; x64)"},"timeout":5000,"maxRedirects":10}. Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

~~~

So it seems there is something wrong with my app.

Can anyone give me a tip where I can find the culprit ?

Roelof

**Comment by dougwilson** [comment]
Hi! Make sure you have at least v1.1.0 of kick off koa installed.

**Comment by roelof1967** [comment]
Thanks, 

I have this version kick-off-koa@1.1.7 installed so that is not the problem

**Comment by dougwilson** [comment]
Gotcha :) There have been some race conditions where your server doesn't end up on the expected port. I'll wait for someone else to come by here to help :)

**Comment by roelof1967** [comment]
oke, then the only thing I can do is wait :(

**Comment by dead-horse** [comment]
migrate to https://github.com/koajs/kick-off-koa/issues/27
