### ISSUE TITLE
tutorial wanted question 

### ISSUE THREAD

**Issue by roelof1967** [koajs/koa#408]
Hello, 

When im more familair with Koa I like to make a ecommerce site with it.

Now I wonder one thing 

Let's say I have a membership api where I can add, delete customers.
And I have a order api where I can add, delete orders.

How can I tell Koa that a order depends on a member. 

Is there somewhere a tutorial about how I can make this work ?

Roelof

**Comment by hallas** [comment]
This is not something that is built in Koa as Koa is a _micro_framework. You will have to define this logic your self using database models :-)
