### ISSUE TITLE
Retain CORS headers in onerror

### ISSUE THREAD

**Issue by TheThing** [koajs/koa#411]
Right now, when you call `this.throw()` if the error is not handled, then koa returns a generic error to the user. Nothing wrong with that except if you included CORS headers in a middleware. Those are currently being stripped out, causing any result be unreadable in the browser (so to speak).

This is a side effect from an open issue in koa-cors here: https://github.com/evert0n/koa-cors/issues/17

If you're dealing with CORS, then being unable to trust in koa to handle the error can provide undesired effect. You'd always have to catch the error yourself and be extra careful not to accidentally throw errors that koa will catch.

I think that instead of removing all headers here: https://github.com/koajs/koa/blob/master/lib/context.js#L120 that we should instead reset it while copying all CORS related headers over. That way, the programmer doesn't have to be paranoid about errors.

I can provide a sample pull request if this is acceptable solution.

**Comment by jonathanong** [comment]
yep PR sounds good to me. makes sense

**Comment by jonathanong** [comment]
closing as your app should handle this. feel free to make PRs to error handling middleware!
