### ISSUE TITLE
fix node stream BS

### ISSUE THREAD

**Issue by tj** [koajs/koa#416]
Can't remember if propagate events to the context to avoid the onFinished type of junk all over, but it might be nice to add that. Forgot how terrible node's stream API is, people shouldn't have to worry about all those edge-cases

I guess it would  have to be on this.request etc so it's not ambiguous, but this is nasty:

```js
  var stream = events.stream(projectId);
  this.req.on('close', stream.close.bind(stream));
  this.req.on('finish', stream.close.bind(stream));
  this.req.on('error', stream.close.bind(stream));
  this.body = stream;
```

**Comment by jonathanong** [comment]
we already added this a long time ago! https://github.com/koajs/koa/blob/master/lib/response.js#L151

**Comment by tj** [comment]
I think I'm streamin wrong, should be a read stream not a write stream proxied I guess haha. Node hurts my head
