### ISSUE TITLE
How to test for `obj instanceof koaContext`?

### ISSUE THREAD

**Issue by garrett-gottlieb** [koajs/koa#417]
While trying to write a wrapper to stringify objects, I could not figure out how to test for `instanceof ctx`.
```
      // if (obj instanceof require('koa/lib/context')) { // doesn't work, had to use below
      if (obj.request && obj.response && obj.app) {
        return '[object KoaContext]'
      }
```
This seems very hacky, and although this looks like a simple test, I can't seem to figure this out.

**Comment by jonathanong** [comment]
> trying to write a wrapper to stringify objects

that itself sounds very hacky :P i don't understand what you're trying to do or why you would need this.

**Comment by garrett-gottlieb** [comment]
An example would be when we pass the context to a `beforeCreate` hook using the `options` Object parameter. We use the context to ensure the logged in user is the user who should own that object (whose data is attached to the context among other things), and would like to simply print out all options for all `beforeCreate`s.

To do so, we sanitize the object so large things, like the koa context, are not output in full. Then we stringify the rest and print it out. Here is the stringify part:
```js
function stringify(obj, options) {
  obj     = getSanitizedObject(obj)
  options = _.defaults({},
                       options,
                       {
                         depth  : null,
                         colors : true
                       })
  return '\n' + util.inspect(obj, options) + '\n'
}```

It's very easy and useful for debugging, and the context is passed around quite a bit (as it should be).

**Comment by jonathanong** [comment]
sorry this still doesn't make sense to me. sounds like you want to do authorization, but i don't see how stringifying is relevant to authorization. i also don't know what `beforeCreate` is.

**Comment by fengmk2** [comment]
obj instanceof app.context
