### ISSUE TITLE
Implications of adopting async await with es7

### ISSUE THREAD

**Issue by calebboyd** [koajs/koa#420]
It's looking like koa might adopt `async` `await`syntax coming in es7. And its implementation (specifically the way middleware are composed) raises some questions. 

As the proposal stands, the `async` modifier is set indicating the function returns a `Promise`; explicitly or by awaiting one, then returning a value. 

My question comes from the observation that `next` is not a promise -- how then, can it be `await`-ed?
Supposing it were a promise. The nature of it being named `next` implies that the upstream has already occurred which should not be true until after `await next`.

A solution would be to alter the api such that middleware must invoke `next()` which imo gives more control to whoever is implementing the middleware

I could be completely wrong and perhaps not understand the direction koa is going. Is koa going to stick with generators? It would seem the api is designed specifically for them.

**Comment by jonathanong** [comment]
https://github.com/koajs/koa/issues/415

if you look at https://github.com/thenables/composition, it is done by simply adding a `.then()` function to `next`, making it a "lazy promise".

**Comment by calebboyd** [comment]
My feedback and questions received no reply in #415. :(  I looked at `composition` and that raised the second question
> Supposing it were a promise. The nature of it being named next implies that the upstream has already occurred which should not be true until after await next.

I guess I'm saying it isn't intuitive that it does indeed call the upstream of the next middleware

**Comment by jonathanong** [comment]
`¯\_(ツ)_/¯` this is the path we've chosen. i guess it is confusing if you're coming from promise-land, not generator-land

**Comment by calebboyd** [comment]
Sounds good
