### ISSUE TITLE
realtime ?

### ISSUE THREAD

**Issue by roelof1967** [koajs/koa#422]
Hello, 

Can I build a realtime app with only koa.
What I have in mind is a shopping cart which is updated as soon as the user presses a buy button.

Roelof

**Comment by yoshuawuyts** [comment]
@roelof1967 if you're looking for an example implementation of websockets + koa, [koala](https://github.com/koajs/koala) might be cool to check out.

**Comment by tj** [comment]
Regular XHR is totally fine for that use-case, just attach an event handler on the client-side and fire off a request to Koa.
