### ISSUE TITLE
this.throw() ignores other headers

### ISSUE THREAD

**Issue by aaronz8** [koajs/koa#423]
Not sure if this is intended, but in the CORS use case the access control headers need to be set even when responding with errors. `this.throw("boom")` has different behavior than setting `this.status=500; this.body="boom";`, which was unexpected.

**Comment by dougwilson** [comment]
This is intended. The reason is because you should not be using the default error handler. Previous discussion here: https://github.com/koajs/koa/pull/413#issuecomment-74398234 :)

**Comment by aaronz8** [comment]
Ah, thanks!
