### ISSUE TITLE
this.status incorrectly set in finally block

### ISSUE THREAD

**Issue by greim** [koajs/koa#424]
I thought try/finally would be a good way to log stuff.

```js
app.use(function*(next){
  try {
    yield next
  } finally {
    console.log('status: %s', this.status)
  }
})
```

It works like I thought in non-error situations, but when `yield next` throws, this.status is 404 in `finally { ... }` even though 500 gets sent to the client.

**Comment by limianwang** [comment]
I am getting 404.

**Comment by limianwang** [comment]
Oh I think the probably is that you are using `finally`.  I think you should use catch to handle only when errors are thrown.

**Comment by greim** [comment]
Ahh. If `try` throws without a `yield`, koa has no opportunity to set the status in the first place, which remains 200 during `finally`. If `yield` throws however, something sets `this.status` to an intermediate value of 404. That's what confused me, probably some internal mechanism, but in any case I think the semantic assumptions underlying my approach are wrong.

**Comment by dougwilson** [comment]
Nothing is setting the status to 404 on the throw, rather the status code actually defaults to 404 in koa.

**Comment by greim** [comment]
Thanks, good to know.
