### ISSUE TITLE
context  extends pattern

### ISSUE THREAD

**Issue by fundon** [koajs/koa#428]
Currently, I saw many koa modules used this pattern to extend `context`.

In the modules:

session.js
```js
module.exports = function (app, ...) {
   app.context.session = function*() {} // or another type
}
```

server.js
```js
require('session')(app, ...);
```

I don't like this style. Maybe this pattern below will be better.
Just extends the `context` from the outside.

session.js
```js
module.exports = function* () {}
```

server.js
```js
Object.Object.defineProperty(app.context, 'session', {
  get: function () {
    return require('session');
  }
});
// Or
app.context.session = require('session');
```

I'm just looking for a better way to extend the `app.context`.

**Comment by juliangruber** [comment]
so your problem is that when you pass a context to a module that you don't know what it's going to do with it?

**Comment by fundon** [comment]
Sometimes, I dont' know.
I hope the module API is simpler and cleaner.
And `extends context` that let users processing.

**Comment by zensh** [comment]
:+1:
