### ISSUE TITLE
 adding support for specifying headers in ctx.onerror

### ISSUE THREAD

**Issue by dead-horse** [koajs/koa#429]
https://github.com/koajs/ratelimit/pull/13

**Comment by jonathanong** [comment]
what can't be done with middleware? streaming errors? if anything, i'd prefer the `.onerror` handler to be configurable.

**Comment by cesarandreu** [comment]
+1 to having `.onerror` configurable

**Comment by tejasmanohar** [comment]
another +1 for configurable

**Comment by tejasmanohar** [comment]
@jonathanong what would this look like? would we just extend the onErrors API to allow passing in `headers` (keys) that should stay in the response `this.res._headers`? is the end goal for the user to be able to specify what headers should stay, what the values of the headers that stay are, and/or just if headers should be unset or not?

**Comment by jonathanong** [comment]
i'm not sure. i'm not sure what the problem reported is

**Comment by pensierinmusica** [comment]
At the bare minimum I think the user should be allowed to keep the headers that have been set up to when the error has been thrown. Then, whether this should be a default behavior, or set as an option it's debatable. Imho should be default but other people might think differently.

**Comment by felixfbecker** [comment]
Related https://github.com/koajs/koa/issues/571

**Comment by jonathanong** [comment]
i think i like https://github.com/koajs/koa/issues/571's solution better. if you agree @dead-horse , wanna close this?

otherwise, `onerror` could be configurable too. technically it should already be configurable - we just need to make it more user-friendly and document it.

**Comment by dead-horse** [comment]
SGTM
