### ISSUE TITLE
Wrap Express's middleware to koa

### ISSUE THREAD

**Issue by fundon** [koajs/koa#430]
I used a way to wrap Express's middleware and ported to koa recently.
Likes:
* [koa-serve-list](https://github.com/koa-modules/serve-list) 
* [koa-serve-static](https://github.com/koa-modules/serve-static)
* [koa-morgan](https://github.com/koa-modules/morgan)
* [koa-multer](https://github.com/koa-modules/multer)

Examples:
```js
var thenify = require('thenify');
var originalMiddleware = require('original middleware')

module.exports = function middlewareWrapper(...args) {
   var middleware = thenify(originalMiddleware(...args));

  return function* (next) {
    yield middleware(this.req, this.res);
    yield next;
  }
}
```

I just share this.
Maybe it's not a best solution, but it's useful.
Enjoy! :)

**Comment by tj** [comment]
Haha sweet, I'd be careful for some but logging etc should be fine! Feel free to add modules to the wiki

**Comment by fengmk2** [comment]
Why not just forget express and callback :)

**Comment by fundon** [comment]
Added to the wiki.
@fengmk2 You're right.
Come on ES6+! haha

**Comment by luckydrq** [comment]
@fundon good thinking :+1: 

More thoughts,  it can also be converted to a `thunk` instead of a `promise`? 

```
var thunkify = require('thunkify');
var originalMiddleware = require('original middleware');

module.exports = function middlewareWrapper(...args) {
   var middleware = thunkify(originalMiddleware(...args));

  return function* (next) {
    yield middleware(this.req, this.res);
    yield next;
  }
}
```

**Comment by fundon** [comment]
I thought it's working with a `thunk`.
The `yield ` supports that way.
BTW, @luckydrq you can try it. :)
