### ISSUE TITLE
Assert in ctx.onerror not caught

### ISSUE THREAD

**Issue by litek** [koajs/koa#432]
I had a promise that rejected with a string as an error instead of a proper Error object. There is an [assert in context.js](https://github.com/koajs/koa/blob/c307c81c4313e13ed8464aafbccd1544e8ecf3a8/lib/context.js#L106), but it's never caught in [application.js](https://github.com/koajs/koa/blob/c307c81c4313e13ed8464aafbccd1544e8ecf3a8/lib/application.js#L128) so both the error string and the assert are silently swallowed and no response is sent to the client.

**Comment by hallas** [comment]
Can you provide a failing example? Assert throws so it should catch. Could be the error is not caught somewhere else?

**Comment by litek** [comment]
The first test case works as expected, the second times out.

**Comment by juliangruber** [comment]
strings aren't errors, forever

**Comment by jonathanong** [comment]
thanks for the test case. instead of "support"ing it, i'd rather have the assert do `console.error('Strings are not errors'); process.exit(1);`. another option is to cast to an error object.

@litek either way, can you propagate the issue upstream? Strings are NOT ERRORS!

**Comment by tur-nr** [comment]
> Strings are NOT ERRORS!

+1

**Comment by litek** [comment]
Absolutely. The main problem is that the assertion is silent, which made it more difficult to locate the bug. I guess casting to a "non-error thrown: ..." would be the most straight forward, since it looks like the intention is to actually throw that error.
