### ISSUE TITLE
Any consideration for clientside support?

### ISSUE THREAD

**Issue by DylanPiercey** [koajs/koa#435]
I've been reading a lot into isomorphic javascript and was wondering if that was something that this project may eventually accomplish?

It would be very useful to hook into the history location api and be awesome for passing around state through a flux style architecture.

I found something similar here:
https://github.com/kentjs/koa-client

**Comment by jonathanong** [comment]
if you could provide concrete examples, we could consider it, though either way it would be a different module.

personally, i don't believe in isomorphic apps. you should maximize each environment's advantages vs. settling for the common denominator.

**Comment by tj** [comment]
-1 from me personally, I'd rather keep it pristine and focused for the server, and I agree with @jonathanong – I've never found that sort of structure overly appealing. Hell technically even writing/directly consuming HTTP services makes little sense, HTTP is an implementation detail, RPC-ish is the way to go

**Comment by yoshuawuyts** [comment]
@DylanPiercey is this what you're looking for? - https://github.com/yoshuawuyts/fax 

I haven't used it in any projects yet, so there'll probably be plenty of bugs in there.

I agree with the sentiment that isomorphic applications are not the way to go; with CJS environments available in the browser the amount of modules you can reuse between the client and server is large even if glue code & frameworks aren't shared.

**Comment by DylanPiercey** [comment]
I also agree that a fork would probably be best, was just wondering if there was potential for this project to incorporate browser support.

Laying out middleware and routes is awesome with koa/co and I'm already starting to use generators client side. I've been messing around with it for a while now and have found that the mental model for isomorphic apps becomes a lot simpler if you treat server side rendering the exact same as client side rendering (no React-Router or anything) and redirects/middleware and other benefits come for free.

**Comment by yoshuawuyts** [comment]
@DylanPiercey servers and clients have different purposes, so you'll end up with a different api regardless. Forking koa and then floating patches on top of it to maintain compat doesn't seem like the best solution to me, but if you want to try it then by all means go for it!

**Comment by DylanPiercey** [comment]
@yoshuawuyts Actually the way I am architecting the client and server are almost exactly the same. The kicker is that the (rest) api for the app is a completely separate and independent koa module. As such both the server and the client contact the api in the same way but I would like the server that hosts react also to isomorphically render and act the same way as the browser implementation.

Currently I'm creating a fork to test this architecture out further.

**Comment by DylanPiercey** [comment]
https://github.com/DylanPiercey/koa

If anyone is interested in helping that would be great. There are currently no extra tests and likely many bugs but it is able to handle URL changes in the browser and trigger a request through koa (handles forms and a tags). Also redirects should work.

The goals are:
- Keep the exact same api as koa for the server.
- Keep as much functionality as possible (without being pointless) for the browser.
- Maintaining the exact same api in the browser.

Hopefully sometime next week I'll post an example react app that demonstrates the elegentness of this approach.
