### ISSUE TITLE
node.js and io.js, which is better for building RESTful API with koa?

### ISSUE THREAD

**Issue by heziqiang99** [koajs/koa#437]
As stated in the topic.

**Comment by jonathanong** [comment]
i've been using io.js, but unfortunately it moves so fast that i've hit so many bugs with updates that i have to use old versions of io.js.

node.js, on the other hand, is so old and behind that you should never use it.

solution: use an older version of io.js (i.e. second to last minor version) and stick to it for a while.

**Comment by bucaran** [comment]
@heziqiang99 We use Node v0.12 internally and our product will go into production soon. So far so good. I want to use io.js too, but like @jonathanong says it's a moving target. I am sure we'll get there though! :)

**Comment by dougwilson** [comment]
I have also struggled to bring in io.js to company production due to is moving so fast as well.

**Comment by heziqiang99** [comment]
thank for your(@jonathanong & @bucaran) reply. It seems Node v0.12 is more suitable for me.

**Comment by fengmk2** [comment]
iojs require gcc>=4.8, our production server's gcc current version is gcc@4.1. 
And our devops don't want to upgrade gcc for this year.
So we still using 0.11.x.
