### ISSUE TITLE
can anyone explain why this is not working 

### ISSUE THREAD

**Issue by roelof1967** [koajs/koa#441]
Can someone help me with this problem : http://pastebin.com/8mFWV1WG

I have solved this with co-body and now I try with this body-parser

**Comment by hallas** [comment]
Hi @roelof1967 

These sort of questions actually belong on user groups. However it doesnt look like you are using the body-parser right. If you want our help you should explain the reasoning behind your code and why it's written as it is, makes it so much easier for everybody :-)

**Comment by hallas** [comment]
If you add a middleware after the bodyParser you can probably read the JSON using `this.request.body`. Give it a go.

**Comment by roelof1967** [comment]
I can try. With middleware you mean something like this : 

~~~

app.use(function *() {
    // you can set the response body in handler like this                                                                                                                                                                                
    this.body = 'hello koa';                                                                                                                                                                                                                 
});

~~~

Second question : where can I find the user groups ?

**Comment by hallas** [comment]
To the first question: Yep!

To the second question. I think there should be like a nodejs user group on google and a Koa IRC channel and gitter channel as well.

**Comment by roelof1967** [comment]
I have asked in the gitter channel but no answer. 
I will try it.

**Comment by roelof1967** [comment]
I do not get it working but is koa-body-parser not middleware

**Comment by roelof1967** [comment]
solved with the help of the irc channel
