### ISSUE TITLE
What are the units for the Koa vs Express "performance" table?

### ISSUE THREAD

**Issue by richb-hanover** [koajs/koa#442]
... in the table, "Is Koa faster than Express" at https://github.com/koajs/koa/blob/master/docs/koa-vs-express.md#is-koa-faster-than-express

I'm not entirely clear what test setup/program was used. Is it in the repo?
 
And what are the units shown in the table: Seconds? Iterations? Furlongs per fortnight? :-)

**Comment by hallas** [comment]
requests/second I think

**Comment by jonathanong** [comment]
we should probable remove that. super outdated, and things change when you no longer use `--harmony-generators`.

**Comment by hallas** [comment]
Yeah. I agree

**Comment by fengmk2** [comment]
+1
