### ISSUE TITLE
Add a silent option

### ISSUE THREAD

**Issue by cesarandreu** [koajs/koa#447]
I do a lot of my development in `test` environment, i.e. run mocha with `-w` flag and write code with tests. But when I get errors JS errors it's annoying, because koa doesn't log errors when `'test' == this.env`.

I'd propose adding an `app.silent` option, and using that instead of `'test' == this.env` to determine if errors should be printed to stderr by default. The initial value for `app.silent` can be set to the result of `'test' == this.env` so it doesn't break backwards compatibility.

This is not only useful for errors, though. `app.silent` can be used from your logging middleware, to determine if messages should be sent to stdout / stderr or not.

Adding this option shifts the concern to the application developer. If I want, I can have whatever set of conditionals I want, e.g. `app.silent = process.env.SILENT || process.env.CI`.

Thoughts?

**Comment by jonathanong** [comment]
talking about https://github.com/koajs/koa/blob/0ad06c9810079174660fa4948ca183d9b90efd3c/lib/application.js#L167? you should be using your own error handler instead during testing, which is what i do.

**Comment by tj** [comment]
in general I'm +1 for anything that isn't env-specific, envs should define config not the other way around so I'm down

**Comment by jonathanong** [comment]
reading it more, i'm cool with an `app.silent` option. @cesarandreu wanna make a PR?

**Comment by tejasmanohar** [comment]
@jonathanong This also benefits me! If this hasn't been PR'd or worked on yet by @cesarandreu, I'd love to do it as an intro to contributing to KoaJS.

Just to clarify, the `app.silent` option would replace the env-specific checks in https://github.com/koajs/koa/blob/0ad06c9810079174660fa4948ca183d9b90efd3c/lib/application.js#L167, right? Would/should there be any defaults based on your env? I was thinking if you're in test, the silent mode would be on by default but dev could override w/ the option (i.e. use this.silent if passed but if not, just default value of `silent` based on if this is running in 'test' env)

**Comment by tejasmanohar** [comment]
I implemented it without any env-based defaults in PR #486 since @tj said

>in general I'm +1 for anything that isn't env-specific, envs should define config not the other way around so I'm down

That said, I can easily add env-based defaults if that's preferred.

**Comment by tejasmanohar** [comment]
This issue can now be closed since #486 has been merged // cc @cesarandreu

**Comment by jonathanong** [comment]
https://github.com/koajs/koa/pull/486 thanks!!!!
