### ISSUE TITLE
question :  where do I close the database 

### ISSUE THREAD

**Issue by roelof1967** [koajs/koa#449]
Hello, 

I saw a example how to use mongodb with koa here : https://www.npmjs.com/package/koa-mongo

but I wonder where do you close the database ? 

Roelof

**Comment by targos** [comment]
Maybe ask directly on the koa-mongo repo: https://github.com/MangroveTech/koa-mongo

**Comment by hallas** [comment]
Yep. Please ask at the relevant repository. :-)
