### ISSUE TITLE
wiki page: please swap places of package name and downloads state widget

### ISSUE THREAD

**Issue by DenisIzmaylov** [koajs/koa#450]
When I open wiki page I see list of package names and its descriptions.
There is 2 unusual things:
1. I move mouse pointer to package name. In this moment downloads widgets has been loaded and package name has been shifted to right by the widget.
2. I'm reading list of package names to search something interested. In this moment downloads widget has been loaded and shifted package name to right. I lost my focus - downloaded widgets break it.

It would be better if downloads state widget has been placed after package name or description. Or on the next line.

**Comment by DenisIzmaylov** [comment]
Ok, I fixed it by replacing list by tables:
https://github.com/koajs/koa/wiki

**Comment by tj** [comment]
nice! can't remember what it looked like before but I dig it! thanks man

**Comment by gabeio** [comment]
https://github.com/koajs/koa/wiki/Home/_history

**Comment by DenisIzmaylov** [comment]
@tj you're welcome
@gabeio yeah, in first time I started to update it by hands, then I decided to do it with regular expressions and after first commit I found this mistake and fixed it immediate.

**Comment by jonathanong** [comment]
damn this is awesome. thanks!

care to share the module or code you used to do it?

**Comment by DenisIzmaylov** [comment]
No code used. Just my hands. :)
