### ISSUE TITLE
problem with using wildcard

### ISSUE THREAD

**Issue by divramod** [koajs/koa#452]
code:

    var serve = require('koa-static');
    var cors = require('koa-cors');
    ...

    app.use(cors({
        origin: true,
        credentials: true
    }));

    app.use(compress());

    
    app.use(route.get('/admin', function*(next) {
        var ctx = this;
        ctx.url = "index.html";
        yield next;
    }));

    app.use(route.get('/admin/(.*)', function*(next) {
        var ctx = this;
        ctx.url = "index.html";
        yield next;
    }));

    app.use(serve('..'));
    ...

problem: 
1 when i request /admin everything is running fine.
2 when i request /admin/home yield next gives me: 
    You may only yield a function, promise, generator, array, or object, but the following was passed: "home"

i logged next in both cases. in 1 next logs {} in 2 next logs "home".

i am using koa 0.12.2.

what am i missing?

**Comment by coderhaoxin** [comment]
> app.use(route.get('/admin/(.*)', function*(next) {

app.use(route.get('/admin/(.*)', function*(param, next) {
