### ISSUE TITLE
koa-static question

### ISSUE THREAD

**Issue by node-rookie** [koajs/koa#453]
var koa = require('koa');
var server = require('koa-static');
var app = koa();
var path = require('path');

app.use(server(path.join(__dirname, 'public')));

app.listen(3000, function(){
    console.log('listening on port: 3000');
});

this is static file server, when i require 'localhost:3000/public/test.html' ,  got 404 error, why?

**Comment by cesarandreu** [comment]
It should work on `localhost:3000/test.html`.

Github issues are not appropriate for asking questions.

**Comment by juliangruber** [comment]
we have a [mailing list](https://groups.google.com/forum/#!forum/koajs) for this :)
