### ISSUE TITLE
Is it possible to compile a Koa app to ES5?

### ISSUE THREAD

**Issue by d4goxn** [koajs/koa#454]
I am trying to use Babel to compile a Koa backend, partly for consistency with the ES6/7 front end code, some of which will be executed server-side for isomorphic rendering. Since the compiler replaces the generators, I get an assertion error from Koa:

    AssertionError: app.use() requires a generator function

Has anyone been able to compile an ES6/7 Koa app?

app.js:

```
import koa from "koa";
import router from "koa-router";

let app = koa();
app.use( router( app ));

export default app;
```

index.js:

```
require( "babel/register" )({
	sourceMaps: "inline",
	stage: 1
});

var app = require( "./src/app" );

app.listen( process.env.port || 3000 );
```

**Comment by targos** [comment]
@d4goxn does it work with the following patch ?
https://gist.github.com/targos/1c79e564138a5ec369e7

**Comment by d4goxn** [comment]
I'm afraid not, that just checks to see if fn.constructor is the string 'GeneratorFunction', right? The assertion still fails. If I remove the assertion completely, I get errors in koa-compose when it tries to call the "generator's" `next` function.

I am going to look at tweaking babel to produce ES6 code instead of ES5, or at least prevent it from replacing generator functions.

**Comment by targos** [comment]
No it checks the function itself, not the name. It is strange that you get this issue, because babel generates the correct code for both cases:

test.js
```js
var GeneratorFunction = (function*(){}).constructor;

function*fn(){}

console.log(GeneratorFunction == fn.constructor);
console.log('GeneratorFunction' == fn.constructor.name)
```

```
% babel-node test.js
true
true
```

**Comment by targos** [comment]
OK, in fact you are using koa-router incorrectly.
try `app.use(router.routes())`
see https://github.com/alexmingoia/koa-router#new_module_koa-router--Router_new

**Comment by cesarandreu** [comment]
It works. I've used babel with koa, and I also have other apps that compile the whole server with webpack.

I think your error is caused by incorrect usage of koa-router. That usage was deprecated with v5.

**Comment by cesarandreu** [comment]
If you wanted to, you could disable generator transpilation by disabling the regenerator transformer.

I'd suggest making a `.babelrc` with your desired config so you don't have to pass it in to the require call. 

And if you're using a recent version of iojs you can do `iojs -r babel/register index.js`, which lets you avoid  having to register babel in your app's entry point. This is nicer because then in your test environment (at least for mocha), you could set babel as a compiler and run any tests (either glob or a one-off test).

**Comment by cesarandreu** [comment]
We have a mailing list and an IRC channel, which is more appropriate, if future issues arise.

**Comment by hung-phan** [comment]
I also have a question regarding to this problem in mailing list - https://groups.google.com/forum/#!topic/koajs/u9Bbs--luQA. Have any one got koa.js running successfully with webpack and babel when have it on production mode like uglifier? My current server is:
```
'use strict';

import koa from 'koa';

const app = koa();

app.use(function *(next){
  var start = new Date;
  yield next;
  var ms = new Date - start;
  console.log('%s %s - %s', this.method, this.url, ms);
});

// response
app.use(function *(){
  this.body = 'Hello World';
});

app.listen(3000);
console.log('Server listening on port 3000');
```

Also run into:

```
assert.js:88
  throw new assert.AssertionError({
        ^
AssertionError: app.use() requires a generator function
```

**Comment by hallas** [comment]
Greetings.

What does Babel do with function* () ? Do you know?

**Comment by targos** [comment]
@hallas They use the [facebook/regenerator](http://babeljs.io/docs/advanced/transformers/other/regenerator/) runtime.

**Comment by hallas** [comment]
Okay well there you have the answer :-)

**Comment by hallas** [comment]
Do you under why now @hung-phan  ?

**Comment by hung-phan** [comment]
Yup. I try to injecting regeneratorRuntime but it does not work in my case. I will try to solve and post the answer here. My current config is `loader: 'babel-loader?optional=runtime'`. Thanks guys

**Comment by hallas** [comment]
Babel would have to transform the part of Koa that checks for a generator function as well as your own generator middleware.

**Comment by hung-phan** [comment]
Solved.

```
    new webpack.optimize.UglifyJsPlugin({
      mangle: {
        except: ['GeneratorFunction', 'GeneratorFunctionPrototype']
      }
    })
```
I have to enable mangle options for UglifyJSPlugin. Thanks @hallas

**Comment by hallas** [comment]
Cool
