### ISSUE TITLE
Stream error handling

### ISSUE THREAD

**Issue by blacksonic** [koajs/koa#456]
When i do the following in a controller
```
var stream = new require('stream').Readable();
stream.push('content');
stream.emit('error', 'Some error');
stream.push(null);

this.body = stream;
```
I get this error
```Cannot assign to read only property 'domainEmitter' of Some error```
How can i handle errors here properly?

**Comment by hallas** [comment]
Stack trace? Just curious

**Comment by blacksonic** [comment]
Well found it out...an error is thrown at the place of the emit call...it only generated within a test where i mocked a method.
It works but i still dont know how to test it.
