### ISSUE TITLE
Koa Debugging

### ISSUE THREAD

**Issue by VenkatRamNDD** [koajs/koa#459]
I am new to koajs. please help me how to debug my koa code. i already used "node-inspector" it is showing this error: 

Starting the interactive shell (REPL). Type `.help` for help.
The module in the current directory was not loaded: C:\Users\xxx\Koa Sample\app.js:6
app.use(function *(next){
                 ^
Unexpected token *.
Didn't want to start REPL? Run `C:\Users\xxxx\AppData\Roaming\npm\node_mo
dules\node-inspector\bin\node-debug.js .` instead.

**Comment by juliangruber** [comment]
That's most likely because your installation of nodejs lacks generator support. See https://github.com/koajs/koa#installation

**Comment by VenkatRamNDD** [comment]
juliangruber,  I am ruuning node 0.12.5 and "node --harmony app.js" this command is working for me but i am unable to debug my code can you please help me,,,,

**Comment by hallas** [comment]
@VenkatRamNDD that error is rather specific to not having generators enabled when running node, usually enabled using the right binary and the --harmony flag.

**Comment by juliangruber** [comment]
@VenkatRamNDD can you post some javascript we can run to test this issue?

**Comment by VenkatRamNDD** [comment]
@juliangruber followed this https://github.com/node-inspector/node-inspector to debug my koa(node) code...
This is my code:
   var koa = require('koa');
   var route= require('koa-route');
   var app= koa();
            app.use(function *(next){
                             var start = new Date;
                             yield next;
                             var ms = new Date;
                             console.log('%s %s - %s', this.method, this.url, ms, this.status);
              });
            app.use(function *(){
                                 this.body = 'Hello World';
              });
             app.use(route.get('/index', index));
                  function *index(){	
	                           this.body="This is Index";		
                  }

            app.listen(3000);
            console.log('Koa listening on port 3000');

**Comment by juliangruber** [comment]
and how exactly do you run it?

**Comment by juliangruber** [comment]
or rather, does your app work if you're not debugging? because if so, you should open an issue on your debugger's repo

**Comment by VenkatRamNDD** [comment]
@juliangruber my app works fine but debugging is problem...

**Comment by hallas** [comment]
@VenkatRamNDD Then please open an issue with your debugger. :-)

**Comment by hallas** [comment]
Still, the unexpected token * smells of non-harmony, so maybe when you run the debugger you must make sure you enabled harmony?

**Comment by juliangruber** [comment]
^ what I'm thinking
