### ISSUE TITLE
How can I find the original route?

### ISSUE THREAD

**Issue by parris** [koajs/koa#463]
Let's say a request matched to `/user/:id`. Is there an easy way from some middleware's context to get the original route string instead of the current path.

`this.url` might produce `/user/1234`, but I'm looking for `/user/:id` so I can do some additional checks before some other middleware. 

Thanks!

**Comment by targos** [comment]
The concept of routes is not directly in koa and there are several router packages. You may have to ask this in the repository of the one that you are using.

**Comment by parris** [comment]
Alright thanks. Moving here: https://github.com/koajs/route/issues/29
