### ISSUE TITLE
Not possible to throw exception on "error" event

### ISSUE THREAD

**Issue by pensierinmusica** [koajs/koa#464]
Hi,

I know there are logging utilities for handling errors in Koa, and they work fine. On the other hand, there are a couple of things I don't entirely understand.

#### 1) It's not possible to throw an exception on an error event

I'd like to be able to do something like this:

```js
app
  .on('error', function (err) {
    if (!err.expose) throw err;
  });
```

The code above though unfortunately doesn't `throw`, the app instead stalls indefinitely and doesn't return any response to the client. Why?

#### 2) It's not possible to set the error object as response body

For example:

```js
app
  .on('error', function (err) {
    console.log(JSON.stringify(err));
    this.body = err;
  });
```

The code above generates this error:

```
Unhandled rejection Error: Can't remove headers after they are sent.
```

Why is that?

Thanks!

**Comment by juliangruber** [comment]
1) if you throw an error there your app should crash and yeah not respond to clients any more. why do you want to throw an error? what do you want to be sent to the client?

2) this can be achieved through middleware, something like

```js
app.use(function*(next){
  try {
    yield next;
  } catch (err) {
    this.body = err;
  }
});
```

just insert this before other middleware

**Comment by fengmk2** [comment]
If the `error` is not happen on a `request` context, you can't send it back to the client.

If you want to custom error response, maybe you can use [koa-onerror](https://www.npmjs.com/package/koa-onerror).

**Comment by pensierinmusica** [comment]
After some more testing I did, I think it's better to split this issue in two separate ones.

So I'm assigning the point 2 of the initial post to #465. Here I'll continue with point 1 instead. I also changed the issue title accordingly.

@juliangruber I agree that throwing an exception there should make the app crash, but it doesn't happen instead, and I suspect it might be a bug.

Take this code for example:

```js
var app = require('koa')();

app
  .use(function* () {
    throw 42;
  })
  .on('error', function (err) {
    throw err;
  });

app.listen(3000);
```

As I mentioned earlier, this code doesn't throw, the app instead stalls indefinitely and doesn't return any response to the client. Why?

Even this doesn't crash (probably for the same reason):

```js
var app = require('koa')();

app
  .use(function* () {
    throw 42;
  })
  .on('error', function (err) {
    foo;
  });

app.listen(3000);
```

Obviously `foo` is not defined, besides having malformed syntax, and the app should definitely throw an exception, but it doesn't happen!! Btw, according to JavaScript specs, in this case I'm not sure if the exception should be thrown at "interpretation" time, or at runtime. Someone more expert in how the engine works should know.

Why is this happening? Is it because we're catching all errors inside the "error" event handler in Koa's codebase?

**Comment by juliangruber** [comment]
why do you want to crash the app inside the `'error'` handler?

If you really want to do that, this code would work:

```js
var app = require('./')();

app
  .use(function* () {
    throw 42;
  })
  .on('error', function(err){
    console.error(err);
    process.exit(1);
  });

app.listen(3000);
```

However this wouldn't write anything to the client either as the process just exits.

**Comment by pensierinmusica** [comment]
@juliangruber, that would make it crash but it wouldn't report the error correctly. Still, I don't understand why throwing an exception doesn't work. I think the behavior described above is non-standard in JavaScript and should be fixed.

[From MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw):
>The `throw` statement throws a user-defined exception. Execution of the current function will stop (the statements after throw won't be executed), and control will be passed to the first catch block in the call stack. If no catch block exists among caller functions, the program will terminate.

**Comment by juliangruber** [comment]
| Execution of the current function will stop 

That's what happening, nothing after the throw is being executed inside your `.on('error', fn)` handler.

Basically what you're trying to do isn't supported by koa. Use the middleware method as described above. We could implement a try/catch around `app.emit('error', new Error)` but that's even less standard compliant.

Also check out the wiki for more details: https://github.com/koajs/koa/wiki/Error-Handling

**Comment by pensierinmusica** [comment]
To be precise, this is what the official JS docs say:

> Execution of the current function will stop, and control will be passed to the first catch block in the call stack. If no catch block exists among caller functions, the program will terminate.

So, the relevant part here is "the program will terminate". And currently it doesn't.

**Comment by juliangruber** [comment]
tbh I don't know why the process doesn't crash.

This does cause a crash:

```js
var e = new Emitter;
e.on('error', function(){
  throw new Error('nope');
});
e.emit('error');
```

I couldn't find any `process.on('uncaughtException', fn)` in koa's source tree and dependencies. Inserting a `debug` in front of the `throw` also didn't give any results.

**Comment by dead-horse** [comment]
because this error is thrown in a [promise chain](https://github.com/koajs/koa/blob/master/lib/application.js#L128). (`app.emit('error', err)` called in `ctx.onerror`).

so if you really want to throw this error in app's error event handler, you should do:

```
app
  .on('error', function (err) {
    setImmediate(function () { 
      throw err; 
    });
  });
```

but this really dosent make any sense. it will crash the app.

**Comment by fengmk2** [comment]
This why I don't like promise...
