### ISSUE TITLE
On "error" event not possible to set error object as response body

### ISSUE THREAD

**Issue by pensierinmusica** [koajs/koa#465]
As mentioned in #464 at point 2 of the first post.

On "error" event it's not possible to set the error object as response body.

#### Example 1

```js
app
  .on('error', function (err) {
    this.body = err;
  });
```

The code above generates this error:

```
Unhandled rejection Error: Can't remove headers after they are sent.
```

@juliangruber mentions this can be achieved through middleware (before any other middleware).

#### Example 2

```js
app.use(function* (next) {
  try {
    yield next;
  } catch (err) {
    this.body = err;
  }
});
```

Still, I don't fully understand why the code in example 1 doesn't work, and I think it could be desirable to use the standard centralized error event listener, deciding within it how to handle different cases (which might include sending the error object in the response body).

Thoughts?

**Comment by jonathanong** [comment]
`.on('error')`'s `this` is `app`. you're setting `app.body = err`.

`this.body = err` should work, but you should try `console.log(new Error('some error!'))` javascript is fun and doesn't make all the properties enumerable.

**Comment by dead-horse** [comment]
actually it is possible to send error object or message as response body in app's error event.

```js
var koa = require('koa')

var app = koa()

app.use(function* () {
  if (this.path === '/error') return this.throw('oops, something wrong!')
  this.body = 'everything is ok'
})

app.on('error', function (err, ctx) {
  console.error(err.stack)
  if (!ctx || ctx.headerSent || !ctx.writable) return

  ctx.writable = false //  interrupt `ctx.onerror`
  ctx.status = err.status || 500
  ctx.res.end(err.message)
})

app.listen(3000)
```

but i think it is not the best practise.
