### ISSUE TITLE
It's time to release 1.0.0

### ISSUE THREAD

**Issue by fengmk2** [koajs/koa#467]
Hi all, there is no bug issues report for a long time.
And nodejs will enable generator by default on 4.0.0.

So can we release the koa 1.0.0 after nodejs 4.0.0 publish?

**Comment by booxood** [comment]
:clap:

**Comment by targos** [comment]
:+1:

**Comment by mattma** [comment]
Thai is a great idea. Since generators become in the mainstream, ES2015 is stabilized and released, Node.js is going to release long time support. It is safe to release 1.0 to own some shared market. I am betting on Koa over Express. I would like to see Koa takes off to win over the framework war! +1

**Comment by thelinuxlich** [comment]
Excellent and please advertise A LOT the production quality, we want Koa to be the king!

**Comment by hallas** [comment]
Can we review the dependencies before we lock on 1.0.0? Is there any that we need to upgrade?

**Comment by ruimarinho** [comment]
nodejs 4.0.0 will be released in early September afaik, but I think we should consider working on the logging api before publishing 1.0.0. It has been on the issue tracker for almost a year now (https://github.com/koajs/koa/issues/367) and for many of us it's an integral part of production usage. Most of the community-developed koa middlewares and - koa itself - depend directly on the `debug` module which makes it extremely hard to plugin other loggings utils, such as bunyan or winston, which are more appropriate for centralised logging solutions.

It could also be an interesting exercise to list known companies using koa in production on the readme file.

**Comment by tj** [comment]
:+1: 

The logging stuff sounds reasonable to me, the profiling stuff would be cool too but that could just be a `{ duration: }` key in debug level logs to simplify for now

**Comment by cesarandreu** [comment]
:+1:  :shipit: 

Very excited to see koa make the 1.0 jump!

**Comment by gxcsoccer** [comment]
:+1:

**Comment by JacksonTian** [comment]
:+1:

**Comment by LeslieYQ** [comment]
nice

**Comment by jerryge** [comment]
![image](https://cloud.githubusercontent.com/assets/935589/9399999/653c4858-47ee-11e5-94db-e1295bac3d30.png)

**Comment by Dongss** [comment]
<img class="emoji" title=":+1:" alt=":+1:" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png" height="20" width="20" align="absmiddle">
excited to see nodejs 4.0.0 and koa 1.0.0

**Comment by xudafeng** [comment]
:+1:

**Comment by leecade** [comment]
cool

**Comment by xiaokekeT** [comment]
😀

**Comment by Pana** [comment]
:+1:   Is Node.js 4.0 will support all the ES 2015 features such as arrow functions and so on ?

**Comment by popomore** [comment]
@Pana Not all, bug arrow function will be supported in 4.0.

**Comment by chemdemo** [comment]
:+1:

**Comment by agileago** [comment]
![image](https://cloud.githubusercontent.com/assets/11799110/9401732/6fd5e2b6-4806-11e5-9c88-c8a223b52cc0.png)

**Comment by fengmk2** [comment]
@ruimarinho I add a [1.x](https://github.com/koajs/koa/labels/1.x) label for issues need to be closed before we release 1.0.0.

@ruimarinho @tj any idea to impl logging for koa?

**Comment by zhangda89** [comment]
image

**Comment by wenshiqi0** [comment]
how to make a icon for nice = =
nice!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by magicdawn** [comment]
:+1: Waiting

**Comment by idreamshen** [comment]
:+1:

**Comment by tj** [comment]
@fengmk2 we've got a milestone for 1.0. I'm impartial for logging being a 1.0 thing since it's additive, so I'm down with whatever there

**Comment by jonathanong** [comment]
there are some dependencies i was waiting for that would require a semver bump (cookies), but we can just release 1.0.0 and follow semver!

**Comment by jonathanong** [comment]
0b9c032af148d4b16129c7f712577b5a9e44e353

**Comment by jonathanong** [comment]
oh i noticed you asked to wait for node 4.0.0 - there's no need for that because nothing's gonna change

**Comment by fengmk2** [comment]
@jonathanong nice!

**Comment by dionoid** [comment]
:thumbsup: :thumbsup: :thumbsup:
