### ISSUE TITLE
use next version of cookies

### ISSUE THREAD

**Issue by jonathanong** [koajs/koa#469]
https://github.com/pillarjs/cookies

waiting on @dougwilson to release it :)

**Comment by smcmurray** [comment]
@jonathanong, I don't see a new branch for cookies. What next version does 2.0.0 milestone depend on? What new features/functionality are you expecting that new version to provide?

**Comment by jonathanong** [comment]
https://github.com/pillarjs/cookies/pull/48

**Comment by tejasmanohar** [comment]
@jonathanong Is there a v2.0 branch? Or, can we create one? if we have suggestions/refactors for v2.0 and they're not really fit for being PR'd into master, that may be a good idea...

**Comment by ezintz** [comment]
@jonathanong look [here](https://github.com/pillarjs/cookies/commit/e2aedb1bff6f26147895d7ee9a19d4345c6236d9), seems something going on (;

**Comment by 3imed-jaberi** [comment]
@dead-horse, @jonathanong 
I think this issue should be closed that we have the latest version of cookies.

**Comment by dead-horse** [comment]
Thanks for the reminder. :)
