### ISSUE TITLE
Setting a custom value on the 'context'

### ISSUE THREAD

**Issue by chrisbuttery** [koajs/koa#470]
Hello.
I’m just wondering I can get some feedback on this example.

I'm looking at running the same web app as an electron desktop app and just differentiating the two by a query parameter. E.g. `localhost:3000` for the normal web app and `localhost:3000?desktop` for the electron app.

I'll need to check for a specific parameter (`?desktop`) and pass through a boolean to my templates.
The templates will then show/hide content based on that bool.

At the moment I’m checking the URL and then storing `this.isDesktop`as boolean in the first request.
I’m wondering if this is a crappy implementation and if I should be doing this a different way. Kinda feels like I'm polluting context.

I guess, ideally it doesn't need to be checked for every request seeing `?desktop` will most likely be around for the life of the desktop app being run.

Here’s an example:

```
const koa = require('koa')
const route = require('koa-route')
const render = require('koa-ejs')

// ejs
render(app, {
  root: join(__dirname, 'views'),
  layout: 'template',
  viewExt: 'html',
  cache: false,
  debug: true
})

// check for localhost:3000?desktop and set value on context
app.use(function * (next) {
  this.isDesktop = this.request.querystring === 'desktop'
  yield next
})

// pass `isDesktop` through to template
app.use(route.get('/', function *() {
  yield this.render('users', {
    title: 'Users',
    isDesktop: this.isDesktop
  })
}))

app.use(route.get('/pets', function *() {
  yield this.render('pets', {
    title: 'Pets',
    isDesktop: this.isDesktop
  })
}))

app.listen(3000);
console.log('you look amazing!, 3000');
```

**Comment by juliangruber** [comment]
this looks fine to me, and if you worry about cluttering `this` you can put all your things on `this._blerg.*` etc

**Comment by chrisbuttery** [comment]
Good point, thanks

**Comment by cesarandreu** [comment]
@chrisbuttery I think it's alright to add request state to the context, especially if it's your own app and it affects everything.

In my apps I add a few app "globals" to the context as well, e.g. models.
