### ISSUE TITLE
add support for ctx.origin

### ISSUE THREAD

**Issue by matthewmueller** [koajs/koa#476]
Shorthand for: `this.protocol + '//' + this.host`

**Comment by jonathanong** [comment]
@fengmk2 @dead-horse didn't we have another issue similar to this?

**Comment by hallas** [comment]
I remember something with host + port but not this in particular

**Comment by dead-horse** [comment]
https://github.com/koajs/koa/blob/master/lib/request.js#L69

**Comment by matthewmueller** [comment]
yah, I think origin is probably more useful for servers talking with servers

**Comment by jonathanong** [comment]
PR anyone?

**Comment by chentsulin** [comment]
I submit one PR for this.

**Comment by dead-horse** [comment]
@matthewmueller https://github.com/koajs/koa/pull/480

do you need to publish a new version to npm?

**Comment by jonathanong** [comment]
merged https://github.com/koajs/koa/pull/480
