### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by pensierinmusica** [koajs/koa#477]
Hi,

Is there any plan to support [HTTP/2](https://en.wikipedia.org/wiki/HTTP/2) in Koa?

Thanks!

**Comment by jonathanong** [comment]
you can use https://github.com/indutny/node-spdy, which AFAIK supports HTTP 2

koa is server agnostic - just create wrap the app in whichever server implementation you'd like. 

if you were looking for a http push helper, you can try https://github.com/jshttp/spdy-push

**Comment by pensierinmusica** [comment]
Hi @jonathanong, thanks for clarifying that Koa is server agnostic, I will look into the server implementation that best suits my use case!

Apart from this, in [Koala's docs](https://github.com/koajs/koala/blob/master/docs/spdy.md) there's a section that states:
>Once SPDY becomes an HTTP standard and is baked into node.js, some of these features will be placed in Koa.

In my understanding, HTTP/2 has replaced and extended the SPDY protocol (which [will not be supported from Google](https://blog.chromium.org/2015/02/hello-http2-goodbye-spdy-http-is_9.html) from early 2016 onwards).

As for the differences between SPDY adn HTTP/2, some information can be found in the Wiki link that I posted in the first comment: https://en.wikipedia.org/wiki/HTTP/2

Putting the two pieces of information together, I wondered if there was any plan to integrate HTTP/2 as the standard `app.listen()` in future Koa versions.

Cheers!

**Comment by jonathanong** [comment]
`app.listen()` will continue use `require('http')` by default. we just gotta wait until node supports http2 out of the box.

**Comment by rally25rs** [comment]
I'm curious if anyone actually got this to work. I was trying to use [node-http2](https://github.com/molnarg/node-http2) and this very simple example:

```
var http = require('http2');
var koa = require('koa');
var app = koa();

var options = {
  key: fs.readFileSync('./localhost.key'),
  cert: fs.readFileSync('./localhost.crt')
};

var handleRequest = function*(next) {
  this.body = 'Hello World';
  yield next;
  console.log('done');
};

app.use(handleRequest);
http.createServer(options, app.callback()).listen(8080);
```

never completes the request. From the client perspective, the request is 'pending' forever, and there are no errors in node. The line `console.log('done');` is hit and writes to the console.

If I swap the `require` from `'http2'` to `'http'` then it works fine.

**Comment by tomchentw** [comment]
Confirmed what @rally25rs mentioned about `node-http2` module. I had the same issue today with `koa@2.0.0`. Also traced down to `response.writable`. Good catch!

**Comment by pieterb** [comment]
As of [release 3.3.2](/molnarg/node-http2/tree/v3.3.2) (maybe earlier) of node-http2, the response object has a .socket property as suggested by @temchentw above.

**Comment by tomchentw** [comment]
I was just about to raise up an issue on `node-http2`. Thanks @pieterb for the comment. But at the moment I [forked](https://github.com/molnarg/node-http2/compare/master...tomchentw:fix/koa-compatibility?expand=1) from `node-http2`, it's `3.3.2` and there's no `response.socket` exists.

I also checked their latest code but with no luck. Would you mind to point out where it is?

**Comment by rally25rs** [comment]
Adding it to `node-http2` seems like fixing the wrong thing to me; `response.socket` is an implementation detail of node's `http` implementation that is not a documented part of the API, so other libraries (namely `koa`) shouldn't rely on its existence.

**Comment by pieterb** [comment]
Hi @tomchentw, there was a link in my earlier comment, but here's link to the specific version, file and line:
<https://github.com/molnarg/node-http2/blob/v3.3.2/lib/http.js#L506>

**Comment by pieterb** [comment]
Oops, I'm mistaken: that commit introduced **request.socket**. You're talking about **response.socket**. No, this hasn't been introduced into node-http2. Please send the pull-request!

**Comment by tomchentw** [comment]
@pieterb what do you think about the comment from @rally25rs ? I'm concerning about it too and I'm seeing my fork of `node-http2` is just a hacky solution.

**Comment by pieterb** [comment]
@tomchentw I'd say Er comment makes a lot of sense. I've been trying to understand the relevant bits of code in koajs and node's core http and https modules, but I don't feel confident enough to create a pull request.

To be honest, I don't (fully) understand the reasoning behind testing the socket's writability in the first place. AFAICS, the intention is to check if the user has bypassed koa's response object and called res.write() or res.end() on the underlying lower-level reponse object. The test was introduced in commit 9fe483ca767b64de3e9b9e2c78b7bfaf420861c2, without explanation.

**Comment by pieterb** [comment]
I've been looking into this a bit further. There's some interesting discussion on this topic in issues #142 and #143. I suggest we continue this discussion under #143, and convince the koa team to undo that commit (9fe483ca767b64de3e9b9e2c78b7bfaf420861c2).

**Comment by kristianmandrup** [comment]
Please make a nice way to use `http2` with koa without having to resort to writing a full infrastructure around `spdy` or similar :)

**Comment by kasperlewau** [comment]
@kristianmandrup I'm playing around with `node-spdy` and `koa@2` and have gotten a fair bit. 

There's a brief explanation along with some code examples over at [node-spdy#277](https://github.com/indutny/node-spdy/issues/277)

Semi working as of now, at this point I can push resources out to the client w/ manifest support. 

It doesn't work quite as well when bumping up the amount of resources to push (from ~5 to ~100) as it seems to always end up in a ton of [`FLOW_CONTROL_ERROR`](https://http2.github.io/http2-spec/#FlowControl)'s so I'm definitely doing _something_ wrong. 

I'll see about extracting the necessary bits of code into a repo where it's easily hackable.

**Comment by kasperlewau** [comment]
@kristianmandrup I've pushed what I have so far into this repo https://github.com/kasperlewau/koa-h2-man-pusher. 

It's still very much a work in progress. There's a couple of examples in the `/examples` dir that can be run with `node server.js`. That will bootup a SPDY server w/ self signed certs on port 3000. The examples cover three cases; 16, 100 & 200 assets pushed to the client. 

Again, it's not quite what you're asking for as far as spdy support within koa goes - but I suppose it's a start 😄

**Comment by kristianmandrup** [comment]
@kasperlewau Sweet :) Good job!

**Comment by maticrivo** [comment]
is it worth reopening this issue now that node is about to support http2 from the core?
https://medium.com/the-node-js-collection/say-hello-to-http-2-for-node-js-core-261ba493846e
https://github.com/nodejs/node/pull/14239

**Comment by EduardoRFS** [comment]
A api to things like server push is a cool feature

**Comment by saadq** [comment]
FWIW, it looks like `http2` [landed in node core](https://twitter.com/MylesBorins/status/893566926236024834) a few days ago so people can start experimenting with it.

**Comment by corysimmons** [comment]
Please reopen.

**Comment by AndreLion** [comment]
Node.js v8.4.0 starts supporting `http2`.
@jonathanong please reopen this issue and put `http2` on the agenda. :nerd_face:

**Comment by nitrocode** [comment]
Reopen? @jonathanong

**Comment by corysimmons** [comment]
Is this literally as easy as swapping out `http` for `http2`? If so I'll fork/maintain until they catch up.

**Comment by fl0w** [comment]
Is there any benefit to using http2 other than push?

**Comment by kristianmandrup** [comment]
http2 supports better parallel fetching of assets and a whole host of other optimisations besides push...

**Comment by ssut** [comment]
http2 is [what makes HTTPS faster than HTTP](http://www.httpvshttps.com/).

**Comment by DominusVilicus** [comment]
Is this supported?
