### ISSUE TITLE
Limit on HTTP request headers size

### ISSUE THREAD

**Issue by pensierinmusica** [koajs/koa#479]
Hi,

Is there any default limit in Koa to the size of HTTP request headers?

As [mentioned in StackOverflow](http://stackoverflow.com/questions/686217/maximum-on-http-header-values) on the topic:

> The HTTP spec does not define a limit, however many servers do by default. This means, practically speaking, the lower limit is 8K. For most servers, this limit applies to the sum of the request line and ALL header fields (so keep your cookies short).

> Apache 2.0, 2.2: 8K
> nginx: 4K - 8K
> etc...
> It's worth noting that nginx uses the system page size by default, which is 4K on most systems.

In case there isn't any limit in Koa, what would the best approach to build a high-performance middleware that implements a given max headers size limit on every HTTP request?

Thanks!

Cheers

**Comment by jonathanong** [comment]
koa doesn't handle any of this. https://nodejs.org/api/http.html#http_server_maxheaderscount maybe this is enough for you? otherwise, you would have to write your own middleware.

**Comment by pensierinmusica** [comment]
Thanks @jonathanong!

Mmm... Node docs on this are a bit ambiguous... how do you interpret it: `maxHeadersCount` sets a limit to the maximum number of a request headers, or to the total length of a request headers?

>Limits maximum incoming headers count, equal to 1000 by default. If set to 0 - no limit will be applied.

Cheers!

**Comment by slaskis** [comment]
Node uses http_parser which seems to use an 80k limit by default, configurable using defines during compile time:

https://github.com/nodejs/node/blob/master/deps/http_parser/http_parser.h#L55-L64

Koa doesn't care at all about the parsing but delegates that to node by default if you use `app.listen()`

**Comment by soknifedev** [comment]
Referenced link has changed to https://github.com/nodejs/http-parser/blob/master/http_parser.h#L55-L64

> Node uses http_parser which seems to use an 80k limit by default, configurable using defines during compile time:
> 
> https://github.com/nodejs/node/blob/master/deps/http_parser/http_parser.h#L55-L64
> 
> Koa doesn't care at all about the parsing but delegates that to node by default if you use `app.listen()`
