### ISSUE TITLE
ES6 refactor

### ISSUE THREAD

**Issue by tejasmanohar** [koajs/koa#484]
Would Koa be interested in an ES6 refactor via PR? Since we're using Babel, I could do it bit-by-bit. Just to name a few benefits- Readability via const, import/export instead of require, => functions, enhanced object literals, destructuring for things like `const { req } = this`...

// cc @jonathanong @tj

**Comment by martysmind** [comment]
With node 4.x's ES6 support I would support a roadmap that embraces ES6 support.  Personally I would prefer Typescript.. though some many not be as keen on static typing.

**Comment by tejasmanohar** [comment]
@martysmind I'd still recommend using Babel since ES6 isn't 100% complete in Node 4.x (I don't think, haven't played enough) and we can support < Node 4.x.x then... but would we do this via requiring babel's require hook, or via babel-runtime and precompiling?

Eh, I'd avoid typescript for community, future of JS/ES, etc. reasons but would rather not get off-topic in this thread :wink:

**Comment by jonathanong** [comment]
`const` - for sure, this could be done now with a PR

not sure if we need the other ones. not sure we have enough ES6+ for a need to transpile with babel.

**Comment by dead-horse** [comment]
+1 for  ES6. -1 for use babel.

**Comment by tejasmanohar** [comment]
`const - for sure, this could be done now with a PR`
@jonathanong Alright; on it. 

`+1 for ES6. -1 for use babel.`
Aight. I'll stick to what's in stock w/ Node 4 w/o flags then.

**Comment by yanickrochon** [comment]
No TypeScript, please. It's alright for some projects, or part of projects, but there's no benefit in using a transpiler for Koa.

**Comment by tejasmanohar** [comment]
@yanickrochon Agreed.

**Comment by felixfbecker** [comment]
This might fit here - I looked at the source code and asked myself why the heck is koa exporting prototypes? (I tried to unit test middleware by creating fake contexts - and couldn't get it working).
I love the general idea of this framework and I don't quite understand why it uses ES6 generators but not ES6 classes etc. Would love to see a refactor with clean classes.

**Comment by tejasmanohar** [comment]
@felixfbecker I was planning to send in PRs feature-by-feature for ES6 changes.

Anything under this list-
https://nodejs.org/en/docs/es6/#which-es6-features-ship-with-node-js-by-default-no-runtime-flag-required
should be good-to-go, imo.

I've sent in `const` refactor PR already. We'll see reactions on that one first!

**Comment by felixfbecker** [comment]
Nice work. I would help out too if needed.

**Comment by tejasmanohar** [comment]
@jonathanong What do you think of incorporating the following features?-
1. `let`
2. Obj literal shorthand
3. Arrow functions (gets rid of some of the `var x = this` stuff)

I'd love to use destructuring but it requires a harmony flag- so I'm guessing we should pass on it for now since Node 4.x.x is out and these are supported natively ^. Some of these features require 'use strict' / strict mode... is that ok with you? I've looked through the ups/downs, and personally, I think it's reasonable.

**Comment by felixfbecker** [comment]
And what do you two think about classes? They're native in Node 4.x too and would improve the code readability a *lot*.

**Comment by jonathanong** [comment]
make a separate PR for each feature and let people decide :) some people might care about performance a lot

**Comment by tejasmanohar** [comment]
@jonathanong fair enough. i will do so for every feature in that list... unfortunately, merge conflicts will suck but it's ok :tired_face:

**Comment by tejasmanohar** [comment]
@felixfbecker classes, too_ just updated list :+1:

**Comment by yanickrochon** [comment]
I personally care a lot about performance. Especially since the actual code in apps is usually limited to creating koa instance and calling `app.use`. All the rest is maintainer-land.

**Comment by ruimarinho** [comment]
I think this a good and modern approach if the performance hurt is not significant. The downside is probably having to release koa@2 since Node 4 is quite recent and those features would require a considerable engine dependency bump.

**Comment by tejasmanohar** [comment]
@wryk Aren't these features supported w/ --harmony though which the README requires for node 0.12 users (our base version)? (i may be mistaken)

**Comment by ruimarinho** [comment]
@tejasmanohar none of them afaik, at least implemented properly.

**Comment by felixfbecker** [comment]
Well if performance is too bad there is still the option to transpile with babel which would result in basically the same code as we have today.

**Comment by fixe** [comment]
+1 for what @felixfbecker said.

**Comment by tejasmanohar** [comment]
@felixfbecker Yeah, that's why I thought maybe we should transpile, too. Babel is optimized like crazy... babel's runtime can be set as a devDep and we can add a prepublish script, eh?

Either way, I think as @ruimarinho said, ES6 is the future and we should move forward!

**Comment by tejasmanohar** [comment]
`const` has been PR'd in. Please comment there on your thoughts. There's a PR open to my branch `es6_const` on the fork called `es6_let` which adds `let` in but there have been some known performance issues w/ `let` in Node 4.x.x.

I'm facing one issue w/ strict mode which is noted here- https://github.com/koajs/koa/pull/485#issuecomment-145685400. If anyone has an idea, please reply there ;)

**Comment by tejasmanohar** [comment]
>@tejasmanohar none of them afaik, at least implemented properly.

@ruimarinho http://stackoverflow.com/questions/28388885/ecmascript-6-features-available-in-node-js-0-12
Top answer here says `const` was supported without harmony and `let` was supported w/ harmony in v0.12 so those two shouldn't be any problem (except performance) as far as I can tell.

Arrow functions are also fine without a major version increase (still works w/ v0.12 --harmony) but classes are a no-go without a major version increase for Node v4.0 as the minimum (i think), Babel (which probably also warrants a major version increase) transpiling.

**Comment by yanickrochon** [comment]
@felixfbecker in this case, why re-writing if the end result is roughly the same?

Don't get me wrong, I like all the new ES6 features and onward, but I think this is overkill and too much efforts for so little gain at the moment. Unless, as @ruimarinho said, a new branch (2.0-dev) is created and tested as this *is* a significant code change and project structure.

**Comment by tejasmanohar** [comment]
@yanickrochon IMO, readability trumps all (within reasonable boundaries). I think a branch v2.0-dev needs to be created if we do go w/ Babel, but let/const should be good to incorporate (via the existing PR... and sub-PR thing) without a major version change (w/ semver) since it works based on the minimum node version w/ --harmony as stated in our current README.

**Comment by tejasmanohar** [comment]
I would be willing to work towards a v2.0-dev branch using all of Babel, but before I put in that much energy into refactoring and testing a lot of this, I'd rather hear from the community and maintainers to see if it's a go / no-go.

**Comment by yanickrochon** [comment]
@tejasmanohar Oh, I don't mind the `const` or `let` usage. I'm actually talking about converting prototypes to classes and even using a transpiler. That I have strong reservations at the moment. I do not agree with adding build tasks and dev dependencies to Koa.

**Comment by mattstyles** [comment]
Readability is great, and great for development of this ecosystem, but surely for library code performance has to be key over code readability?

As your average consumer I actually dont much care about the code, I need to know the API and usage is clean and simple and that it performs super quick so that my time spent optimising is optimising my own code. Sure, I might poke around in the code to work out how to do things, but good documentation solves that problem and its not like the code is currently messy or unreadable anyways.

Dont get me wrong, I love the new features, just about every project I use is babel transpiled but I'd be against it for library code, unless the benefits really make it viable, which I dont think they do here.

**Comment by tejasmanohar** [comment]
Using Babel won't affect performance... and we do need to think about "by how much" when looking at performance.

**Comment by dead-horse** [comment]
Personally I'm -1 on babel:

1. I want people always see the source code in their `node_modules/koa` directory.
2. What @mattstyles said:

>  I love the new features, just about every project I use is babel transpiled but I'd be against it for library code, unless the benefits really make it viable, which I dont think they do here.

**Comment by tejasmanohar** [comment]
Alright... looks like most people are either -1 or +0 on Babel including the maintainers so pass on that.

**Comment by tejasmanohar** [comment]
@dead-horse When do you think it's an ideal time to say Node 4.0 and up as the minimum Node v for Koa? 2.x.x?

**Comment by ruimarinho** [comment]
I actually think the opposite, i.e., I don't mind library code being transpiled if none of the concerns mentioned in this thread are neglected (e.g. performance). The `loose` babel mode creates pretty readable and fast code and we can still benefit from additional optimisations should we move forward with node 4+ support by whitelisting certain transforms (e.g. arrow functions). 

We may also bundle `src/` and `dist/` in the package so that everyone feels right at home reading the source in ES6 and occasionally attempt to debug something with the transpiled version.

@tejasmanohar arrow functions are *unusable* (i.e. incorrectly implemented) on the version of V8 that ships with 0.12.

**Comment by felixfbecker** [comment]
My opinion is no babel, require Node 4 for v2, let the user decide what Promise library to use (all koa needs to do is call a `then`) and use arrow functions, classes and all that good stuff.

**Comment by tejasmanohar** [comment]
#499

**Comment by tejasmanohar** [comment]
>I love the general idea of this framework and I don't quite understand why it uses ES6 generators but not ES6 classes etc. Would love to see a refactor with clean classes.
...
Nice work. I would help out too if needed.

@felixfbecker - Refactor to classes is being made in #503. Only Application is done so far. If you'd like to contribute, just send PRs to the [es2015_classes branch of my fork](https://github.com/tejasmanohar/koa/compare/es2015_classes...koajs:master).

**Comment by felixfbecker** [comment]
I would find it much cleaner and more consistent with application.js if context.js, response.js and request.js exported actual classes `Context`, `Response` and `Request` like `Application` instead of exporting object literals that are then used as prototypes somewhere else. What do you think?

**Comment by tejasmanohar** [comment]
@felixfbecker Indeed. That's the next step (and thus, what's left for that PR to not be "tracking" anymore).

**Comment by felixfbecker** [comment]
(Y) (I like it when the code of the library I'm using is just as organized as my own)

**Comment by tj** [comment]
This is why I don't like JavaScript haha, changes for the sake of changes

**Comment by tejasmanohar** [comment]
>This is why I don't like JavaScript haha, they keep adding multiple ways to do things, just promotes bikeshedding. IMO using an object without a constructor (or 'class') is fine, that's what it is with or without a class anyway, but if classes make more sense to most people then we should do that
agreed, @tj. using a JS object is pretty simple and i don't really see any major readability benefits (personally) of using `class` but seems others do and that's the way things are moving so... i guess so

**Comment by tejasmanohar** [comment]
The main part left in ES6 refactor is classes, and I'll attack that b/w today and tomorrow.

**Comment by tj** [comment]
awesome thanks man!

**Comment by tejasmanohar** [comment]
i'll close this since we've gone forth w/ the es6 factor and a lot of it is already on master

**Comment by felixfbecker** [comment]
There is a very specific use case why koa shouldn't export object literal prototypes. If I create a module that can either take a context or a koa request/response as argument I want to check what the user passed. Now, if a class (or a function) is exported, I can `require('koa/lib/context')` and check with `instanceof`. With object literals..... ?

**Comment by tj** [comment]
duck type, check for the presence of what your program can work with, instead of explicit "classes". Just like interfaces in Go. Then I can't pass a mock to your thing if it's explicitly testing for Context etc

**Comment by tejasmanohar** [comment]
determine what you're dealing w/ based on its properties. if we were in ruby, this could be a bit neater :)
