### ISSUE TITLE
Weird function spacing

### ISSUE THREAD

**Issue by tejasmanohar** [koajs/koa#487]
All the functions seem to be declared as `fn(){`, not `fn() {`, though the latter is more conventional formatting... not that it makes a difference functionally. Based on what I see in @tj's other projects, he usually uses `fn() {` (even in express).

**Comment by tejasmanohar** [comment]
PR ^ #488 - All tests still pass.

**Comment by juliangruber** [comment]
i personally am using `fn(){}` spacing as well, as long as it's coherent in one project it's fine

**Comment by tj** [comment]
As long as things are consistent :1, my preference would be for (){} these days

**Comment by tejasmanohar** [comment]
alrighty. i will close this then
