### ISSUE TITLE
Minimum version -> Node 4.0

### ISSUE THREAD

**Issue by tejasmanohar** [koajs/koa#494]
When should we bump the minimum Node version to 4? I vote KoaJS 2.0. On a side note, do we have a KoaJS 2.0 dev branch / place to PR things for 2.0 into?

**Comment by tsing** [comment]
Or bump to the upcoming LTS version of node ?

**Comment by tejasmanohar** [comment]
This should probably be continued in #484 since that's the big change w/ Node 4 that we're concerned with (so far).
