### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by jonathanong** [koajs/koa#495]
TODO:

- [ ] run linting in CI 
- [ ] add `eslint` and `babel-eslint` into this package so it lints ES6+
- [ ] add `.eslintrc` to this repo so editors lint
- [ ] add `.editorconfig`

**Comment by jonathanong** [comment]
oh maybe there is linting... we need to add it to the CI

**Comment by juliangruber** [comment]
no semicolons :P

**Comment by dead-horse** [comment]
+1 for standard

**Comment by tj** [comment]
that whitespace though :( `function hello (name) {`, looks so disjointed, 1run(function () { ... })`, ಥ_ಥ. I don't care about semi's but if anything the widely adopted implicit standard is to use them so I'd -1 that

**Comment by tejasmanohar** [comment]
+1 on linter

-1 on standard.
- in @tj's examples, the spaces b/w `hello` and `(` and `function` and `(` kinda annoy me.
- semicolons are more popular/conventional... i guess they also help avoid edge cases though that shouldn't be much of a problem here.
- `For the ternary operator in a multi-line setting, place ? and : on their own lines.` also depends on context, imo so wouldn't want that in the linter

i think we should just use our own eslint configuration, there's babel-eslint too

**Comment by stojanovic** [comment]
+1 for standard, not perfect but good enough.
For semicolons, it does require them in front of ( and [ so there should be no edge cases.
eslint config also works, it's probably easier in this case, because standard will require some changes and eslint can be adjusted to a current code style.

**Comment by jonathanong** [comment]
we already have linting... i just don't know where the rules are coming from. you can run `make lint`. we just need to:

- update the rules or package so it works with the current code as well as ES6+. i get a lot of `Unexpected token ILLEGAL`s
- add rules so that linting is strict
- add the command to the CI

**Comment by juliangruber** [comment]
it's https://www.npmjs.com/package/make-lint which depends on https://www.npmjs.com/package/eslint and has the defaults

**Comment by tj** [comment]
hrmm repo is gone

**Comment by tejasmanohar** [comment]
> For semicolons, it does require them in front of ( and [ so there should be no edge cases

@stojanovic i don't like inconsistencies. i know standard forces semicolons where needed (or, i actually thought it just warns against doing things where they are needed), but i'd rather not mix & match when things just work and are conventional w/ semicolons.... yet i don't have a strong preference either which way

**Comment by stojanovic** [comment]
@tejasmanohar It'll just enforce semicolons when ( or [ are at the beginning of the line, I don't think that's something often seen in the source of Koa. Anyway, it's just semicolons, not an important thing at all, it'll work the same with or without them :)

**Comment by tejasmanohar** [comment]
Alrighty... i'll give it a try at least, see how things are in "standard" land :wink: - #524 in-progress, it's integrated w/ CI there... and most of the codebase passes now but still some to go

**Comment by felixfbecker** [comment]
I like to write without semicolons. We all write each statement in a new line anyways. Without semicolons method chains or function assignments over multiple lines look cleaner imo:
```js
getMeAPromise()
  .then(function () {
    doSemething()
  })
  .then(function () {
    andMore()
  })
let aFunction = function (arg) {
  doIt()
}
```
Semicolons are only required in a case where you call a method on a literal, like
```js
[1].forEach(number => { ... })
```
because you might wanted to access the second item of an array returned by a previous statement. You shouldn't do this, instead save it in a constant first so it's clear what the values are for:
```js
const numbers = [1]
numbers.forEach(number => { ... })
```
But I would say make an eslintrc that makes the current code pass so we don't have to do a massive fixup and break git blame. A good editor can detect settings in an eslintrc.
Also I believe you only need babel-eslint if you want to use ES7 features that must be transpiled, like async/await. You just need to set `es6` to `true` in `env`. Also in `env` set `mocha` to `true` so it doesn't fail for the global `describe`, `it`, etc.

Just as an example, here is the config I use for my projects:
```
{
  "rules": {
    "indent": [2, 2],
    "brace-style": [1, "1tbs"],
    "quotes": [2, "single", "avoid-escape"],
    "linebreak-style": [2, "unix"],
    "semi": [2, "never"],
    "no-unused-vars": [1],
    "eqeqeq": [1],
    "yoda": [2],
    "curly": [2],
    "camelcase": [1],
    "spaced-comment": [2, "always"]
  },
  "env": {
    "es6": true,
    "node": true,
    "mocha": true
  },
  "parser": "babel-eslint",
  "extends": "eslint:recommended"
}
```

**Comment by jonathanong** [comment]
https://github.com/koajs/koa/pull/525

awesome
