### ISSUE TITLE
Remove support for node < 4

### ISSUE THREAD

**Issue by jonathanong** [koajs/koa#496]
- `0.12` requires `--harmony`, which is bad
- `1` and `2` are no longer maintained
- `3` is kind of maintained, but...
- `4` is now stable and LTS

anyone object? 

allows us to merge PRs like https://github.com/koajs/koa/pull/493

**Comment by targos** [comment]
:+1:

**Comment by jonathanong** [comment]
if we remove support for `< 4` then should we bump a major version?

**Comment by targos** [comment]
It's probably better to do that if you don't want to break apps that depend on `^1.0.0`

**Comment by tejasmanohar** [comment]
:+1:  for node 4+ as well as major version. these are pretty big changes... i almost think we should save them for 2.x.x (maybe a v2-dev branch?) and keep it on a separate branch. can fix other things like https://github.com/koajs/koa/blob/master/lib/response.js#L46 in the process

**Comment by tejasmanohar** [comment]
#499

**Comment by ruimarinho** [comment]
I'm :+1: for dropping support for node `< 4` with a major version bump.

**Comment by fixe** [comment]
+1

**Comment by stojanovic** [comment]
:+1:

**Comment by tj** [comment]
major bump makes sense to me if we bundle the middleware changes as well so it's not immediately followed by a 3.x haha

**Comment by jonathanong** [comment]
https://github.com/koajs/koa/commit/07619f65c33122317bc4f3e4ff24c55c8e4a49c4
