### ISSUE TITLE
Build failing - style issues

### ISSUE THREAD

**Issue by felixfbecker** [koajs/koa#522]
Seems like build is failing because eslint complains about extra semicolons in pretty much every file. I'm all against using semicolons but apparently koa codebase uses them even though eslintrc is configured to complain about them. Would a PR making eslint pass be of help?

**Comment by jonathanong** [comment]
that's this PR that's failing: https://github.com/koajs/koa/pull/520

i haven't gone through the rules yet. help would be appreciated!

**Comment by felixfbecker** [comment]
Gonna close this as duplicate of #495
