### ISSUE TITLE
'Content-Type' hard not to send

### ISSUE THREAD

**Issue by rektide** [koajs/koa#532]
I'm working to implement a spec that calls for a [201 Created response with no body](https://tools.ietf.org/html/draft-ietf-webpush-protocol-00#section-5). Currently Koa is giving me a application/octet-stream with a content-length of 0, which seems a little silly. I'd like some way to not send a Content-Type.

Related is #277.

**Comment by jonathanong** [comment]
that's weird. if there's a `content-length` of `0`, then there should not be a `content-type` because there is no body.

a PR for a fix or even just a test-case would be great (against v1.x)!

**Comment by tejasmanohar** [comment]
I can take on a PR for this issue after replicating it. Will look tomorrow... that said, if you have an isolated runnable example / repo / gist, that would be great and speed up the whole process, @rektide!

**Comment by danneu** [comment]
Reproduce with:

``` javascript
var koa = require('koa');
var route = require('koa-route');

var app = koa();

app.use(route.get('/test', function*() {
  this.status = 201;
  this.body = '';  // else koa turns it into 204 No Content
  this.type = null;
}));

app.listen(3000, () => console.log('Listening on 3000'));
```

```
$ http localhost:3000/test
HTTP/1.1 201 Created
Connection: keep-alive
Content-Length: 0
Content-Type: application/octet-stream
Date: Sun, 18 Oct 2015 00:30:37 GMT
```

Maybe the fix is as simple as changing this:

``` javascript
// lib/response.js
set type(type) {
  this.set('Content-Type', getType(type) || 'application/octet-stream');
},
```

to this:

``` javascript
// lib/response.js
set type(type) {
  if (null == type) { // handle this.type = null or undefined
    this.res.removeHeader('Content-Type');
  } else {
    this.set('Content-Type', getType(type) || 'application/octet-stream');
  }
},
```

**Comment by tejasmanohar** [comment]
Yes, can replicate. On it :smile:

**Comment by tejasmanohar** [comment]
#534 covered it
