### ISSUE TITLE
Response headers are ignored on error

### ISSUE THREAD

**Issue by pensierinmusica** [koajs/koa#537]
Hi,

Here's a code example:

```js
var app = require('koa')();

app
  .use(function* () {
    this.set('foo', 'bar');
    this.throw(400);
  })

app.listen(3000);
```

The response has code 400 but doesn't include the "foo" header.

On the other hand:

```js
var app = require('koa')();

app
  .use(function* () {
    this.set('foo', 'bar');
    this.status = 400;
  })

app.listen(3000);
```

Now the response has code 400 and includes the "foo" header.

Imho in the first code example the response should include the "foo" header too. If one wants to include it only if there's no error it can be written as follows:

```js
app
  .use(function* () {
    this.throw(400);
    this.set('foo', 'bar');
  })
```

Can this default behavior in Koa be changed to avoid removal of set headers in responses when an error is thrown?

Cheers!

**Comment by jonathanong** [comment]
yes, this is intended and could be documented better. `this.onerror()` is handling the error - if you want to handle the error your own way, create an "upstream" middleware that `try/catch`es the error, then do what you want with it.

**Comment by pensierinmusica** [comment]
@jonathanong ok, possibly we could mention it briefly in the koajs homepage under the `ctx.throw([msg], [status], [properties])` paragraph. What do you think? Cheers

**Comment by pensierinmusica** [comment]
Btw, out of curiosity, what are the advantages of this approach? In my current project for example it makes things quite more cumbersome, because when an assertion is not met the back-end automatically strips away some headers that the front-end actually needs in the response.

**Comment by jonathanong** [comment]
`.onerror()` is more of a fallback than a feature. the approach is minimalism. 

would you like to make a PR w/ docs? it's more helpful coming from someone who knows what they want to know.

**Comment by tj** [comment]
Originally onerror wasn't even public API but some people sort of started using it I guess haha, mostly because of Node limitations since you can't catch allllllllll errors with try/catch. Not sure how I feel about it being public API, overriding a funky named method is a little weird

**Comment by pensierinmusica** [comment]
@jonathanong if you like I can send a PR so that HTML response headers are not stripped away when an error is thrown. Would this be ok to merge? Cheers :)

**Comment by dougwilson** [comment]
In my opinion, I think the default error handler should stay how it is, stripping all pending response headers. As a generic error handler, this is the best course of action, as an error can occur at any point and as far as Koa is concerned, an error that reaches the default error handler is an "unhandled error" and thus cannot trust the state of the response, as it may be in an incomplete state. By resetting all headers, this puts the response back into a known state.

If you want different behavior, just use your own error handler.

**Comment by jonathanong** [comment]
@pensierinmusica maybe look into this instead? https://github.com/koajs/koa/issues/429

**Comment by pensierinmusica** [comment]
@dougwilson I partly agree with you. Let's see if we can get best of both worlds and make a PR to implement it.

> ...an error that reaches the default error handler is an "unhandled error" and thus cannot trust the state of the response, as it may be in an incomplete state. By resetting all headers, this puts the response back into a known state.

I agree this could be the default behaviour for any errors that are not thrown by the user, and generate a 500 response status.

On the other hand, for user-level errors (as defined in Koa docs under `ctx.throw([msg], [status], [properties])`) headers should be kept by default. If the user doesn't want them it will be manifest in the code itself as I had a chance to show in the example on the top of this thread (https://github.com/koajs/koa/issues/537#issue-112488365).

Would this make everyone agree? Should I send a PR? Cheers  :)

**Comment by tj** [comment]
I'd be +1 for some way to explicitly pass headers, I can definitely see a ton of cases where keeping the .set() headers would be problematic. With `properties` already a param that is pretty verbose though haha. I wouldn't mind a more concrete use-case, what's wrong with just try/catch? (aside from the stream edge-case)

**Comment by pensierinmusica** [comment]
@tj what do you think about my proposal of keeping headers only on `err.expose`? Wouldn't this be the best of both worlds?

Imho the developer should be free to choose whether to pass headers anyway on user-level error or not, depending on how the code is written (see example at the top and the bottom of this post: https://github.com/koajs/koa/issues/537#issue-112488365). It's just more transparent, and explicit. In my opinion it's not something that the platform should impose without a choice.

On the other hand, for all other errors that are not thrown by the user (i.e. without `err.expose`) I think the behavior we have today is perfectly fine. Does it make sense? Cheers

**Comment by tj** [comment]
HmmMmm maybe, but I imagine there would still be a lot of scenarios where you'd have to unset a bunch, vs maybe having `throw()` provide an explicit set. In cases where you want to expose the `err.expose` errors in a meaningful way (html or whatever), wouldn't you want to implement a middleware anyway?

**Comment by jonathanong** [comment]
merging into https://github.com/koajs/koa/issues/429
