### ISSUE TITLE
end-to-end testing w/ babel

### ISSUE THREAD

**Issue by jonathanong** [koajs/koa#539]
using async functions. we've tested generators but not async functions

**Comment by broucz** [comment]
I quickly wrote some lines, at least to start the discussion around this issue.
_(I wasn't 100% sure about @jonathanong needs, so this comment could be not related to the topic..)_

Testing async functions need to update the workflow, and we can first discuss & define the guidelines here.

Babel need `babel-runtime` devDependencie, and the minimal `.babelrc` config file look like:
(`"state": 2` is enabled by default)
```
{
  "whitelist": [
    "regenerator",
    "es7.asyncFunctions"
  ]
}
```

Unfortunately, mocha don't allow options to `--compilers js:babel/register`, and so this file is needed (but if you know an inline workaround please let me know) - (we can also require a hook with babel register inside, more or less the same).

An other point was, I guess, to keep making current test without babel. A possible solution could be to add `*.next.js` extension to the files that needed to be target by babel, and filter them using make:

```
TESTS-NEXT := $(wildcard test/**/*.next.js)
TESTS := $(filter-out $(TESTS-NEXT), $(wildcard test/**/*.js))
```

and so the folder looks like for example:

```
test /
  application/
    context.js
    context.next.js
```

We could also split in 2 different folder, or use subfolders, etc...

I [commit a working example in my fork](https://github.com/broucz/koa/commit/43dfefbe175c2458c8e4155c5e6dca3a1bd9247d) if you want to try this config.

I needed to remove mocha user-interface options _only_ for non babel tests to avoid timeout error, but I probably set something wrong.

Also `arrow-parens` rule break the lint test using async arrow function, we need to use [eslint-plugin-babel](https://github.com/babel/eslint-plugin-babel).

One other point to highlight: coverage work but use the same folder (no time so far to search a solution), but we need to track it.

**Comment by menems** [comment]
Hi, maybe I will say something stupid.
I think it's not necessary to test async function, testing promised function is enough no?

**Comment by felixfbecker** [comment]
I actually agree kind of... Babel says "I will transpile async functions to promise". So if it works with promises, but doesn't work with Babel, it's a bug in Babel, not koa. You're not testing Koa, you're testing Babel.

**Comment by felixfbecker** [comment]
But of course end-to-end testing means testing "the whole package"

**Comment by broucz** [comment]
Actually we should test all possible combinaison, even if the last one could be async function due to his current support. But people will probably use it soon thanks to babel, and so test it is not a bad idea for me.

Also, having this kind of separate test allow us to prepare next JS support (ES2016, ... ES2030), writing tests in advance, and then transitioning them slowly to regular test sync with node support.

What about this testing workflow? (in the case we keep on testing babel)
