### ISSUE TITLE
Use arrow functions for all callbacks

### ISSUE THREAD

**Issue by stojanovic** [koajs/koa#551]
This is just a matter of consistency, we are not gaining anything.
So, should we use something like this:
```
it('should', done => {...});
```
instead of
```
it('should', function(done){...});
```
everywhere?

I didn't check if there's a difference in performance between normal and arrow functions in node v4, maybe we should check that too?

cc. @broucz

**Comment by broucz** [comment]
As in #550 @juliangruber  last comment we can refactor using arrow fn.
I didn't find so far any optimization proof of arrow function, but for test usage I guess it's ok.

@stojanovic do you have time atm for this refactor ? We could organise it in order to avoid unnecessary PR ?

**Comment by stojanovic** [comment]
Yes, I can do it now.
Just tests or everything?

**Comment by broucz** [comment]
I guess just `./test/*`
I'm refactoring `./test/application/*`, but lint rules may need update also no ?

**Comment by stojanovic** [comment]
No, they works. Part of it is already in #549.

**Comment by stojanovic** [comment]
I can take response and request, but not sure what's the best way for PR? If I do PR to master it will add it to #549 and I don't think that's a good idea. Maybe a separate branch. But again it would be good to have all tests changed at the same time. Since you started let me know what's the best way for me to help.

**Comment by fundon** [comment]
+1

**Comment by broucz** [comment]
@stojanovic sure you're right, PR once it's better.
I work on an other branch: `broucz/koa/refactor-test-with-arrow`.
You may work on it, I'm not  git master :[

**Comment by broucz** [comment]
But it's quite fast to do, so as you want

**Comment by juliangruber** [comment]
@broucz no-one should work straight in master, always try to make pull requests for everything, except maybe if you're tj :P

**Comment by broucz** [comment]
As I'm not tj, next PR will be from the branch don't worry :P

**Comment by broucz** [comment]
@juliangruber Ho, you mean PR on a dedicated koa branch right ?

**Comment by juliangruber** [comment]
@broucz yeah, just create a branch in your fork and submit a pull request against koa master

**Comment by broucz** [comment]
@juliangruber ok thanks, I'll push `broucz/koa:refactor-test-with-arrow` to `koa:master` so

**Comment by tejasmanohar** [comment]
:+1:

**Comment by stojanovic** [comment]
This is done in #553, but PR needs to resolve some conflicts atm.

**Comment by jonathanong** [comment]
added `prefer-arrow-callback` should be good
