### ISSUE TITLE
Indentation for multiple props in new lines

### ISSUE THREAD

**Issue by stojanovic** [koajs/koa#552]
I think this
```
request(server)
  .get('/')
  .expect(404)
  .end(function(err){
    if (err) return done(err);
    calls.should.eql([1, 2, 3, 4, 5, 6]);
    done();
  });
```
is a bit more readable than this
```
request(server)
.get('/')
.expect(404)
.end(function(err){
  if (err) return done(err);
  calls.should.eql([1, 2, 3, 4, 5, 6]);
  done();
});
```

Again, it's just a readability, there's no real gain here.
Should we update this or leave it as it is?

Also, do we need to follow 80 chars limit? I saw some lines a bit longer, but it's an easy fix.

cc. @tejasmanohar

**Comment by tj** [comment]
sounds fine to me, but I don't want every commit for Koa to be bikeshedding, maybe 1% of the recent activity is "real" progress

**Comment by stojanovic** [comment]
Cool, I'll do it later today.

**Comment by felixfbecker** [comment]
I think the opposite.

**Comment by broucz** [comment]
More or less the same for me even if I'm more used to @stojanovic indent.
We should add a lint rule for this (both version can be find -at least- in test folder), also to avoid some [blank line](https://github.com/koajs/koa/blob/master/test/application/respond.js#L148) (it could be intentional here, better comprehension).

**Comment by tejasmanohar** [comment]
+1, this indentation is more common too... I think Koa is one of the few places I've seen it differently

**Comment by stojanovic** [comment]
Actually it was mixed in Koa.
[Some parts](https://github.com/koajs/koa/blob/master/lib/context.js#L166) of the current master already has that kind of indentation.

**Comment by tj** [comment]
:+1: for linting, then we have nothing to bikeshed

**Comment by stojanovic** [comment]
Done in #555.
