### ISSUE TITLE
Daemon on top of Koa

### ISSUE THREAD

**Issue by devjet** [koajs/koa#554]
Hi all.

From documentation:
*A Koa application is an object containing an array of middleware generator functions which are composed and executed in a stack-like manner upon request.*

To start application I have to call app.listen(%PORT%)
but, I desired to use it with kind of internal CRON (or Interval, etc)
otherwords there's no need to handle requests.

Can you please suggest best practice in this case?

I'm searching for somethig like this:
```javascript
app.use(function *(next){
  console.log('hi i\'m daemon ');
  yield next;
})

app.start();
```

I'm new to this wonderfull framework, sorry for an dumb question.
Thanks.

**Comment by tj** [comment]
You could technically do it, and issue requests against itself during the run, but an http web server is a bad choice for something that runs periodically for processing and does not accept requests.

 I'd definitely recommend looking into something else or just running a regular node script via cron. You could just use an array of promises for example to get a similar effect, or https://github.com/tj/co directly.

**Comment by felixfbecker** [comment]
i would recommend to write a plain node script and run it periodically with something like [pm2](https://www.npmjs.com/package/pm2).
