### ISSUE TITLE
How to set `app.proxy`?

### ISSUE THREAD

**Issue by jchapple** [koajs/koa#563]
Hello,

I see it mentioned in the docs that you can set `app.proxy` to trust proxy header fields. I have been trying this in the following way:

```javascript
const app = koa();
app.proxy = true;
```

However, this doesn't seem to have any effect, and when I later inspect `app`, it seems the value isn't set. All I get back is: `{ subdomainOffset: 2, env: 'development' }`.

Am I missing something?

**Comment by jchapple** [comment]
Never mind. It's set but not seen when inspected by design.

**Comment by tj** [comment]
Ahhh nice catch, we were missing that field
