### ISSUE TITLE
Broken middleware since 2.0.0

### ISSUE THREAD

**Issue by rbaprado** [koajs/koa#564]
Hello, I just upgraded to Koa 2.0.0 and due to the generator support dropping, all my middleware simply broke (i.e. koa-session). I tried co.wrap them but got other errors (I will provide more information shortly). Could someone please present an example of using middleware not yet ported to 2.0.0?

Original code:
`app.use((session(app));`

My attempt:
`app.use(co.wrap(session(app)));`

**Comment by madbence** [comment]
Try [`koa-convert`](https://www.npmjs.com/package/koa-convert), it can transform a generator-based middleware into a promise based one.

**Comment by rbaprado** [comment]
So it would become:
`app.use(convert(session(app))`?

**Comment by menems** [comment]
yep

**Comment by rbaprado** [comment]
That did the job. Could someone explain why that is different than co.wrap?

**Comment by menems** [comment]
the difference is the signature, in new Koa, the context is pass as argument not in legacy

**Comment by rbaprado** [comment]
Don't you think the error message koa throws recommending to use co.wrap a bit misleading then?

**Comment by yanickrochon** [comment]
Yes. `co.wrap` is only to use a gnerator function with Koa 2.0. Old middlewares need to be converted, until they are updated to follow the current next major release's middleware signature.

**Comment by madbence** [comment]
in `koa@2` the context is an arg, so you write your middlewares like `async (ctx, next) => ...`, `co.wrap` just wraps your `function* (next) {...}` middleware into an `async (next) => ...`, so it won't work.

you *can* use generators, if the have proper signature (`function* (ctx, next) { ... }`)

**Comment by rbaprado** [comment]
Ok, I got it now. Thank you all.
