### ISSUE TITLE
Logo 2.0

### ISSUE THREAD

**Issue by yanickrochon** [koajs/koa#566]
Is this the time to revive issue #230 ? With Koa soon to be releasing a major version, I thought it could be possible to renew it's logo, or something. Well, at least I thought adding a `2.0`-ish mention somewhere so it is more apparent that this project made a leap forward and has got substantial changes.  Since some like the tree, here's my first proposal. Point to note, there is too much details in the tree. A simpler tree should perhaps be a better candidate.

![koajs-2](https://cloud.githubusercontent.com/assets/78461/10793268/8147b3f4-7d66-11e5-9cb8-cb753cd92840.png)

(EDIT: here's the [GIMP project](http://mind2soft.com/images/uploads/Koajs.xcf).)

**Comment by felixfbecker** [comment]
:+1: I like this tree. The third one should be combined with the existing koa title in the readme.

**Comment by mattstyles** [comment]
I like it too, could maybe do with some simplification for the smaller icons, and if I'm nitpicking I feel the border is too thick at larger sizes, but, I like it

**Comment by tj** [comment]
we could 99design's it up, the Koa logo fund haha

**Comment by stojanovic** [comment]
:+1: for a new logo :D

**Comment by tejasmanohar** [comment]
:+1: tree is neat

**Comment by ide** [comment]
I like the tree but agree the sample icon is too detailed. I'll pitch in $5 towards the winning design.

**Comment by alsotang** [comment]
seems not a simple one

**Comment by syuilo** [comment]
:+1: Cool

**Comment by NickNaso** [comment]
I don't know generally i prefer something more simple

**Comment by randy-sesser-locm** [comment]
Reminds me of Smog City's logo... not that it's a bad thing. I like beer.

![Smog City](http://www.smogcitybrewing.com/images/general/SmogCityLogo.png)

**Comment by dominhhai** [comment]
Simple is the best.
Hard to draw is not good Logo, imo.

**Comment by tj** [comment]
gonna close for now since we're not actively looking for a new logo. If we get an OpenCollective thing going we could probably put together a little contest or 99design it

**Comment by nswbmw** [comment]
![koa](https://cloud.githubusercontent.com/assets/4279697/20612738/ed1cb422-b2f7-11e6-9463-97cc0095b45d.png)
