### ISSUE TITLE
TypeError: Class constructors cannot be invoked without 'new'

### ISSUE THREAD

**Issue by thelinuxlich** [koajs/koa#568]
Trying to test koa 2 alpha, getting this error:

```
constructor() {
10/28/15 06:20:06
aidax-collector-1 aidax[1491]: ^
10/28/15 06:20:06
aidax-collector-1 aidax[1491]: TypeError: Class constructors cannot be invoked without 'new'
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at require (module.js:384:17)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at normalLoader (/app/releases/20151028201122/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at startup (node.js:117:18)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Function.Module.runMain (module.js:475:10)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Module._compile (module.js:434:26)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Object.Module._extensions..js (module.js:452:10)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Module.load (module.js:355:32)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Function.Module._load (module.js:310:12)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Object.<anonymous> (/app/releases/20151028201122/node_modules/koa-cluster/lib/http.js:9:11)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at require (module.js:384:17)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Module.require (module.js:365:17)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Function.Module._load (module.js:310:12)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Module.load (module.js:355:32)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Object.<anonymous> (/app/releases/20151028201122/index.js:6:1)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Module._compile (module.js:434:26)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Object.Module._extensions..js (module.js:452:10)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at node.js:951:3
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Module.require (module.js:365:17)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Module.load (module.js:355:32)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Function.Module._load (module.js:310:12)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Object.require.extensions.(anonymous function) [as .js] (/app/releases/20151028201122/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
10/28/15 06:20:05
aidax-collector-1 aidax[1491]: at Module._compile (module.js:434:26)
```

**Comment by felixfbecker** [comment]
In koa2 you need to do `const app = new Koa()` instead of `const app = koa()`

**Comment by thelinuxlich** [comment]
Thanks, that is easy to miss

**Comment by tejasmanohar** [comment]
Yeah, we need a major changes doc b/w v1 and v2 :P

That said, even though I submitted the PR for making Application a class, I'm still meh about it. There's little to no practical use of 2 "Koa"s in 1 app so why shall it be a class vs a prototype or instance returned

but looks like this is the upcoming standard / where the community is going

**Comment by dtothefp** [comment]
Quick note on this, if you are using Koa 2 and trying to do something like this

```js
class MyServer extends Koa {
  constructor() {
    super();
    this.use(convert(serve('./dist')));
  }
}

const app = new MyServer();
```

You will get this error if you are using the full monty babel presets

```json
{
  "plugins": ["add-module-exports", "typecheck", "transform-decorators-legacy"]
}
```

Instead I only use the presets I need with and let Node 5 support the rest and it works
```js
const babelrcServer = `
  {
    "babelrc": false,
    "presets": ["react"],
    "plugins": [
      "transform-es2015-for-of",
      "syntax-object-rest-spread",
      "transform-es2015-parameters",
      "transform-object-rest-spread",
      "syntax-async-functions",
      "transform-es2015-arrow-functions",
      "transform-es2015-spread",
      "transform-es2015-destructuring",
      "transform-es2015-modules-commonjs",
      "transform-strict-mode",
      "transform-regenerator"
    ]
  }
`;

require('babel-register')(JSON.parse(babelrcServer));
```

**Comment by tejasmanohar** [comment]
> TypeError: Class constructors cannot be invoked without 'new'
I don't think we should add any custom handling of this since the error is super descriptive ^^. Sure, it's easy to miss when moving from v1 to v2 but easy to figure out why as well :)

**Comment by julie1013** [comment]
I'm having trouble with the error you are talking about? Any ideas?

**Comment by tejasmanohar** [comment]
@julie1013 Post code? Did https://github.com/koajs/koa/issues/568#issuecomment-151983902 not help?

**Comment by julie1013** [comment]
For a class I'm in... for example, I had a FarmAnimal class and I did this:

class Cow extends FarmAnimal(){
  constructor(name, sound, image){
    super("Milky", "moo", "images/cow.jpg");
  }
}


But I got "Class FarmAnimal cannot be invoked without 'new'"

**Comment by PlasmaPower** [comment]
@julie1013 Is this even related to Koa? Try stackoverflow.

**Comment by PlasmaPower** [comment]
It looks like this is third in the list of a "class constructors cannot be invoked without 'new'" Google search, we should consider locking this thread with a quick explanation.

**Comment by julie1013** [comment]
Sorry, I guess I am in the wrong place and was just desperately looking for an answer! :)

**Comment by dtothefp** [comment]
@julie1013 if you are using Babel depending upon your presets/plugins you can see this error. Make sure not to compile your classes. Have a look at this babelrc and maybe it works https://github.com/dtothefp/build-boiler/blob/master/.babelrc

**Comment by mgthomas99** [comment]
@julie1013 You've got a syntax error.
```js
class Cow extends FarmAnimal(){
                            ^^
```
The parentheses shouldn't be there.

**Comment by dinozarafonitis** [comment]
> @julie1013 You've got a syntax error.
> 
> ```js
> class Cow extends FarmAnimal(){
>                             ^^
> ```
> 
> The parentheses shouldn't be there.
> 
> EDIT: Just noticed this was over a year ago.

Thanks, that helped!
