### ISSUE TITLE
Do I have to pass ctx to await next() ?

### ISSUE THREAD

**Issue by thelinuxlich** [koajs/koa#569]
Because my middlewares are not getting params updated in upper middlewares.

**Comment by jonathanong** [comment]
yeah. first argument is `ctx`!

**Comment by thelinuxlich** [comment]
Ok, from the example it seems that we don't need to pass anything

**Comment by thelinuxlich** [comment]
so it should be something like this?

```
module.exports = async (ctx,next) => {
    await(ctx,next);
}
```

**Comment by thelinuxlich** [comment]
with the middlewares sending ```await next(ctx)``` I still don't get data passed through :(

**Comment by felixfbecker** [comment]
Uhm @jonathanong I thought you changed the API to just `await next()`? I know the initial proposal was to do `await next(ctx)`, was this changed and if yes, why? And if no, why has ctx to be passed but bot next?

**Comment by jonathanong** [comment]
OH SHIT sorry read this wrong. @felixfbecker is right.

```js
async (ctx, next) => {
  await next()
}
```

**Comment by felixfbecker** [comment]
So basically next is not the next middleware, but a koa magic function that calls the next middleware with the ctx and the middleware after next and returns its promise?

**Comment by thelinuxlich** [comment]
I'm trying to do a poor man's router:

```
app.use((ctx, next) => {
    if (ctx.method === "GET" && routes[ctx.path]) {
        return routes[ctx.path](ctx, next);
    } else {
        ctx.status = 404;
    }
});
```

But this is not passing the next function to the middleware :(

**Comment by thelinuxlich** [comment]
Hmm actually my example is working, it was a error on my side.

Although I think this deserves some explanation on the docs, I don't know what is the difference between ```return next()``` and ```return something(ctx,next)```

**Comment by jonathanong** [comment]
yeah, one of the updates i have to do is "composing middleware", which is no longer as simple as before

**Comment by jonathanong** [comment]
please open a new issue or a PR if the docs are still insufficient
