### ISSUE TITLE
Documentation should include an example of babel configuration

### ISSUE THREAD

**Issue by thelinuxlich** [koajs/koa#572]
Now with Babel 6, things got a little more complex:

```
// index.js
require("babel-polyfill");
require('babel-core/register')({
    presets: ["es2015"],
    plugins: ["syntax-async-functions", "syntax-async-generators"]
});

require('./app.js');
```

**Comment by scttcper** [comment]
so that's how it works now... thank you!

**Comment by tj** [comment]
Is it more idiomatic to just use babel-node?

**Comment by thelinuxlich** [comment]
I think the require polyfill has less friction, but it's just me

**Comment by jonathanong** [comment]
yes this is one reason why i want https://github.com/koajs/koa/issues/539 - as a good example. i believe in transpiling into separate files then loading those. i believe that `babel-node` and the script above is actually NOT recommended for production because it uses a lot of memory.

**Comment by jonathanong** [comment]
http://babeljs.io/docs/usage/cli/#babel-node nvm seems like only `babel-node` is not recommended

**Comment by kriswill** [comment]
People use the polyfill to build isomorphic node apps, like loading up Redux and React JSX files, then running the route thru the redux-router, setting up initial state and pre-rendering the page.  All without having to muck with the JS2015/ES6 files.

**Comment by kriswill** [comment]
here's an example `/index.js`
```js
require('babel/register')({stage: 0})

if (process.env.NODE_ENV === 'production' || require('piping')({
  ignore: /(\/\.|~$|webpack-assets.json)/,
  hook: true
})) {
  require('./src/server/index.js')
}
```
`src/server/index.js`:
```js
import 'babel/polyfill'

import koa from 'koa'
const app = koa()
export default app

import logger from 'koa-logger'
app.use(logger())

import Routes from './routes'
Routes(app)

const port = process.env.PORT || 1337
app.listen(port, () => console.log(`API Server listening on http://localhost:${port}`))
```

**Comment by tejasmanohar** [comment]
just stumbled upon this issue and saw @tj's comment-
> Is it more idiomatic to just use babel-node?

yea, i used to do this in dev mode when i precompiled (and didn't use require hooks)... but ->

https://babeljs.io/docs/usage/cli/#babel-node

>You should not be using babel-node in production. It is unnecessarily heavy, with high memory usage due to the cache being stored in memory. You will also always experience a startup performance penalty as the entire app needs to be compiled on the fly.

**Comment by kriswill** [comment]
@tejasmanohar Yeah, I always transpile the ES6/7 code specifically to ES5 + node.js 5 ES6 features using Babel 6's specific transforms prior to production deployments.  Babel 6 lets you choose specifically to retain arrow functions, generators, template strings, etc for native V8 support in node.

**Comment by cesarandreu** [comment]
With Babel 5 you can do: 

```sh
$ node -r babel/register ./index.js
```

I haven't tried it, but maybe the following works with Babel 6:

```sh
$ node -r babel-core/register ./index.js
```

**Comment by tejasmanohar** [comment]
Maybe but You'll def need babel-polyfill as well for async/await

**Comment by mattstyles** [comment]
not necessarily, regenerator or bluebird would suffice, you wouldnt need the whole polyfill if you're not using those features

**Comment by tejasmanohar** [comment]
@mattstyles ah ok, thought something changed in babel 6 for needing polyfill for async/await with require hooks, but maybe i'm wrong. will check on this later.

**Comment by mattstyles** [comment]
I dont think so, and you can specify how you want `async` transformed to i.e. which lib to use. I've put babel6 on a back-burner for a couple of weeks as its still in such flux, will settle down shortly I'm sure.

**Comment by mattstyles** [comment]
Using `transform-async-to-generator` you dont actually need any polyfill, it's appended to the top of each file.

If you use `transform-regenerator` then you'll need the `regenerator-runtime`, either include it yourself or use `babel-polyfill` or `babel-regenerator-runtime`.

You can also transpile to `bluebird coroutines`, in which case you'd need to include `bluebird` obvs. I can't remember to config offhand but programmatically its

```
require( 'babel-plugin-transform-async-to-module-method' ), { 
  module: 'bluebird', 
  method: 'coroutine' 
}
```

**Comment by scttcper** [comment]
@mattstyles docs are http://babeljs.io/docs/plugins/transform-async-to-module-method/

**Comment by mattstyles** [comment]
haha, yeah, I figured it'd be about the same for the config option

**Comment by vtfn** [comment]
Are there any downsides of using babel this  way over transpiling all code to, say, a 'dist/ folder, and running the application from there?
