### ISSUE TITLE
response.js "TODO: wtf" :)

### ISSUE THREAD

**Issue by stojanovic** [koajs/koa#575]
Just adding TODO's from the code as an issues so we can clean them up.

[This one](https://github.com/koajs/koa/blob/master/lib/response.js#L48) is the first.
`this.res._headers` are the original headers from node's `http.createServer`.

@tj I see that this is your comment and it seems pretty old :) Do you still know how to do it better or we can just remove the comment?

**Comment by tj** [comment]
I'm not positive but I doubt node has improved thee

**Comment by stojanovic** [comment]
As I know it's still the same.

**Comment by stojanovic** [comment]
Just checked. No they didn't and I doubt they will.
Should we just leave that comment in case they improve it in the future?

**Comment by tj** [comment]
might as well get rid of it if we don't see them adding anything similar, either works for me!
