### ISSUE TITLE
get socket() - "TODO: TLS"

### ISSUE THREAD

**Issue by stojanovic** [koajs/koa#576]
This is one can be found [here](https://github.com/koajs/koa/blob/master/lib/response.js#L36) and [here](https://github.com/koajs/koa/blob/master/lib/request.js#L301) and it's from 2013 too.

Code is the same:
```js
get socket() {
    // TODO: TLS
    return this.req.socket;
},
```

**Comment by jonathanong** [comment]
i don't remember what need to do... i believe w/ SSL this socket is a little different. anyone remember?

**Comment by tj** [comment]
I think it was wrapped like this.req.socket.socket or something weird like that hahaha.. but that could be completely different now :D

**Comment by jonathanong** [comment]
going to remove this until we know what it means :P

**Comment by stojanovic** [comment]
:+1: 
Haha, we'll never know :)

**Comment by tj** [comment]
haha im 99% sure that req.socket was a different or missing for tls at some point, it was something like req.socket.connection
