### ISSUE TITLE
[Koa 2] Style of middleware with extra arguments

### ISSUE THREAD

**Issue by gyson** [koajs/koa#591]
in Koa 1.x, middleware (e.g. `koa-route`, `koa-router`) with extra arguments would use:

```
function * (a, b, c, next) { ... }
```

e.g. in `koa-route`

```js
app.use(_.get('/pets/:name', function * (name, next) {

})
```

Which styles should we use in Koa 2 ?

1. `(ctx, next, a, b, c) => { ... }`
2. `(ctx, a, b, c, next) => { ... }`
3. `(a, b, c, ctx, next) => { ... }`

I think we need a consensus about it.

What's your opinion ?

**Comment by felixfbecker** [comment]
No extra arguments at all, add the data to `context.state`.

**Comment by tj** [comment]
`const {a, b, c} = ctx.state` works for me! or maybe `({a, b, c}, ctx, next)` but meh

**Comment by gyson** [comment]
Is `.state` recommended namespace for storing routing params ? I see that `.params` is mostly used.

relevant: koajs/route#38, alexmingoia/koa-router#202

**Comment by felixfbecker** [comment]
hm for router I find `ctx.params` more intuitive. Actually, I find `ctx[anything]` more intuitive than `ctx.state[anything]`. I mean, the only reason why koa wraps request and response in a context object for me is so you can add more properties without touching req or res like in express (besides doing the context-as-this thing in koa1). A router param isn't really a _state_. Maybe we should just stop encouriging people to use `ctx.state` in koa2? All it does is nest properties one extra level.

**Comment by yanickrochon** [comment]
I find `ctx.params` to be better (i.e. more intuitive too) for routers. As for `ctx[anything]` for URL params, this will most likely lead to name conflict at some point.

**Comment by tj** [comment]
:+1: for params. I prefer the lack of unified ctx.state too, from a technical side I think it's cleaner since it lets us do whatever we like at the context level api-wise but I'm not in love with it personally. With destructuring I think the ugliness of it is negligible, and it's a bit easier to inspect

**Comment by felixfbecker** [comment]
I mean't having params in `ctx.params` (not `ctx.state.params`), a JWT token in `ctx.token` (not `ctx.state.token`), etc etc. You could still do destrcuturing.

**Comment by tj** [comment]
I know, I just mean that destructuring makes the ctx.params / ctx.state objects less ugly in use. I don't think we should advocate throwing everything on ctx instead of ctx.state, unless it's something that really benefits from that like ctx.user is a more obvious one

**Comment by madbence** [comment]
afaik es2015 supports nested destructuring :wink: 

```js
app.use(get('/:id', async ({ params: { id }, user }, next) => {
  if (permitted(user, id)) {
    await next();
  } else {
    throw Error();
  }
}));
```

**Comment by jbielick** [comment]
I think a good bit of middleware was written before `ctx.state` was introduced. It may already be in the docs, but as middlewares are updated, most of them could probably do a better job of staying out of `ctx` props.

@madbence why destructure like that if you have to come up with a creative way to retain the actual object you're destructuring?

**Comment by yanickrochon** [comment]
@madbence yes, it's `var id = ctx.params.id;` :P

**Comment by madbence** [comment]
maybe attach `ctx` to itself, like `ctx.ctx = ctx` haha

```js
app.use(get('/:id', async ({ params: { id }, user, ctx}, next) => {
  if (permitted(user, id)) {
    await next();
  } else {
    ctx.throw(403, 'frobz qux');
  }
}));
```

**Comment by simplyianm** [comment]
Nah, there you could just do

```
app.use(get('/:id', async (ctx, next) => {
  const { params: { id }, user } = ctx;
  if (permitted(user, id)) {
    await next();
  } else {
    ctx.throw(403, 'frobz qux');
  }
}));
```

**Comment by yanickrochon** [comment]
:+1:

**Comment by madbence** [comment]
@simplyianm :+1: it doesn't look that bad at all, i'm just a bit disappointed that you cannot destructure everything on the parameter list :disappointed:

**Comment by simplyianm** [comment]
You can do that in Elixir :wink:

**Comment by tj** [comment]
To me it gets too cluttered in the params anyway

**Comment by jonathanong** [comment]
leaving this as an option for routers and other middleware. feel free to open issues in each router's repo!

i personally prefer `this.params = {}`
