### ISSUE TITLE
Sending chunked responses

### ISSUE THREAD

**Issue by lukas-zech-software** [koajs/koa#593]
I try to implement a long polling mechanism using chunked headers to keep the connection alive.

Basically I run a very long async operation on the server, and while waiting for this operation to finish, I want to sent data over the connection to keep it alive.
This behaviour is necessary to keep Heroku from shutting down the connection after 30 seconds

Therefore I assigned a stream to ```this.body``` and push spaces to the stream every 2 seconds, expecting that these will be immediately be sent to the client via a chunked transfer response.

But the response is not sent until the stream is flushed, then sending the whole data at once.

Currently I solved it like this
```javascript
    //Send the headers
    //Tell the client everything is fine and that we will send JSON
    //Set the headers manually so that koa does not try to set them, when the response is flushed
    this.status = 200;
    this.type = 'application/json';

    //Create a ChunkedResponseStream to send a chunked response
    const chunkedResponse = new stream.Readable();
    chunkedResponse._read=()=>{};
    chunkedResponse.pipe(this.res);

    //Write a space character to the response every second to keep the connection alive
    //the space will not invalidate the JSON that will be sent later
    interval = setInterval(()=> {
        chunkedResponse.push(' ');
    }, 2000);

    try {
        const result = yield expensiveOperation();
        //Write the serialized JSON to the stream
        chunkedResponse.push(JSON.stringify({result: result}));
    } catch (e) {
        //As it is too late to set the header to an error state, we log it and send an error message to the client
        console.error('Error while calling "expensiveOperation"', e);
        chunkedResponse.push(JSON.stringify({error: 'Error while calling "expensiveOperation"'}));
    } finally {
        //Once the data is there, clear the interval
        clearInterval(interval);
        //End the stream
        chunkedResponse.push(null);
    }
```

Is there any built in mechanic that I could use for this kind of operation?
 Piping to ```this.res``` does not seem like the koa-way of doing this

I understand that there are difficulties in unwinding the middleware stack if headers cannot be set anymore, as they have been already sent with the first chunk, but is there any built in possibility to support chunked transfers or telling all following middle ware, that the headers are blocked?

**Comment by juliangruber** [comment]
Instead of piping to res set "this.body = chunkedResponse". Also you might want to make that stream a "require('stream').PassThrough" instead of a readable. You also won't need to set the status to 200 with this.body set.

**Comment by lukas-zech-software** [comment]
@juliangruber Thanks for your answer but that will lead to the unwanted behaviour I described in the third sentence 
> But the response is not sent until the stream is flushed, then sending the whole data at once.

I want each data chunk written to the stream to be sent immediately to the client [with chunked transfer](https://en.wikipedia.org/wiki/Chunked_transfer_encoding)

Setting ```this.body``` to a stream does not seem to support this.

**Comment by jbielick** [comment]
Would the chunk size of the stream affect when it flushes / not getting one whitespace char at a time? http://stackoverflow.com/questions/16909227/using-transfer-encoding-chunked-how-much-data-must-be-sent-before-browsers-s

**Comment by juliangruber** [comment]
Yup, try sending a newline

**Comment by lukas-zech-software** [comment]
Instead of sending one whitespace I tried to send a string with 2.2 Kb to overflow any limit that could apply to a single chunk.
I also tried to send  ``` \n ``` newline characters instead

Both approaches still had the same effect: The is no chunked content transmitted, the whole date is transferred at once when the stream is flushed, not a single byte is send before that.

**Comment by juliangruber** [comment]
Did you try curl as a client? Maybe browsers are messing with this

**Comment by lukas-zech-software** [comment]
Strangley curl does not output anything while receiving chunked content on my solution.
It outputs the whole output once the transfer has finished.

Firefox's, Chrome's DevTools and Fiddler show the chunked content being pushed to the client when using ``` chunkedResponse.pipe(this.res);``` while all three show nothing until the end when using ```this.body = chunkedResponse```

I can also se the characters (when not using whitespaces) popping up one by one in my browser as it renders them

I'm pretty sure this is specific to curl, I don't know and could not find out if it is supposed to do so

**Comment by dead-horse** [comment]
```js
const through = require('through');
const http = require('http');
const koa = require('koa');
const app = koa();

app.use(function *(){
  const tr = through();
  setInterval(() => tr.write('blabla\n'), 100);
  setTimeout(tr.end, 5000);
  this.type = 'text';
  this.body = tr;
});

app.listen(7001, () => {
  http.request({
    host: '127.0.0.1',
    port: 7001,
    method: 'GET'
  }, res => {
    res.on('data', data => console.log(data));
  }).end();
});
```

both node and `curl http://localhost:7001` works fine for me, maybe this issue is cause by implementation of different client?

**Comment by dead-horse** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=156023

looks like a chromium bug

**Comment by marcusdarmstrong** [comment]
For anybody that, like me, ends up reading this random closed issue looking for a fix:

When you set the koa response body to a stream, that stream is only piped to the output stream of the application _after complete execution of the request handler_. So getting the desired behavior here requires using a fire-and-forget approach in the request handler with respect to writing the response stream.

**Comment by jayli** [comment]
Here are some demos for this issue. Maybe it will help you.

<https://github.com/jayli/koa-stream-await-call-error>
