### ISSUE TITLE
How do I get the real ip?

### ISSUE THREAD

**Issue by thelinuxlich** [koajs/koa#599]
I set ```app.proxy = true``` but sometimes I still get someone with ```ctx.ip = "127.0.0.x"```

**Comment by alsotang** [comment]
sometimes or always?

2015-11-19 11:38 GMT+08:00 Alisson Cavalcante Agiani <
notifications@github.com>:

**Comment by thelinuxlich** [comment]
always when someone is behind a NAT

**Comment by jonathanong** [comment]
this is what https://github.com/jshttp/proxy-addr is for, which i haven't had to implement. PR would be welcomed.  https://github.com/koajs/koa/issues/281

**Comment by thelinuxlich** [comment]
So getting the last ip of ctx.ips is not enough?

**Comment by thelinuxlich** [comment]
This seems to be working for returning the real ip:

```
const current_ip = ctx.ips.length > 0 ? ctx.ips[ctx.ips.length - 1] : ctx.ip;
```

**Comment by tj** [comment]
the client's ip should be first, check out https://en.wikipedia.org/wiki/X-Forwarded-For

**Comment by thelinuxlich** [comment]
I know, I want the last ip because it is returning LAN ips

**Comment by jgdev** [comment]
There's a problem using koa over nginx server, when I force X-Forwarded-For in the request.

An  `X-Forwarded-For` header requested by client overwrites `this.request.ip`. This is a critical security issue.

Found the problem in line 381 of koa/lib/request.js
https://github.com/koajs/koa/blob/master/lib/request.js#L381

It's better use X-Real-IP over X-Forwarded-For.

**Comment by tj** [comment]
`real_ip_header    X-Forwarded-For`? supporting two sounds annoying to me, why not use the more common one?

**Comment by jgdev** [comment]
Thats because NginX appends external request's `X-Forwarded-For` value to final header but clears external `X-Real-IP` header and gets it right with far end's value.

**Comment by tj** [comment]
hmm yea I suppose it depends how nginx is configured, though if you have X-Real-IP you might as well just clobber X-Forwarded-For to ensure it's correct

**Comment by fengmk2** [comment]
If your koa app behind a nginx, you must add 'proxy_set_header        X-Forwarded-For $remote_addr' to the nginx proxy conf.

**Comment by pepkin88** [comment]
I just found that you can spoof an IP address on the standard configuration of nginx. And I happen to whitelist payment servers on my webhook by an IP address.
I agree with @jgdev, this is a critical security issue and should be fixed.

**Comment by runhwguo** [comment]
in nginx:
location / { 
    proxy_pass http://test; proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Real-PORT $remote_port;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

in node koa:
app.proxy = true;
ip = ctx.ip;

**Comment by ProMasoud** [comment]
> in nginx:
> location / {
> proxy_pass http://test; proxy_set_header Host $host:$server_port;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Real-PORT $remote_port;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> }
> 
> in node koa:
> app.proxy = true;
> ip = ctx.ip;

for me this worked plus 

```
ip = ctx.request.ip;
```

**Comment by Gherciu** [comment]
I had the same problem but resolved it by using this module found on NPM `request-ip`

in koa it can be simply used `userIp = requestIp.getClientIp(ctx.request)`

The user ip is determined by the following order:
```
X-Client-IP
X-Forwarded-For (Header may return multiple IP addresses in the format: "client IP, proxy 1 IP, proxy 2 IP", so we take the the first one.)
CF-Connecting-IP (Cloudflare)
Fastly-Client-Ip (Fastly CDN and Firebase hosting header when forwared to a cloud function)
True-Client-Ip (Akamai and Cloudflare)
X-Real-IP (Nginx proxy/FastCGI)
X-Cluster-Client-IP (Rackspace LB, Riverbed Stingray)
X-Forwarded, Forwarded-For and Forwarded (Variations of #2)
req.connection.remoteAddress
req.socket.remoteAddress
req.connection.socket.remoteAddress
req.info.remoteAddress
```
If an IP address cannot be found, it will return null.
