### ISSUE TITLE
Npm Koa: Wrong version

### ISSUE THREAD

**Issue by wcastand** [koajs/koa#602]
When i use :
```
'npm install koa'
```
I get :
```
"koa": "^1.1.2"
```
I guess it's normal, but you should write it on the README because i tried for 2 hours your examples code lol

**Comment by fundon** [comment]
Koa@2 is not the latest version on npm site, so a special version (2.0.0-alpha.1) is required.

**Comment by wcastand** [comment]
Yeah i see that now. But the examples on the README are for version 2, and on the README, they use:
```
npm install koa
```
That's confusing :/ at least for me lol

**Comment by fundon** [comment]
Koa 2 is not released.

**Comment by wcastand** [comment]
I understand that :)
But why the examples on the README of this repo are for version 2 and they don't specify it.

**Comment by yanickrochon** [comment]
Well, since Koa 2 will not likely release for a long.... long time, the current master should be moved to a `2.0` branch and put the latest 1.x as master.

**Comment by tejasmanohar** [comment]
@yanickrochon Yeah, suggested this in #533

**Comment by dead-horse** [comment]
```
$ npm dist-tag ls koa
latest: 1.1.2
next: 2.0.0-alpha.3
```
