### ISSUE TITLE
default branch to v1.x

### ISSUE THREAD

**Issue by dead-horse** [koajs/koa#603]
- [x] create a branch `v2.x` from master.
- [x] force update master to `v1.x`
- [x] change `latest` tag in npm point to koa@1
- [x] add a `next` tag point to koa@2, people can install  koa@2 by `npm install koa@next`
- [x] make all the middlewares' master branch support koa@1
- [x] make all the middlewares' latest tag support koa@1, and add a tag named `next` to support koa@2. eg: `npm install koa-bodyparser@next`
- [ ] add how to use `koa@2` in README.md

**Comment by czy88840616** [comment]
good idea +1

**Comment by fengmk2** [comment]
Yep! Keep koa@1 stable before async/await enable by Node.js.

**Comment by gxcsoccer** [comment]
lts +1

**Comment by shaoshuai0102** [comment]
:+1:

**Comment by ngot** [comment]
+

**Comment by dead-horse** [comment]
https://github.com/koajs/bodyparser:

- [x] master branch support koa@1
- [x] latest tag support koa@1
- [x] next tag support koa@next

```sh
$ npm dist-tag ls koa-bodyparser
latest: 2.0.1
next: 3.0.0
```

**Comment by fundon** [comment]
Nice

**Comment by alsotang** [comment]
+1

2015-11-24 16:11 GMT+08:00 Fangdun Cai <notifications@github.com>:

**Comment by dead-horse** [comment]
now master branch is force updated to `v1.x`. run commands below can fix your local git repo.

```bash
$ git fetch --all
$ git reset --hard origin/master # replace `origin` to your own remote name
```

**Comment by Pana** [comment]
When will 2.0 released ?

**Comment by jedahan** [comment]
@Pana I think when async/await is supported by node

**Comment by dj-hedgehog** [comment]
Before node can support async-functions they need to be included in V8 first. — [v8 Issue #4483](https://code.google.com/p/v8/issues/detail?id=4483)

The only other way I can think off is compiling Microsoft's fork of Node which replaces V8 with their own Chakra JS engine. Is has experimental async function support.

**Comment by tejasmanohar** [comment]
@dj-hedgehog Yep, we'll wait on V8.

**Comment by tejasmanohar** [comment]
@dead-horse Could we add set `peerDependencies` to the list of tasks for this issue? I think it'd make sense to do so so that users get warnings if they're installing the wrong stuff. @tj suggested the same earlier in some of the issues of middleware.
