### ISSUE TITLE
Extending context with Koa 2.0

### ISSUE THREAD

**Issue by derek-duncan** [koajs/koa#609]
I may be missing this in the source code, but it doesn't appear that extending the context works anymore in Koa 2.0. Here's the code I've tried.

    app.context.render = myRenderFn;

When I try to use `ctx.render()` in a route, it turns up as undefined. Any thoughts?

**Comment by alsotang** [comment]
notice that `context.render` is a getter, not a variable.


2015-11-26 5:26 GMT+08:00 Derek Duncan <notifications@github.com>:

**Comment by dead-horse** [comment]
can you provide a short example for this issue?

**Comment by tejasmanohar** [comment]
@derek-duncan Did @alsotang's comment help? If not, I'll take a peek if you provide a small isolated yet runnable example. Thanks!

**Comment by jonathanong** [comment]
Closing. Please reopen with a test case
