### ISSUE TITLE
why context.onerror remove headers?

### ISSUE THREAD

**Issue by menems** [koajs/koa#613]
https://github.com/koajs/koa/blob/v2.x/lib/context.js#L121

I don't understand why headers are removed if you throw an error?
I'm sure there is a reason.

concrete example: if I use cors and jwt middleware. domain is authorize to make a request but try to access a unauthorize api, why `Access-control...`headers should be removed?

The only way is for now, to catch the error(401) and set ctx.status =  401.

But if i want to centralize my errors, i 'd like to use the app.on('error') for example and not add before all other middeleware something like that:

````
app.use(ctx => {
   return next().catch(e => ctx.status = e.status)
}

**Comment by tj** [comment]
dup, convo is over at #571
