### ISSUE TITLE
`ctx` passed as a argument vs bound as `this`

### ISSUE THREAD

**Issue by joshmanders** [koajs/koa#615]
So I just noticed Koa v2 is on it's way soon, and I decided to take a gander at it and I noticed that it's now the signature is `function (ctx, next)` instead of `function (next)` with `ctx` bound as `this`. Is there a reason this was changed in v2?

**Comment by yanickrochon** [comment]
This has been discussed in details in #581.

**Comment by joshmanders** [comment]
Okay thank you, I tried to find it but couldn't.

**Comment by joshmanders** [comment]
Hmmm, after reading them, I failed to see why the change in signature was made, just examples using it.

**Comment by jonathanong** [comment]
the primary reason is so that you can write koa apps w/ async arrow functions:

```js
async (ctx, next) => {
  await next()
}
```

using `this`, it is impossible

**Comment by joshmanders** [comment]
Ah, arrow functions. Makes sense. Thanks @jonathanong
