### ISSUE TITLE
Middlewares compatible with Koa 2.0

### ISSUE THREAD

**Issue by mugli** [koajs/koa#618]
One nice thing about Koa is one can take a lot of decisions on which middleware to use for what purpose reading this single page wiki: https://github.com/koajs/koa/wiki

However, since the project is going through a major upgrade at this moment, it became harder to decide if I start a new project now, should I be using Koa 1x or 2. A middleware compatibility chart for Koa 2.0  could help us take a more informed decision quickly, and that would also encourage the community contributors to add 2.0 compatibility to their middlewares, showing how fast others are proceeding.

I suggest there should be a new column (like `Koa 2.0 compatibility`) in the current wiki: https://github.com/koajs/koa/wiki

Any thoughts?

**Comment by jonathanong** [comment]
sounds great!

**Comment by mugli** [comment]
One downside would be out of date information for some middleware, for some period. Regardless, please let me know if I can help by opening a PR for this.

**Comment by yanickrochon** [comment]
Good initiative. Perhaps as the list grow, more project owners will make their middleware compatible, too.

**Comment by zackify** [comment]
Why not go look at the repo for a middleware and check if it has a 2.x
branch?

**Comment by mugli** [comment]
@zackify Not all middleware maintain that pattern in their repo. I just knew few hours ago from twitter that `koa-socket` now supports 2x style middleware, but you won't find any 2.x branch there: https://github.com/mattstyles/koa-socket, it'll only become obvious once you read the doc.

Point is precisely just that, saving time by documenting something, otherwise everyone would have to repeat that for themselves.

**Comment by tejasmanohar** [comment]
+1 for this. Official middleware should have 2.x/next branches, but we can't control unofficial ones.

**Comment by fl0w** [comment]
@jonathanong This can be closed now I believe.
