### ISSUE TITLE
koa automaticlly caught exceptions caused me I can't record the error message，I want to record this message in the log，besides modify source code ，could I have some good method ? 

### ISSUE THREAD

**Issue by wfsovereign** [koajs/koa#619]
can anyone help me ?

**Comment by tj** [comment]
Do you have a specific case that isn't working? Otherwise try adding a middleware such as:

```js
app.use(function *(next){
  try {
    yield next;
  } catch (err) {
    console.log(err);
    this.body = 'Something exploded';
  }
});
```

**Comment by alsotang** [comment]
show some example code

2015-12-10 10:57 GMT+08:00 wfsovereign <notifications@github.com>:

**Comment by wfsovereign** [comment]
sorry, just to see your response.

my means is that I want to caught exceptions to write in the log file, but koa already caught expceptions [source code](https://github.com/koajs/koa/blob/master/lib%2Fcontext.js#L101),[](https://github.com/koajs/koa/blob/master/lib%2Fapplication.js#L169)

example:

```js

console.log(a);

```
it will threw err,500,a undefined, in koa-v1, this err will caughted by koa, but I need caught this exceptions and write log file.

At present, my solution is add log code to koa/lib/context.js onerror method

**Comment by wfsovereign** [comment]
Is there anything else I didn't say clear？
my english is not very good , I try my best to explain it.

**Comment by gyson** [comment]
@wfsovereign Are you trying to override `app.context.onerror` ? Maybe following snippet could be helpful.

```js
const defaultErrorHandler = app.context.onerror

app.context.onerror = function (err) {
  // this check is necessary because of `onFinished(res, ctx.onerror)`
  if (err == null) return; 
  //  
  // log it here
  //
  return defaultErrorHandler.call(this, err)
}
```

**Comment by wfsovereign** [comment]
@gyson cool, I can override it in my project!
I give it a try.
@tj @alsotang @gyson thank you very much.

**Comment by wfsovereign** [comment]
@gyson your method request me have deep understanding for koa framework, but I contact with koa for two weeks and after a series of trying to less successful, so I decided to this issues and further to learn koa framework.
