### ISSUE TITLE
Create migration docs from Koa 1.x to 2.x

### ISSUE THREAD

**Issue by pensierinmusica** [koajs/koa#621]
Refers to https://github.com/koajs/koa/issues/523#issuecomment-164284106

Are there any docs about:

- What is being changed from 1.x to 2.x, why, and what is the performance difference
- How 2.x works
- What are best practices to convert from 1.x to 2.x
- What modules support 2.x

Also, @tj how reliable is Koa 2.0.0-alpha.3 to be used in production?

Thanks!

**Comment by alqu** [comment]
@pensierinmusica I am using it since a couple of weeks now.
It is pretty stable. I use it in a "near production" environment and plan to release the final version in 1 month.

No problems so far. I had to write a little module for basic auth (well, 10loc only), a modified logger with winston and my own error handler and that's it.
The rest - mongoose, koa-bodyparser@3.0.0, koa-router@7.0.0 and koa-serve-static work nicely together with koa 2.0

Just my 2 cents.

**Comment by pensierinmusica** [comment]
@alqu thanks for the feedback!

> I had to write a little module for basic auth (well, 10loc only), a modified logger with winston and my own error handler and that's it.

Does Koa 2.x still provide this default error handler?

```js
app.on('error', function(err){
  log.error('server error', err);
});
```

Cheers!

**Comment by alqu** [comment]
well, it looks a bit different:

```js
app.on('error', function (err, ctx) {
  if (err == null) return

  if (!(err instanceof Error)) err = new Error(`non-error thrown: ${err}`)

  if (ctx) {
    // do some stuff here.
    let msg = {} // whatever you want to respond with
    // finally, make sure you finish properly:
    msg = JSON.stringify(msg)
    ctx.res.statusCode = err.status
    ctx.res.length = Buffer.byteLength(msg)
    ctx.res.end(msg)
  }
})
```

**Comment by alqu** [comment]
But... yeah, you could write this one. But you should also react on Errors... like NOT going on and just finishing the response.

**Comment by pensierinmusica** [comment]
@alqu of course ;) That was just copy / paste from Koajs official docs, what I wondered is if the 'error' event handler was still there in Koa 2.x, which you confirm. Great!

**Comment by jonathanong** [comment]
i updated the description here: https://github.com/koajs/koa/issues/533#issuecomment-166740065

closing this issue - any future comments should go in that thread :)
