### ISSUE TITLE
Unexpected handling of errors with expose=true

### ISSUE THREAD

**Issue by cmbankester** [koajs/koa#630]
I recently came across a situation where I wanted to throw an error from within a koa middleware and have it both exposed to the client and conditionally logged to the console. My method for handling this was:
* Add a middleware high up the stack for catching errors and conditionally passing them to `app.emit('error', ...)`:
  ```javascript
  app.use(function *error(next){
    try {
      yield next;
      if (404 == this.response.status && !this.response.body) this.throw(404);
    } catch (err) {
      this.status = err.status || 500;

      // application
      (err.log !== false) && app.emit('error', err, this);

      // accepted types
      switch (this.accepts('text', 'json')) {
        case 'text':
          this.type = 'text/plain';
          if (env === 'development') this.body = err.message
          else if (err.expose) this.body = err.message
          else throw err;
          break;

        case 'json':
          this.type = 'application/json';
          if (env === 'development') this.body = { error: err.message }
          else if (err.expose) this.body = { error: err.message }
          else this.body = { error: http.STATUS_CODES[this.status] }
          break;
      }
    }
  });
  ```
* Create an `Error` object and give it `err.expose = true` and `err.log = true` (or `err.log = false` in the instance where the error should not be logged) from within another middleware and throw it

This led me to discover that if an error `err` is marked with `err.expose = true`, Koa's default `app.on('error', ...)` handler will ignore it, as per this line: https://github.com/koajs/koa/blob/master/lib/application.js#L173

Does it really make sense for the default error handler to not log errors that are exposed to the client?

**Comment by tj** [comment]
I think it's reasonable for a default, doesn't really matter I suppose. It's definitely ideal to use something custom or like koajs/logger for "real" logging

**Comment by cmbankester** [comment]
True, and in fact I am using koajs/logger in this instance, but that's just for logging the request/response. I am using `app.emit('error', ...)` for logging the error though (which I thought was the standard technique for handling errors?).

**Comment by tj** [comment]
Ah sorry you're right, I forgot we re-throw there. I guess the difference is that the exposed ones are supposed to represent user errors, so they should be displayed somewhere in UI or in the response

**Comment by cmbankester** [comment]
Yeah, no problem, I just wanted to bring it up here since it took me off guard. Definitely not something that needs to be changed within the code, since as you said, it's reasonable for a default. We should, however, document the currently-undocumented `err.expose` (and [`err.silent`](https://github.com/koajs/koa/blob/master/lib/application.js#L174)) functionality somewhere in the docs.

The fix I've landed with here is to override the default error handler via:
```javascript
app.on('error', log);
```

Such that any error which passes through `app.emit` will always land in the log.

**Comment by jonathanong** [comment]
@cmbankester we would love a doc PR!
