### ISSUE TITLE
Cannot set this.body inside an Async call

### ISSUE THREAD

**Issue by isikfsc** [koajs/koa#632]
I am trying to make an async call to a database in my route function, and I see the error:
`throw new Error('Can\'t remove headers after they are sent.');`
It seems koa itself sets the `this.body` synchronously. How to prefer that until ı can set it with the returned from query result. Should I use a third-party defer tool. If so this is a common case for an http server, shouldn't there be a built in correct way to achieve such purposes?
```js
function x(cb) {
		g.V("Humphrey Bogart").In("name").All(function(error, result) {
			if(error){
				console.log(error);
				
			} else {
				console.log("from query callback:", result);
				cb(result);
				//app.use with url match
			}
		});
};

publicRouter.get('/x', function* (next){
	x((result)=>{
            console.log("from route:", result);
            this.body = result;
 });
});
```
Here a use yield and it works for that library. a query to Postgresql with pg-promise:
```js
publicRouter.get('/db1', function* (next){
	var result = yield db.query('select * from news');
	if(!result){
		console.log(result);
	}
	console.log(result);
	this.body = result;
});
```
But here yield does not work to set `this.body`, which is leaved `undefined`. This one uses another library. A query to cayley db with cayley-node:
```js
function* x() {
		g.V("Humphrey Bogart").In("name").All(function(error, result) {
			if(error){
				console.log(error);
				
			} else {
				console.log("from query callback:", result);
				return result;
			}
		});
};

publicRouter.get('/x', function* (next){
	var result = yield x();
	if(!result){
		console.log(result);
	}
	console.log(result);
	this.body = result;
});
```

**Comment by juliangruber** [comment]
updated your issue to be more readable

**Comment by isikfsc** [comment]
:) I was just update it too. adding github flavour to my markup.

**Comment by juliangruber** [comment]
the problem with the first example is that your `function*(next){}` function finishes before `this.body` is set.

The flow of events is

```js
publicRouter.get('/x', function* (next){
    // 1)
    x((result)=>{
            console.log("from route:", result);
            this.body = result;
            // 3) this is where you're really done
   });
   // 2) now koa thinks you're done
});
```

Your idea to yield x was on the right track, however your `function* x` still uses callbacks internally. You need to make the `g` library promise/thunk/generator compatible. Either find a version of it that already supports one of the before mentioned, or wrap it's call like so:

```js
function* x() {
        const query = g.V("Humphrey Bogart").In("name");
        const All = thunkify(query.All.bind(query));
        var result = yield All();
        console.log("from query callback:", result);
        return result;
};
```

**Comment by isikfsc** [comment]
In the meantime I have done this, and it works:
```
publicRouter.get('/x', function* () {
	yield g.V("Humphrey Bogart").In("name").All((error, result) => {
		if(error){
			console.log(error);
			
		} else {
			console.log("from query callback:", result);
			this.body = result;
		}
	});    
});
```

thanks for responses. Should this issue be closed?

**Comment by juliangruber** [comment]
ah, so .All already returns a promise. try

```js
var result = yield g.V('...').In('...').All;
this.body = result;
```

**Comment by isikfsc** [comment]
@juliangruber you take them just from my mouth, :), thank you very much. yours precedes again.

**Comment by juliangruber** [comment]
glad to help!

**Comment by lourd** [comment]
Hi @isikfsc! I'm glad you found an answer to the problem you were facing and learned more about the API you were trying to use. I'd like to ask why you didn't ask your question on StackOverflow (using the #koa tag) or one of the other [community](https://github.com/koajs/koa#community) mediums outlined in the README.

I understand that it's difficult to get an answer on StackOverflow sometimes and that it's tempting to go straight to the maintainers. After all, they're the ones who built it, they know best how to help you, right? Unfortunately when we use GitHub issues as a support avenue instead of bug tracking, feature requests, and other development-specific issues, it makes it harder to maintain and support open source projects.

It's not a single email that makes the difference. I don't mean to harp on you specifically — it's an obstacle that all open source projects face. I just want to point it out and for you to think about it.

**Comment by isikfsc** [comment]
Hi @lourd.
I agree with your remarks, I also would not want to spend the time of the maintainers that bring us awesome tools.
I was not very well aware of the other community channels to ask questions on, my mistake.
On SO, I face the difficulty you mentioned. if not tempted I felt repelled from the place I am familiar asking questions, SO, to the some sort of second place I am best aware of for issues.

After all this, there was in the question, if you remember, my impression of "this should be in other way". So if it was correct some maintainer related action should be taken. That is the big why of I carried my investigation here. But it turns out my mistake. The problem was in the **scope** of my **arrows**, now I am aware.

**Comment by vitaly-t** [comment]
@isikfsc In the future, if the same issue happens in a different context, you can use a regular callback function on the top level, while wrapping the implementation into a task with generators, if you want to use generators that is:

```js
publicRouter.get('/db1', function (next) {
    db.task(function * t() {
            return yield t.query('select * from news');
        })
        .then(data=> {
            this.body = data;
        })
        .catch(error=> {
            console.log(error);
            this.body = error; // or something else;
        });

});
```

**Comment by isikfsc** [comment]
@vitaly-t thanks.
If I do not use generators, and use promise signature here, (and for future maintenance convenience if koa will switch to that style ,too), with a normal function again;
```
publicRouter.get('/db1', function (next) {
    var self = this;
    db.query('select * from news')
        .then(data=> {
            self.body = data;
        })
        .catch(error=> {
            console.log(error);
            self.body = error; // or something else;
        })
});
```
no task used. Is that correct, will it set the `ctx.body` before koa does? As was the case @juliangruber above.

My point is to be able to set the `this.body` and anything related to koa's `ctx` inside a Promise `then`or `catch`. Otherwise it turns out to be inconvenient, doesn't it, for route handlers in web apps?

**Comment by vitaly-t** [comment]
@isikfsc that looks fine also.

**Comment by isikfsc** [comment]
Later I have tested it does not work.

Somehow koa sets the `ctx.body` itself no matter I use arrow callback functions to allow `this` to be koa handler's `this`, i.e. `ctx`, or carry koa `ctx` inside callback functions via assigning a variable, `self`, to `this`, koa `ctx`, outside callbacks.
I think I must open a question on SO. How to access `request` or `response` objects inside a callback function in a route handler, without `yield`ing?
