### ISSUE TITLE
Newbie question: how to start with Koa 2?

### ISSUE THREAD

**Issue by romu70** [koajs/koa#633]
Hi,
I'm an almost total newbie in web dev (not in computing though). I've followed some tutorials on Koa 1.x and I really like it. I'm not in a hurry, and I've so much to learn that even if Node doesn't currently support await/async, I can start my project with Koa 2 and see how things are going. Newbie question: as it is not released, it's not available through NPM, so how can I install it?

Thanks.

**Comment by fl0w** [comment]
You can, try:
```bash
$ npm install --save koa@next
```

**Comment by romu70** [comment]
Perfect, thanks a lot, didn't know the way to use NPM to install specific branches. (Really so much to learn!). Thanks again.

**Comment by romu70** [comment]
Just reopened because of another stupid question.

From what I've read so far, one can write and run a Koa 2 app, without any specific other tool like Babel, as soon as the code doesn't contain any async or await keyboard. Am I right or wrong?

**Comment by juliangruber** [comment]
Just try it ;)

**Comment by romu70** [comment]
Why closing the issue? I'm posting because I'm trying indeed and I get this exception:

```
.../node_modules/koa/lib/application.js:38
  constructor() {
             ^

TypeError: Class constructors cannot be invoked without 'new'
    at Application (.../node_modules/koa/lib/application.js:38:14)
    at Object.<anonymous> (/home/romu/git/iamacc/index.js:2:11)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
``` 

I run Node 5.3.0.

**Comment by juliangruber** [comment]
It's now `var app = new Koa();`

**Comment by romu70** [comment]
Ok thanks, I'm a bit less stupid, but more important a bit more familiarized with Node stack traces. Thanks a lot. Really helpful for me.

**Comment by rajinder-yadav** [comment]
You should ask how-to questions on stackover! Leave the issues for reporting bugs.
