### ISSUE TITLE
Mistake in the koa v2 examples

### ISSUE THREAD

**Issue by dantman** [koajs/koa#639]
The koa v2 example used in [the README](https://github.com/koajs/koa#v2-alpha) and the [Koa 2.0.0 issue](https://github.com/koajs/koa/issues/533#issue-111732707) looks wrong.

```js
// uses async arrow functions
app.use(async (ctx, next) => {
  try {
    await next() // next is now a function
  } catch (err) {
    ctx.body = { message: err.message }
    ctx.status = err.status || 500
  }
})

app.use(async ctx => {
  const user = await User.getById(this.session.userid) // await instead of yield
  ctx.body = user // ctx instead of this
})
```

`this.session.userid` is used, but it's used inside of an arrow function, where `this` should refer to the global object, not something related to the request.

**Comment by jonathanong** [comment]
Oops yeah. Should be ctx. Would you like to make a PR? :)

**Comment by tejasmanohar** [comment]
#641 merged, issue should be closed.

**Comment by tejasmanohar** [comment]
oh, i guess i said "solves" not "resolves", [bleh](https://help.github.com/articles/closing-issues-via-commit-messages/)
