### ISSUE TITLE
render handlebars

### ISSUE THREAD

**Issue by EasonWang01** [koajs/koa#642]
I'm new to here,how to render handlebars without middleware?Is code below works?

```
const handlebars = require('handlebars')
app.use((req, res) => {
  const locals = req.locals // get template locals 
  locals.cache = process.env.NODE_ENV === 'production' // set the template cache
  const html = handlebars.renderFile('templates/home.handlebars', locals) // render the template
  res.setHeader('Content-Length', Buffer.byteLength(html))
  res.setHeader('Content-Type', 'text/html; charset=utf-8') // set the content type header
  res.end(html) // send the response
})
```

**Comment by coderhaoxin** [comment]
There are multi middlewares for this, such as:

https://github.com/jwilm/koa-hbs
https://github.com/dominicbarnes/koa-handlebars
https://github.com/queckezz/koa-views

Why you need render handlebars without middleware?

**Comment by jonathanong** [comment]
^ that code is also for express, not koa

**Comment by jonathanong** [comment]
you could also try stackoverflow, etc. to learn and ask.
