### ISSUE TITLE
404 with `await ctx.render('404')` has `application/json` content type

### ISSUE THREAD

**Issue by niftylettuce** [koajs/koa#646]
this is because the body is empty per https://github.com/koajs/koa/blob/971115cfbd970f97a79df1a02a4ef7f980170773/lib/response.js#L135

so the only way to fix is to not only set `ctx.throw(404)` but to also reset the content type when you're sending a 404 error

we should maybe account for `404` errors here before we unset everything?

**Comment by jonathanong** [comment]
what is `ctx.render()`?

**Comment by niftylettuce** [comment]
for koa@next when I have error middleware like this at the top of my file, I have to explicitly say `ctx.type = 'html';` for example...  (maybe I'm doing it wrong?) -- this was from code I did the other day

```js
// initialize try/catch error handling right away
// adapted from: https://github.com/koajs/onerror/blob/master/index.js
// https://github.com/koajs/examples/issues/20#issuecomment-31568401
app.use(async (ctx, next) => {

  try {
    await next();
    if (ctx.status === 404)
      ctx.throw(404);
  } catch (err) {

    if (err.name) {
      switch (err.name) {
      case 'ValidationError':
        err.status = 400;
        if (err.errors) {
          let errors = _.map(
            Object.values(err.errors),
            (e) => {
              switch (e.kind) {
              case 'required':
                return `${_.upperFirst(e.path)} is required`;
              default:
                return _.trimEnd(e.message, '.');
              }
            }
          ).join(', ');
          err.message = `${err.message}: ${errors}`;
        }
        break;
      }
    }

    ctx.status = err.status || 500;
    ctx.body = Boom.create(err.status, err.message).output.payload;

    app.emit('error', err, ctx);

    let type = ctx.accepts(['text', 'json', 'html']);

    if (!type) {
      ctx.status = 406;
      ctx.body = Boom.notAcceptable().output.payload;
    }

    switch (type) {
    case 'html':
      if (ctx.status === 404) {
        ctx.type = 'html';
        // https://github.com/koajs/koa/issues/646
        await ctx.render('404');
      } else {
        ctx.flash('error', err.message);
        ctx.redirect('/');
      }
      break;
    case 'json':
      ctx.body = JSON.stringify(ctx.body);
      break;
    default: // case 'text':
      ctx.type = 'text';
      ctx.body = JSON.stringify(ctx.body, null, 2);
      break;
    }

  }

});
```

**Comment by niftylettuce** [comment]
see how i use `ctx.render` in that block -- it's my nunjucks rendering via https://github.com/hanai/koa-nunjucks-promise

**Comment by niftylettuce** [comment]
also for reference, `Boom` is https://github.com/hapijs/boom

**Comment by jonathanong** [comment]
yeah i always throw the error and let upstream error handlers handle those pages. i also don't set headers unless i know the status code isn't gonna be an error, which makes things a little more robust, but is more annoying to code.

i also don't do content negotiation anymore :P hard to cache

**Comment by niftylettuce** [comment]
how the heck do we do this then?  for example: https://github.com/niftylettuce/ratelimit/blob/master/src/index.js#L67-L74

**Comment by jonathanong** [comment]
you'd have to remove the headers yourself. :(

**Comment by niftylettuce** [comment]
how do I do that? @jonathanong very confused here...

**Comment by jonathanong** [comment]
https://github.com/koajs/koa/blob/fcacb352208115e60fffe145394f904743dfa8c3/lib/context.js#L121

hacks galore!

unless you want to make a PR for https://github.com/koajs/koa/issues/571 :)

**Comment by niftylettuce** [comment]
@jonathanong how do we override that `onerror`, via `app.onerror = fn`?  is there any examples of someone doing this?

**Comment by jonathanong** [comment]
just doing `app.context.onerror =` should work, but `onerror` should only be used when extremely necessary.

instead, this and similar middleware should be relying on an upstream error handler like:

```js
app.use(function* (next) {
  try {
    yield next
  } catch (err) {
    // handle error
    this.status = err.status || 500
    this.body = { message: err.message }
  }
})
```

but then you have to do special cases for middleware like that rate limit one... which is why it's better just to have a public API

**Comment by jonathanong** [comment]
oh shit. i read the code wrong. i thought you were setting that body after `await next` but you're early returning.

what's the issue?

**Comment by niftylettuce** [comment]
the issue is that headers are removed from the request on an error, when I don't want them to be

**Comment by jonathanong** [comment]
only if `onerror` handles it. if you make your own middleware, you can do wahtever you want.

**Comment by PlasmaPower** [comment]
Does c826467 resolve this?

**Comment by jonathanong** [comment]
yes https://github.com/koajs/koa/commit/c82646756053395e463cad059ed776611a99c1fd should resolve this
