### ISSUE TITLE
A minimal boilerplate of koa v2.

### ISSUE THREAD

**Issue by geekplux** [koajs/koa#648]
https://github.com/geekplux/koa2-boilerplate

This is a minimal boilerplate of koa v2.
It may be a good try and example for koa2 project. Welcome PR :)

#### Dependencies

- Watcher and hot-reload: [nodemon](http://nodemon.io/)
- Test:
    + [mocha](https://mochajs.org/)
    + [should](https://github.com/tj/should.js/)
    + [supertest](https://github.com/visionmedia/supertest)
- Build: [babel](http://babeljs.io/)
    + tools: babel-cli, babel-register
    + presets: babel-preset-es2015, babel-preset-es2015-node5, babel-preset-stage-3
    + plugins: babel-runtime, babel-plugin-transform-runtime
- *Lint*: [standard](https://github.com/feross/standard)
    + add `babel-eslint` for ES6/ES7 support

#### Reference

#533 
#596

**Comment by menems** [comment]
Hi, I don't understand why everyone wants to add all babel-stage-3 for koa, the only things you need in koa context for v2 is to add async/await so the only package you need is:

```javascript
{
    plugins: [
        'transform-async-to-generator',
        'syntax-async-functions'
    ]
}
```

I understand to add all other stuff in project when you use babel, but in koa context it is not necessary, no?

**Comment by tj** [comment]
feel free to add it to the wiki!

**Comment by geekplux** [comment]
Thanks.
