### ISSUE TITLE
Unable to extend the app's context in Koa@2

### ISSUE THREAD

**Issue by aj1310** [koajs/koa#652]
Trying to extend the context of the application since migrating to koa@2 throws this error:

```
TypeError: Cannot set property 'property_name' of #<Object> which has only a getter
```

A small example code
```javascript
import Koa from 'koa';

const app = new Koa();
app.context.host = process.env.HOST || '0.0.0.0';
app.context.port = process.env.PORT || 8080;
```

**Comment by menems** [comment]
Hi,

The host property on the context is the host of the request object. not the host of your running server instance. 

if you want to change your host:port you have to change it on the http listen function.

**Comment by AJ-1310** [comment]
It was just as an example that I picked the host port here. My bad. But any other parameters throws an error when trying to set something to context.

**Comment by dead-horse** [comment]
`context.host` a `setter/getter`, so if you want to override it, try:

```js
Object.defineProperty(app.context, 'host', {
 get: function() {
   return '0.0.0.0'
 },
});
```

**Comment by tejasmanohar** [comment]
https://github.com/koajs/koa/pull/605

**Comment by jonathanong** [comment]
would es6 classes even solve this issue?

**Comment by PlasmaPower** [comment]
I don't think so, as delegate is still used for Request and Response.

**Comment by jonathanong** [comment]
added docs here: https://github.com/koajs/koa/commit/e61d54565b6bfe1810ea41afa702db8f9c06691a

make a PR if you have any suggestions!

**Comment by duanchongchong** [comment]
for(var i=0;i<100;i++){
console.log(i)
}

**Comment by xiaoxin999** [comment]
6666666
