### ISSUE TITLE
Getting EPIPE error when spamming refresh, is this normal?

### ISSUE THREAD

**Issue by Gacnt** [koajs/koa#655]
If I click the home button repetitively I end up getting spammed with this error:
```
server error { [Error: write EPIPE]
  code: 'EPIPE',
  errno: 'EPIPE',
  syscall: 'write',
  address: undefined } { request:
   { method: 'GET',
     url: '/javascripts/bundle.js',
     header:
      { host: 'localhost:3000',
        connection: 'keep-alive',
        accept: '*/*',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36',
        referer: 'http://localhost:3000/',
        'accept-encoding': 'gzip, deflate, sdch',
        'accept-language': 'en-US,en;q=0.8',
        cookie: '',
        range: 'bytes=83220-83220',
        'if-range': 'Thu, 28 Jan 2016 09:52:33 GMT' } },
  response:
   { status: 200,
     message: 'OK',
     header:
      { 'last-modified': 'Thu, 28 Jan 2016 09:52:33 GMT',
        'content-length': '757382',
        'cache-control': 'max-age=0',
        'content-type': 'application/javascript; charset=utf-8' } },
  app: { subdomainOffset: 2, proxy: false, env: 'production' },
  originalUrl: '/javascripts/bundle.js',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
```

First time I've seen this, I'm using [Koa-Generator](https://github.com/base-n/koa-generator) and I'm using `Koa2`, not sure if this is normal or what, but any information would be great, or where I could start to debug this, I can clearly see that it's `/javascripts/bundle.js` which is generated from `webpack`, I don't seem to get this error on any other file so I don't know why it's just my bundle.js.

**Comment by juliangruber** [comment]
that error happens when you try to write to a socket that has already been closed. looks like the code responsible for your bundle route isn't taking that fact into account.

**Comment by Gacnt** [comment]
@juliangruber Thanks for the reply, so are you saying that the middleware static parser I'm using is to blame for this? Or my own sockets?

**Comment by juliangruber** [comment]
you're not using koa there, not sure how it relates
