### ISSUE TITLE
Unable to set statusText via this.throw(status, message)

### ISSUE THREAD

**Issue by gios** [koajs/koa#656]
I was trying to sent statusText via **this.throw(status, message)**, but as we can see message has not been replaced. I attached some code to this issue.
```javascript
router.post('/authenticate', function *(next) {
    let email = this.request.body.email
    let password = this.request.body.password

    let foundUser = yield knex('users').where({
      email,
      password
    })
    .first('username', 'email', 'id')
    .catch((err) => {
      logger.error(err)
    })

    if (!foundUser) {
      this.throw(404, 'Wrong user or password')
    }

    let token = jwt.sign(foundUser, SHARED_SECRET, { expiresIn: 60 * 5 });
    this.body = { id_token: token }
    yield next
  })
```
![untitled](https://cloud.githubusercontent.com/assets/6967294/12829493/19ce7426-cb93-11e5-99c4-4236dcad910e.png)

**Comment by jonathanong** [comment]
you wanna set your own error handler middleware that formats the error however you'd like. the default handler will not set the status text for you.

**Comment by gios** [comment]
Thank you for explanation.

**Comment by OKNoah** [comment]
I also had this issue. It works on one project, but not another. No middleware involved. Was there a change between versions?
