### ISSUE TITLE
Flush headers option?

### ISSUE THREAD

**Issue by ChALkeR** [koajs/koa#657]
I know that this _could_ cause problems, e.g. if someone tries to add headers after those were flushed, but that is a user error.

Sample code:
```javascript
	api.use(route.get('/myendpoint', async ctx => {
		ctx.type = 'text/plain; charset=utf-8';
		ctx.set('My-Queue-Size', queue.size);
		ctx.status = 200;
		// I want to flush headers here
		ctx.body = (await my_method()).stdout;
	}));
```

It would be useful if there was an convenient way to flush the headers before the `await` is fullfilled. Currently, that is impossible due to `respond` being a noop if headers were already sent: [lib/application.js#L184](https://github.com/koajs/koa/blob/2.0.0-alpha.3/lib/application.js#L184).

It's possible to work-around that by creating a PassThrough stream:
```javascript
	api.use(route.get('/myendpoint', async ctx => {
		ctx.type = 'text/plain; charset=utf-8';
		ctx.set('My-Queue-Size', queue.size);
		ctx.status = 200;
		ctx.body = new stream.PassThrough();

		let child;
		let closed = false;
		ctx.res.on('close', () => {
			closed = true;
			if (child) child.kill('SIGKILL');
		});

		setImmediate(async () => {
			ctx.res.flushHeaders();
			child = await my_method();
			child.on('exit', () => { child = undefined; })
			if (closed) child.kill('SIGKILL');
			child.stdout.pipe(ctx.body);
		})
	}));
```

But that doesn't look very nice.

**Comment by jonathanong** [comment]
what's the goal here? if you have no upstream middleware/logic then the headers will be flushed pretty quickly. 

i also believe we added a flag to allow this, but i don't remember...

**Comment by jonathanong** [comment]
oh it's just https://github.com/koajs/koa/blob/89f539724e7522ebf00e4db3a99b2a6617e6d468/lib/application.js#L190

would calling the `respond()` function early work?

**Comment by ChALkeR** [comment]
> what's the goal here? if you have no upstream middleware/logic then the headers will be flushed pretty quickly.

The goal is to send headers before `await` completes. It could wait for 10 seconds, for example, but there is no reason in delaying the headers.

> `if (false === this.respond) return;`

Does not look like an good option, that requires interacting with res manually, which is btw documented as not supported.

> would calling the `respond()` function early work?

No, it won't, `ctx.body` is not set yet. It would also call `res.end()`.

**Comment by jonathanong** [comment]
sorry keep pressing the gray button for some reason.

well i'm not against having an API like `.flushHeaders()` that throws if you try to do `.set()` after it's called. what are your thoughts on an API?

**Comment by ChALkeR** [comment]
`ctx.flushHeaders()` that calls `ctx.res.flushHeaders()` should be good, though the flag is now called `.headerSent` (note the header/headers difference, btw, why is that not called `.headersSent`?).

It should set `.headerSent` to true, of course (it would do that automatically), and it should allow to set `ctx.body` later and actually get that sent to the client.

The main point where this is blocked now is [lib/application.js#L184](https://github.com/koajs/koa/blob/2.0.0-alpha.3/lib/application.js#L184) — response does not do anything if the headers were already sent. That should be somehow fixed, for example by adding an own flag instead of relying on `.headersSent`. That came in https://github.com/koajs/koa/commit/9fe483ca767b64de3e9b9e2c78b7bfaf420861c2 and includes a testcase.

Any attempt from the user to set headers afer those were already sent should cause an error (I think it already does).

Any automated header assigments from the koa side (e.g. content-length) should happen either before the headers were flushed (if possible) or not happen at all.

**Comment by jonathanong** [comment]
i think @tj said something about it being the "header" vs. "headers", but that's semantics. i have no idea idea which one is right.

yes, i'd set a separate flags for `this.flushHeaders()` since `res.headersSent` can be called outside of Koa.

> Any automated header assigments from the koa side (e.g. content-length) should happen either before the headers were flushed (if possible) or not happen at all.

this means that we would also infer some headers like `content-length`. during the `.flushHeaders()` call, meaning it will come with some refactoring.

**Comment by jonathanong** [comment]
@koajs anyone have opinions?

anyone wanna try a PR? otherwise i'll try push something up this weekend

**Comment by tj** [comment]
It's a "header" with many "header fields"

**Comment by jonathanong** [comment]
solved here https://github.com/koajs/koa/issues/667
