### ISSUE TITLE
How to stop server, mid process?

### ISSUE THREAD

**Issue by ElegantScripting** [koajs/koa#659]
Hi, when using webpack's HMR, and changing the server's port, it leaves the previous Koa server still in tact on another port.

How can I stop the Koa server mid-stage, allowing HMR to restart another one?

Is there a `koa.close` like there is a `server.close`?

**Comment by juliangruber** [comment]
this should do the trick:

```js
var destroyable = require('server-destroy');
var http = require('http');

var server = http.createServer(app.callback());
server.listen();
destroyable(server);

// then
server.destroy();
```

for more questions like this, please post on stackoverflow because it's more about usage than bugs or improvements to koa.

**Comment by metrue** [comment]
@juliangruber 's solution  totally works, but here is a simpler one.

```
  const app = new Koa();
  const _server = app.listen(3000);  // start
  

 _server.close();   // stop

```

**Comment by juliangruber** [comment]
this won't close when there are still open connec tions, the destroy method above really enforces the server to close, no matter what

**Comment by corysimmons** [comment]
Neither of these solutions work when using chokidar to reload a `server.js` on file changes.

**Comment by rbecheras** [comment]
Both works in a after hook in mocha unit tests
