### ISSUE TITLE
app as middleware

### ISSUE THREAD

**Issue by guileen** [koajs/koa#660]
I can use `app.callback()` to get an regular node style http handler, it make possibility of integrate koa app with regular node http app in one process.

But there is no way to integrate an koa app into another koa app.

If I use below code, it can't handle correctly, parent app will not wait child app handle complete and throw 404 Not Found.
```
var handler = appv1.callback()
app.use(async(ctx, next) => {
    if(ctx.url.startsWith('/v1')) {
       handler(ctx.req, ctx.res)
    } else {
       await next()
    }
})
```

I wish I can do this:

```
app.use(async(ctx, next) => {
    if(ctx.url.startsWith('/v1')) {
       await appv1.middleware()
    } else {
       await next()
    }
})
```

**Comment by fl0w** [comment]
Just leaving this here;

This could be solved by using user-land solutions, such as [koa-router](https://github.com/alexmingoia/koa-router).

**Comment by guileen** [comment]
I got the solution

```
appv1Middleware = compose(appv1.middleware)
app.use(async(ctx, next) => {
    if(ctx.url.startsWith('/v1')) {
       await appv1Middleware(ctx, next)
    } else {
       await next()
    }
})
```
