### ISSUE TITLE
Cant remove headers after they are sent

### ISSUE THREAD

**Issue by christiansakai** [koajs/koa#662]
Already googled a lot, still confused

My suspicion is with my middleware

```
// isAuthenticated middleware
import koaJwt from 'koa-jwt';
import compose from 'koa-compose';
import convert from 'koa-convert';
import User from '../api/user/user.model';

const validateJwt = convert(koaJwt({
  secret: config.secrets_session
}));

/**
 * Attaches the user object to the request if authenticated
 * Otherwise returns 403
 */
export function isAuthenticated() {
  function authentication(ctx, next) {
    // allow access_token to be passed through query parameter as well
    if (ctx.query && ctx.query.hasOwnProperty('access_token')) {
      ctx.headers.authorization = `Bearer ${ctx.query.access_token}`;
    }
    
    validateJwt(ctx, next);
  }

  function attachUserToContext(ctx, next) {
    User.findById(ctx.state.user._id)
      .then(user => {
        if (!user) {
          return ctx.status = 401;
        }

        ctx.state.user = user;

        next();
      })
      .catch(err => next(err));
  }
 
  return compose([authentication, attachUserToContext]);
}
```

```
// koa router
router.get('/me', auth.isAuthenticated(), controller.me);
```

```
// user controller

function respondWithResult(ctx, statusCode = 200) {
  return function(entity) {
    ctx.status = statusCode;
    ctx.body = entity;
  };
}

/**
 * Get my info
 */
export async function me(ctx, next) {
  const userId = ctx.state.user._id;

  try {
    const me = await User.findOne({ _id: userId }, '-salt -password');
    
    respondWithResult(ctx)(me);
  } catch (err) {
    console.log(err);
    handleError(ctx)(err);
  }
}
```

It throws the error `Can't remove headers after they are sent`.  Any idea?

**Comment by jonathanong** [comment]
you probably have to `return validateJwt(ctx, next);`

**Comment by christiansakai** [comment]
tried that, didn't work :(

**Comment by lourd** [comment]
Instead of including the `validateJwt` function inside of `isAuthenticated` you want to include it in in the composition.

```js
return compose([authentication, validateJwt, attachUserToContext])
```

Friendly reminder that GitHub issues are for bugs, not support questions :wink:

**Comment by christiansakai** [comment]
@lourd thanks for the suggestion.  I'll try your suggestion.

yeah I realized that, should've posted this on stackoverflow, sorry for that!

**Comment by christiansakai** [comment]
@lourd still does not work :(

**Comment by lourd** [comment]
`attachUserToContext` also looks problematic. You're missing two return statements. Middleware functions are expected to return a Promise, you're not returning anything. I would guess that by the time your `.then` function gets called the Koa middleware stack has already finished its process, responding with a 404 or something.

```js
function attachUserToContext(ctx, next) {
    **return** User.findById(ctx.state.user._id)
      .then(user => {
        if (!user) {
          return ctx.status = 401;
        }

        ctx.state.user = user;

        **return** next();
      })
      .catch(err => next(err));
  }
```

And you're also using the `next` function to handle errors like Express. This is Koa, throw that bitch. Omit the `.catch` so the returned Promise is a rejected one.

If you're using async-await, and it looks like you are, then I would write the function like this:

```js
async function attachUserToContext(ctx, next) {
  const user = await User.findById(ctx.state.user._id)
  if ( !user ) {
    ctx.status = 401
    return;
  }
  ctx.state.user = user
  return next()
}
```

Omitting a `try-catcy` block around `User.findById` means that if it _does_ throw it will get caught by the Koa-wide error handler, which I believe by default returns a 500 status code and logs the error.

**Comment by christiansakai** [comment]
@lourd thanks for the suggestion. It is still throwing the same error. I'll update more

**Comment by lourd** [comment]
make sure to also `return next()` from the `isAuthenticated` function

**Comment by christiansakai** [comment]
@lourd finally works!! the `return next()` fixes it! thank you

**Comment by lourd** [comment]
:smile_cat: :tada: You're welcome :+1:
