### ISSUE TITLE
Request .get should return undefined instead of '' as falsy value for missing headers.

### ISSUE THREAD

**Issue by brownstein** [koajs/koa#663]
Currently, Koa's request object returns an empty string instead of undefined for undefined headers. I'm requesting that this change to undefined to avoid confusion for greater compatibility with Express's convention.

This change is primarily motivated by issue #30 in [koa-oauth-server](https://github.com/thomseddon/koa-oauth-server), a module which adapts [node-oauth2-server](https://github.com/thomseddon/node-oauth2-server) for Koa. Node Oauth2-Server checks against an undefined literal, causing a false positive when encountering an empty string. While I understand that it is not Koa's responsibility to support 3rd-party modules, I believe that this change has a low level of risk and makes Koa more usable in general in addition to solving this integration issue.

**Comment by jonathanong** [comment]
^ see https://github.com/koajs/koa/pull/664#issuecomment-189978557

**Comment by brownstein** [comment]
Closing this, as it is arguably a potentially breaking change.

**Comment by PlasmaPower** [comment]
@brownstein doesn't this still apply to Koa 2?

**Comment by PlasmaPower** [comment]
An idea if we don't want to make it breaking: add an argument `fallbackValue` which is the value that it falls back to. That argument can default to `''`. You could set this to `undefined` if you want this new behavior.

**Comment by tj** [comment]
no poitn having a fallback param IMO, easy enough to just `|| v`

**Comment by PlasmaPower** [comment]
It would be used to distinguish between undefined and a blank string while still using Koa methods.

**Comment by PlasmaPower** [comment]
This option would be (in my opinion) a better version of a flag to toggle this behavior.

**Comment by brownstein** [comment]
@PlasmaPower I really like that idea, as the alternative could lead to downstream module maintainers proxying requests for compatibility.
