### ISSUE TITLE
Delegated functions destructured from ctx throw when invoked

### ISSUE THREAD

**Issue by noahlange** [koajs/koa#669]
More of a curiosity than anything, but I ran into this while attempting to destructure `redirect` from `ctx` and things exploded. Koa 2.x, no Babel, only `--harmony_destructuring` vis-à-vis node flags.

Steps to reproduce:
1. take a method assigned to the `ctx` via the `delegates` module
2. destructure the function from `ctx`
3. throws when invoked

The following will *not* throw.
1. default functions not assigned to `ctx` via the `delegates` module, in this case only `assert`
2. other functions attached to the `ctx` by a middleware
3. functions assigned to `ctx` via the `delegates` module but then bound to the `ctx`

An example application showing a bound, delegated function, a random function attached to the ctx, and a non-bound, throwing function attached by `delegates` (in this case, `redirect`).

```javascript
const Koa = require('koa');
const nunjucks = require('nunjucks');
const app = new Koa();

app.use(function(ctx, next) {
  ctx.render = nunjucks.renderString;
  ctx.redirectTo = ctx.redirect.bind(ctx);
  return next();
})

app.use(function(ctx, next) {
  const { query: { name = 'world' }, render, assert, redirect, redirectTo } = ctx;

  if (name === 'assert') {
    assert(true === false, 400, 'Assert called as expected.');
  } else if (name === 'redirectTo') {
    redirectTo('/?name=DANGER');
  } else if (name === 'redirect') {
    redirect('/?name=DANGER');
  }
  
  ctx.body = render('Hello, {{ name }}', { name });
});

app.listen(3000);
```

And the error below...
```
  TypeError: Cannot read property 'redirect' of undefined
      at proto.(anonymous function) (/Users/Noah/code/node_modules/delegates/index.js:40:24)
      at /Users/Noah/code/koa-issue/issue.js:23:7
      at dispatch (/Users/Noah/code/node_modules/koa-compose/index.js:41:32)
      at next (/Users/Noah/code/node_modules/koa-compose/index.js:42:18)
      at /Users/Noah/code/koa-issue/issue.js:8:10
      at dispatch (/Users/Noah/code/node_modules/koa-compose/index.js:41:32)
      at /Users/Noah/code/node_modules/koa-compose/index.js:34:12
      at Server.<anonymous> (/Users/Noah/code/node_modules/koa/lib/application.js:126:7)
      at emitTwo (events.js:100:13)
      at Server.emit (events.js:185:7)
```

Anyway, thank you all so much for your work with Koa! Sorry if this isn't the right place, I don't know enough about the `delegates` module internals to be able make a helpful issue there.

**Comment by jonathanong** [comment]
a i c. so it's a context binding problem. i'm not sure there's a really good solution to this problem unless we bind everything :/.

**Comment by juliangruber** [comment]
binding koa methods is one thing, but binding _everything_ on `ctx` is a whole other story.

i would suggest just using `ctx.render()` or binding yourself.

**Comment by PlasmaPower** [comment]
Minimal setup to reproduce (needs `--harmony_destructuring`):

```
const Koa = require('koa');
const app = new Koa();

app.use(function(ctx, next){
  const { redirect } = ctx;
  if (!ctx.url.match(/other/)) redirect('/other');
})

app.listen(3000);
```

I would say that this is not a bug, because not binding functions is standard practice. However, there's really no reason not to bind functions, so I guess we could? I don't think it matters to much, I'd be fine with either.

**Comment by tj** [comment]
this is just how javascript works, unless you want to bind all methods ever, this isn't a normal practice

**Comment by PlasmaPower** [comment]
Is there a reason not to bind it? If you delegate a bound function, the expected behavior is that the delegated function should be bound. As for standard practice, a lot of node standard libraries either don't use `this` (fs) or bind themselves (console).

Also, I added tests.

**Comment by tj** [comment]
I don't think it's clean to go arbitrarily binding methods for some objects and not others personally. I'd bet a good 95%+ libraries don't do it, because javascript naturally does not have bound methods, it's basically a hack but I don't think de-structuring is a good enough reason to add it.

When I see `var foo = ctx.foo` I see an unbound `foo`, unless I've explicitly done a bind in my code I would be confused otherwise.

**Comment by PlasmaPower** [comment]
The thing is, `delegate` is special in that you can't apply it to another object. The function itself is already "bound" (apply is called on it), the function that isn't bound is the delegate function itself. It doesn't make sense to call a delegated function on another delegator, so I think that it should be bound to it's delegator. I understand that it's not default JS behavior, but I think that it makes sense in this case.

**Comment by tj** [comment]
I guess to rephrase, I wouldn't expect `const { redirect } = ctx` to work, or any library to ever pre-bind, so I don't think it's an important thing to change

**Comment by PlasmaPower** [comment]
Yeah I do see your point. It becomes less clear when you pass things as callbacks, but the only thing there is `onerror` and that's already bound.

**Comment by tj** [comment]
Yea it looks like a bug unless you know that lib X is arbitrarily pre-binding for you

**Comment by dead-horse** [comment]
-1 for binding. just like you can't do something like:

```js
const event = new EventEmitter();
const {emit} = event;

emit('error', new Error());
```

we'd better follow what javascript does.

**Comment by fengmk2** [comment]
`const { query: { name = 'world' }, render, assert, redirect, redirectTo } = ctx;` look terrible...
