### ISSUE TITLE
Coding style: why sometimes have a space before curly brace while sometimes not?

### ISSUE THREAD

**Issue by mouhong** [koajs/koa#671]
Hey guys,

For example, the request.js: https://github.com/koajs/koa/blob/master/lib/request.js

For getter/setter functions, we have a space before the opening curly brace:
e.g., `get ips() {`
https://github.com/koajs/koa/blob/master/lib/request.js#L395

For other functions, we do NOT have a space before the opening curly brace:
e.g., `inspect: function(){`
https://github.com/koajs/koa/blob/master/lib/request.js#L608

This might be a trivial question, but why the inconsistency? Is there any reason for this?

**Comment by PlasmaPower** [comment]
Yeah we need a coding style document. It's pretty inconsistent right now.

**Comment by jonathanong** [comment]
if someone wants to cherry-pick the eslintrc file from v2.x to master, that would be great!

**Comment by gihrig** [comment]
The reasoning behind JS Standard Style [https://github.com/feross/standard](https://github.com/feross/standard)

From their README:
_No decisions to make. No .eslintrc, .jshintrc, or .jscsrc files to manage. It just works._

_This module saves you (and others!) time in two ways:_

_No configuration. The easiest way to enforce consistent style in your project. Just drop it in._
_Catch style errors before they're submitted in PRs. Saves precious code review time by eliminating_ _back-and-forth between maintainer and contributor._

I've managed to get over wanting _my_ style and moved on. Standard Style has worked out well for me.

**Comment by jonathanong** [comment]
not doing standard for this repo because then that would be a really ugly git diff

**Comment by PlasmaPower** [comment]
@jonathanong I wonder if there is a way to apply it per commit? In other words, rewrite all the commits to agree to standard. Rewriting all the commits in the repo doesn't seem like a good idea though. Maybe for koa v2 we could start with standard? It would be an ugly diff still, but we could merge everything into an initial commit if we want.

**Comment by PlasmaPower** [comment]
A PR adding the eslintrc from next and updating koa to agree with it would be accepted, correct? The diff might be a bit big, IDK.

**Comment by jonathanong** [comment]
was super quick because there's `eslint --fix` now. review here: https://github.com/koajs/koa/pull/672

**Comment by jonathanong** [comment]
yeah there's no way of making this diff simple. it'll be solved in v2.x, regardless.

**Comment by jonathanong** [comment]
solved in v2
