### ISSUE TITLE
response.end(body) need more parameters

### ISSUE THREAD

**Issue by mailofliujin** [koajs/koa#688]
We want to read a file and show it directly in browser.

When I use this command, the image is not showing.
this.body = fs.readFileSync('a.jpg','binary');  //any file, sometimes it's from db eg.redis

So I have added some lines to kao/lib/response.js:
  set encoding(val){
      this.encoding = val;
  },

and change kao/lib/application.js:
  if ('string' == typeof body) {
      return res.end(body, this.encoding);
  }

now it works. 
this.encoding = 'binary';
this.body = fs.readFileSync('a.jpg','binary');

**Comment by targos** [comment]
You can set the body directly as a Buffer and avoid the encode/decode steps.
Just do `this.body = fs.readFileSync('a.jpg')`

**Comment by juliangruber** [comment]
try not passing `'binary'` to fs.readFileSync. This option will return a binary string, which is way less efficient than the buffer that `fs.readFileSync` is returning by default.

Also you shouldn't use a *Sync function call inside a koa handler as it will block the whole process while the file is being read. Try using a promise fs wrapper.
