### ISSUE TITLE
Add v2 column to wiki:Home w/ an initial pass

### ISSUE THREAD

**Issue by fl0w** [koajs/koa#692]
https://github.com/fl0w/koa/wiki

I basically did some manual labour here (thus error-prone).
I did **NOT practically test** any of these.
For a checkmark, I required one of the following:

* has a next (or equivalent branch), actually checked it was of `Koa v2` type branch as well.
* library root export has v2 signature
* repo has a clear example in readme of v2 usage

To be fair, from the looks of things - most will actually work out of the box (due to `koajs/convert`), so I'm thinking this might be misleading initially?

Related issue: #618

**Comment by PlasmaPower** [comment]
Looks good. Maybe add a note about koa-convert at the top?

**Comment by fl0w** [comment]
@PlasmaPower Added a paragraph. Phrasing might be off, mind taking a peak?

**Comment by PlasmaPower** [comment]
Looks good!

**Comment by jonathanong** [comment]
@fl0w :+1: i don't mind if you guys update the wiki here. i never look at it (i just search koa on npm). i really like the format, but it seems like a lot of work to maintain. haha

**Comment by fl0w** [comment]
@jonathanong I'm with you. Never use it. 

Had no idea it was open to public to non-members.
So, I just did the update. It's easily reverted if anyone else within the org objects. Closing this one.
