### ISSUE TITLE
Koa 2 ctx.query nesting

### ISSUE THREAD

**Issue by liangxingchen** [koajs/koa#697]
```javascript
// When GET /path?a[b]=c
// I think `ctx.query ` should be:
{
   a:{
      b:'c'
   }
}
// But it is
{
   'a[b]':c
}

// Is this a bug?

// if it is, I think
// koa/lib/request.js line 11
const qs = require('querystring');
// should replaced by
const qs = require('qs');
```

**Comment by coderhaoxin** [comment]
@liangxingchen you need https://github.com/koajs/qs

**Comment by lourd** [comment]
Alternatively, you can use the qs module yourself in a middleware and put the parsed result on the context's state, i.e. `ctx.state.query = qs.parse(ctx.querystring)`. That's what I do in my projects.

**Comment by fl0w** [comment]
If my memory serves me correctly - this is simple by design.
Complexities such as depth can be solved in user land, which as you pointed out: `qs` has done.

**Comment by tj** [comment]
There's only an implicit spec for nested query strings, which is why it's not in core. If there's ever a real spec then :+1:, until then it's just random semantics that people attempt to derive out of historical use-cases

**Comment by jonathanong** [comment]
Yeah I believe they're working on a real spec for nested query strings. The current semantics is prone to security issues, which is why it isn't included with koa.

**Comment by liangxingchen** [comment]
the koa-qs works good! thank you all!

**Comment by jdalrymple** [comment]
I've been trying to do this for a while now and havent gotten anywhere :(

**Comment by demisx** [comment]
I second @lourd's approach and would use [qs](/ljharb/qs) directly instead of going through another npm dependency, especially since it's not being actively maintained:

```js
app.use(async (ctx, next) => {
  ctx.state.query = qs.parse(ctx.querystring)
  await next()
})
```
