### ISSUE TITLE
Is koa setting status to 404 by default?

### ISSUE THREAD

**Issue by felixsanz** [koajs/koa#705]
Code: https://github.com/koajs/koa/blob/v2.x/lib/application.js#L132

Bad documentation? https://github.com/koajs/koa/blob/v2.x/docs/api/response.md#responsestatus

> response.status

> Get response status. **By default, response.status is not set** unlike node's res.statusCode which defaults to 200.

This piece of code generates a 404 in response.status:

```javascript
import Koa from 'koa'

const app = new Koa();

app.use(async (ctx, next) => {
  console.log(ctx) // <------ response.status = 404
  await next()
});

app.use(async ctx => {
  ctx.body = 'Hello World'
})

app.listen(3000);
```

**Comment by PlasmaPower** [comment]
I'm pretty sure the documentation is simply incorrect.

**Comment by tj** [comment]
Ah yea the wording there is misleading. We don't (or didn't at least) pre-populate the status to 200, which is useful so that middleware can perform logging etc without assuming 200, and koa defaults to 404 when it sees that status is unset.

**Comment by PlasmaPower** [comment]
> We don't (or didn't at least) pre-populate the status to 200, which is useful so that middleware can perform logging etc without assuming 200, and koa defaults to 404 when it sees that status is unset.

However, we do pre-populate the status to 404, so the following is incorrect:

> By default, response.status is not set unlike node's res.statusCode which defaults to 200.

I'll make a PR to fix that.
