### ISSUE TITLE
Set Content-Length header using createReadStream

### ISSUE THREAD

**Issue by pierreburgy** [koajs/koa#708]
Trying to create a stream to download a file from the server to the web browser, I can not set the `Content-Length` header.

``` js
let fileName = 'myFile.zip';
let filePath = __dirname + '/' + fileName;
let fileStat = fs.statSync(filePath);
          
this.response.type = mimeType;
this.response.attachment(filePath);
this.body = fs.createReadStream(filePath);
this.response.length = fileStat.size;

return;
```

Am I doing something wrong?

**Comment by PlasmaPower** [comment]
That looks correct to me, how do you know that the `Content-Length

**Comment by jonathanong** [comment]
LGTM

**Comment by pierreburgy** [comment]
Actually, I can not use curl to test it because it logs the file content and make my terminal crash (same thing using Postman).

What I would like to have is the total size of the file when I download it with a web browser : 

 - what I have currently

<img width="214" alt="screen shot 2016-04-15 at 10 16 07" src="https://cloud.githubusercontent.com/assets/5550462/14555609/dd787f60-02f3-11e6-8f7f-a820d8a65db2.png">

- what I would like

<img width="214" alt="screen shot 2016-04-15 at 10 24 50" src="https://cloud.githubusercontent.com/assets/5550462/14555728/5b846ac2-02f4-11e6-9fe9-d82953ccecbb.png">

**Comment by juliangruber** [comment]
pass `-I` to curl, like so:

```bash
$ curl -I http://juliangruber.com/
HTTP/1.1 200 OK
Server: GitHub.com
Date: Fri, 15 Apr 2016 09:44:11 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 1705
Last-Modified: Thu, 17 Mar 2016 09:22:40 GMT
Access-Control-Allow-Origin: *
Expires: Fri, 15 Apr 2016 09:54:10 GMT
Cache-Control: max-age=600
Accept-Ranges: bytes
X-GitHub-Request-Id: 4E303A93:4DC2:1663BA09:5710B7EA
```

**Comment by pierreburgy** [comment]
Thanks @juliangruber, here is the result : 

```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: WWW-Authenticate,Server-Authorization
Access-Control-Max-Age: 31536000
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD
Access-Control-Allow-Headers: Content-Type,Authorization,DashboardToken
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000; includeSubDomains
Content-Type: application/zip
Content-Disposition: attachment; filename="myFile.zip"
Content-Length: 184610319
X-Response-Time: 347ms
Date: Fri, 15 Apr 2016 09:47:31 GMT
Connection: keep-alive
```

So, Content-Length header is actually set. Do you have any idea about what could be the issue concerning the web browser download display (probably not related to Koa)?

**Comment by detailyang** [comment]
@pierreburgy hey, we cannot reproduce what you have said. Maybe you should tell us more detail code about how to reproduce :)

**Comment by jonathanong** [comment]
please reopen if you have something reproducible by everyone else. sorry :(
