### ISSUE TITLE
How might I access `ctx` outside of a middleware or a route?

### ISSUE THREAD

**Issue by Gacnt** [koajs/koa#712]
I'm trying to implement `socket.io` to my app, and I want to have it work like `sailsjs` has, where you can do `req.socket.emit` or w/e.

I'm trying to add `io` to the `ctx` variable so that I could do something like

`ctx.io.emit('hello', "Hello!");`

But I can't seem to find how to access `ctx` without binding the io to it in every single middleware request (only really needs to be a one time thing). Any information would be great thanks.

**Comment by tj** [comment]
Hmm I forget how socket.io integrates with servers, but `req.socket.emit` is still a request-level property (just like `ctx`).

**Comment by Gacnt** [comment]
Thanks that seems to work, I did a `console.log(app)` and only seen 3 properties, `context` was not one of them. Is this added afterwards in the `app.callback()`? 

I did:
```
var server = http.createServer(app.callback());
var io     = require('socket.io')(server);

app.context.io = io;
io.on('connection', function(socket) {
  app.context.clisock = socket;
});
```

Which seems to work fine, if I do
```
app.use(async (ctx, next) => {
  
  setTimeout(function() {
    ctx.csocket.emit("hello", "hello test");  
    console.log("Emitted");
  }, 3000)
  await next();
});
```

I get a socket message. I guess I'll have to see if for some reason this will be a bad way to go about this. But for now seems to work fine.

**Comment by tj** [comment]
ahh that's because we have .inspect: https://github.com/koajs/koa/blob/master/lib/application.js#L85, we could probably remove that and leave the toJSON

**Comment by Gacnt** [comment]
Sorry one more quick thing, is the `app.context` client specific, or will all connected people share the same `clisock` until a new one connects, or does each `app.context` have their own `clisock`

**Comment by tj** [comment]
Each request receives a new ctx but that object inherits `app.context`, so it'll be a shared clisock
