### ISSUE TITLE
ctx wasn't able to return after set in other callback function

### ISSUE THREAD

**Issue by xinshouke** [koajs/koa#713]
I used the below code, the last line doesn't work in callback function of getall. there is no any response was return.
----------------------------------------------------
router.get('/',function (ctx, next) {
     getall(function(result){
        console.log('result===>',result);
        ctx.body=result;
     }
}
but I move the last line in out of the getall, it may return a response correctly.

**Comment by liangxingchen** [comment]
```javascript
router.get('/', function(ctx, next) {
	return new Promise(function(resolve, reject) {
		getall(function(result) {
			console.log('result===>', result);
			ctx.body = result;
			resolve();
		})
	});
})
```

**Comment by liangxingchen** [comment]
koa send http response immediately when sync middleware called.
If there has async code in the middleware, the middleware should be `async function` or return a `Promise`

**Comment by jonathanong** [comment]
as @liangxingchen stated, you aren't doing control flow properly. middleware should always be returning a promise in koa v2

**Comment by xinshouke** [comment]
Yes, it works. Thanks
