### ISSUE TITLE
Need help from experienced people.

### ISSUE THREAD

**Issue by BruceHem** [koajs/koa#714]
![screenshot from 2016-04-22 16-17-40](https://cloud.githubusercontent.com/assets/15667259/14737341/c8ed9b7c-08a5-11e6-98a2-93ea76d6091c.png)

in the if error condition i want to create a function as the following:

this.fail(status, body, x-message); so that i don't have to repeat too much codes.

Can anyone help? or if you have better solution?

**Comment by dominhhai** [comment]
```javascript
function fail (ctx, status, body, xMessage) {
  ctx.set('x-messsage', xMessage)
  ctx.status = status
  ctx.body = body
}
```

then call this `fail` function.

**Comment by BruceHem** [comment]
Thanks it works well. And 1 more where should i defined this function if i want to have available globally in my app?

**Comment by BruceHem** [comment]
thanks a lot. :smile:
