### ISSUE TITLE
ECONNRESET error  

### ISSUE THREAD

**Issue by YaroslavLyzlov** [koajs/koa#725]
I use for sendfile this simple library: https://github.com/koajs/sendfile

this library use stream for send file, but after  ctx.body = fs.createReadStream(path) application throw error ECONNRESET

fs.createReadStream(path).pipe(process.stdout) is worked. 

where to find the problem?

Ерфлы!

**Comment by YaroslavLyzlov** [comment]
Sorry, problem in ngnix :)

**Comment by scragg0x** [comment]
@YaroslavLyzlov Do you remember the Nginx issue and how you solved it?

**Comment by YaroslavLyzlov** [comment]
@scragg0x I don't remember well, but I think in upstream settings
