### ISSUE TITLE
Koa blocking main thread

### ISSUE THREAD

**Issue by felixsanz** [koajs/koa#727]
When you open 2 tabs with the same URL and hit refresh at the same time, one tab blocks the other.

The second doesn't start processing until the first one finished. This doesn't happen when the request URL is different. But why happens? Aren't them different contexts?

Related: http://stackoverflow.com/questions/32889291/koajs-blocking-main-thread

**Comment by targos** [comment]
This actually at the level of Node.js, not koa. The following code has the same behavior:

```js
    var server = require('http').createServer(function(req, res){
        console.log('Start processing');
        var before = Date.now();
        setTimeout(function(){
            var after = Date.now();
            console.log('Processing took ' + (after - before) + 'ms');
            res.end('ok');
        }, 3000);
    });

    server.listen(3000)
```

**Comment by PlasmaPower** [comment]
You can use the [node cluster module](https://nodejs.org/api/cluster.html) to mitigate this I think.

**Comment by jonathanong** [comment]
i don't think it's either node or koa. i believe this is how browsers work. see what happens when you refresh to different browsers at the same time.

**Comment by PlasmaPower** [comment]
Yeah I had a feeling that node wouldn't be blocking like that. Try using `curl` to test it.

**Comment by felixsanz** [comment]
closing the issue then :) thanks!
