### ISSUE TITLE
co-busboy was unable to parse ctx using multipart/form-data in koa2

### ISSUE THREAD

**Issue by xinshouke** [koajs/koa#728]
I plan to test a file upload using  multipart/form-data, the below was my code:
------------------------------------code--------------------------------------------
    var parts = parse(ctx.request);
// or  var parts = parse(ctx);
    var part;
    while (part = await parts) {
    var stream = fs.createWriteStream(path.join(os.tmpdir(), Math.random().toString()));
    console.log('part===>', part);
    part.pipe(stream);
    console.log('uploading %s -> %s', part.filename, stream.path);
    }
------------------------------------finished---------------------------------------------
but  I get the below error as below,my question is :how to get the uploading file name and the content of uploading file ?
[TypeError: part.pipe is not a function]

**Comment by coderhaoxin** [comment]
@xinshouke please move this issue to [cojs/busboy](https://github.com/cojs/busboy/issues)
