### ISSUE TITLE
Create an open collective for Koa

### ISSUE THREAD

**Issue by xdamman** [koajs/koa#729]
Hi there!

I've been talking to @tj about creating an open collective for KoaJS like we did for https://github.com/apex/apex (see https://opencollective.com/apex)

The goal is to enable the community to collect money from backers and sponsors in full transparency.
Could be to pay for expenses (see for example [Yeoman](https://opencollective.com/yeoman)), or for paying some of the contributors to spend extra hours to maintain the project (which is the goal of [MochaJS](https://opencollective.com/mochajs)), or to organize meetups.

We are still in private beta but we would love to have you part of it.
You can see the other open source projects that we have at the moment and the companies who are already sponsoring them here: https://opencollective.com/opensource
(talking of open source, we are also open source :) https://github.com/opencollective/opencollective)

Instead of reaching out privately to each of you, I thought it would be cool to start this as a github issue to get your thoughts and give a chance to everyone to give feedback.

**Comment by tj** [comment]
🎉

**Comment by PlasmaPower** [comment]
+1, this seems like a good idea and I don't see any downsides. Maybe some of the money could go to bountysource issues? I'm not sure how helpful that is though, it seems like a lot of issues rot on there.

**Comment by tj** [comment]
Yea that's a bit of a problem, if we accept donations we'll have to figure out how to distribute them. I don't think we'll ever really have expenses TBH

**Comment by xdamman** [comment]
Yes, this often comes up. Here is what we've heard from other collectives when we asked them "what would you spend the money on?":
- (if budget permits) pay one part time maintainer to make sure there is a regular number of hours per week to maintain the project.
- organize meetups (and pay for food/drinks)
- offer swags (stickers, hoodies, ...)
- gift cards to the main contributors before the holidays (or pay for perks like a Spotify subscription)
- donate to a cause (e.g. CharityWater, or more tech related like [Women Who Code](https://opencollective.com/wwcode) to get more women in tech)

You could also donate to other open source projects that have less visibility than Koa but that you are using.

**Comment by tj** [comment]
oo charity is a great idea, I like that, though I suppose people would just donate to charity if they wanted to donate to charity

**Comment by fengmk2** [comment]
+1

**Comment by juliangruber** [comment]
+1

**Comment by piamancini** [comment]
Hi, @piamancini here, also from OpenCollective & following up on this. I think that using the $ for some issues that you want to bounty for could be useful, also spending it in the community with gifts or perks. 
lmk if you want to create one. 
hi @fengmk2 I saw you signed up & I shot you an email early today, happy to chat about it here tho.

**Comment by piamancini** [comment]
Hi @tj I created the Koa Collective : https://opencollective.com/koajs Do you have the logo in transparent (svg would be great). Also, I added the authors as core contributors as well as @fengmk2 since he was in this thread. Anyone else I should add? I tried to add @PlasmaPower but there's no info on the profile. I got the 'member since' dates from the date of first commit to repo. I'll create a PR now for the adding backers/sponsors in readme.

**Comment by tj** [comment]
Sweet sounds good! I'll send something over after work, not sure if I have the original or that font anymore hahaha.. maybe the first thing we should invest in is a proper logo :D

**Comment by piamancini** [comment]
I can ask the oc designers to create one out of the existing one if not. lmk

**Comment by jonathanong** [comment]
interesting. i'm not really into meetups, swag, etc. if someone wants to handle that, that would be cool.

charity would be awesome, but i don't think it'll be tax deductible unless open collective is a 501(c)(3) as well

**Comment by piamancini** [comment]
We are filing for a 501c3. In the meantime, we can host this collective in [Democracy.Earth](http://democracy.earth) a 501c3 that acts as a host for several collectives.

**Comment by PlasmaPower** [comment]
About bountysource: I think it might work, but only as a way to motivate existing contributors to contribute more/stay around longer, not to get bugs fixed by people not planning on contributing to the project.

I'm not quite sure what the point of contributing **solely** to charity through this would be; if a donation to Koa goes directly to charity, then why is it shown as a donation to Koa? It seems almost like trying to trick the donator into donating to charity - the money would almost certainly not end up improving Koa.

**Comment by PlasmaPower** [comment]
Do we want to put a link to the open collective somewhere? Maybe at koajs.com and in the README.

**Comment by xdamman** [comment]
@PlasmaPower here is the PR: https://github.com/koajs/koa/pull/748

**Comment by piamancini** [comment]
Hi! I wanted to share here some news before we do it publicly. We've created a matching fund to incentivize backers to give to open source. We will be matching what your first 10 backers give to Koa (up to $100 per month total). More about it here https://medium.com/@piamancini/d442585fb924 <3

**Comment by Clown-Fox** [comment]
@piamancini Good evening, Pia, and what a lovely evening it is too. My associates and I noticed that you and your colleagues have pioneered this here OpenCollective and I, in my humble Fox way, thought I should approach and see what the commotion is about, as I assure you many still talk in hushed and awed voices about it. And here, unfortunately, I have to temporarily dispense with the poetic to say:

We want to be cut in on the deal. Particularly with respect to this here Koa server, which I'm told by our resident technology expert THE WIZARD (we call him this for his technical wizardy, if you'll pardon my obvious pride in a close colleague and even closer business associate) is the best of the best currently on offer. So, if you'll allow me further indulgence -- a proposition and a question tied to it...

If my five colleagues (Rabbit-Cat, Pirate-Weasel, Deer-Wolf, The WIZARD and Giraffe-Furry, agree to each donate a significant, though not right yet exceptional, amount, would you be so kind -- and here with my proposition you will note also, and tightly bound together, comes my question -- as to tell us in simple terms, how we simple forest dwelling folk who are not all, alas, as nobly (though also notoriously) technologically savvy as your wondrously good selves, and in the hopes.. and I do say this with a most gracious though unfortunately shaped smile on my vulpinous features (a Fox's face can be a trial at times, don't you agree; whatever thoughts are as to our sophistication, such can interfere much with notions of trust...) and with the utmost care to the Koa team's paramount rights of self-direction -- how will we  be able to track how the money we spend is channelled into working code (or things related to working code; I understand you can't make an omelette without raising your chickens right and/or breaking into the coups of a few well-raised chickens, were you inclined to, which of course I never would be..) that's useful to us specifically in our project, and helps our erstwhile band's own _forest-roots_ **schema**tics, which... well, it wouldn't do to tell you yet all of the grand designs we have in mind. But that a Fox enjoys dinning at a table he has richly set himself, even if Fox riches are not quite of the sort you have in mind (about $5 per person at the moment, we could probably spare, with the right assurances...)

**Comment by tj** [comment]
![wait-what-meme-05](https://cloud.githubusercontent.com/assets/25254/16571706/e9663c98-4215-11e6-882c-58c53903a75a.jpg)

good luck @piamancini hahah

**Comment by piamancini** [comment]
Oh là là Monsieur le Fox (@Clown-Fox), I see you finally stopped jumping over that lazy dog of yours. Well my dear, it was about time... 

Without even trying to comprehend the your message, I'd like to volunteer a couple of thoughts: 

- The way to track is going to https://opencollective.com/koajs more specifically: https://opencollective.com/koajs/expenses to see what use your good money has been put  to

- now, if the question remains, how you'll know if it will be spent on stickers or code, that my friend is a decision that lies entirely in the hands of the team here. 

- if, alas, the question still remains, how will Koa be able to get their hands on your cash, then it's a simple procedural PayPal enabled exchange (money contra invoice/receipt)

Hoping this gives you the right assurances, ladies and gents please refer to https://opencollective.com/koajs and make you backings.  Otherwise, please redirect.

**Comment by ThePurpleRabbits** [comment]
@piamancini thank you very much for knocking my friend down a peg or two. He's gone off in a sulk but I am personally interested. A test investment seems in order.

I'm willing to invest $5 this month out of my own pocket, as a starter. I'll then get my people to submit ideas and bugs and we'll take a look at the expenses reports as and when they arrive, as well as any progress made on the repo that fits our requirements.

If your progress seems to be aiding in our progress then we may consider keeping the payment up, or some of my friends might invest too.

I'll drop the cash into the account before midnight tonight.

**Comment by Shakyamuni177te** [comment]
@ThePurpleRabbits Has the cash arrived at the destination yet? Do you have confirmation it left your account?

**Comment by GranularDetective** [comment]
@Shakyamuni177te Am I getting paid this month?

**Comment by Shakyamuni177te** [comment]
@GranularDetective Please message me personally about this! You have my e-mail address. But in answer to your question: no. You have enough money to get by and you knew when you joined the team you'd have to wait until we were making money to get paid. 

No-one in the company is getting a wage. I'm not. Clown-Fox isn't. No-one is. We love you and we really appreciate your time and effort, and when we get paid YOU WILL BE. But right now we can't. Sorry but we really can't.

**Comment by GranularDetective** [comment]
@Shakyamuni177te I know. I love you too for doing this, in a friend way. But I have people who will pay me for doing the same thing. I know you don't. I'm sorry.

**Comment by Shakyamuni177te** [comment]
@GranularDetective That's nice but when you try to help someone you put yourself on the line. We wouldn't ask you to do that. It's not your place.

**Comment by GranularDetective** [comment]
@Shakyamuni177te I have a right to a fair wage for the job I do. I know you can't get anyone to employ you. It's your own fault for causing trouble. You're an idiot.

**Comment by GranularDetective** [comment]
@Shakyamuni177te I care about your project. I hope you do well. I'm sorry again.

**Comment by GranularDetective** [comment]
@Shakyamuni177te I'm deleting my GitHub.

**Comment by ThePurpleRabbits** [comment]
@Shakyamuni177te @GranularDetective Basically what you need to do is a) go to sleep b) delete all these comments that have absolutely nothing to do with the OpenCollective.

**Comment by ThePurpleRabbits** [comment]
@GranularDetective Sleep it off. Sort it out :P.

**Comment by ThePurpleRabbits** [comment]
@Shakyamuni177te Thanks for the sermon :P.

**Comment by GranularDetective** [comment]
@ThePurpleRabbits *Shrugs* Another public play with nothing to do with real life, eh? ;)

**Comment by tj** [comment]
![djxqa2](https://cloud.githubusercontent.com/assets/25254/16676067/954b7764-447b-11e6-9f35-db735bec42bf.jpg)
