### ISSUE TITLE
The link to Koa 2 migration docs is (slightly) broken

### ISSUE THREAD

**Issue by nicolasmccurdy** [koajs/koa#741]
Here's the link included in Koa 2's deprecation notice:

https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x

And here's the current URL for this section:

https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x---deprecated

It seems like someone updated the heading in the readme and forgot to update the link. The "broken" link goes to GitHub's page for the v2.0.0 branch, but it doesn't scroll to the right section.

**Comment by dead-horse** [comment]
Hi, can you send a PR for this? :)

**Comment by nicolasmccurdy** [comment]
Thanks for the fix @fl0w. I noticed your fix is on the 2.0.0 branch now, but is this fix published on npm (for the appropriate tag) yet?

**Comment by fl0w** [comment]
@nicolasmccurdy no, not yet.

**Comment by fl0w** [comment]
@dead-horse This could be closed I assume (not sure why the merge didn't close this).
