### ISSUE TITLE
Allow immutable definition of server and router

### ISSUE THREAD

**Issue by EECOLOR** [koajs/koa#746]
I would like to be able to do:

```
new Koa([use1, use2])
```
instead of 
```
const app = new Koa()
app.use(use1)
app.use(use2)
```

I would like to do the same for routes. It's more in line with the immutable / functional way of thinking.

**Comment by PlasmaPower** [comment]
I don't think this should be bultin to Koa, but you could do this:

```js
Koa = class CustomKoa extends Koa {
    constructor(mw) {
        super();
        if (mw) mw.forEach(fn => this.use(fn);
        Object.defineProperty(this, 'middleware', {
            value: this.middleware,
            writable: false
        })
    }
};
```

**Comment by juliangruber** [comment]
we're not going to go down that route, the app.use() stuff is highly unlikely ever to change. that's the core api promise! but as @PlasmaPower you're always free to have your own fork, and publish functional-koa.

**Comment by PlasmaPower** [comment]
@juliangruber Yeah I agree, I prefer app.use by a lot. I was just putting out another option :)

**Comment by tj** [comment]
FWIW app.use() doesn't make it mutable, the internal array is "private", so you can only append

**Comment by nswbmw** [comment]
@EECOLOR try [koa-use](https://github.com/nswbmw/koa-use)
