### ISSUE TITLE
how do you run benchmarks?

### ISSUE THREAD

**Issue by capaj** [koajs/koa#750]
I tried `make bench` but only to get 
```
/run: line 9: wrk: command not found
```

How do you install wrk-as ruby gem?

**Comment by PlasmaPower** [comment]
Wrk isn't ruby, it's C. If you're on Linux/MinGW or OSX, see these:

https://github.com/wg/wrk/wiki/Installing-Wrk-on-Linux
https://github.com/wg/wrk/wiki/Installing-wrk-on-OSX

**Comment by capaj** [comment]
@PlasmaPower thanks, just googled it myself.
