### ISSUE TITLE
A logical middleware signature

### ISSUE THREAD

**Issue by EduardoRFS** [koajs/koa#752]
My suggestion is to in a possible "v3" a new signature, is more logical using promise when promise resolve it call another middleware. Old and new signature is supported by this change

example

```javascript
app.use(async ctx => {
  ctx.body = 'first'
});
// using two arguments it not automatically call next
app.use((ctx, next) => {
  ctx.body += 'second'
  next();
});
app.use(async ctx => {
  ctx.body += 'third'
});
```

And is a really simple to implement, five line changes on koa-compose. It is more intuitive

**Comment by PlasmaPower** [comment]
I don't think we should be looking at the number of arguments accepted, it's hacky. The current solution works fine.

**Comment by yanickrochon** [comment]
I agree with @PlasmaPower. This suggestion would require `next` to be passed if you want to prevent `next` to be called anyhow. It defies the purpose in my opinion.

**Comment by EduardoRFS** [comment]
Yes, but a "next" existance in koa is not necessary, on express is only to call asynchronous, but in koa? With async / await? Is really required a next argument? In my projects only the end points not call "next".
Next is only useful sometimes

```javascript
app.use(async (ctx, next) => {
  const start = new Date();
  await next();
  const ms = new Date() - start;
  console.log(`${ctx.method} ${ctx.url} - ${ms}ms`);
});
```

**Comment by PlasmaPower** [comment]
What @yanickrochon is saying is that in a lot of instances you don't want to call next, say:

```js
app.use(async ctx => {
  ctx.bod = 'Example';
});
```

With your method, I'd have to add `next` as a parameter to that example for it to work as it worked (not executing future middleware), which can be significantly faster and have other side effects depending on your middleware setup.

**Comment by tj** [comment]
Isn't this what we already have for v2? `(ctx)` and `(ctx, next)`

**Comment by EduardoRFS** [comment]
I know, but in all you need to add a `next`, a real example

```javascript
// my suggestion
app.use(async ctx => {
	let user = await mongoose.User.findOne({ _id: 'Admin' });
	if (!user) return;
	user.configure();
	ctx.state.user = user;
});

//actually
app.use(async (ctx, next) => {
	let user = await mongoose.User.findOne({ _id: 'Admin' });
	if (!user) return next();
	user.configure();
	ctx.state.user = user;
	next();
});
```

**Comment by tj** [comment]
@EduardoRFS hmm that doesn't make sense to me, the middleware has to choose some point at which to "yield" to the rest of the middleware

**Comment by PlasmaPower** [comment]
@tj This issue is that we should automatically call next at the end if the mw only accepts 1 arg

**Comment by EduardoRFS** [comment]
@tj no. Is basically "when middleware return, call next middleware"

**Comment by tj** [comment]
Ah, FWIW arity based stuff has definitely confused people in the past with Express

**Comment by PlasmaPower** [comment]
@EduardoRFS I'm talking about a mw that outputs a body - in that case, the most likely end user case, yours would be more complicated.

@tj Agreed.

**Comment by EduardoRFS** [comment]
hmm is really confuse based on express, thx

**Comment by tj** [comment]
I like that with the current implementation you can "short circuit" the middleware, by just not calling next(). That would be the main reason to keep it as-is I think, since it changes what downstream middleware have to "know", if they're _always_ invoked.

**Comment by dead-horse** [comment]
-1, don't add too many hidden logic in framework, that make people confused, middlewares should always be the same, people will call next when they want to. also this will break a bunch of code.
