### ISSUE TITLE
Make Koa v2 compatible with the style guide of Airbnb

### ISSUE THREAD

**Issue by kripod** [koajs/koa#755]
Setting `ctx.body` means mutating a function's parameter, which is against [the rules of the Airbnb style guide](https://github.com/airbnb/javascript#functions--mutate-params).

I would suggest adding `setBody`, `appendToBody` and `clearBody` functions to `ctx` in order to avoid the behavior described above.

**Comment by juliangruber** [comment]
Sorry but that's not going to happen. Setting values on the context is what you're expect to do with koa. If you add `.setBody` etc, you're still doing the same thing, changing the underlying state.

If you wanted to do the side effect free, you'd need to return a new context object from every middleware. That's just too expensive and not convenient. `ctx` is your state, your side effect.

**Comment by kripod** [comment]
Okay, thanks for your assistance!
