### ISSUE TITLE
acceptsLanguages is not returning the expected language

### ISSUE THREAD

**Issue by marr** [koajs/koa#761]
I just created a pr that illustrates what I see when trying to find the language from the `accepts-language` header. According to the docs, `ctx.acceptsLanguages` should return the best fit, and I am seeing unexpected behavior when I send in headers with values such as `en,en-US;q=0.8` which is standard US browser header value in Chrome. 

If I call `ctx.acceptsLanguages('en-US', 'en-GB')` I would expect the result to be `en-US` as that is an acceptable language that the server supports. The result is instead `en-GB`, leading me to believe there is a bug.

See https://github.com/koajs/koa/pull/760 for illustration of the failure.

**Comment by dougwilson** [comment]
I have Chrome installed (and even just installed it on a new machine) in the US and Chrome is sending the header `en-US,en;q=0.8` by default, which is exactly the opposite from the one you pasted, and the one that actually makes sense to send (the one you provided is a seemingly non-sense header). What does the assertion "which is standard US browser header value in Chrome." come from?

**Comment by fl0w** [comment]
Appears to be invalid, relevant discussion: jshttp/negotiator#46

**Comment by marr** [comment]
@dougwilson that must have been an error on my part assuming that the default with Chrome is `en,en-US;q=0.8`. However, I don't think it is a nonsense header -- if you drag _English (United States)_ under the _English_ value in the settings panel, `en,en-US;q=0.8` will be sent.

**Comment by dougwilson** [comment]
Sorry, "non-sense" was not the best way to describe it :) What I meant was that the header, as set out by the standards, says the following (if you translated it into an English description):

> I accept a resource in English, but I can also accept a resource in United State English if you can still keep it at at least 80% the quality of any other English.

So it's really just a pretty uncommon form to see it in, as what it does is setup a specific type of English to be less acceptable that the other Englishes (as in, it sets up all Englishes are good, but specifically class out one of those Englishes as specifically less good than the others). Typically you always see it the other way around, where some specific language is more preferred and the rest and less-preferred.

By "non-sense" I meant that if you accepted all Englishes, it's kind of weird to call out one specific English as being less acceptable than the others, as typically, as humans, we would prefer a specific over a general.

**Comment by marr** [comment]
Makes _sense_
