### ISSUE TITLE
how to redirect correctly in route  (koa, koa-router with socket.io and polymer)

### ISSUE THREAD

**Issue by Karl01** [koajs/koa#763]
Hi, I'm trying to redirect in a route but get the '"Can't set headers after they are sent" error, what is the correct approach to redirect in Koa on server side, want to keep all routing on the server

thanks

```
router.get('/',` async (ctx, next) => {
   ctx.body = await fs.createReadStream(__dirname+'/index.html');
    io.of('/index').on('connection', function (socket) {

     //more socket.on stuff...
    
      //client sent which menu item we clicked
      socket.on('ironPage', async (reqObj) => {
        switch (reqObj) {
          case 'item5':
          ...
         case 'item6':
            await ctx.response.redirect('/role');
          };
        }); 
    });
 });

...

router.get('/role.....
```

**Comment by PlasmaPower** [comment]
You'll need to return a promise that resolves when the response has finished. With that code, koa has no way of knowing when it can go ahead and send the response. It'll be a bit more complicated since you're using events, you could either create your own promise or try to use `event-promise`.

**Comment by Karl01** [comment]
cheers

**Comment by juliangruber** [comment]
i guess this means the issue has been solved. feel free to reopen if otherwise

**Comment by Karl01** [comment]
Thanks, actually it means I'm trying to figure it out myself before I ask again, will come back if no result

**Comment by luckydrq** [comment]
@PlasmaPower could you give a link to `event-promise` repository? Is it this [repo](https://github.com/rschaosid/node-event-promise)?

**Comment by PlasmaPower** [comment]
Sorry, I meant `event-to-promise`. [NPM](https://www.npmjs.com/package/event-to-promise) which has a [GitHub](https://github.com/JsCommunity/event-to-promise) link.

**Comment by luckydrq** [comment]
thank you!

**Comment by Karl01** [comment]
thanks, will try that, event-to-promise also has a ES6 pattern example for the babelized
