### ISSUE TITLE
how to skip or jump a middleware with koa2

### ISSUE THREAD

**Issue by shuperry** [koajs/koa#764]

**Comment by juliangruber** [comment]
you can't tell koa to skip a middleware, but you can tell the middleware not to do anything.

something like

```js
app.use(async (ctx, next) => {
  if (skipThis) return await next();
  // ...
})
```

Maybe tell us what kind of middleware you want to skip, and why.

**Comment by shuperry** [comment]
@juliangruber thks first, I tried this like
`router.use(async (ctx, next) => {
    if (_.contains(authPaths, ctx.url)) {
      console.log('into if')

      try {
        await next()
      } catch (err) {
        if (401 === err.status) {
          logger.debug('catched Invalid token UnauthorizedError...')

          ctx.body = {error: '未登录或登录已失效, 请重新登录'}
        } else {
          throw err
        }
      }
    } else { // skip jwt middleware.
      console.log('into else')

      return await next()
    }
  })

  router.use(jwt({secret: config.get('jwt:secretKey'), cookie: config.get('jwt:cookie:token')}))`

**Comment by shuperry** [comment]
@juliangruber I am sorry, I misunderstand it, you mean skip this middleware, not the next one.

**Comment by juliangruber** [comment]
the code seems about right. do you see the `into else` line being printed out on the console?

**Comment by shuperry** [comment]
@juliangruber I do see the `into else` line being printed, but the next jwt middleware also being excuted.

**Comment by juliangruber** [comment]
oh, yeah you can't tell koa to skip the next middleware. i would instead only mount the jwt middleware on routes that it's required on, something like

```js
authPaths.forEach(path => {
  router.use(path, jwt)
})
```

**Comment by luckydrq** [comment]
Maybe you can use `return` instead of `return await next()` to stop request  going deeper in the middleware stack which means jwt middleware will be skipped here.

**Comment by shuperry** [comment]
@luckydrq I figured out a easier way, thks to koa-unless module, here is my code:

```
// catch Invalid token UnauthorizedError.
  router.use(async (ctx, next) => {
    try {
      await next()
    } catch (err) {
      if (401 === err.status) {
        logger.debug('catched Invalid token UnauthorizedError...')

        ctx.body = {error: '未登录或登录已失效, 请重新登录'}
      } else {
        throw err
      }
    }
  })

  // only urls in config file need check authority.
  router.use(jwt({secret: config.get('auth:jwt:secretKey'), cookie: config.get('auth:cookie:token')}).unless((ctx) => {
    return !_.contains(config.get('auth:paths'), ctx.url)
  }))
```

**Comment by PlasmaPower** [comment]
@shuperry I think what you're looking for is this:

```js
router.use(async (ctx, next) => {
  if (config.get('auth:paths').contains(ctx.url)) {
    return jwt({secret: config.get('auth:jwt:secretKey')(ctx, next)
  } else {
    return next()
  }
})
```

**Comment by shuperry** [comment]
@PlasmaPower thks, your mind works and easier to understand.
