### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by urbaitel** [koajs/koa#765]
There are node modules that provide versioning for express like this one: https://www.npmjs.com/package/express-routes-versioning

How can we do API versioning with koa?

**Comment by tj** [comment]
Take a look at the [wiki](https://github.com/koajs/koa/wiki) I see a few there

**Comment by fl0w** [comment]
I purpose this to be closed.

If @urbaitel has further questions regarding middleware authoring other channels are more appropriate, or just continue commenting on the closed issue.
