### ISSUE TITLE
JSON error when donating to your OpenCollective

### ISSUE THREAD

**Issue by ThePurpleRabbits** [koajs/koa#767]
Not sure if this is to do with your personal OpenCollective, or something more general, but when I tried to make my donation I saw this page:

[https://s32.postimg.org/protevkzp/Open_Collective.png](https://s32.postimg.org/protevkzp/Open_Collective.png)

Could you check for me and make sure the money has arrived in the account? Also, I note that other contributors have a link to a website or GitHub linked from the page. This would be very useful to us, and I would like to include a particular profile on there.

**Comment by tj** [comment]
not the right place to report OpenCollective stuff sorry!

**Comment by ThePurpleRabbits** [comment]
Have your collective not received the money due to you guys? If not it needs sorting out.

**Comment by tj** [comment]
It goes into OpenCollective first, I have no clue
