### ISSUE TITLE
Three backers listed on the main site header, but only one backer shows on click event

### ISSUE THREAD

**Issue by ThePurpleRabbits** [koajs/koa#770]
The onclick event (or whatever the equivalent within the language or framework you are using) for:

[https://github.com/koajs/koa#backers](https://github.com/koajs/koa#backers)

Shows three backers, but routes to a page which shows only one backer, and does not include our donated amount.

**Comment by tj** [comment]
not the right place to report OpenCollective stuff sorry!

**Comment by ThePurpleRabbits** [comment]
Have you not received the money?
