### ISSUE TITLE
Feature request: seemless support for VirtualBox

### ISSUE THREAD

**Issue by ThePurpleRabbits** [koajs/koa#771]
We have Koa running fine on our main system but would like to run it on an Ubuntu 16.04 server we virtualise through VirtualBox. Support for seamless port-forwarding from VirtualBox to host machine via scripting would be a definite plus for us.

**Comment by tj** [comment]
Port forwarding isn't really relevant to Koa, I'm assuming you're using Vagrant but it features port forwarding

**Comment by Clown-Fox** [comment]
No. VirtualBox. Vagrant is a different thing. THE WIZARD set it up, but I know a bit. And yeah, they're not the same thing. It would be a difficult feature to support, but it would be _very_ useful for us.

**Comment by ThePurpleRabbits** [comment]
@tj Vagrant and VirtualBox are both virtual machines but they are not the same. Other examples of Virtual Machines are VMWare Player and VMWare Workstation. Often virtual machines require very different parameters for port forwarding.

**Comment by GranularDetective** [comment]
@tj Hi TJ! I love your work! But the guys are right, it is relevant because Koa is a server/middleware/scripting tool and we really need your help. Because right now our VirtualBox running Koa won't serve to our host IP address. And that's a bad thing.

**Comment by tj** [comment]
VirtualBox via Vagrant I meant, but either way port forwarding is easily done at the OS level, no need for anything special here. Beyond that if you have an issue with binding, then it's a Node issue because Koa's listen() is just Node's listen().

**Comment by PlasmaPower** [comment]
Agreed, sorry but this is not within the scope of Koa. You might try developing your own Node.JS module for this (it wouldn't be within the scope of Koa middleware).

**Comment by PlasmaPower** [comment]
Also, you might try a bridged Virtualbox network adapter, it might mitigate this problem.

**Comment by ThePurpleRabbits** [comment]
Same you guys weren't able to help. Thanks for trying.

**Comment by ThePurpleRabbits** [comment]
We have been trying a bridged adapter....

**Comment by tj** [comment]
I've had no problems with Vagrant in the past: https://www.vagrantup.com/docs/networking/forwarded_ports.html

**Comment by ThePurpleRabbits** [comment]
You suggest Vagrant instead of VirtualBox as the supported solution for Koa?

**Comment by tj** [comment]
Vagrant is just a thin layer on top VBox and others

**Comment by ThePurpleRabbits** [comment]
I'll look into the solution you offered tomorrow. It's late in the UK and I spend too much time on work.

**Comment by yanickrochon** [comment]
What about running nginx? I use that inside a Virtualbox machine, forwarding from port 80 (nginx) to port 4040 (koa app) and things work fine... I don't understand how koa can help, here, since you cannot do more with this module that the native `http` one does already. Or I'm totally off-topic and I am missing something obvious.

**Comment by detailyang** [comment]
nginx as a load balancer is a good choose, which easy to set up different upstream address:port @ThePurpleRabbits

**Comment by tj** [comment]
Closing since it's not koa specific.

**Comment by tj** [comment]
oh it was closed :D oops
