### ISSUE TITLE
Award for least appropriate meme

### ISSUE THREAD

**Issue by GranularDetective** [koajs/koa#772]
We should have one.

**Comment by GranularDetective** [comment]
Sapmmapapam evreyymw

Soar macq troth

**Comment by tj** [comment]
Come on at least have some more clever trolling :p

**Comment by Clown-Fox** [comment]
I personally thought the characterisation was a little off in the late stages. And I was never entirely sure if that Shakyamuni177te character was playing himself, a character, or some sort of comedic exaggeration of his own traits.

Either way, the dialogue wasn't particularly enlightening or believable, but I wouldn't exactly call it spam.

You can probably close this issue now. Though Granular was right that, as far as I'm aware it's impossible to X-Site Script from a readme, but then, you never know... 🎱
