### ISSUE TITLE
this.subdomains is error parsed

### ISSUE THREAD

**Issue by jackmasa** [koajs/koa#775]
when host is 127.0.0.1 this.subdomains=> [127,0,0]

**Comment by juliangruber** [comment]
i guess this wasn't noticed because you can also use `localhost` and it's quicker to type, but yeah we should probably fix this

**Comment by jackmasa** [comment]
any IP is error parsed.

**Comment by fl0w** [comment]
What's the expected result here? undefined?

**Comment by jackmasa** [comment]
```javascript
  get subdomains() {
    var offset = this.app.subdomainOffset;
    return (this.host || '')
      .split('.')
      .reverse()
      .slice(offset);
  },
```
