### ISSUE TITLE
how to delete a cookie

### ISSUE THREAD

**Issue by shuperry** [koajs/koa#777]
I tried `ctx.cookies.set('jwt', null)`, but the cookie still there.

**Comment by shuperry** [comment]
I found it worked in browser, but not worked in Postman, erm..

**Comment by luckydrq** [comment]
just set a outdated expire date

**Comment by shuperry** [comment]
@luckydrq I know the way you said, `ctx.cookies.set('jwt', null)` this code works, but only in browser, I found that is Postman's bug.

**Comment by luckydrq** [comment]
ok, but what is Postman?

**Comment by shuperry** [comment]
@luckydrq It's a tool to test api, [here](http://www.getpostman.com/)

**Comment by luckydrq** [comment]
>@luckydrq I know the way you said, ctx.cookies.set('jwt', null)

yeath, you're right. It's the same as set a outdated date. I've found the clue: https://github.com/pillarjs/cookies/blob/master/lib/cookies.js#L113

**Comment by cpprookie** [comment]
For anyone arrive here,  `ctx.cookies.set('jwt', null)` works in postman now.

**Comment by runhwguo** [comment]
ctx.cookies.set(cookieName, '');

**Comment by nadavoosh** [comment]
actually, looks like it's just `ctx.cookies.set(cookieName)`

**Comment by wangjiafenghw** [comment]
> ok, but what is Postman?

https://www.getpostman.com/    It's a good tool for testing api

**Comment by wangjiafenghw** [comment]
> > ok, but what is Postman?
> 
> https://www.getpostman.com/ It's a good tool for testing api

restlet client run in chrome,this is better

**Comment by maml** [comment]
> actually, looks like it's just `ctx.cookies.set(cookieName)`

this is correct, per the documentation for [`cookies.set`](https://github.com/pillarjs/cookies#cookiesset-name--value---options--)

> If the _value_ is omitted, an outbound header with an expired date is used to delete the cookie.

**Comment by zidian257** [comment]
be sure to include the domain you mean to clean
