### ISSUE TITLE
pipeling request will lost!

### ISSUE THREAD

**Issue by zensh** [koajs/koa#779]
### Test result:
```
=== Http server ===
Request count: 1 , Error listeners: 1
Request count: 2 , Error listeners: 1
HTTP/1.1 200 OK
Date: Wed, 20 Jul 2016 02:56:47 GMT
Connection: keep-alive
Content-Length: 1

1HTTP/1.1 200 OK
Date: Wed, 20 Jul 2016 02:56:47 GMT
Connection: keep-alive
Content-Length: 1

2

=== Toa server ===
Request count: 1 , Error listeners: 1
Request count: 2 , Error listeners: 1
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 1
X-Powered-By: Toa
Date: Wed, 20 Jul 2016 02:56:47 GMT
Connection: keep-alive

1HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 1
X-Powered-By: Toa
Date: Wed, 20 Jul 2016 02:56:47 GMT
Connection: keep-alive

2

=== Koa server ===
Request count: 1 , Error listeners: 2
Request count: 2 , Error listeners: 2
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 1
Date: Wed, 20 Jul 2016 02:56:47 GMT
Connection: keep-alive

1
```

### Reason

When server emit a `request`, `responce` instance may not have `socket` for the time being, [_http_server.js](https://github.com/nodejs/node/blob/master/lib/_http_server.js#L487), `this.writable === false` in [application.js](https://github.com/koajs/koa/blob/master/lib/application.js#L199)

**Comment by zensh** [comment]
Toa fixed: https://github.com/toajs/toa/commit/95875dbd9b8f6a9b8356dc4187a26102cc1bb57e

**Comment by dead-horse** [comment]
change https://github.com/koajs/koa/blob/master/lib/application.js#L199 this line to `res.headersSent || res.finished` will fix this issue?

**Comment by zensh** [comment]
@dead-horse I think that if socket closed before `respond()`, `respond` should not be called.

**Comment by PlasmaPower** [comment]
I'd be in favor of `res.headersSent || !res.writable || res.finished`.

**Comment by dead-horse** [comment]
when will `res.writable` set to false? Can't find any related code [here](https://github.com/nodejs/node/blob/master/lib/_http_outgoing.js)

**Comment by PlasmaPower** [comment]
@dead-horse When `.end` is called: https://github.com/nodejs/node/blob/master/lib/_http_outgoing.js#L593

That's [part of the WritableStream interface](https://nodejs.org/api/stream.html#stream_writable_end_chunk_encoding_callback) so pipes will use it of course.

**Comment by PlasmaPower** [comment]
Oh, `.writable`. Oops. I think that's part of `writeHead` which doesn't seem to be in the file linked (I'm not sure where it is, checking now).

**Comment by PlasmaPower** [comment]
Nope, I was thinking of something else there. I'm not quite sure, but I suspect it's linked closer to the TCP socket (rather than being HTTP level).
