### ISSUE TITLE
Koa middleware as chain of generators

### ISSUE THREAD

**Issue by nnnikolay** [koajs/koa#780]
Hey, thanks for your framework guys!!

Could you please point me how to make something similar with Koa?
I've made that example with koa-router and koa2.

```
// 1st middleware
let gen1 = function *() {
  let arr = [0,1,2,3];
  for(let i=0; i<arr.length;i++) {
    yield arr[i];
  }
};

// 2nd middleware
let gen2 = function *() {
  for(i of gen1()) {
      yield i + 2;
  }
};

// 3rd middleware
let test = function (ctx) {

  let arr = [];
  for(i of gen2()) {
    arr.push(i);
  }
  ctx.body = arr;
}


router.get('/', function(ctx, next) {
  test(ctx);
});
```

I tried to do deal with GeneratorFunction middlewares like that

```
app
    .use(co.wrap(function *(ctx, next) {
        console.log('first');
        yield next();
    }))
    .use(co.wrap(function *(ctx, next) {
        console.log('second');
        yield next();
    }));
```

But it does not `yield` generator result.

What is the right way to achieve what I need with help Koa framework?

**Comment by sodawy** [comment]
```javascript```
app
    .use(function *(next) {
        let ctx = this;
        console.log('first');
        yield next;
        console.log('fourth');
    })
    .use(function *(next) {
        console.log('second');
        yield next;
        console.log('third');
    });
```
If you have knew how to use`generator` `yield`,  [koa-compose](https://github.com/koajs/compose/blob/master/index.js) is how koa middleware works

**Comment by tj** [comment]
Koa uses generators basically as a hack to implement something similar to async/await, which in turn effectively disables the regular generator usage. This is the lib used behind the scenes, might give you some more insight: https://github.com/tj/co

**Comment by nnnikolay** [comment]
Yeah thanks, I understood already that generators here not used to send data between middlewares as in my example. You use it just to get "async"  call for next middleware.
