### ISSUE TITLE
Concurrent Connections and Timeouts

### ISSUE THREAD

**Issue by dtothefp** [koajs/koa#784]
I'm using Koa 2 and compiling through babel using the following config:
```
{
  "presets": ["react", "es2015-node6/object-rest"],
  "plugins": [
    "add-module-exports",
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": false
    }],
    "transform-object-rest-spread",
    "bluebird-async-functions"
  ]
}
```
When doing load testing I'm using [wrk2](https://github.com/giltene/wrk2).  A typical wrk2 test might look like:
```
wrk -c50 -t2 -d1m -R100 https://some-url/
# -c concurrent connections
# -t threads
# -d duration
# -R requests per second
```
I have three questions that might show my ignorance of how Node/Koa works but would appreciate any help you can offer:

##### Inconsistent timeout times for asynchronous request
I'm trying to timeout an API request using `Promise.race` and am seeing inconsistent results when load testing, i.e. a cached API request on our development server that is racing against a 2000ms timeout does not seem to resolve before a the 2000ms timeout. I've seen that `setTimeout` is not completely reliable in this situation I'm assuming due to handoff between the event loop and synchronus processing of incoming requests
```js
const req = new Promise(res => request.get('some/cached/request').end((err, {body}) => res(body))
const timeout = new Promise((res, rej) => setTimeout(rej.bind(null, new Error('timeout')), 2000))

//in Koa middleware
try {
  const data = await Promise.race([req, timeout])
catch (err) {
  //2000ms timeout occurred 
}
```
Because the API request is cached I'm assuming it resolves almost immediately but at high load I see the timeout occurring often, as well as the timeout times increasing in our monitoring to above 2000ms (assuming this has to do with how node handles requests and checks back with the event loop?). Anyhow, I'm not sure if this is the proper way to timeout a request in Koa or if I should use a different approach.

##### Increasing times for asynchronous processes throughout the request/response lifecycle 
With increasing load asynchronous processes take longer and longer to load throughout a single request cycle. For example:
```js
//config middleware
async (ctx, next) {
  const {map: asyncMap} = require('async')

  ctx.config = await new Promise(res => {
     const json = ['one.json', 'two.json', 'three.json']

     asyncMap(json, readJson, (err, result) => {
         const data = result.reduce((acc, d) => Object.assign(acc, d))

         res(data)
     })
  })
  await next()
}

//request middleware
async (ctx, next) => {
  try {
    ctx.data = await Promise.race([req, timeout])
  } catch (err) {
    ctx.status = err.status || 503
  }
 
  await next()
}

//render middleware 
async (ctx, next) => {
  if (ctx.status) return

  try {
    ctx.body = new Promise((res, rej) => {
      const renderData = Object.assign({}, ctx.config, ctx.data)

      page.render(renderData, (err, html) => {
        if (err) return rej(err)
       
        res(html)
      })
    })
  } catch (err) {
    ctx.status = 404
  }

  await next()
}
```
In the above sequence of middleware, time to render HTML should not be dependent on the API request time although it must wait for the API request to complete. At low loads this is what our monitoring shows, essentially HTML consistently renders much faster than the API request takes. But as load increases we see an increase in render time in relation to the API request time showing that HTML starts to take much longer to resolve from the callback than the actual API request takes. I'm curious if this somehow relates to how the event loop is handled at high concurrency/rqs and if there is something I can do within Koa/Node to increase this performance?

The chart below shows as load increasing for a 5000ms API timeout:

![sos dd load testing cropped](https://cloud.githubusercontent.com/assets/4656726/17085121/7a4e71ca-519e-11e6-9c0e-adb5df7036b0.jpg)

##### Significant dropped/timed out requests during load testing 
The load tests are resulting in significant dropped/timed out requests. I read that Node's default request timeout is 120,000ms so I'm unsure why this is happening because the entire request/response cycle at high load does not exceed 10s as viewed in our monitoring. Results from wrk2 are as follows resulting in 610 timeouts over 30 seconds:

```
wrk -c50 -t2 -d30s -R100 https://some-url
Running 30s test @ https://some-url
  2 threads and 50 connections
  Thread calibration: mean lat.: 9223372036854776.000ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 8380.416ms, rate sampling interval: 17661ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    20.60s     4.63s   28.31s    64.71%
    Req/Sec     1.83     13.74   200.00     98.19%
  73 requests in 30.72s, 5.03MB read
  Socket errors: connect 0, read 0, write 0, timeout 610
  Non-2xx or 3xx responses: 1
Requests/sec:      2.38
Transfer/sec:    167.60KB
```
Not sure how to interpret this but it results in an average of 2.38 requests per second actually being handled by the Koa server.

**Comment by juliangruber** [comment]
`setTimeout` will callback not early than what you specified, but can indeed call back later when the event loop is busy

**Comment by juliangruber** [comment]
with high load, keep in mind that even if the endpoint you're requesting is cached, node could run out of sockets for new requests and thus take a bit longer

**Comment by dtothefp** [comment]
@juliangruber could Node running out of sockets be resulting in the "Socket errors" timeouts being reported by wrk2 in the 3rd part of my question, and if so is there a way for me to remedy this?

**Comment by juliangruber** [comment]
yeah that's most likely what's happening. try bumping the limit of available sockets, eg `ulimit -n 99999`

**Comment by dtothefp** [comment]
@juliangruber I think our `ulimit` and potentially concurrent connections are limitied by NGINX reverse proxying the server on EC2, found some info in these articles:

http://blog.yld.io/2016/02/08/squeeze-the-juice-out-of-node

https://www.jayway.com/2015/04/13/600k-concurrent-websocket-connections-on-aws-using-node-js/

**Comment by juliangruber** [comment]
It's limited by a bunch of factors, but yeah the reverse proxy in front can be one of them. Since you already found some helpful articles and since this is not strictly related to koa - it's really a node issue after all - I'm going to close this.

Feel free to reach out in #koajs on freenode or StackOverflow, if you have additional questions regarding this topic.
