### ISSUE TITLE
It may be a naive question, but I'm confused with the promise behavior

### ISSUE THREAD

**Issue by thelinuxlich** [koajs/koa#785]
So I have a middleware doing something like this:

```javascript
module.exports = async(ctx, next) => {
   dbOperation();
   dbOperation();
   dbOperation();
   dbOperation();
   dbOperation();
   await next();
}
```

And I see that not all dbOperations are being executed, but if I change to this:

```javascript
module.exports = async(ctx, next) => {
   await dbOperation();
   await dbOperation();
   await dbOperation();
   await dbOperation();
   await dbOperation();
   await next();
}
```
Then it works, so is the request finishing before all Promises are correctly dispatched?

**Comment by tj** [comment]
They won't be executed sequentially of course but they should still execute just fine. Can't comment on the Babel implementation though, maybe a bug? Unrelated to Koa though.

**Comment by PlasmaPower** [comment]
Are you sure your database operations will work even if they aren't run in order?

**Comment by PlasmaPower** [comment]
Also, they aren't guaranteed to complete before next. Maybe you're looking for this?

```js
await Promise.all(dbOperation(), dbOperation(), dbOperation(), ...).then(next);
```

**Comment by thelinuxlich** [comment]
I don't need to wait, I just need to be sure they were acnowledged by the database server. But it seems to happen only if I await all of them

**Comment by tj** [comment]
Those situations are a little tricky since it's either-or. You could `await` _after_ the `await next()` but fire them off before, but then you're blocking on the response as well. 

If you do a `Promise.all([a, b, c]).catch(console.error)` before or after it should still work fine but you have to either `await` it and block or just do something else with the potential error.

**Comment by thelinuxlich** [comment]
So the final answer is there I need to await to guarantee these db promises are dispatched? I don't need their results.

**Comment by PlasmaPower** [comment]
@thelinuxlich The final answer is that the code you've gave us works, the problem is probably in `dbOperation` (or it might be in Babel, but that's very unlikely).

**Comment by PlasmaPower** [comment]
> I don't need to wait, I just need to be sure they were acnowledged by the database server

I don't think this is your problem, but if you need them acknowledged (but not necessarily to succeed) then do `await Promise.all(dbOperation(), dbOperation(), ...).then(next)` which will probably also accidentally fix your main problem.

**Comment by tj** [comment]
Yea if you don't need to wait, then just doing `doOperation()` is fine, but you'll want to `doOperation().catch(fn)` to have some sort of error logging

**Comment by PlasmaPower** [comment]
Also, for general debugging, try `process.on('unhandledRejection', console.error)`. That will print any promise rejections (errors) not caught.

**Comment by thelinuxlich** [comment]
Thanks for all the great tips, guys!
