### ISSUE TITLE
Swagger support?

### ISSUE THREAD

**Issue by mmc41** [koajs/koa#790]
Any plans for swagger support in Koa ? I am very interested in using KoaJs for REST API's because of it's modern design but the lack of swagger support blocks me.

**Comment by stojanovic** [comment]
I don't think it makes sense to support swagger or any library in framework's core.
But you can use a separate module for that, ie. https://www.npmjs.com/package/swagger-koa, there's a few more on NPM, I don't use swagger so I am not sure which one is the best.

**Comment by yorkie** [comment]
There is an existing module to provide what you want, check https://github.com/rricard/koa-swagger.

**Comment by juliangruber** [comment]
closing, as there seem to be sufficient solutions for this is user space
