### ISSUE TITLE
Turning off 'koa deprecated' warnings?

### ISSUE THREAD

**Issue by coodoo** [koajs/koa#791]
Is it possible to turn off `koa deprecated Support for generators will been removed in v3` warnings for `koa v2.x`? It somewhat clustered the terminal window, thanks.

**Comment by chentsulin** [comment]
why not just convert middleware via koa-convert?

**Comment by coodoo** [comment]
That could do the trick but would rather having cleaner code with fewer temporary fillers.

**Comment by chentsulin** [comment]
Koa use depd npm module to display deprecated message under the hood, so you can set NO_DEPRECATION=koa to disable it.

**Comment by coodoo** [comment]
Sounds good, thanks for the tip!
