### ISSUE TITLE
Change * (asterisk) position in generator declarations in the docs

### ISSUE THREAD

**Issue by chrisngobanh** [koajs/koa#799]
In the docs, we are declaring generators like this: `function *() { ...`

However, `function` and `*` are part of the same keyword. So, the correct way to declare a generator is like this: `function* () {...` or like `function*() {...`

Reference:
[Mozilla Developer Network JS Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*)
[Airbnb's JavaScript Style Guide](https://github.com/airbnb/javascript#generators--spacing)

**Comment by stojanovic** [comment]
Both `function*` and `function *` works the same.
This is just a matter of style, not functionality, and since Koa 2.x is using async/await instead of generators in my opinion this is not important at all.

**Comment by tj** [comment]
agreed, these kinds of issues aren't helpful or productive sorry!
