### ISSUE TITLE
use Destructuring for require module

### ISSUE THREAD

**Issue by fundon** [koajs/koa#810]
Currently, just Node.js **v6** enable `destructuring` by default. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

Example:

From:

```js
const isIP = require('net'). isIP;
const getType = require('mime-types').contentType;
```

To: 
```js
const { isIP } = require('net');
const { contentType: getType } = require('mime-types');
```

**Comment by fl0w** [comment]
I feel this is unnecessary, unless there's an advantage I'm unaware off. I much rather wait for modules to are natively supported and just follow that convention (similar to how we wait for `async`/`await` currently for a `test/` brush up (#703))

**Comment by fundon** [comment]
Related to https://github.com/nodejs/node/pull/8680.

**Comment by juliangruber** [comment]
Ideally all calls to `require()` happen at app boot time so performance shouldn't matter much here.
