### ISSUE TITLE
@next is confusing across all packages

### ISSUE THREAD

**Issue by niftylettuce** [koajs/koa#812]
We should standardize how we address packaging this version-wise, and then go out to all packages using Koa@next and let them know of the standards.  This is super confusing to end-users.  It seems like Koa@next is unstable by not being the latest.  Is Koa@1.x even really used as much as Koa@2.x?  It's just super confusing to package maintainers to have to make a version that's not the latest but SHOULD be used (since it's newer/better - we should just add deprecation notices to people if they install a new version that is using koa@next?  maybe we standardize the deprecation notice?).

**Comment by jonathanong** [comment]
i wish i knew usage statistics between v1 and v2.

**Comment by niftylettuce** [comment]
@jonathanong I reached out to NPM support, let's get them numbers!

**Comment by dead-horse** [comment]
we are using v1 with 100+ production apps and more than 40, 000 download per month(from our private registry). :)

**Comment by niftylettuce** [comment]
Is Koa@next not stable or something?  Can't we release an official version?  There's native Promise support now.

**Comment by PlasmaPower** [comment]
Quick observational study: koa-static introduced Koa v2 support on March 24th. Looking at the per month download graph [at npm-stat](https://npm-stat.com/charts.html?package=koa-static&from=2015-09-01&to=2016-08-31) I see no increase with the introduction of Koa v2. However, this is probably due in large part to koa-convert being used in place of v2 support. This does, however, imply that either Koa v2 is not being used very much (unlikely) or Koa v2 users are fine with using koa-convert for important parts of their system for the time being.

@niftylettuce The plan is to wait until async/await support arrives stable in Node, so users will get a more function*/yield style experience.

**Comment by niftylettuce** [comment]
@PlasmaPower that makes sense - any idea when async/await will get added in Node stable?  Is there a blog post about it or any GH issues on Node side?

**Comment by PlasmaPower** [comment]
@niftylettuce nodejs/promises#4 is the main one. It's landed in git, but it'll be a while before it's in a release. In addition, it'll probably be hidden behind a harmony flag first. We have yet to decide if we'll be releasing Koa v2 then, or when it becomes default, but it looks like we won't be waiting for it to be default (see discussion in #533).

**Comment by onbjerg** [comment]
@niftylettuce It's "expected" to come out in 2017 ([all finished proposals for the next versions of ES are listed here](https://github.com/tc39/proposals/blob/master/finished-proposals.md)).

**Comment by ide** [comment]
async/await is now in Chrome 55 (stable) without a flag and will likely ship with Node 8 which is slated for April 2017 and perhaps a Node 7.x release if V8 5.5 gets merged (in progress but who knows what the outcome will be). That being said, I don't think it's actually helpful to wait for Node 8 because even if the latest version of Node supports async/await, everyone on Node 6 or 7 for example will need to compile their async/await code to generators anyway...

**Comment by chovy** [comment]
Its working with node v7 and harmony flag: `--harmony-async-await`

**Comment by mrpatiwi** [comment]
Well, good news: https://github.com/nodejs/node/pull/11029

**Comment by bonesoul** [comment]
it happened: https://nodejs.org/en/blog/release/v7.6.0/

**Comment by jonathanong** [comment]
https://github.com/koajs/koa/commit/6c6aa4dab41bd3d11a62afe5de9fc144f9b2add3 :)
