### ISSUE TITLE
How to use koa to download the network image and preview the page

### ISSUE THREAD

**Issue by dounine** [koajs/koa#815]
I find a lot of information is not found, I want to use Java as a background service, the use of node+angularjs, but do not know how to use koa to get Java background provides the test images, and displayed in the angularjs side, can you help me, thank you very much.

**Comment by fundon** [comment]
1. http request client: get image from backend of Java (Java api: http://127.0.0.1:7001)

2. image pipe to res (`ctx.body = image`) (Koa api: http://127.0.0.1:3000)

3. browser http request client: get the image from Koa api.

**Comment by dounine** [comment]
Java background has been written, the front desk has been written, is poor koa this step does not know how to write, I use the koa-router and request module to write, but the picture does not come
.the following is my part of the code
```
get('/captcha', function *(next){
        var $self = this;
        yield (loginSer().captcha()
            .then(function (response) {
                $self.response.length = response.length;
                $self.response.type="image/png";
                $self.response.body = response;
}));
```
The result is the following
![image](https://cloud.githubusercontent.com/assets/7344514/18440475/d93005ea-793b-11e6-8631-40f4bee1127e.png)

**Comment by slaskis** [comment]
If I'm not mistaken I believe you should be able to yield the promise directly and rewrite that code like this:

```
get('/captcha', function *(next){
    const image = yield loginSer().captcha()
    this.type = 'image/png'
    this.body = image
}))
```

It depends on what response if though, but I'm assuming it's a Buffer of png data.

**Comment by jonathanong** [comment]
^ @slaskis's got it

@dounine closing :) please let us know if you have any other questions
