### ISSUE TITLE
Not able to set response body with erroneous status codes

### ISSUE THREAD

**Issue by erf** [koajs/koa#819]
When i return set the response status with an erroneous code, for example 400, and set a body with some value, for example a string `test`, the body returned is allways `null`.

I'm using koa version `1.2`.

**Comment by welladamm** [comment]
@erf a minimal working example, please?

**Comment by erf** [comment]
@welladamm sorry for not writing an example, i thought this was maybe by design. 
I created a minimal example and found Koa NOT to be the problem, rather it was Java's `getInputStream` would not read the stream when the http code was erroneous.
