### ISSUE TITLE
Converting simple route function

### ISSUE THREAD

**Issue by arcanewater** [koajs/koa#822]
So i just switched to Koa from Express, and started with Koa2, and the warning i get is 

Support for generators will been removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x app.js:14:5

for a simple route function like
```
app.use(route.post('/api/test', function*() {
    this.body = 'Post';
}));
```

So i documentation it says to use co, installed it but not sure how to properly use co on this kind of function like:
`app.use(co.wrap(route.post('/api/test', function*() {`

Or am i getting this wrong? Also maybe one example for basic function would be great in documentation but not sure if belongs to co or koa?

**Comment by dougwilson** [comment]
@arcanewater have you been able to read through https://github.com/koajs/koa#koa-v2 yet? You should be using the `async` keyword with Koa2 or you can use the `koa-convert` module (https://github.com/koajs/convert) to use generator functions with Koa2.

**Comment by arcanewater** [comment]
@dougwilson Thanks! Gonna read through that. So also this app.use(route.post)) should all be async?

**Comment by BruceHem** [comment]
Read the thing bro
