### ISSUE TITLE
Nodejs fails start after upgrading it to v.6.7.0

### ISSUE THREAD

**Issue by howardEagle** [koajs/koa#825]
There is an error, which says, that something wrong in function render() in journalctl log. It shows whole page html and error, that this rendered html is not an object

**Comment by juliangruber** [comment]
can you post the error message please?

**Comment by fl0w** [comment]
I cannot confirm this locally (we just deployed v6.7, koa@2 on staging - seems to be working as expected).

What version of koa is this?

**Comment by juliangruber** [comment]
what is `journalctl` log even? please post some more context.

**Comment by PlasmaPower** [comment]
Not OP, but `journalctl` is the system log manager for systemd based versions of Linux. Most likely the Node.JS server is running as a systemd daemon.

**Comment by PlasmaPower** [comment]
Also, I think this error might be coming from your templating library instead of Koa, or at least the error isn't coming from Koa itself (we have no render function).  The full error would be appreciated.

**Comment by juliangruber** [comment]
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.7.0 doesn't reveal anything obvious. Does this issue strictly only appear with node 6.7.0?

**Comment by fl0w** [comment]
We've had 6.7 running (without a templating engine though) on staging under simulated load for a while now - no apparent issues for us. I think this is user-space or 3rd party lib related, not Koa itself (at least not Koa v2).

**Comment by jonathanong** [comment]
@howardEagle closing until you give us more info! i'm running 6.7 fine w/ both koa@1 and koa@2
