### ISSUE TITLE
Question: New project on v1 vs. v2

### ISSUE THREAD

**Issue by hrmoller** [koajs/koa#826]
Hi,

We're about to start up a new project and we're a little unsure whether we should choose to go with v1 versus v2-alpha.

It's a relatively small project which will hit our production lines within this year. It's our first project based on koa but we have several projects running on Express already.

Our main concern is whether v2 will be held up to date against v1. I.e. if a new feature is implemented in v1 will it then also be in v2?

In other parts of our project we're expecting to be use `async/await` why our babel setup will be able to handle that syntax no matter if we're on v1 or v2 anyways.

Any advise would be appreciated.

**Comment by ShimShamSam** [comment]
async/await just landed in  V8, so if you use the Node nightly build (v7.x) with the --harmony flag, you don't have to do any transpiling on your server code.

**Comment by fl0w** [comment]
With regards to features, there's really not that much to it. You should not think of koa as a framework but rather a library on-top of core http modules. I wouldn't worry to much.

**Comment by hrmoller** [comment]
Perfect! Thanks for your answers @ShimShamSam and @fl0w - we'll stick with v2😊
