### ISSUE TITLE
[suggestion] W3C Headers

### ISSUE THREAD

**Issue by jimmywarting** [koajs/koa#828]
Just wanted to see if you want to use my lib i created yesterday: [fetch-headers](https://www.npmjs.com/package/fetch-headers)

It has some good parts like for...of iterator, case insensitive, getAll, keys, values
...Follows the W3C spec

example:
```javascript
header = new Headers({
  accept: 'application/json']
})
header.append('accept': 'text/plain')

console.log([...headers]) // [["accept","application/json"],["accept","text/plain"]]
```

**Comment by juliangruber** [comment]
It's a great idea to use a specced API for this, even though it's still tagged as experimental. To me it seems like this makes immediate sense for client side code, however in node.js land the fetch() API hasn't really arrived yet - or at least as far as I'm aware of.

Therefore I personally vote for waiting with this and seeing how fetch() is adapted inside node land or even node core.

**Comment by jimmywarting** [comment]
Not sure fetch will arrive to node at all. Maybe that's why we have [node-fetch](https://github.com/bitinn/node-fetch)

I just wanted to break out the Headers part of two fetch libraries since it could be used more generic and not be tied to node-http, xhr, or fetch
IMO It's a good idea to break stuff into smaller modules so it can be incorporate to other stuff like koa, express and what else

Personally I have never used Koa. Just wanted to see if you were interested in this `¯\_(ツ)_/¯`

**Comment by juliangruber** [comment]
Gotcha! Yeah if you want to propose using this library, the simplest way to discuss this is when you make a pull request to this project. This also means that you need to look into the project a little to decide whether it's worth the effort. I can't remember this project having issues with header stuff really, so this would be more like a refactor.

If you still think it's a good fit, a pull request is greatly appreciated :) I'm closing for now, but open for you and other maintainers to reopen if I'm wrong.

**Comment by jimmywarting** [comment]
Can maybe do a pull request if it's appreciated
