### ISSUE TITLE
Question: Use legacy middleware inside of modern middleware

### ISSUE THREAD

**Issue by basickarl** [koajs/koa#830]
Hello! I've been trying to get this small example to work to try and understand Koa/middleware a bit better, but I ain't getting it to work.

```
'use strict';
const Koa = require('koa');
const app = new Koa();

const convert = require('koa-convert');
const bind = require('co-bind');

function* myGen(next) {
    // before
    console.log('myGen before');
    yield* next;
    // after
    console.log('myGen after');
}

function myFn(ctx, next) {
    let newMyGen = bind(myGen, ctx, next);
    let conMyGen = convert(newMyGen);
    conMyGen();

    // before
    console.log('myFn before');
    return next().then(() => {
        // after
        console.log('myFn after');
    });
}

app.use(myFn);

app.use(function(ctx, next) {
    console.log('body');
    ctx.body = 'done';
});

app.listen(3000);
```

The console displays the following:
```
myGen before
myFn before
body
myFn after
```

I'm not doing something right to get back to the rest of myGen function.

**Comment by PlasmaPower** [comment]
You shouldn't be binding it yourself, let convert do the magic:

```js
function myFn(ctx, next) {
    let conMyGen = convert(newMyGen);

    console.log('myFn before');
    conMyGen(ctx, () => {
        console.log('myFn after');
        return next();
    });
}
```

As with any middleware, converted middleware must be passed the context and a next function.

**Comment by basickarl** [comment]
@PlasmaPower Ah I see. I did try your example however it shows the following:

```
myFn before
myGen before
myFn after
body
myGen after
```

I was expecting:
```
myFn before
myGen before
body
myGen after
myFn after
```
Any ideas (I'm learning a lot from this)?

**Comment by fl0w** [comment]
In practice, your overcomplicating this here immensely to get the expected output.
The following would suffice (except you'd get a warning because koa is converting for you in this care):

```js
'use strict'
const Koa = require('koa')
const app = new Koa()

function* myGen(next) {
    console.log('myGen before')
    yield next
    console.log('myGen after')
}

app.use(myGen)
app.use((ctx, next) => {
  console.log('body before')
  return next().then(() => {
    console.log('body after')
  })
})
app.use(function(ctx, next) {
    console.log('body')
    ctx.body = 'done'
});

app.listen(3000)
```

If you want to avoid the generator* warning and convert yourself you'd do:
```js
'use strict'
const Koa = require('koa')
const app = new Koa()
const convert = require('koa-convert')

function* myGen(next) {
    console.log('myGen before')
    yield next
    console.log('myGen after')
}

function myGenFn() {
  return convert(myGen)
}

app.use(myGenFn())
app.use((ctx, next) => {
  console.log('body before')
  return next().then(() => {
    console.log('body after')
  })
})
app.use(function(ctx, next) {
    console.log('body')
    ctx.body = 'done'
})

app.listen(3000)
```

**Comment by basickarl** [comment]
Ah yes I see. I think I must make my story more clear however.

The reason I'm looking into this issue is because there is a module (old middleware) where it is setup like the following (notice the star `yield* next;`):
function* myGen(next) {
    // before
    console.log('myGen before');
    yield* next;
    // after
    console.log('myGen after');
}

The whole story is that I wish to use https://github.com/koajs/koa-range inside of https://github.com/lasso-js/lasso, to make lasso work with koa and ranges.

If I was to remove the star (like in your example) things would make more sense. I've been reading some of the other koa issues here on github and they explain that the stars aren't mentioned in general to not over complicate matters for users (I'd like to learn though). I hope this explains the situation a little better!

**Comment by basickarl** [comment]
I've gotten some success with send. I'll reopen if this becomes an issue again.
