### ISSUE TITLE
v2: Error handling 

### ISSUE THREAD

**Issue by tunnckoCore** [koajs/koa#831]
Hi. Yea think there's some mistake in the error handling in v2. If you wanna handle errors from middlewares using `error` listener you can't, because [lib/application.js#L136](https://github.com/koajs/koa/blob/v2.x/lib/application.js#L136). It always attachs `app.onerror` which in one side is okey, but in another is not, because it not emits `error` event - never called actually?

Wanna PR?

**Comment by tunnckoCore** [comment]
I think we can change it to

```js
      fn(ctx).then(() => respond(ctx)).catch((err) => {
        if (!this.listeners('error').length) {
          return this.onerror(err);
        }
        this.emit('error', err);
      });
```

**Comment by dead-horse** [comment]
can you provide a simple example to reproduce the problem?

we want this error pass to `ctx.onerror`, and `ctx.onerror` will emit error event in `app`.

**Comment by tunnckoCore** [comment]
Actually above snippet isn't so correct, so yea..

```js
    return (req, res) => {
      res.statusCode = 404;
      const ctx = this.createContext(req, res);
      const onerror = err => {
        if (!this.listeners('error').length) {
          return ctx.onerror(err)
        }
        this.emit('error', err, ctx)
      };
      onFinished(res, onerror);
      fn(ctx).then(() => respond(ctx)).catch(onerror);
    };
```

> can you provide a simple example to reproduce the problem?

hm. it's seems it works with latest "alpha7" currently.

```js
var Koa = require('koa')
var app = new Koa()

app.on('error', function (err) {
  console.log(arguments)
})
app.use(function () {
  asd
})
app.listen(1234)
```

Okey. So we can close this one, but I can't get from where `error` is fired actually? Haha
