### ISSUE TITLE
Can't set cookies because app can't detect https?

### ISSUE THREAD

**Issue by House3272** [koajs/koa#835]
I'm using Nginx to upstream certain api routes.
Since Nginx is where the https encryption takes place, Koa can't detect it?
So when attempting to set cookies, I get "cannot send secure cookie over encrypted connection"

I did find [this commit](https://github.com/pillarjs/cookies/commit/51006921f0d57fba18bad0313e392c9610852e8b) which seems to address this.
However, I can't figure out how to use it.

**Comment by jonathanong** [comment]
have you tried `app.proxy = true`?

**Comment by House3272** [comment]
Nope! Thanks much.

**Comment by seminelee** [comment]
我设置了`app.proxy = true`仍然无效，设置`secure`属性仍然报错
I set `app.proxy = true` . But setting the `secure` attribute still gives an error.
``` js
ctx.cookies.set(
      'key', 
      'value',
      {
        secure: ctx.request.secure
      }
    )
```
