### ISSUE TITLE
console.log(require.cache) fails when koa is present

### ISSUE THREAD

**Issue by paulpflug** [koajs/koa#837]
``` js
koa = require('koa')
console.log(require.cache)
```

will fail because of the custom `inspect` implementation in [`context.js`](https://github.com/koajs/koa/blob/master/lib/context.js#L27), which uses the custom `toJSON`, which relies on a properly set `this`, which is not the case.

not very important. But noteworthy - I guess
At least is costed me some time to figure it out.

**Comment by skbolton** [comment]
I've been chasing down multiple angles at this and I can't seem to get my finger on whats going on.
`console.dir(require.cache)` works fine.`require.cache` even works fine as a variable for whatever reason `console.log clashes with `inspect()` inside of context.js.

**Comment by skbolton** [comment]
I think it has something to do with the module.exports of the file being the same value as the delegate. Not saying this is a proper solution but moving context.js to a class definition instead of a functional shared pattern worked.

**Comment by skbolton** [comment]
Found the culprit
In nodes documentation of util package
```
// Provide a hook for user-specified inspect functions.
  // Check that value is an object with an inspect function on it
  if (ctx.customInspect && value) {
    const maybeCustomInspect = value[customInspectSymbol] || value.inspect;

    if (typeof maybeCustomInspect === 'function' &&
        // Filter out the util module, its inspect function is special
        maybeCustomInspect !== exports.inspect &&
        // Also filter out any prototype objects using the circular check.
        !(value.constructor && value.constructor.prototype === value)) {
      let ret = maybeCustomInspect.call(value, recurseTimes, ctx);

      // If the custom inspection method returned `this`, don't go into
      // infinite recursion.
      if (ret !== value) {
        if (typeof ret !== 'string') {
          ret = formatValue(ctx, ret, recurseTimes);
        }
        return ret;
      }
    }
  }
```

**Comment by juliangruber** [comment]
this was discussed before, and while I can't remember the exact issue we decided this is a node problem and we want to keep our inspect property

**Comment by PlasmaPower** [comment]
I don't think we discussed this exact question before, but we probably did discuss `this` being undefined with another function. https://github.com/koajs/koa/issues?utf8=%E2%9C%93&q=is%3Aissue%20inspect%20OR%20toJSON%20

Since this is more builtin to Node and doesn't involve rebinding functions manually I'm more inclined to support it.

**Comment by skbolton** [comment]
Well if pr [605](https://github.com/koajs/koa/pr/605) happens (changing from a shared object to a class) then this error will be gone as well.

**Comment by PlasmaPower** [comment]
@skbolton you can use the `#605` which automatically links the issue or pull request: #605 (also your link doesn't work)

**Comment by skbolton** [comment]
Learn something everyday, fixed.
