### ISSUE TITLE
Using koa 1.2.4, TypeError: next is not a function

### ISSUE THREAD

**Issue by resistdesign** [koajs/koa#840]
Seems to be a breaking change within a minor release. Everything works a couple minors back but the latest gives an error. Was this intended? Does koa use semver or no?

**Comment by PlasmaPower** [comment]
Can you give us some code to replicate it? If downgrading Koa fixes it, then we might have a problem.

**Comment by slaskis** [comment]
I don't see [any change](https://github.com/koajs/koa/compare/1.2.3...1.2.4) that might cause this. So more information would be great!

**Comment by PlasmaPower** [comment]
What version did you have before? That patchset is only 1.2.3 -> 1.2.4.

**Comment by resistdesign** [comment]
Sorry, the issue was a plugin. :)
