### ISSUE TITLE
this.Response.redirect(url) doesn't work at all, anybody can help?

### ISSUE THREAD

**Issue by wenboSky** [koajs/koa#841]
In one of my middleware, I use this.response.redirect('/route') to try to jump to a route, and I hope client React Router to handle this route, but the url doesn't change at all, the browser display no response from koa server. How can I address this issue? Thanks guys.

**Comment by PlasmaPower** [comment]
Can you give us some code to replicate this? Most likely the problem does not lie in the redirect function.

**Comment by wenboSky** [comment]
Thanks guy, i used Koa-mount and Koa-router as following:

`//The following doesn't work.
app.use(mount('/signIn', function* (next){
 this.response.redirect('/newUrl');
}));
//The following works well.
router.get('/signin', function(){
  this.response.redirect('/newUrl');
})`

What's the different? BTW, I'm new on Koajs, maybe this is a stupid question.

**Comment by PlasmaPower** [comment]
For future visitors, I'm pretty sure the issue got figured out and it wasn't redirect itself.

**Comment by PlasmaPower** [comment]
Or not, was that close accidental?

**Comment by wenboSky** [comment]
Thanks guy, i used Koa-mount and Koa-router as following:
`
//The following doesn't work. 

app.use(mount('/signIn', function* (next){ this.response.redirect('/newUrl'); })); 

//The following works well. </br>
router.get('/signin', function(){ this.response.redirect('/newUrl'); })
`
What's the different? BTW, I'm new on Koajs, maybe this is a stupid question.

**Comment by PlasmaPower** [comment]
Is it the capitalization? `signIn` vs `signin`?

**Comment by wenboSky** [comment]
that should be `signin` for both, it's mistake editing here.

**Comment by PlasmaPower** [comment]
If you put a `console.log` in the not working version's function, I'm assuming it doesn't trigger?

**Comment by wenboSky** [comment]
yes, you're right. What's the problem?

**Comment by PlasmaPower** [comment]
I can't tell without the rest of the code, but it's definitely not the mount itself. I just made [this](https://gist.github.com/c4b9acc801a7afdbef746d8881c3f70b
) for testing, and it works fine. Are you sure the redirect isn't after a 404 handler or similar? Most likely one of your previous middleware functions isn't calling next, stopping the chain there.

**Comment by PlasmaPower** [comment]
Oh, also, you can just use `this.redirect(...)` instead of accessing it directly through the response object.

**Comment by wenboSky** [comment]
Thanks guy, I will try to comment other middleware code to see whether this can work, then get back to here, any way, thank you very much.

**Comment by wenboSky** [comment]
@PlasmaPower , guy, I have addressed this issue, it's a mistake, the project used Koa2 not Koa, so the middleware cannot be executed. That's it. thank you.
