### ISSUE TITLE
Recommendations for setting cookies behind load balancer that terminates SSL

### ISSUE THREAD

**Issue by djbobbydrake** [koajs/koa#844]
We have an architecture where secure requests go through an SSL-terminating load balancer. That request is then sent to nginx, and then hits the node js application. Within, the node js application, we are using Koa (ctx.cookies) to set a secure cookie, which then crashes our server with `Error: Cannot send secure cookie over unencrypted connection`. Is it possible to set a secure cookie within this architecture, or are we stuck with setting non-secure cookies?

I'm setting `app.proxy` to `true` but am still seeing issues when trying to set a secure cookie.

**Comment by djbobbydrake** [comment]
Nevermind... I got this working. It was a misconfiguration on the nginx side.

**Comment by jyoti007** [comment]
@djbobbydrake How you have solved this issue. I am facing same

**Comment by ozanmuyes** [comment]
I'm not sure but probably by setting the `X-Forwarded-Proto` header to `https` on client side.
