### ISSUE TITLE
Native async..await is here. Make v2 the official release?

### ISSUE THREAD

**Issue by dj-hedgehog** [koajs/koa#845]
Since Node v7 brings native `async...await` behind the `--harmony-async-await` flag do you consider making v2 already the official release?

**Comment by jonathanong** [comment]
see https://github.com/koajs/koa/issues/533 :)

**Comment by dj-hedgehog** [comment]
Sorry, I was actually subscribed to #533 but it is hard to keep track of such long discussions.
