### ISSUE TITLE
koa2 convert bug

### ISSUE THREAD

**Issue by einsqing** [koajs/koa#851]
```js
koa.use(convert(hbs.middleware({
    extname: '.html',
    viewPath: ['./www/admin', './www/home'],
    layoutsPath: './www',
    partialsPath: ['./www/admin', './www/home'],
    disableCache: true
})));

koa.use(async(ctx, next) => {
    const render = ctx.render;
    ctx.render = async function _convertedRender() {
        return co.call(ctx, render.apply(ctx, arguments))
    }

    await next();
});

await ctx.render('index_index');
```

###Question###
If I open the cache, view rendering not to come out, when I closed the cache, the view can render.

###I recorded a GIF###
http://www.wemallshop.com/hbs.gif

###Result###
![497d7471-fbc4-48db-9527-1f7cfba7b8af](https://cloud.githubusercontent.com/assets/7685948/20129791/533c89b6-a68d-11e6-9816-d4cb98adb7e1.png)

Actually return data, but this. The body has no output to the browser

**Comment by fl0w** [comment]
I'm not sure this should be considered as a bug, as `koa-convert` is a best-effort convert, not a guarantee. Hacking both a 3rd-party middleware and the core render function itself and then reporting it like a bug seems ... inappropriate. Maybe I misunderstood something.
