### ISSUE TITLE
How to accept the data from the post?

### ISSUE THREAD

**Issue by cephiroth** [koajs/koa#853]
I used the “koa-generator” generated project, which quoted the “koa-bodyparser”, I accept post request, but can not accept “ctx.request.body” data, would like to ask, how can the correct access to data

**Comment by scttcper** [comment]
Do you have a code snippet we can look at? Have you enabled koa-bodyparser as middleware that is before your post request? check that your use matches the docs https://github.com/koajs/bodyparser/tree/master#usage

**Comment by cephiroth** [comment]
Here is my code.
app.js:
>const Koa = require('koa');
const app = new Koa();
const router = require('koa-router')();
const views = require('koa-views');
const co = require('co');
const convert = require('koa-convert');
const json = require('koa-json');
const onerror = require('koa-onerror');
const bodyparser = require('koa-bodyparser')();
const logger = require('koa-logger');

>const index = require('./controllers/index');
const users = require('./controllers/users');

>// middlewares
app.use(convert(bodyparser));
app.use(convert(json()));
app.use(convert(logger()));
app.use(require('koa-static')(__dirname + '/public'));

>app.use(views(__dirname + '/views', {
  extension: 'ejs'
}));

>// logger
app.use(async (ctx, next) => {
  const start = new Date();
  await next();
  const ms = new Date() - start;
  console.log(`${ctx.method} ${ctx.url} - ${ms}ms`);
});

>router.use('/index', index.routes(), index.allowedMethods());
router.use('/users', users.routes(), users.allowedMethods());

>app.use(router.routes(), router.allowedMethods());
// response

>app.on('error', function(err, ctx){
  console.log(err)
  logger.error('server error', err, ctx);
});
module.exports = app;

index.js
>'use strict';

>const router = require('koa-router')();
 router.post('/test', async (ctx, next) => {
        ctx.body = JSON.stringify(ctx.request.body);
});

**Comment by cephiroth** [comment]
>{ request:
   { method: 'POST',
     url: '/index/test',
     header:
      { host: '172.20.11.86:3000',
        connection: 'keep-alive',
        'content-length': '3089',
        origin: 'http://172.20.11.86:3000',
        'user-agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1',
        'content-type': 'text/plain;charset=UTF-8',
        accept: '*/*',
        referer: 'http://172.20.11.86:3000/index?id=1001',
        'accept-encoding': 'gzip, deflate',
        'accept-language': 'zh-CN,zh;q=0.8' } },
  response: { status: 200, message: 'OK', header: {} },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/index/test',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }

This is the console print ctx's content

**Comment by tj** [comment]
Here's an example as well:
https://github.com/cojs/co-body

There isn't necessarily one specific "koa way" to do it, but definitely some reasonable options out there.
