### ISSUE TITLE
Let me introduce how to improve performance easily.

### ISSUE THREAD

**Issue by ifsnow** [koajs/koa#855]
koa's concept is really terrific.

I'm sure `koa v2 + async/await` will be the mainstream in the future.
but, I guess someone needs to use `koa v1` for various reasons.

[co-booster](https://github.com/ifsnow/co-booster) is a performance tuning version of `co`.
It's fully compatible with `co`. and, works fastly in many cases.

`co` is used in a core logic of `koa v1` and `koa-convert`.
so, I believe it makes `koa` better without much effort.

Here are my results using koa's benchmark script. (100 middlewares)

```
- koa v1 + nodejs v4.4.7 : 11% better
- koa v1 + nodejs v6.9.1 : 13% better
- koa v2(legacy middleware) + nodejs v4.4.7 : 13% better
- koa v2(legacy middleware) + nodejs v6.9.1 : 14% better
```

I just wondered what author, contributors, and users think about.
I'd like to contribute to `koa` if I have a chance.

**Comment by juliangruber** [comment]
The numbers look good! Since co-booster is fully compatible with co however, what do you think about merging your changes into co instead?

**Comment by fengmk2** [comment]
Look good, I think co-booster and merge together will be good choice for the whole co solution.

**Comment by ifsnow** [comment]
I agree to merging co-booster into co. It depends on the decision of co's maintainers. because it can be a module that is not mature yet. 

I tried a lot to confirm about the compatibility and performance. but, I think it should be checked more thoroughly because it is used by many projects.

**Comment by marvinhagemeister** [comment]
@ifsnow Thats awesome, great work! I'm sure the people over at `co` can help with testing and validating the performance. One way to start the discussion would be to open a PR there 👍

**Comment by ifsnow** [comment]
@marvinhagemeister I'm so flattered. opened a PR in `co`. I hope it will pay off.

**Comment by jonathanong** [comment]
yes, you can make PRs to `co`. koa just uses that library, so you'll have to push changes there.

however, long term, we are using native `await`, so i'm not really interested in improving performance with generators.
