### ISSUE TITLE
Koa2: setting ctx.status prior to ctx.redirect call does not yield any effect.

### ISSUE THREAD

**Issue by gnrlbzik** [koajs/koa#857]
Is this a bug?

per documentation https://github.com/koajs/koa/blob/v2.x/docs/api/response.md#responseredirecturl-alt

if i set ctx.status prior ctx.redirect call my response status should be set to what ever is i specify it to, but this does not happen in my case. I have middle wear that redirects visitor for any path that does not fall under exception if they do not have authenticated session.

```
        if (authRequired && !ctx.isAuthenticated()) {
            ctx.status = authConfig.authRequiredRedirect.statusCode;
            ctx.redirect(authConfig.authRequiredRedirect.path);
        }
```

![image](https://cloud.githubusercontent.com/assets/658148/20578672/0f30fa84-b18e-11e6-9461-ea3a5ee18d79.png)

Am I missing something?

**Comment by jonathanong** [comment]
do you mind making a PR with a failing test case?

**Comment by gnrlbzik** [comment]
I will after i test few more things.

**Comment by gnrlbzik** [comment]
@jonathanong is there a guide how collaboration should be done?

or this is good enough?

**Comment by jonathanong** [comment]
yes, this a great example of making a failing test-case :)

however, i'm not sure why you're using `redirect()` to set a non-redirect status code. you might as well just set the location header

**Comment by gnrlbzik** [comment]
Maybe i am doing this wrong. Possibly my understanding of this subject is off. let me consult web for a bit.

Original goal was to respond to none-auth user with 401 and redirect them to login page.

**Comment by gnrlbzik** [comment]
yeah, i am doing it wrong. i will close both : ) thanks for help
