### ISSUE TITLE
ctx.throw response

### ISSUE THREAD

**Issue by sorahn** [koajs/koa#860]
Hey guys, I saw your response for ctx.throw not supporting a custom response in #194. however I noticed, that it only errors and forces the body when you throw a 500.   If I use `ctx.throw(400, JSON.stringify({some: "data"}))` it works just fine.

Any chance you would re-consider allowing custom responses for 500 errors too?

**Comment by AliasT** [comment]
this might work:
```javascript
ctx.throw(500, JSON.stringify({some: "data"}), { expose: true })
```
but it seems like this feature is just designed  for user-level error
[https://github.com/koajs/koa/blob/master/lib/context.js#L70](https://github.com/koajs/koa/blob/master/lib/context.js#L70)

**Comment by sorahn** [comment]
Interesting, I'll check that out as soon as I can.  Thanks!

Looking at that code (and in the 2.x) branch, there doesn't seem to be anything that Koa is doing that is causing the error not to go through by default.  Maybe it's node doing that.

**Comment by jonathanong** [comment]
i'm not sure what you're trying to do. i don't know why you'd ever want an `err.message` to be a json string.

**Comment by jonathanong** [comment]
i see you've opened up https://github.com/jshttp/http-assert/issues/7

**Comment by sorahn** [comment]
What @AliasT suggested worked.

I didn't open that one, I just responded to it.  But I wanted koa to return a 500 error, have ctx.body be JSON so that the service that is consuming it could print useful errors to the customer.

I Want to use ctx.throw because that stops the request immediatly and doesn't traverse through any other middleware.
