### ISSUE TITLE
Take Charge - Move to 2.0

### ISSUE THREAD

**Issue by tnsupport** [koajs/koa#862]
It is time to just move to 2.0 now that node 7 allows async await with the flag --harmony-await-async.  And it is probable V8 with async await will be in Node without the flag in a few months.  

Even for production, working with the current flag beta condition is better that the confusion of multiple versions of Koa.   

Right now trying to use Koa 2 is too damn confusing with most docs, middleware for vers 1,  And the version thing is far too confusing to explain to others.  

Due to the whole async delay and the babel mess,  it's just easier to use Express right now, even though it's stupid for the longer run.  The sooner this is resolved, the faster the large Express community can switch over and bring along all the resources of Express.    And if there are any issues with the flag version, the switch to koa 2.0 will help resolve them faster.  

It's time to take charge - move forward - time to make it easy for Koa2 to be the node framework of choice.

**Comment by cesarandreu** [comment]
If someone is confused with 2.0 then I'd argue they're not familiarized enough with the ecosystem to be using the async/await flag in the first place.

**Comment by tj** [comment]
We have an issue for this.
