### ISSUE TITLE
BUG in set status = 200

### ISSUE THREAD

**Issue by baryon** [koajs/koa#865]
in my router
```
router.get('/test', function (ctx, next) {
    ctx.status = 200;
});

```

test
`http://localhost:3000/api/test`

got 
```
{
  "statusCode": 404,
  "error": "Not Found",
  "message": "missing"
}
```

if I remove the middleware, everything is OK

**Comment by PlasmaPower** [comment]
What's the desired result? You might want to add `ctx.body = ''` or `return next()`.

**Comment by baryon** [comment]
`ctx.status = 200;` is a very normal code.

**Comment by fl0w** [comment]
The bug isn't in Koa lib. It's either in your middleware-stack or how you compose them.
What router are you using?

**Comment by baryon** [comment]
Sorry
