### ISSUE TITLE
how to deal ajax with koa....

### ISSUE THREAD

**Issue by lxlhum** [koajs/koa#866]
I use Koa as my http framework.
I request a node router with ajax.
The router will deal a task , which is reading and writing a file.but I can not receive right response from ajax.The response backs an “error“ all the time.

By the way, I userd the same programs in Express, the response backs an “success” all the time.
I don't know why.....
I need help,thank you

**Comment by PlasmaPower** [comment]
Can you post your code? You can't simply change express to Koa without changing your middleware.

**Comment by lxlhum** [comment]
I have been solved the issue,thank you.
