### ISSUE TITLE
v2 app.on('error') confusing

### ISSUE THREAD

**Issue by scttcper** [koajs/koa#871]
This sample application only returns 500.
```javascript
const Koa = require('koa');

const app = new Koa();
app.on('error', (err, ctx) => {
  console.log(err);
  console.log(ctx.status);
});
app.use(() => {
  throw new Error('Terrible Error');
});
app.listen(3000);
```

Output:
```
Error: Terrible Error
    ... error stack etc..
404
```

Why is ctx.status 404 in the app.on 'error'?

**Comment by scttcper** [comment]
It looks like the status is added after the error is emitted? https://github.com/koajs/koa/blob/v2.x/lib/context.js#L110 For some reason that's not what I expect to happen.

**Comment by PlasmaPower** [comment]
The error event is made for logging purposes and such. You probably want something like this at the start of your middleware chain (maybe also put one after your rendering code for a fancy error page if this is user exposed):

```js
app.use((ctx, next) => {
  return next().catch(function (err) {
    ctx.status = err.status || 500;
    if (err.expose) {
      ctx.body = err.message;
    }
  });
});
```

**Comment by scttcper** [comment]
Exactly, I'm looking to do logging but of only server errors. It seems a little weird to log a 404 but give the user a 500

**Comment by PlasmaPower** [comment]
Oh, oops. I thought you were trying to change the status.

**Comment by scttcper** [comment]
Meh. It's not that confusing once you read the code.
