### ISSUE TITLE
did koa version follow semver?

### ISSUE THREAD

**Issue by AntSworD** [koajs/koa#872]
I want get the version of koa by program，but i found `koa@2.0.0-alpha.7` after `koa@2.0.0`,  it is not same with [semver](http://semver.org/). I'm confuse.

**Comment by dead-horse** [comment]
koa@2 is not official released, so it is still in alpha. http://semver.org/#spec-item-9

koa@1 follows semver strictly.

**Comment by AntSworD** [comment]
@dead-horse but `koa@2.0.0` already release, I think the alpha was before the patch version [](http://semver.org/#spec-item-11). If I misunderstand ?

**Comment by tj** [comment]
2.0.0 may have been an accident, I don't think you can remove them from npm now

**Comment by AntSworD** [comment]
@tj @dead-horse  er.. I see. THX!

**Comment by giggio** [comment]
Yes, it is not following semver and it is confusing. You should be working on `2.0.1`, then, and let the incorrect `2.0.0` die.
