### ISSUE TITLE
ctx.protocol can never be https?

### ISSUE THREAD

**Issue by mosquito1994** [koajs/koa#878]
Hello I'm using koa2 in one of my project. When the project moved to https I found I cannot get the correct protocol https with `ctx.protocol`. Could you please tell me what to do to solve the problem?

**Comment by jonathanong** [comment]
are you hosting it on heroku or something? be sure to do `.proxy = true`?

**Comment by mosquito1994** [comment]
Got the solution. Here node need to redirect to another location in some ways, then change the url to `"//my.location.com"` rather than `ctx.protocol + "://my.location.com"` so that node doesn't need to get the protocol informaiton. And there are two ngnix between node and browser using http only, so node cannot read the https information.
