### ISSUE TITLE
koa failing on citgm AIX

### ISSUE THREAD

**Issue by gdams** [koajs/koa#883]
currently `citgm koa` fails on AIX because `make test` can't be used. AIX needs `gmake test` if there is a way an if statement could be added?

**Comment by fl0w** [comment]
Relates to discussion in https://github.com/koajs/koa/issues/703

**Comment by ilkkao** [comment]
Is it `make test` in package.json that causes node citgm to fail? That could be replaced with a small wrapper shell script that runs gmake for AIX and make for others. That would still not support Windows but that I think should be handled separately under #703

**Comment by gdams** [comment]
@ilkkao that is exactly what we need

**Comment by jonathanong** [comment]
let's merge with https://github.com/koajs/koa/issues/559
