### ISSUE TITLE
Querystring cache

### ISSUE THREAD

**Issue by n7olkachev** [koajs/koa#885]
Hi guys, reading request code I found that Koa uses simple object for querystring cache. Isn't it possible security vulnerability? Generating random querystrings will lead to infinite cache growing or I miss something? Maybe Koa should use something like LRU cache for it?

**Comment by jonathanong** [comment]
it's per-request, so it's not going to grow infinitely. however, a `Map` instance is better than a simple object.

**Comment by n7olkachev** [comment]
Oh, exactly. Thanks for explanation!
