### ISSUE TITLE
How to render/redirect inside a callback?

### ISSUE THREAD

**Issue by guzgarcia** [koajs/koa#887]
I have a problem. In my route, I need to create a PayPal payment. The SDK of PayPal says that I need to pass a callback to the `create` function. The problem comes when I try to redirect inside this callback: I get **Error: headers have already been sent**.

  ```javascript
paypal.payment.create(paymentData, (err, payment) => {
    if (err) {
      console.log(err);
      //ctx.render('payment_error');
    } else {
      ctx.session.paymentId = payment.id;
      let outcome = ''; // PayPal URL to proceed with payment

      payment.links.forEach((p) => {
        if (p.method === 'REDIRECT') {
          outcome = p.href;
        }
      });
      ctx.redirect(outcome); // error: headers have already been sent
    }
});
```

I'm pretty sure this is an asynchrony poblem: when the callback is executed, Koa is setting the headers at the end of the route function. So, when I try to redirect, the error is thrown.

How can I do this?

**Comment by guzgarcia** [comment]
Well, I solved this wrapping the payment inside a function and return a Promise.

**Comment by guzgarcia** [comment]
Solved wrapping the payment inside a function and returning a Promise.

**Comment by PlasmaPower** [comment]
You might also try Bluebird's promisify or promisifyAll utilities for convenience.
