### ISSUE TITLE
koa v2: ctx.status initially 404 rather than undefined.

### ISSUE THREAD

**Issue by sc0ttyd** [koajs/koa#888]
The  [koa-v2 documentation](https://github.com/koajs/koa/blob/v2.x/docs/api/response.md#responsestatus) states that:

> By default, response.status is not set unlike node's res.statusCode which defaults to 200.

Yet, it appears to be initially set to 404. If I make a request to the following simple test server:

```js
const app = new Koa();
app.use(ctx => console.log('status: ' + ctx.status));   // or ctx.response.status
const server = app.listen();
```

I get `status: 404` on the console.

**Comment by PlasmaPower** [comment]
Yes, that's the case. I thought we already fixed the documentation. Oops.

**Comment by PlasmaPower** [comment]
See #705, but the resolution there is incorrect

**Comment by sc0ttyd** [comment]
Slightly a shame in my particular case as I wanted `ctx.status` to be initially `undefined`, but hey ho, I can live with it :grinning:

**Comment by PlasmaPower** [comment]
@sc0ttyd you might try `ctx._explicitStatus && ctx.status || undefined`, but it's undocumented so it might break.
