### ISSUE TITLE
Bad '2.0.0' version published on npm

### ISSUE THREAD

**Issue by stephank** [koajs/koa#890]
There's an old `2.0.0` version published in npm. It's publish date is somewhere between alpha 3 and alpha 4.

```
'2.0.0': '2016-03-23T18:16:30.024Z',
'2.0.0-alpha.1': '2015-10-22T23:37:58.640Z',
'2.0.0-alpha.2': '2015-10-27T23:31:45.783Z',
'2.0.0-alpha.3': '2015-11-05T02:41:26.489Z',
'2.0.0-alpha.4': '2016-07-23T18:07:08.835Z',
'2.0.0-alpha.5': '2016-08-10T19:16:51.922Z',
'2.0.0-alpha.6': '2016-08-29T03:25:49.582Z',
'2.0.0-alpha.7': '2016-09-07T08:29:51.882Z'
```

However, when installing Koa 2 as `npm install --save koa@next`, npm creates a dependency `"koa": "^2.0.0-alpha.7"`, which will afterwards match with this `2.0.0` as the best option. The initial install does install alpha 7, but an `npm update` or `npm install` from initial checkout will 'update' to `2.0.0`.

I imagine this version will also eventually conflict with a final release. :)

**Comment by fl0w** [comment]
This is an old publish and I think there was talk about un-publishing that version because of the mixup.
`koa@next` is currently the preferred way. @jonathanong I think you had a comment about removing the old 2.0.0 tag?

**Comment by jonathanong** [comment]
https://github.com/koajs/koa/issues/839
