### ISSUE TITLE
404 status

### ISSUE THREAD

**Issue by shahen94** [koajs/koa#895]
```
export async function getPlaces(ctx, next) {
    const { error, data } = await PlaceModel.getPlaces(ctx.query);
    console.log(error, data);
    if (error) {
        return ctx.throw(422, error);
    }
    ctx.body = data;
}
```
Koa everytime sends 404 status and empty body, what i'm doing wrong ?

**Comment by CNBlackJ** [comment]
@shahen94 I also have this problem. Could you tell me how to fix it?

**Comment by BruceHem** [comment]
error and data must be undefined that's why u get 404

**Comment by CNBlackJ** [comment]
@shahen94 
I can get data, just fail to return data.

```javascript
module.exports = async(ctx, next) => {
  const books = await Book.find({ isDeleted: false })
  console.log(books) // success to output books
  ctx.body = books  // return 404
}
```

**Comment by shahen94** [comment]
Hey guys, i had a middleware which hindered to send response

**Comment by CNBlackJ** [comment]
@shahen94 
Hi buddy,
I just use `koa-bodyparser` and `koa-router`.

----

I have try below code just now, still cannot return data

```javascript
// app.js
const Koa = require('koa')
const Book = require('./db')
const app = new Koa()

app.use(async(ctx, next) => {
	const books = await Book.find({})
	ctx.body = books
})
app.listen(3000)
```

```javascript
// db.js
const mongoose = require('mongoose')
const bluebird = require('bluebird')
mongoose.Promise = bluebird
mongoose.createConnection('mongodb://localhost/dev');
const Schema = mongoose.Schema
const bookSchema = new Schema({
	title: String,
	price: Number
});
const Book = mongoose.model('book', bookSchema)
module.exports = Book

```

**Comment by shahen94** [comment]
can you please but log after first line in middleware, like this:
```
const books = await Book.find({})
console.log(books);
ctx.body = books
```

**Comment by CNBlackJ** [comment]
It print nothing, seems like it was blocked by `await Book.find({})`.

when i change `const books = await Book.find({})` to `const books = await 'I am a book.'`,
it works well.

**Comment by shahen94** [comment]
it means this issue isn't related to Koa itself, something wrong in your db

**Comment by CNBlackJ** [comment]
yeah, thanks man!
My mistake, I have fixed this problem.
