### ISSUE TITLE
Don't set Content-Length

### ISSUE THREAD

**Issue by alexhultman** [koajs/koa#902]
This header is set automatically by the HTTP module (much more efficient) and does not need to be set in the library. Setting Content-Type is fine since that is not something the HTTP module can infer.

**Comment by Akcbryant** [comment]
It appears that the HTTP node module isn't setting the content-length when koa doesn't set it explicitly.

**Comment by jonathanong** [comment]
yeah, the only time it _could_ be set is if you do `.end(buf)` without a `.write()`. however, it's impossible to know the content length is if the response body is streamed with `.write()`s

**Comment by Akcbryant** [comment]
This can probably be closed then.
