### ISSUE TITLE
Node officially supports async/await, it's 2.x release time!

### ISSUE THREAD

**Issue by Jabher** [koajs/koa#910]
> Until async/await is natively supported in Node Koa 1.x is the official release, however you may wish to adopt 2.x early by using Babel to compile. Koa 1.x generator-based middleware may be "upgraded" to the 2.x flavour using koa-convert.

Node 7.6 [released](https://nodejs.org/en/blog/release/v7.6.0/) today, with native async/await support (by [updating v8 to 5.5](https://v8project.blogspot.ru/2016/10/v8-release-55.html))!

**Comment by fl0w** [comment]
Discussion in #533 already ongoing. No need to open new issue.

**Comment by Jabher** [comment]
my bad :(
