### ISSUE TITLE
Error: Cannot find module [..]/my-koa-app.js

### ISSUE THREAD

**Issue by kevart** [koajs/koa#924]
```
node my-koa-app.js
module.js:472
    throw err;
    ^

Error: Cannot find module '[..]/koa_test/my-koa-app.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3

```

Steps to reproduce:

```
nvm install 7
yarn init
yarn add koa
node my-koa-app.js

```

Same issue following [these steps](http://koajs.com/#introduction) using npm.

There is a _koa_ folder under _node_modules_ but _my-koa-app.js_ is missing.

**Comment by fl0w** [comment]
It makes sense for node to not find a file that doesn't exist.

**Comment by kevart** [comment]
I indeed expected the file to exist. It looks like a quickstart, just copy/paste and see it running immediately.

**Comment by PlasmaPower** [comment]
See fl0w's edit. Also I'd recommend against using `yarn` as its templates are not official.
