### ISSUE TITLE
custom http code

### ISSUE THREAD

**Issue by thorinisme** [koajs/koa#927]
Currently koa seems to only handle standard code.

When i use a code like 420 with `ctx.throw('custom message', 420)` , koa replace it by a 500.
When i use ...
```javascript
const err = new Error('custom message');
err.status = 420;
err.expose = true;
throw err;
```
... koa throw the error `invalid status code: 420`

I need to use custom code. Is there a way to add custom code to koa ?

**Comment by fl0w** [comment]
Whenever you throw, it resets to default status. You'll want a middleware in front to catch and manipulate user facing errors, here a simplified version how our error handler/middleware works:

```js
const Koa = require('koa')
const app = new Koa()

// error handler
app.use(async (ctx, next) => {
  try {
    await next()
  } catch (err) {
    switch (err.code) {
      case 422:
        ctx.status = 422
        // simplified for brevity
        ctx.body = { error: err.message }
      default:
        // send stack and stuff to sentry
        ctx.status = 500
        ctx.body = { error: 'something else went wrong' }
    }
  }
})

app.use(async ctx => {
  // throws if not found
  ctx.body = await User.getById(ctx.request.body.id)
})
```

**Comment by thorinisme** [comment]
Hi thanks for answer but i still use an error handler.

`err.code` is undefined.
`err.status` give me 500

Problem is i need custom code. 422 is standard. 420 is not.

What i need is to use custom code for application errors like for example : my user didn't accept TOU
Goal is to open a specific view in my webapp. i don't want to use native codes for that cause i still use native codes.

**Comment by fl0w** [comment]
Yes, `err.code` is undefined. We do this (this was an excerpt from our code just to give you an idea). We're trying to avoid identifying errors by its messages.

**Comment by thorinisme** [comment]
so you don't use koa "native" error handling.

Can a dev of KOA answer me please ?

**Comment by PlasmaPower** [comment]
Look at the tests here: https://github.com/koajs/koa/blob/master/test/response/status.js

```js
statuses['700'] = 'custom status';
```

**Comment by thorinisme** [comment]
so good answer is 
```javascript
let statuses = require('koa/node_modules/statuses')
statuses['700'] = 'custom status';
ctx.throw(700);
```

Would be usefull to give access to statuses in app
