### ISSUE TITLE
need your help for hot-reloading server with webpack

### ISSUE THREAD

**Issue by budarin** [koajs/koa#929]
Hi everyone!

After reading the article [Hot reload all the things!](https://hackernoon.com/hot-reload-all-the-things-ec0fed8ab0#.5qeswpl2k) I've created a simple [koa-hot-reloading-server](https://github.com/budarin/koa-hot-reload).

Unfortunately it doesn't work while changes are recompile.
original server based on express works fine [express-hot-reloading-server](https://github.com/mhaagens/hot-reload-all-the-things)

the main thing is in this code:

```
import http from 'http'
import app from './server'

const server = http.createServer(app)
let currentApp = app
server.listen(3000)

if (module.hot) {
 module.hot.accept('./server', () => {
  server.removeListener('request', currentApp)
  server.on('request', app)
  currentApp = app
 })
}
```

I've translated it into koa:
```
import http from 'http';
import app from './server';

const port = 3000;

const appCallback = app.callback();
const server = http.createServer(appCallback);

let currentApp = appCallback;

server.listen(port);

if (module.hot) {
    module.hot.accept('./server', () => {
        server.removeListener('request', currentApp);
        server.on('request', appCallback);
        currentApp = appCallback;
    });
}

console.log(`Server running on: http://localhost: ${port}`);
```

it serves requests but doesnt reload servers new code, e.g. these lines are not have an action
```
        server.removeListener('request', currentApp);
        server.on('request', appCallback);
        currentApp = appCallback;
```

Help me please

**Comment by nickb1080** [comment]
You need to call `app.callback()` upon `module.hot.accept`. A difference between Koa and Express is that `express` "instances" are actually functions (which can be passed to `http.createServer directly) with extra properties on them, whereas `new Koa()` returns an object, with a method (called `callback`) which returns a function for use with `http.createServer`.

This should work:

```js
import http from 'http';
import app from './server';

const port = 3000;

let currentApp = app.callback();
const server = http.createServer(currentApp);

server.listen(port);

if (module.hot) {
    module.hot.accept('./server', () => {
        server.removeListener('request', currentApp);
        currentApp = app.callback();
        server.on('request', currentApp);
    });
}

console.log(`Server running on: http://localhost: ${port}`);
```

**Comment by budarin** [comment]
thanks for the explanation! 
I've made push to the project but it doesn't help - changes are not reloaded and after some changes server doesn't service request - page in status loading...

**Comment by nickb1080** [comment]
It seems to work fine for me -- adding logs shows that the number of listeners for `request` event is correct:

```js
import http from 'http';
import app from './server';

const port = 3000;

let currentApp = app.callback();
const server = http.createServer(currentApp);

server.listen(port);

if (module.hot) {
    module.hot.accept('./server', () => {
        server.removeListener('request', currentApp);
        console.log("after `removeListener`", server.listeners("request").length);
        // look in the console for this line ^^

        currentApp = app.callback();
        server.on('request', currentApp);
        console.log("after `on`", server.listeners("request").length);
        // ... and for this line ^^
    });
}

console.log(`Server running on: http://localhost: ${port}`);
```

**Comment by jonathanong** [comment]
going to close this as it's been inactive.

FWIW I think hot reloading apps is crazy. I personally use https://www.npmjs.com/package/node-dev. the server should spin up quickly, so u should only need reloading, not hot reloading.

**Comment by nickb1080** [comment]
In code bases with several hundred source files and thousands of node modules, I've seen startup time run to [several seconds](https://kev.inburke.com/kevin/node-require-is-dog-slow/) -- and much worse if using something like babel when developing. Being able to hot reload (particularly for things like running the tests -- or a specific subset of them) can dramatically speed up the feedback loop. It's not bulletproof though, but it has its uses.

**Comment by budarin** [comment]
Thanks for replay!I only use hot reloading for development purpose. 21:23, 15 марта 2017 г., Nick Bottomley <notifications@github.com>:In code bases with several hundred source files and thousands of node modules, I've seen startup time run to several seconds -- and much worse if using something like babel when developing. Being able to hot reload (particularly for things like running the tests -- or a specific subset of them) can dramatically speed up the feedback loop. It's not bulletproof though, but it has its uses.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.    С уважением Бударин Вадим

**Comment by pke** [comment]
does this only work with webpack or also parcel?

**Comment by sibelius** [comment]
@jonathanong does node-dev works well with babel 7?
