### ISSUE TITLE
Not getting the latest version 2.1.0

### ISSUE THREAD

**Issue by evoluzin** [koajs/koa#933]
While using npm update getting 1.3.0 as the latest version.

**Comment by magicdawn** [comment]
```sh
npm i koa@latest --save
```

**Comment by ilkkao** [comment]
@evoluzin you probably have something like `"koa": "^1.0.0"` in your `package.json`. `npm update` will respect semver.

**Comment by jonathanong** [comment]
fixed. `latest` is dumb...

**Comment by evoluzin** [comment]
thank you @jonathanong it works now.
