### ISSUE TITLE
Content Type not working

### ISSUE THREAD

**Issue by tomatau** [koajs/koa#937]
I'm building a fairly unusual use-case of a koa app boilerplate and when I try to migrate to koa2, every response is `Content-Type: application/octet-stream` unless I manually overwrite. This includes responses serving static assets! Most responses are `ctx.response.body = "<html>some string</html>"` and a few are plain JSON.

NB:
My app boilerplate is for a "universal/isomorphic" React boilerplate that abuses babel-runtime compilation and the node require.cache to get live updates to the server code. There's also some funky business with injecting routes and assets at runtime to improve testability. None of these factors affected the auto Content-Type in Koa1 so I've no idea why it would stop working for Koa2?

**Comment by magicdawn** [comment]
maybe use a koa@2 version koa-static

**Comment by tomatau** [comment]
```
"koa-static": "^3.0.0",
```

**Comment by PlasmaPower** [comment]
Can you give a minimal example? Most likely, the problem doesn't originate from Koa itself.

**Comment by tomatau** [comment]
I've drilled down to it being a problem with the "koa-webpack-middleware".

https://github.com/leecade/koa-webpack-middleware/blob/master/middleware/hotMiddleware.js#L7-L8

Thanks
