### ISSUE TITLE
Typo in the readme

### ISSUE THREAD

**Issue by slikts** [koajs/koa#943]
"Koa is a middleware framework that can take 3 different kinds of functions as middleware:"

It should say 2 instead of 3, since it only lists common and async functions, not generators.

**Comment by chinesedfan** [comment]
Btw, how about switch the list to match sequences of examples? Or switch examples.

Now the first one of the list is "Common function", while the first example is "async functions". Maybe "async function" without "s".

**Comment by jonathanong** [comment]
@slikts sometimes it's easier to make a PR by editing in GitHub than by opening a new issue :)

**Comment by jonathanong** [comment]
@chinesedfan that sounds good

**Comment by fl0w** [comment]
@slikts to be fair, due to `koa-convert` the paragraph is accurate - for now.

**Comment by fl0w** [comment]
I think this one is closed as https://github.com/koajs/koa/commit/87036857e6b79cfd564d7bf2352ef7abb922b48d landed?
