### ISSUE TITLE
any-promise: global leak detected: @@any-promise/REGISTRATION

### ISSUE THREAD

**Issue by tomoat** [koajs/koa#945]
Error: global leak detected: @@any-promise/REGISTRATION

```bash
$ npm ls any-promise
...
└─┬ koa@2.2.0
  └─┬ koa-compose@3.2.1
    └── any-promise@1.3.0
```

**Comment by tj** [comment]
+1 for removing haha, such a bizarre library. Promises are global, any polyfill should also just be global. Even worse is you don't even know what you might get https://github.com/kevinbeaty/any-promise/blob/master/register.js#L76-L86

**Comment by tomoat** [comment]
Well, it looks like it must be replaced, thanks  @tj

**Comment by jonathanong** [comment]
let's keep this open until we do replace it :)

**Comment by stringa** [comment]
Any update on this?

**Comment by fl0w** [comment]
https://github.com/koajs/koa/commit/7bd82ac4103aef28fb2d2f40be91f495dfa6db5d
https://github.com/koajs/compose/commit/f0eac55369461ee2160d086358f43acb50004274

All merged and ready for next Koa release, soon (tm) @stringa.

**Comment by tomoat** [comment]
I find the already are fixedThe already been fixed
