### ISSUE TITLE
webstorm 

### ISSUE THREAD

**Issue by shiqiliang** [koajs/koa#947]
![e2ccde79-421d-42be-8ed7-71a7f3b7ede7](https://cloud.githubusercontent.com/assets/4377660/24133996/3e9bbaba-0e3c-11e7-8f9c-a86d5717afb3.JPG)

how resolve this problem?

**Comment by jonathanong** [comment]
what is it trying to do? look up `.use`?

**Comment by fl0w** [comment]
This is a local settings issue, just check a colleagues webstorm setup which does not behave like this.

**Comment by shiqiliang** [comment]
Yes，trying to look uo .use function

**Comment by chinesedfan** [comment]
It is an issue of WebStorm, rather than koa. Because javascript is a kind of dynamic types languages, WebStorm can not always find the right function definition.

**Comment by yoneal** [comment]
In order for WebStorm to get the right function definition for libraries like koa, just set the project's Javascript libraries (Languages & Frameworks > Javascript > Libraries). Press Download then find koa from the Typescript community stubs

**Comment by jonathanong** [comment]
> It is an issue of WebStorm, rather than koa. Because javascript is a kind of dynamic types languages, WebStorm can not always find the right function definition.
