### ISSUE TITLE
a generator for koa like express-genertaor

### ISSUE THREAD

**Issue by glennWang** [koajs/koa#949]
Long long ago,  I used express, and express-generator (https://github.com/expressjs/generator)

The lead of express team is said to  maintain the express-generator.

But when I found Koa, I think Koa is more simple to use .

Koa is greate.  If Koa has a generator like express-generator , koa will become more and more 

simple to use. 

The generator github.com/17koa/koa-generator has not been updated for a long time.

**Comment by BruceHem** [comment]
I think doing this doesn't require a generator.
 ```javascript
const Koa = require('koa');
const app = new Koa();

app.use(ctx => {
  ctx.body = 'Hello World';
});

app.listen(3000);
```

**Comment by glennWang** [comment]
https://github.com/17koa/koa-generator   has been updated.

Thanks all the same
