### ISSUE TITLE
How to upload file in koa2?

### ISSUE THREAD

**Issue by SteveCruise** [koajs/koa#952]
And most important, with a callback when upload finish, like jquery-file-upload-middleware in express.
Getting params is also needed.

**Comment by carlisliu** [comment]
[koa upload example](https://github.com/koajs/examples/tree/master/upload)

**Comment by SteveCruise** [comment]
@carlisliu Thank you very much. But there should have a plugin to do that.

**Comment by fl0w** [comment]
@SteveCruise you mean like https://github.com/koa-modules/multer?

**Comment by SteveCruise** [comment]
@fl0w [koa-better-body](https://github.com/tunnckoCore/koa-better-body)

**Comment by SteveCruise** [comment]
Formidable is hard to deal with multiple upload.

**Comment by valVk** [comment]
here is another promise based file uploader I'm using that in my project
https://github.com/m4nuC/async-busboy

**Comment by BruceHem** [comment]
I use koa multer and works pretty well.

**Comment by SteveCruise** [comment]
@BruceHem Yes， [koa-multer](https://www.npmjs.com/package/koa-multer) is what I want, but it has little readme, I must read [multer for express](https://github.com/expressjs/multer) first.

**Comment by BruceHem** [comment]
Try search for kodejs I made an upload API using Koa multer.

**Comment by SteveCruise** [comment]
I summarize the best choise of koa middleware here.
koa-router 
koa-multer
koa-bodyparser 
koa-send
koa-session-minimal & koa-redis
koa-sslify 
koa-favicon
koa-logger
koa-static 
koa-ejs

**Comment by SteveCruise** [comment]
@valVk Thank you very much.

**Comment by hirako2000** [comment]
I also had some struggle, thus wrote my own wrapper.

**Comment by crazyyi** [comment]
@valVk Thanks this one is really easy to use.

**Comment by haifahrul** [comment]
@crazyyi Hi, what the best of it for upload file? What should I use?

**Comment by std4453** [comment]
What can I use to upload files directly as binary stream? Like with AWS S3 (and minio)?

**Comment by gideaoms** [comment]
`function store(ctx) {
    const form = new formidable.IncomingForm(...);
    form.parse(ctx.req, (fields, files) => {
        if (err) {
             ....
        }
        ...
    })
}
`

**Comment by nfantone** [comment]
Exactly my question, @std4453. I was trying to scavenge around, searching for a solution - but failed to find a single mention to that use case. `multipart/form-data` encoding only makes sense in the context of HTTP forms.

The way I ended up handling it is using [`raw-body`](https://github.com/stream-utils/raw-body) myself in a custom middleware and messing with the request body as a `Buffer`.
