### ISSUE TITLE
ctx.type= behavior & documentation mismatch

### ISSUE THREAD

**Issue by magicdawn** [koajs/koa#970]
## doc
http://koajs.com/#response

![image](https://cloud.githubusercontent.com/assets/4067115/25311920/0a0bdd12-283f-11e7-8816-99aa56ec6a26.png)

## behavior

set full `text/html` also gets charset set

![image](https://cloud.githubusercontent.com/assets/4067115/25311961/bc7207d8-283f-11e7-8982-7bf3b8942d33.png)

https://runkit.com/58955398e6ac1b00142b7580/58fc61ac15bef7001293cdb7/branches/master

**Comment by magicdawn** [comment]
koa version v2.2.0.
I guess just using `ctx.set('content-type', 'text/html')` works

**Comment by jonathanong** [comment]
seems like the docs are incorrect. it should always set the charset because it doesn't hurt.

**Comment by magicdawn** [comment]
Em, right. But it's nicer to point a way to get rid of the charset part. like `ctx.set('content-type', blabla)` directly
