### ISSUE TITLE
ctx.request.query can not get post query obj when I make an ajax 'post' request through axios

### ISSUE THREAD

**Issue by alex1504** [koajs/koa#973]
ctx.request.query can not get post query obj when I make an ajax 'post' request through axios, but in postman I can get query obj. I don't know what happens and how can i solve this problem. 

More specific description in stackoverflow:

 [http://stackoverflow.com/questions/43604063/koa2-ctx-request-query-is-not-defined-when-i-make-an-ajax-request-but-in-postman](url)

**Comment by fl0w** [comment]
I'm assuming you're using body parser? A common gotcha with postman is to set correct content-type.

The link doesn't work.

**Comment by jonathanong** [comment]
i'm guessing axios improperly sends the query obj as a request body
