### ISSUE TITLE
koa hangs when using ctx.body with 500kB of JSON [UPD: actually it's not the reason]

### ISSUE THREAD

**Issue by DreaMinder** [koajs/koa#975]
tested on OS: Ubuntu, koa: 2.0, 2.2, nodejs: 7.6, 7.9
Originally in my project there was mongoose data aggregation with 100kB of output data. Requests were running up to 200ms, but sometimes they just stoped responding.
So I assigned JSON copy of DB collection to ctx.body to test this issue. 
`ctx => { ctx.body = [hella huge array] }` 
Same thing, but now I have to make just 7-15 requests (fr. 0.5req/sec, but this doesn't actually mater) to see that one of them a bit laggy and the next one doesn't apears in logs and hangs. CPU consuption is 100% on node.js process. 
express.js runs fine, by the way.
Sorry for my bad english. Hope that it would be easy to reproduce the problem. And good luck with solution. My project is not so big, so I going to port it to express.js. So no hurry. 

UPD: turns out that koa is fine, see my comments below

**Comment by motet-a** [comment]
Have you tried to use a stream? In general, you can with Mongoose:

```js
const JSONStream = require('streaming-json-stringify')

...

ctx.body = JSONStream()

User.find({})
  .cursor()
  .pipe(ctx.body)
```

It’s much better when you have a lot of data.

**Comment by DreaMinder** [comment]
Thanks for advice, I'll use it for response speed optimisation, but it will not solve the problem.
I have found what have been causing this behavior. In my project there is a sheduled http request using axios. When this requests are disabled, koa response runs fine with any amount of data.
So I changed axios to "request" and now the problem is gone.
