### ISSUE TITLE
Docs not showing intro and app sections

### ISSUE THREAD

**Issue by pensierinmusica** [koajs/koa#976]
When I visit http://koajs.com/ there seems to be a problem on the docs homepage, where the "Introduction" and "Application" sections are blank. The docs start from the "Context" section.

Is this just on my side, or do you also notice the same problem?

Thanks!

**Comment by jonathanong** [comment]
yeah i noticed this, but i couldn't figure out what's going on. anyone have any ideas?

**Comment by pensierinmusica** [comment]
Seems somewhat urgent to fix... @tj or @dead-horse any idea?

**Comment by draconteus** [comment]
I can reproduce it locally, just by not running `make -j4`.
Redeploy the koajs.com and that'll update the docs as well. ;)

**Comment by jonathanong** [comment]
👍  thanks @draconteus

**Comment by pensierinmusica** [comment]
Awesome thanks @jonathanong and @draconteus!
