### ISSUE TITLE
Replace eslint-config-standard with standard

### ISSUE THREAD

**Issue by rynz** [koajs/koa#989]
Is there a reason why koajs and current/future middleware can't all use [standard](http://standardjs.com/) instead of `eslint-config-standard`?

**Comment by OneNewLife** [comment]
@rynz 

i guess it's just a traditional style guided by @tj with a long history, maybe @dead-horse can tell u why.

**Comment by bySabi** [comment]
With `standard` you can´t use custom `.eslintrc` files needed for example `jest` lint rules: https://github.com/koajs/koa/blob/master/test/.eslintrc

**Comment by dead-horse** [comment]
every project has their own style guide, we just need to ensure the code style is unified in this project.
