### ISSUE TITLE
Update request headers for upstream middleware

### ISSUE THREAD

**Issue by domarmstrong** [koajs/koa#991]
Hello. I'm migrating a code base to Koa. Which is great and removing loads of complexity for me in a lot of places, where I had wrappers and extensions to handle async middleware and upstream transformations after controllers. So thanks!

I've just run into this issue though with my validation layer:

```
Cannot set property headers of #<Object> which has only a getter
```

I currently have header validation middleware that does:
```
// validate and update with defaults/type casting
ctx.request.headers = Joi.attempt(ctx.request.headers, schema)
```

It has schema based validation which may set some default if values don't exist. Like if content-type isnt passed it sets content-type application/json (just an example). This is done on headers/body/query. So upstream middleware should just see it as though the client sent this.

Any suggestions on how I can handle this?

**Comment by dead-horse** [comment]
for now, you can change `ctx.req.headers` directly. But I think it is reasonable to add `ctx.request.headers=`.

**Comment by domarmstrong** [comment]
Thanks for the response. I've worked around it with the following for now based on that:

```
ctx.req.headers = mapKeys(Joi.attempt(ctx.request.headers, schema), key => key.toLowerCase());
```
