### ISSUE TITLE
Restrict koa from using non-promise middlewares

### ISSUE THREAD

**Issue by atassis** [koajs/koa#997]
Hello there. In koa@2 when you use the mix of normal and async functions as middlewares, the normal function behave unproperly if it doesn't return a promise. I propose to add a verification if function returns promise, so no other developers will be confused.

**Comment by fl0w** [comment]
This has been discussed in many issues, a function that doesn't return a promise is valid.

```js
const Koa = require('koa')
const app = new Koa
app.use(ctx => {
  ctx.body = 'I am valid'
})
```

**Comment by SergProduction** [comment]
Yes. But it breaks previous async middlewares

**Comment by atassis** [comment]
@fl0w in addition to @SergProduction, I want to suggest some type of strict mode, when normal functions are restricted. This truely breaks async functions.

**Comment by LestaD** [comment]
@fl0w Maybe restrict sync middlewares that have arity 2

**Comment by danwkennedy** [comment]
Sounds like this would be best done as a linter rule instead of part of the framework. It could then be configured as a warning or an error depending on your preference.

**Comment by fl0w** [comment]
@danwkennedy that was pretty much what others was saying as well in https://github.com/koajs/compose/pull/73

@SergProduction @atassis sounds like what https://github.com/koajs/koa/pull/955 does, but simplified maybe. `forceAsync` would be an option. Koa team has not decided on it yet though - and that PR is somewhat borked.

**Comment by LestaD** [comment]
@danwkennedy I think, framework should check that to avoid stupid mistakes, like forgotten `async`

**Comment by fl0w** [comment]
@LestaD Koa is not a framework - and I strongly disagree with guarding against what's basically erroneous javascript (not specific to Koa).

**Comment by danwkennedy** [comment]
@LestaD linters will already warn you about these kinds of things:
http://eslint.org/docs/rules/require-await

**Comment by atassis** [comment]
@fl0w still, it is not obvious for even matured developers how the code from koajs.com site works. It is an individual case of using middlewares. And yes- it is not about JS itself, it is about Koa.

**Comment by atassis** [comment]
@danwkennedy not everyone is using this kind of linters as well as it mustn't be covering a case with function returning promises. Or is it?

**Comment by danwkennedy** [comment]
You don't have to return a promise for the middleware to be valid. Execution simply stops when the function returns and goes back up the stack. If you expect your middleware to passthrough, you do have to await or return the result of `next()`. So then the solution can't simply be a check for a returned promise. The solution explored in https://github.com/koajs/compose/pull/73 concluded with this is mainly just a user error that would be unperformant and hacky to check for.

**Comment by SergProduction** [comment]
@danwkennedy I think it needs to be written in the documentation so people do not puzzle why their code does not working

**Comment by danwkennedy** [comment]
@SergProduction That's fair. I looked over the docs website and the http://koajs.com/#cascading section could make this behavior more explicit. Either that or listing possible structures for middleware functions and what would happen when they're called.

@fl0w would you have any suggestions/comments on that? I'd be willing to PR it if you'd like.

**Comment by fl0w** [comment]
@danwkennedy I'm +0, wouldn't be opposed having a section to reference, as this issue seems to crop up.

Though I can't speak for what the maintainers wants the docs to include. If you feel like you have the time, do a PR and await *(pun intended)* a review - or, let this simmer a bit until the members chip in with grand opinions :)

**Comment by SergProduction** [comment]
OR

![image](https://user-images.githubusercontent.com/18291975/26901718-800bcd74-4bdf-11e7-88a0-c324844b11e3.png)

**Comment by fl0w** [comment]
@danwkennedy https://github.com/koajs/koa/issues/954 is marked as documentation, I would assume a PR would be appreciated.

**Comment by fl0w** [comment]
I'm going to close this due to inactivity. This is more of a general javascript "gotchya". As I've understood the consensus, this is at best a documentation issue and thus overlaps with #954 which is already tagged accordantly.
